package auth

import (
	"context"
	"net/netip"
	"time"

	"github.com/devline/onebook-eld/internal/pgconv"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/devline/onebook-eld/internal/db"
)

// SessionMatch is the result of looking a refresh token hash up. Current is
// false when the hash matched the previous, already rotated value, which is
// exactly the refresh token reuse signal.
type SessionMatch struct {
	Session db.Session
	Current bool
}

// NewSessionInput describes the session a successful login creates.
type NewSessionInput struct {
	CompanyID  *uuid.UUID
	UserID     uuid.UUID
	DeviceID   string
	DeviceType string
	TokenHash  string
	ExpiresAt  time.Time
	AppVersion string
	IP         string
	UserAgent  string
}

// InvitationInput describes an invitation or password reset token.
type InvitationInput struct {
	CompanyID *uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	Channel   string
	Purpose   string
	ExpiresAt time.Time
}

// Invitation purposes mirrored from the invitations.purpose CHECK constraint.
const (
	PurposeInvitation    = "invitation"
	PurposePasswordReset = "password_reset"
)

// Repo is everything the auth service needs from storage. Every method is
// parameterised SQL generated by sqlc; no statement is ever concatenated.
type Repo interface {
	FindUsersByLogin(ctx context.Context, login string) ([]db.User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (db.User, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (db.Role, error)
	RolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error)
	GetCompany(ctx context.Context, id uuid.UUID) (db.Company, error)

	MarkLoginSuccess(ctx context.Context, userID uuid.UUID) error
	MarkLoginFailure(ctx context.Context, userID uuid.UUID, threshold, lockMinutes int32) (int32, *time.Time, error)

	CreateSession(ctx context.Context, in NewSessionInput) (db.Session, error)
	ReplaceDeviceSessions(ctx context.Context, userID uuid.UUID, deviceType, reason string) ([]uuid.UUID, error)
	SessionByRefreshHash(ctx context.Context, hash string) (SessionMatch, error)
	RotateSession(ctx context.Context, id uuid.UUID, newHash string, expiresAt time.Time, appVersion string) (db.Session, error)
	RevokeSession(ctx context.Context, id uuid.UUID, reason string) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID, reason string) ([]uuid.UUID, error)
	PauseSession(ctx context.Context, id uuid.UUID) error
	ResumeSession(ctx context.Context, id uuid.UUID) error
	GetSession(ctx context.Context, id uuid.UUID) (db.Session, error)
	ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]db.Session, error)

	SetUserPassword(ctx context.Context, userID uuid.UUID, hash string) error
	SetUserPIN(ctx context.Context, userID uuid.UUID, hash string) error
	SetUserTOTP(ctx context.Context, userID uuid.UUID, secretEnc string, enabled bool, recovery []string) error

	CreateInvitation(ctx context.Context, in InvitationInput) (db.Invitation, error)
	InvitationByTokenHash(ctx context.Context, hash string) (db.Invitation, error)
	MarkInvitationUsed(ctx context.Context, id uuid.UUID) error
	InvalidateUserInvitations(ctx context.Context, userID uuid.UUID, purpose string) error

	SystemSettings(ctx context.Context) (map[string][]byte, error)
}

// PgRepo is the pgx/sqlc implementation of Repo.
//
// Authentication runs before a tenant is known, so every statement executes
// inside Pool.WithAuthTx: it opens the narrow app.auth_stage RLS window that
// migration 00013 defines. Application level filtering (company_id, user_id)
// still happens in the queries themselves.
type PgRepo struct {
	pool *db.Pool
}

// NewRepo builds the storage adapter.
func NewRepo(pool *db.Pool) *PgRepo { return &PgRepo{pool: pool} }

func (r *PgRepo) tx(ctx context.Context, fn func(q *db.Queries) error) error {
	return r.pool.WithAuthTx(ctx, func(tx pgx.Tx) error {
		return fn(db.New(tx))
	})
}

// FindUsersByLogin implements Repo.
func (r *PgRepo) FindUsersByLogin(ctx context.Context, login string) ([]db.User, error) {
	var out []db.User
	err := r.tx(ctx, func(q *db.Queries) error {
		rows, err := q.FindUsersByLogin(ctx, login)
		out = rows
		return err
	})
	return out, err
}

// GetUserByID implements Repo.
func (r *PgRepo) GetUserByID(ctx context.Context, id uuid.UUID) (db.User, error) {
	var out db.User
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.GetUserByID(ctx, id)
		return err
	})
	return out, err
}

// GetRoleByID implements Repo.
func (r *PgRepo) GetRoleByID(ctx context.Context, id uuid.UUID) (db.Role, error) {
	var out db.Role
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.GetRoleByID(ctx, id)
		return err
	})
	return out, err
}

// RolePermissions implements Repo.
func (r *PgRepo) RolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	var out []string
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.ListRolePermissions(ctx, roleID)
		return err
	})
	return out, err
}

// GetCompany implements Repo.
func (r *PgRepo) GetCompany(ctx context.Context, id uuid.UUID) (db.Company, error) {
	var out db.Company
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.GetCompany(ctx, id)
		return err
	})
	return out, err
}

// MarkLoginSuccess implements Repo.
func (r *PgRepo) MarkLoginSuccess(ctx context.Context, userID uuid.UUID) error {
	return r.tx(ctx, func(q *db.Queries) error {
		return q.MarkUserLoginSuccess(ctx, userID)
	})
}

// MarkLoginFailure implements Repo.
func (r *PgRepo) MarkLoginFailure(ctx context.Context, userID uuid.UUID, threshold, lockMinutes int32) (int32, *time.Time, error) {
	var row db.MarkUserLoginFailureRow
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		row, err = q.MarkUserLoginFailure(ctx, db.MarkUserLoginFailureParams{
			ID: userID, Column2: threshold, Column3: lockMinutes,
		})
		return err
	})
	if err != nil {
		return 0, nil, err
	}
	return row.FailedLogins, pgconv.ToTimePtr(row.LockedUntil), nil
}

// CreateSession implements Repo.
func (r *PgRepo) CreateSession(ctx context.Context, in NewSessionInput) (db.Session, error) {
	var out db.Session
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.CreateSession(ctx, db.CreateSessionParams{
			CompanyID:        pgconv.UUIDPtr(in.CompanyID),
			UserID:           in.UserID,
			DeviceID:         nilIfEmpty(in.DeviceID),
			DeviceType:       in.DeviceType,
			RefreshTokenHash: in.TokenHash,
			ExpiresAt:        in.ExpiresAt.UTC(),
			AppVersion:       nilIfEmpty(in.AppVersion),
			Ip:               parseIP(in.IP),
			UserAgent:        nilIfEmpty(in.UserAgent),
		})
		return err
	})
	return out, err
}

// ReplaceDeviceSessions implements Repo.
func (r *PgRepo) ReplaceDeviceSessions(ctx context.Context, userID uuid.UUID, deviceType, reason string) ([]uuid.UUID, error) {
	var out []uuid.UUID
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.RevokeUserDeviceSessionsReturning(ctx, db.RevokeUserDeviceSessionsReturningParams{
			UserID: userID, DeviceType: deviceType, RevokedReason: nilIfEmpty(reason),
		})
		return err
	})
	return out, err
}

// SessionByRefreshHash implements Repo.
func (r *PgRepo) SessionByRefreshHash(ctx context.Context, hash string) (SessionMatch, error) {
	var m SessionMatch
	err := r.tx(ctx, func(q *db.Queries) error {
		row, err := q.GetSessionByAnyRefreshHash(ctx, hash)
		if err != nil {
			return err
		}
		m = SessionMatch{
			Current: row.IsCurrent,
			Session: db.Session{
				ID: row.ID, CompanyID: row.CompanyID, UserID: row.UserID,
				DeviceID: row.DeviceID, DeviceType: row.DeviceType,
				RefreshTokenHash: row.RefreshTokenHash, Status: row.Status,
				RevokedReason: row.RevokedReason, ExpiresAt: row.ExpiresAt,
				LastSeenAt: row.LastSeenAt, AppVersion: row.AppVersion,
				Ip: row.Ip, UserAgent: row.UserAgent,
				CreatedAt: row.CreatedAt, UpdatedAt: row.UpdatedAt,
			},
		}
		return nil
	})
	return m, err
}

// RotateSession implements Repo.
func (r *PgRepo) RotateSession(
	ctx context.Context, id uuid.UUID, newHash string, expiresAt time.Time, appVersion string,
) (db.Session, error) {
	var out db.Session
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.RotateSessionToken(ctx, db.RotateSessionTokenParams{
			ID: id, RefreshTokenHash: newHash, ExpiresAt: expiresAt.UTC(),
			AppVersion: nilIfEmpty(appVersion),
		})
		return err
	})
	return out, err
}

// RevokeSession implements Repo.
func (r *PgRepo) RevokeSession(ctx context.Context, id uuid.UUID, reason string) error {
	return r.tx(ctx, func(q *db.Queries) error {
		return q.RevokeSession(ctx, db.RevokeSessionParams{ID: id, RevokedReason: nilIfEmpty(reason)})
	})
}

// RevokeAllUserSessions implements Repo.
func (r *PgRepo) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID, reason string) ([]uuid.UUID, error) {
	var out []uuid.UUID
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.RevokeAllUserSessionsReturning(ctx, db.RevokeAllUserSessionsReturningParams{
			UserID: userID, RevokedReason: nilIfEmpty(reason),
		})
		return err
	})
	return out, err
}

// PauseSession implements Repo.
func (r *PgRepo) PauseSession(ctx context.Context, id uuid.UUID) error {
	return r.tx(ctx, func(q *db.Queries) error { return q.PauseSession(ctx, id) })
}

// ResumeSession implements Repo.
func (r *PgRepo) ResumeSession(ctx context.Context, id uuid.UUID) error {
	return r.tx(ctx, func(q *db.Queries) error { return q.ResumeSession(ctx, id) })
}

// GetSession implements Repo.
func (r *PgRepo) GetSession(ctx context.Context, id uuid.UUID) (db.Session, error) {
	var out db.Session
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.GetSession(ctx, id)
		return err
	})
	return out, err
}

// ListSessionsByUser implements Repo.
func (r *PgRepo) ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]db.Session, error) {
	var out []db.Session
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.ListSessionsByUser(ctx, userID)
		return err
	})
	return out, err
}

// SetUserPassword implements Repo.
func (r *PgRepo) SetUserPassword(ctx context.Context, userID uuid.UUID, hash string) error {
	return r.tx(ctx, func(q *db.Queries) error {
		return q.SetUserPassword(ctx, db.SetUserPasswordParams{ID: userID, PasswordHash: &hash})
	})
}

// SetUserPIN implements Repo.
func (r *PgRepo) SetUserPIN(ctx context.Context, userID uuid.UUID, hash string) error {
	return r.tx(ctx, func(q *db.Queries) error {
		return q.SetUserPin(ctx, db.SetUserPinParams{ID: userID, PinHash: nilIfEmpty(hash)})
	})
}

// SetUserTOTP implements Repo.
func (r *PgRepo) SetUserTOTP(ctx context.Context, userID uuid.UUID, secretEnc string, enabled bool, recovery []string) error {
	return r.tx(ctx, func(q *db.Queries) error {
		return q.SetUserTotp(ctx, db.SetUserTotpParams{
			ID: userID, TotpSecretEnc: nilIfEmpty(secretEnc), TotpEnabled: enabled,
			RecoveryCodes: recovery,
		})
	})
}

// CreateInvitation implements Repo.
func (r *PgRepo) CreateInvitation(ctx context.Context, in InvitationInput) (db.Invitation, error) {
	var out db.Invitation
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.CreateInvitation(ctx, db.CreateInvitationParams{
			CompanyID: pgconv.UUIDPtr(in.CompanyID), UserID: in.UserID, TokenHash: in.TokenHash,
			Channel: in.Channel, Purpose: in.Purpose, ExpiresAt: in.ExpiresAt.UTC(),
		})
		return err
	})
	return out, err
}

// InvitationByTokenHash implements Repo.
func (r *PgRepo) InvitationByTokenHash(ctx context.Context, hash string) (db.Invitation, error) {
	var out db.Invitation
	err := r.tx(ctx, func(q *db.Queries) error {
		var err error
		out, err = q.GetInvitationByTokenHash(ctx, hash)
		return err
	})
	return out, err
}

// MarkInvitationUsed implements Repo.
func (r *PgRepo) MarkInvitationUsed(ctx context.Context, id uuid.UUID) error {
	return r.tx(ctx, func(q *db.Queries) error { return q.MarkInvitationUsed(ctx, id) })
}

// InvalidateUserInvitations implements Repo.
func (r *PgRepo) InvalidateUserInvitations(ctx context.Context, userID uuid.UUID, purpose string) error {
	return r.tx(ctx, func(q *db.Queries) error {
		return q.InvalidateUserInvitations(ctx, db.InvalidateUserInvitationsParams{
			UserID: userID, Purpose: purpose,
		})
	})
}

// SystemSettings implements Repo.
func (r *PgRepo) SystemSettings(ctx context.Context) (map[string][]byte, error) {
	out := map[string][]byte{}
	err := r.tx(ctx, func(q *db.Queries) error {
		rows, err := q.ListSystemSettings(ctx)
		if err != nil {
			return err
		}
		for _, s := range rows {
			out[s.Key] = s.Value
		}
		return nil
	})
	return out, err
}

func nilIfEmpty(v string) *string {
	if v == "" {
		return nil
	}
	return &v
}

func parseIP(v string) *netip.Addr {
	if v == "" {
		return nil
	}
	addr, err := netip.ParseAddr(v)
	if err != nil {
		return nil
	}
	return &addr
}
