// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const alertsActiveCompanies = `-- name: AlertsActiveCompanies :many

SELECT id, timezone, subscription_status, subscription_end_at
FROM companies
WHERE deleted_at IS NULL AND subscription_status <> 'readonly'
ORDER BY created_at
LIMIT $1
`

type AlertsActiveCompaniesRow struct {
	ID                 uuid.UUID
	Timezone           string
	SubscriptionStatus string
	SubscriptionEndAt  pgtype.Timestamptz
}

// Fon vazifalari uchun query'lar (TZ A§19 cron alertlari). Bularning hammasi
// platforma yoki tenant darajasida `internal/jobs` dan chaqiriladi.
// Kompaniyalar va ularning TZ'lari — 20:00 Company TZ alerti uchun.
func (q *Queries) AlertsActiveCompanies(ctx context.Context, limit int32) ([]AlertsActiveCompaniesRow, error) {
	rows, err := q.db.Query(ctx, alertsActiveCompanies, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertsActiveCompaniesRow{}
	for rows.Next() {
		var i AlertsActiveCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Timezone,
			&i.SubscriptionStatus,
			&i.SubscriptionEndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const alertsCompaniesExpiringOn = `-- name: AlertsCompaniesExpiringOn :many
SELECT id, name, subscription_end_at
FROM companies
WHERE deleted_at IS NULL
  AND subscription_end_at IS NOT NULL
  AND (subscription_end_at AT TIME ZONE timezone)::date = ($1::date)
LIMIT $2
`

type AlertsCompaniesExpiringOnParams struct {
	Column1 pgtype.Date
	Limit   int32
}

type AlertsCompaniesExpiringOnRow struct {
	ID                uuid.UUID
	Name              string
	SubscriptionEndAt pgtype.Timestamptz
}

// Obuna tugash sanasi aniq N kundan keyin bo'lgan kompaniyalar.
func (q *Queries) AlertsCompaniesExpiringOn(ctx context.Context, arg AlertsCompaniesExpiringOnParams) ([]AlertsCompaniesExpiringOnRow, error) {
	rows, err := q.db.Query(ctx, alertsCompaniesExpiringOn, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertsCompaniesExpiringOnRow{}
	for rows.Next() {
		var i AlertsCompaniesExpiringOnRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SubscriptionEndAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const alertsCompanyAdministrators = `-- name: AlertsCompanyAdministrators :many
SELECT u.id FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.company_id = $1 AND u.deleted_at IS NULL AND u.status = 'active'
  AND r.name = 'Administrator'
`

// Administrator rolidagi foydalanuvchilar (obuna alerti aynan ularga boradi).
func (q *Queries) AlertsCompanyAdministrators(ctx context.Context, companyID pgtype.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, alertsCompanyAdministrators, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const alertsStaleUnidentifiedCount = `-- name: AlertsStaleUnidentifiedCount :one
SELECT count(*)::bigint FROM unidentified_events
WHERE company_id = $1 AND status = 'pending' AND start_at < $2
`

type AlertsStaleUnidentifiedCountParams struct {
	CompanyID uuid.UUID
	StartAt   time.Time
}

// 8 kundan beri biriktirilmagan haydash bloklari (unidentified_driving alerti).
func (q *Queries) AlertsStaleUnidentifiedCount(ctx context.Context, arg AlertsStaleUnidentifiedCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, alertsStaleUnidentifiedCount, arg.CompanyID, arg.StartAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const alertsUncertifiedLogDrivers = `-- name: AlertsUncertifiedLogDrivers :many
SELECT dl.driver_id, d.user_id, count(*)::bigint AS log_count, min(dl.log_date)::date AS oldest_log_date
FROM daily_logs dl
JOIN drivers d ON d.id = dl.driver_id AND d.deleted_at IS NULL AND d.status = 'active'
WHERE dl.company_id = $1
  AND dl.certification_status <> 'certified'
  AND dl.log_date <= $2::date
GROUP BY dl.driver_id, d.user_id
ORDER BY dl.driver_id
LIMIT $3
`

type AlertsUncertifiedLogDriversParams struct {
	CompanyID uuid.UUID
	Column2   pgtype.Date
	Limit     int32
}

type AlertsUncertifiedLogDriversRow struct {
	DriverID      uuid.UUID
	UserID        uuid.UUID
	LogCount      int64
	OldestLogDate pgtype.Date
}

// Sertifikatlanmagan kunlik loglar egalari (kuniga 1 marta, 20:00 Company TZ).
func (q *Queries) AlertsUncertifiedLogDrivers(ctx context.Context, arg AlertsUncertifiedLogDriversParams) ([]AlertsUncertifiedLogDriversRow, error) {
	rows, err := q.db.Query(ctx, alertsUncertifiedLogDrivers, arg.CompanyID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertsUncertifiedLogDriversRow{}
	for rows.Next() {
		var i AlertsUncertifiedLogDriversRow
		if err := rows.Scan(
			&i.DriverID,
			&i.UserID,
			&i.LogCount,
			&i.OldestLogDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
