// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT count(*) FROM audit_log a
WHERE a.company_id = $1
  AND ($2::text IS NULL OR a.table_name = $2::text)
  AND ($3::uuid IS NULL OR a.record_id = $3::uuid)
  AND ($4::uuid IS NULL OR a.edited_by = $4::uuid)
  AND ($5::text IS NULL OR a.action = $5::text)
  AND ($6::timestamptz IS NULL OR a.ts >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR a.ts < $7::timestamptz)
`

type CountAuditLogParams struct {
	CompanyID pgtype.UUID
	TableName *string
	RecordID  pgtype.UUID
	EditedBy  pgtype.UUID
	Action    *string
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog,
		arg.CompanyID,
		arg.TableName,
		arg.RecordID,
		arg.EditedBy,
		arg.Action,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (
  company_id, table_name, record_id, field, old_value, new_value,
  action, edited_by, ip, user_agent, ts
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10, COALESCE($11::timestamptz, now()))
RETURNING id, company_id, table_name, record_id, field, old_value, new_value, action, edited_by, ip, user_agent, ts, reason
`

type InsertAuditLogParams struct {
	CompanyID pgtype.UUID
	TableName string
	RecordID  pgtype.UUID
	Field     *string
	OldValue  []byte
	NewValue  []byte
	Action    string
	EditedBy  pgtype.UUID
	Ip        *netip.Addr
	UserAgent *string
	Column11  time.Time
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.CompanyID,
		arg.TableName,
		arg.RecordID,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
		arg.Action,
		arg.EditedBy,
		arg.Ip,
		arg.UserAgent,
		arg.Column11,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TableName,
		&i.RecordID,
		&i.Field,
		&i.OldValue,
		&i.NewValue,
		&i.Action,
		&i.EditedBy,
		&i.Ip,
		&i.UserAgent,
		&i.Ts,
		&i.Reason,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT a.id, a.company_id, a.table_name, a.record_id, a.field, a.old_value, a.new_value, a.action, a.edited_by, a.ip, a.user_agent, a.ts, a.reason, u.first_name, u.last_name, u.username
FROM audit_log a
LEFT JOIN users u ON u.id = a.edited_by AND u.company_id = a.company_id
WHERE a.company_id = $1
  AND ($2::text IS NULL OR a.table_name = $2::text)
  AND ($3::uuid IS NULL OR a.record_id = $3::uuid)
  AND ($4::uuid IS NULL OR a.edited_by = $4::uuid)
  AND ($5::text IS NULL OR a.action = $5::text)
  AND ($6::timestamptz IS NULL OR a.ts >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR a.ts < $7::timestamptz)
ORDER BY
  CASE WHEN $8::text = 'asc' THEN a.ts END ASC,
  a.ts DESC
LIMIT $10 OFFSET $9
`

type ListAuditLogParams struct {
	CompanyID pgtype.UUID
	TableName *string
	RecordID  pgtype.UUID
	EditedBy  pgtype.UUID
	Action    *string
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
	SortDir   string
	RowOffset int32
	RowLimit  int32
}

type ListAuditLogRow struct {
	ID        uuid.UUID
	CompanyID pgtype.UUID
	TableName string
	RecordID  pgtype.UUID
	Field     *string
	OldValue  []byte
	NewValue  []byte
	Action    string
	EditedBy  pgtype.UUID
	Ip        *netip.Addr
	UserAgent *string
	Ts        time.Time
	Reason    *string
	FirstName *string
	LastName  *string
	Username  *string
}

// Audit-log ko'rinishi (TZ A§17) — faqat o'qish, filtr + pagination.
// The actor is resolved inside the tenant only: a platform super admin (whose
// users row carries company_id IS NULL) must stay anonymous in a tenant journal.
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.CompanyID,
		arg.TableName,
		arg.RecordID,
		arg.EditedBy,
		arg.Action,
		arg.FromTs,
		arg.ToTs,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TableName,
			&i.RecordID,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.Action,
			&i.EditedBy,
			&i.Ip,
			&i.UserAgent,
			&i.Ts,
			&i.Reason,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogTables = `-- name: ListAuditLogTables :many
SELECT DISTINCT a.table_name FROM audit_log a
WHERE a.company_id = $1
ORDER BY a.table_name
`

// Audit-log filtri uchun tanlanadigan jadval nomlari (UI dropdown).
func (q *Queries) ListAuditLogTables(ctx context.Context, companyID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAuditLogTables, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var table_name string
		if err := rows.Scan(&table_name); err != nil {
			return nil, err
		}
		items = append(items, table_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyHistory = `-- name: ListCompanyHistory :many
SELECT a.id, a.company_id, a.table_name, a.record_id, a.field, a.old_value, a.new_value, a.action, a.edited_by, a.ip, a.user_agent, a.ts, a.reason, u.first_name, u.last_name
FROM audit_log a
LEFT JOIN users u ON u.id = a.edited_by AND u.company_id = a.company_id
WHERE a.company_id = $1 AND a.table_name IN ('companies','hos_policy_versions','branches','notification_settings')
ORDER BY a.ts DESC
LIMIT $2 OFFSET $3
`

type ListCompanyHistoryParams struct {
	CompanyID pgtype.UUID
	Limit     int32
	Offset    int32
}

type ListCompanyHistoryRow struct {
	ID        uuid.UUID
	CompanyID pgtype.UUID
	TableName string
	RecordID  pgtype.UUID
	Field     *string
	OldValue  []byte
	NewValue  []byte
	Action    string
	EditedBy  pgtype.UUID
	Ip        *netip.Addr
	UserAgent *string
	Ts        time.Time
	Reason    *string
	FirstName *string
	LastName  *string
}

func (q *Queries) ListCompanyHistory(ctx context.Context, arg ListCompanyHistoryParams) ([]ListCompanyHistoryRow, error) {
	rows, err := q.db.Query(ctx, listCompanyHistory, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanyHistoryRow{}
	for rows.Next() {
		var i ListCompanyHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TableName,
			&i.RecordID,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.Action,
			&i.EditedBy,
			&i.Ip,
			&i.UserAgent,
			&i.Ts,
			&i.Reason,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordHistory = `-- name: ListRecordHistory :many
SELECT id, company_id, table_name, record_id, field, old_value, new_value, action, edited_by, ip, user_agent, ts, reason FROM audit_log
WHERE company_id = $1 AND table_name = $2 AND record_id = $3
ORDER BY ts DESC
LIMIT $4 OFFSET $5
`

type ListRecordHistoryParams struct {
	CompanyID pgtype.UUID
	TableName string
	RecordID  pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListRecordHistory(ctx context.Context, arg ListRecordHistoryParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listRecordHistory,
		arg.CompanyID,
		arg.TableName,
		arg.RecordID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TableName,
			&i.RecordID,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.Action,
			&i.EditedBy,
			&i.Ip,
			&i.UserAgent,
			&i.Ts,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
