// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const chatDriverCurrentDutyStatus = `-- name: ChatDriverCurrentDutyStatus :one
SELECT e.status FROM duty_status_events e
WHERE e.company_id = $1 AND e.driver_id = $2
  AND e.event_type = 'duty_status' AND e.superseded_by IS NULL
ORDER BY e.event_time DESC LIMIT 1
`

type ChatDriverCurrentDutyStatusParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
}

// Chatni bloklash uchun haydovchining joriy duty statusi (Q10 — `DR` bo'lsa
// yozish taqiqlanadi).
func (q *Queries) ChatDriverCurrentDutyStatus(ctx context.Context, arg ChatDriverCurrentDutyStatusParams) (*string, error) {
	row := q.db.QueryRow(ctx, chatDriverCurrentDutyStatus, arg.CompanyID, arg.DriverID)
	var status *string
	err := row.Scan(&status)
	return status, err
}

const chatGetDriver = `-- name: ChatGetDriver :one
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.status,
       u.first_name, u.last_name
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.company_id = $1 AND d.id = $2 AND d.deleted_at IS NULL
`

type ChatGetDriverParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type ChatGetDriverRow struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	UserID    uuid.UUID
	BranchID  pgtype.UUID
	Status    string
	FirstName string
	LastName  string
}

func (q *Queries) ChatGetDriver(ctx context.Context, arg ChatGetDriverParams) (ChatGetDriverRow, error) {
	row := q.db.QueryRow(ctx, chatGetDriver, arg.CompanyID, arg.ID)
	var i ChatGetDriverRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const chatGetDriverByUser = `-- name: ChatGetDriverByUser :one
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.status,
       u.first_name, u.last_name
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.company_id = $1 AND d.user_id = $2 AND d.deleted_at IS NULL
`

type ChatGetDriverByUserParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

type ChatGetDriverByUserRow struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	UserID    uuid.UUID
	BranchID  pgtype.UUID
	Status    string
	FirstName string
	LastName  string
}

func (q *Queries) ChatGetDriverByUser(ctx context.Context, arg ChatGetDriverByUserParams) (ChatGetDriverByUserRow, error) {
	row := q.db.QueryRow(ctx, chatGetDriverByUser, arg.CompanyID, arg.UserID)
	var i ChatGetDriverByUserRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const countChatMessages = `-- name: CountChatMessages :one
SELECT count(*) FROM chat_messages WHERE company_id = $1 AND driver_id = $2
`

type CountChatMessagesParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
}

func (q *Queries) CountChatMessages(ctx context.Context, arg CountChatMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChatMessages, arg.CompanyID, arg.DriverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChatThreads = `-- name: CountChatThreads :one
SELECT count(*) FROM drivers d
WHERE d.company_id = $1
  AND d.deleted_at IS NULL
  AND ($2::uuid IS NULL OR d.branch_id = $2::uuid)
  AND ($3::uuid IS NULL OR d.id = $3::uuid)
  AND ($4::bool
       OR EXISTS (SELECT 1 FROM chat_messages m
                  WHERE m.company_id = d.company_id AND m.driver_id = d.id))
`

type CountChatThreadsParams struct {
	CompanyID    uuid.UUID
	BranchID     pgtype.UUID
	DriverID     pgtype.UUID
	IncludeEmpty bool
}

func (q *Queries) CountChatThreads(ctx context.Context, arg CountChatThreadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChatThreads,
		arg.CompanyID,
		arg.BranchID,
		arg.DriverID,
		arg.IncludeEmpty,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadChatForDriver = `-- name: CountUnreadChatForDriver :one
SELECT count(*) FROM chat_messages
WHERE company_id = $1 AND driver_id = $2 AND sender_id <> $3 AND read_at IS NULL
`

type CountUnreadChatForDriverParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	SenderID  uuid.UUID
}

func (q *Queries) CountUnreadChatForDriver(ctx context.Context, arg CountUnreadChatForDriverParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadChatForDriver, arg.CompanyID, arg.DriverID, arg.SenderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (company_id, driver_id, sender_id, kind, text, file_key, lat, lng, sent_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8, COALESCE($9::timestamptz, now()))
RETURNING id, company_id, driver_id, sender_id, kind, text, file_key, lat, lng, sent_at, delivered_at, read_at, created_at, updated_at
`

type CreateChatMessageParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	SenderID  uuid.UUID
	Kind      string
	Text      *string
	FileKey   *string
	Lat       *float64
	Lng       *float64
	SentAt    pgtype.Timestamptz
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.CompanyID,
		arg.DriverID,
		arg.SenderID,
		arg.Kind,
		arg.Text,
		arg.FileKey,
		arg.Lat,
		arg.Lng,
		arg.SentAt,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.SenderID,
		&i.Kind,
		&i.Text,
		&i.FileKey,
		&i.Lat,
		&i.Lng,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldChatMessages = `-- name: DeleteOldChatMessages :execrows
DELETE FROM chat_messages WHERE company_id = $1 AND sent_at < $2
`

type DeleteOldChatMessagesParams struct {
	CompanyID uuid.UUID
	SentAt    time.Time
}

// Retention — TZ §15.4: chat 1 yil saqlanadi.
func (q *Queries) DeleteOldChatMessages(ctx context.Context, arg DeleteOldChatMessagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldChatMessages, arg.CompanyID, arg.SentAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatMessage = `-- name: GetChatMessage :one
SELECT id, company_id, driver_id, sender_id, kind, text, file_key, lat, lng, sent_at, delivered_at, read_at, created_at, updated_at FROM chat_messages WHERE company_id = $1 AND id = $2
`

type GetChatMessageParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetChatMessage(ctx context.Context, arg GetChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessage, arg.CompanyID, arg.ID)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.SenderID,
		&i.Kind,
		&i.Text,
		&i.FileKey,
		&i.Lat,
		&i.Lng,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatLastMessages = `-- name: ListChatLastMessages :many
SELECT DISTINCT ON (m.driver_id)
  m.driver_id, m.id, m.kind, m.text, m.file_key, m.sender_id,
  m.sent_at, m.delivered_at, m.read_at
FROM chat_messages m
WHERE m.company_id = $1 AND m.driver_id = ANY($2::uuid[])
ORDER BY m.driver_id, m.sent_at DESC, m.id DESC
`

type ListChatLastMessagesParams struct {
	CompanyID uuid.UUID
	Column2   []uuid.UUID
}

type ListChatLastMessagesRow struct {
	DriverID    uuid.UUID
	ID          uuid.UUID
	Kind        string
	Text        *string
	FileKey     *string
	SenderID    uuid.UUID
	SentAt      time.Time
	DeliveredAt pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
}

// Bir sahifadagi thread'larning oxirgi xabari.
func (q *Queries) ListChatLastMessages(ctx context.Context, arg ListChatLastMessagesParams) ([]ListChatLastMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChatLastMessages, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatLastMessagesRow{}
	for rows.Next() {
		var i ListChatLastMessagesRow
		if err := rows.Scan(
			&i.DriverID,
			&i.ID,
			&i.Kind,
			&i.Text,
			&i.FileKey,
			&i.SenderID,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, company_id, driver_id, sender_id, kind, text, file_key, lat, lng, sent_at, delivered_at, read_at, created_at, updated_at FROM chat_messages
WHERE company_id = $1
  AND driver_id = $2
  AND ($3::timestamptz IS NULL OR sent_at < $3::timestamptz)
ORDER BY sent_at DESC, id DESC
LIMIT $4
`

type ListChatMessagesParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	Before    pgtype.Timestamptz
	RowLimit  int32
}

// Kursor pagination: `before` — oxirgi ko'rilgan xabarning sent_at qiymati.
func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages,
		arg.CompanyID,
		arg.DriverID,
		arg.Before,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.SenderID,
			&i.Kind,
			&i.Text,
			&i.FileKey,
			&i.Lat,
			&i.Lng,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatThreads = `-- name: ListChatThreads :many
SELECT
  d.id AS driver_id,
  d.status AS driver_status,
  d.branch_id,
  u.id AS driver_user_id,
  u.first_name,
  u.last_name,
  (SELECT count(*) FROM chat_messages m
     WHERE m.company_id = d.company_id AND m.driver_id = d.id
       AND m.sender_id = u.id AND m.read_at IS NULL)::bigint AS unread_count
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.company_id = $1
  AND d.deleted_at IS NULL
  AND ($2::uuid IS NULL OR d.branch_id = $2::uuid)
  AND ($3::uuid IS NULL OR d.id = $3::uuid)
  AND ($4::bool
       OR EXISTS (SELECT 1 FROM chat_messages m
                  WHERE m.company_id = d.company_id AND m.driver_id = d.id))
ORDER BY COALESCE((SELECT max(m.sent_at) FROM chat_messages m
                   WHERE m.company_id = d.company_id AND m.driver_id = d.id),
                  'epoch'::timestamptz) DESC, u.last_name, u.first_name
LIMIT $6 OFFSET $5
`

type ListChatThreadsParams struct {
	CompanyID    uuid.UUID
	BranchID     pgtype.UUID
	DriverID     pgtype.UUID
	IncludeEmpty bool
	RowOffset    int32
	RowLimit     int32
}

type ListChatThreadsRow struct {
	DriverID     uuid.UUID
	DriverStatus string
	BranchID     pgtype.UUID
	DriverUserID uuid.UUID
	FirstName    string
	LastName     string
	UnreadCount  int64
}

// Admin tomoni: har bir faol haydovchi bitta thread, xabari bo'lmasa ham
// ro'yxatda turadi. Oxirgi xabar alohida query bilan olinadi, chunki LEFT JOIN
// ustunlarining nullability'sini sqlc to'g'ri chiqara olmaydi.
func (q *Queries) ListChatThreads(ctx context.Context, arg ListChatThreadsParams) ([]ListChatThreadsRow, error) {
	rows, err := q.db.Query(ctx, listChatThreads,
		arg.CompanyID,
		arg.BranchID,
		arg.DriverID,
		arg.IncludeEmpty,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatThreadsRow{}
	for rows.Next() {
		var i ListChatThreadsRow
		if err := rows.Scan(
			&i.DriverID,
			&i.DriverStatus,
			&i.BranchID,
			&i.DriverUserID,
			&i.FirstName,
			&i.LastName,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChatMessageDelivered = `-- name: MarkChatMessageDelivered :exec
UPDATE chat_messages SET delivered_at = now() WHERE company_id = $1 AND id = $2 AND delivered_at IS NULL
`

type MarkChatMessageDeliveredParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkChatMessageDelivered(ctx context.Context, arg MarkChatMessageDeliveredParams) error {
	_, err := q.db.Exec(ctx, markChatMessageDelivered, arg.CompanyID, arg.ID)
	return err
}

const markChatMessageRead = `-- name: MarkChatMessageRead :execrows
UPDATE chat_messages SET read_at = now(), delivered_at = COALESCE(delivered_at, now())
WHERE company_id = $1 AND id = $2 AND sender_id <> $3 AND read_at IS NULL
`

type MarkChatMessageReadParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	SenderID  uuid.UUID
}

func (q *Queries) MarkChatMessageRead(ctx context.Context, arg MarkChatMessageReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markChatMessageRead, arg.CompanyID, arg.ID, arg.SenderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markThreadRead = `-- name: MarkThreadRead :execrows
UPDATE chat_messages SET read_at = now(), delivered_at = COALESCE(delivered_at, now())
WHERE company_id = $1 AND driver_id = $2 AND sender_id <> $3 AND read_at IS NULL
`

type MarkThreadReadParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	SenderID  uuid.UUID
}

func (q *Queries) MarkThreadRead(ctx context.Context, arg MarkThreadReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markThreadRead, arg.CompanyID, arg.DriverID, arg.SenderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
