// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_admin.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBranchUsers = `-- name: CountBranchUsers :one
SELECT count(*) FROM users
WHERE company_id = $1 AND branch_id = $2 AND deleted_at IS NULL
`

type CountBranchUsersParams struct {
	CompanyID pgtype.UUID
	BranchID  pgtype.UUID
}

func (q *Queries) CountBranchUsers(ctx context.Context, arg CountBranchUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBranchUsers, arg.CompanyID, arg.BranchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompanyAuditHistory = `-- name: CountCompanyAuditHistory :one
SELECT count(*) FROM audit_log a
WHERE a.company_id = $1
  AND ($2::text IS NULL OR a.table_name = $2::text)
  AND ($3::text IS NULL OR a.action = $3::text)
  AND ($4::uuid IS NULL OR a.record_id = $4::uuid)
  AND ($5::uuid IS NULL OR a.edited_by = $5::uuid)
  AND ($6::timestamptz IS NULL OR a.ts >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR a.ts < $7::timestamptz)
`

type CountCompanyAuditHistoryParams struct {
	CompanyID pgtype.UUID
	TableName *string
	Action    *string
	RecordID  pgtype.UUID
	EditedBy  pgtype.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

func (q *Queries) CountCompanyAuditHistory(ctx context.Context, arg CountCompanyAuditHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanyAuditHistory,
		arg.CompanyID,
		arg.TableName,
		arg.Action,
		arg.RecordID,
		arg.EditedBy,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompanyRoleByName = `-- name: GetCompanyRoleByName :one
SELECT id, company_id, name, description, scope, is_system, created_at, updated_at, deleted_at FROM roles
WHERE company_id = $1
  AND lower(name) = lower($2::text)
  AND deleted_at IS NULL
`

type GetCompanyRoleByNameParams struct {
	CompanyID pgtype.UUID
	Name      string
}

func (q *Queries) GetCompanyRoleByName(ctx context.Context, arg GetCompanyRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getCompanyRoleByName, arg.CompanyID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertNotificationSettingDefault = `-- name: InsertNotificationSettingDefault :exec
INSERT INTO notification_settings (company_id, alert_type, channels, recipient_roles, enabled)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT (company_id, alert_type) DO NOTHING
`

type InsertNotificationSettingDefaultParams struct {
	CompanyID      uuid.UUID
	AlertType      string
	Channels       []string
	RecipientRoles []uuid.UUID
}

// Kompaniya yaratilganda TZ A§19 jadvalidagi default kanallar.
func (q *Queries) InsertNotificationSettingDefault(ctx context.Context, arg InsertNotificationSettingDefaultParams) error {
	_, err := q.db.Exec(ctx, insertNotificationSettingDefault,
		arg.CompanyID,
		arg.AlertType,
		arg.Channels,
		arg.RecipientRoles,
	)
	return err
}

const listCompanyAuditHistory = `-- name: ListCompanyAuditHistory :many
SELECT a.id, a.company_id, a.table_name, a.record_id, a.field, a.old_value, a.new_value, a.action, a.edited_by, a.ip, a.user_agent, a.ts, a.reason, u.first_name, u.last_name, u.username
FROM audit_log a
LEFT JOIN users u ON u.id = a.edited_by
WHERE a.company_id = $1
  AND ($2::text IS NULL OR a.table_name = $2::text)
  AND ($3::text IS NULL OR a.action = $3::text)
  AND ($4::uuid IS NULL OR a.record_id = $4::uuid)
  AND ($5::uuid IS NULL OR a.edited_by = $5::uuid)
  AND ($6::timestamptz IS NULL OR a.ts >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR a.ts < $7::timestamptz)
ORDER BY a.ts DESC
LIMIT $9 OFFSET $8
`

type ListCompanyAuditHistoryParams struct {
	CompanyID pgtype.UUID
	TableName *string
	Action    *string
	RecordID  pgtype.UUID
	EditedBy  pgtype.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
	RowOffset int32
	RowLimit  int32
}

type ListCompanyAuditHistoryRow struct {
	ID        uuid.UUID
	CompanyID pgtype.UUID
	TableName string
	RecordID  pgtype.UUID
	Field     *string
	OldValue  []byte
	NewValue  []byte
	Action    string
	EditedBy  pgtype.UUID
	Ip        *netip.Addr
	UserAgent *string
	Ts        time.Time
	Reason    *string
	FirstName *string
	LastName  *string
	Username  *string
}

// GET /company/history — audit_log ning kompaniya sozlamalari bo'yicha kesimi.
func (q *Queries) ListCompanyAuditHistory(ctx context.Context, arg ListCompanyAuditHistoryParams) ([]ListCompanyAuditHistoryRow, error) {
	rows, err := q.db.Query(ctx, listCompanyAuditHistory,
		arg.CompanyID,
		arg.TableName,
		arg.Action,
		arg.RecordID,
		arg.EditedBy,
		arg.FromTs,
		arg.ToTs,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanyAuditHistoryRow{}
	for rows.Next() {
		var i ListCompanyAuditHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TableName,
			&i.RecordID,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.Action,
			&i.EditedBy,
			&i.Ip,
			&i.UserAgent,
			&i.Ts,
			&i.Reason,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const provisionCompanyRolePermissions = `-- name: ProvisionCompanyRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_key)
SELECT nr.id, rp.permission_key
FROM roles nr
JOIN roles tpl
  ON tpl.company_id IS NULL AND tpl.is_system AND tpl.deleted_at IS NULL
 AND lower(tpl.name) = lower(nr.name)
JOIN role_permissions rp ON rp.role_id = tpl.id
WHERE nr.company_id = $1 AND nr.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

// Nusxalangan rollarga shablon permission to'plamini ko'chiradi (nom bo'yicha).
func (q *Queries) ProvisionCompanyRolePermissions(ctx context.Context, companyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, provisionCompanyRolePermissions, companyID)
	return err
}

const provisionCompanyRoles = `-- name: ProvisionCompanyRoles :many

INSERT INTO roles (company_id, name, description, scope, is_system)
SELECT $1, t.name, t.description, t.scope, false
FROM roles t
WHERE t.company_id IS NULL AND t.is_system AND t.deleted_at IS NULL
ON CONFLICT DO NOTHING
RETURNING id, company_id, name, description, scope, is_system, created_at, updated_at, deleted_at
`

// Company boshqaruv modullari (internal/domain/companies, internal/domain/company)
// uchun so'rovlar. Boshqa modullar egallagan fayllarga tegmaslik uchun alohida.
// Yangi kompaniya uchun tizim rol shablonlarining (company_id IS NULL) nusxasi.
func (q *Queries) ProvisionCompanyRoles(ctx context.Context, companyID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, provisionCompanyRoles, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
