// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBranches = `-- name: CountBranches :one
SELECT count(*) FROM branches
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR name ILIKE '%' || $2::text || '%')
`

type CountBranchesParams struct {
	CompanyID uuid.UUID
	Search    *string
}

func (q *Queries) CountBranches(ctx context.Context, arg CountBranchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBranches, arg.CompanyID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompanies = `-- name: CountCompanies :one
SELECT count(*) FROM companies
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR subscription_status = $2::text)
  AND ($3::text IS NULL OR region = $3::text)
`

type CountCompaniesParams struct {
	Search *string
	Status *string
	Region *string
}

func (q *Queries) CountCompanies(ctx context.Context, arg CountCompaniesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies, arg.Search, arg.Status, arg.Region)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHosPolicyVersions = `-- name: CountHosPolicyVersions :one
SELECT count(*) FROM hos_policy_versions WHERE company_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountHosPolicyVersions(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHosPolicyVersions, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (company_id, name, address, timezone)
VALUES ($1,$2,$3,$4) RETURNING id, company_id, name, address, timezone, created_at, updated_at, deleted_at
`

type CreateBranchParams struct {
	CompanyID uuid.UUID
	Name      string
	Address   *string
	Timezone  *string
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.CompanyID,
		arg.Name,
		arg.Address,
		arg.Timezone,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
  name, address, home_terminal_address, timezone, email, phone,
  registration_no, region, unit_system, regulation_profile, plan
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, name, address, home_terminal_address, timezone, email, phone, registration_no, logo_key, region, unit_system, regulation_profile, subscription_status, subscription_end_at, plan, settings, created_at, updated_at, deleted_at
`

type CreateCompanyParams struct {
	Name                string
	Address             *string
	HomeTerminalAddress *string
	Timezone            string
	Email               *string
	Phone               *string
	RegistrationNo      *string
	Region              *string
	UnitSystem          string
	RegulationProfile   string
	Plan                *string
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Address,
		arg.HomeTerminalAddress,
		arg.Timezone,
		arg.Email,
		arg.Phone,
		arg.RegistrationNo,
		arg.Region,
		arg.UnitSystem,
		arg.RegulationProfile,
		arg.Plan,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.HomeTerminalAddress,
		&i.Timezone,
		&i.Email,
		&i.Phone,
		&i.RegistrationNo,
		&i.LogoKey,
		&i.Region,
		&i.UnitSystem,
		&i.RegulationProfile,
		&i.SubscriptionStatus,
		&i.SubscriptionEndAt,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createHosPolicyVersion = `-- name: CreateHosPolicyVersion :one
INSERT INTO hos_policy_versions (company_id, effective_from, policy, created_by)
VALUES (
  $1,
  COALESCE($2::timestamptz, now()),
  $3,
  $4
) RETURNING id, company_id, effective_from, policy, created_by, created_at, updated_at, deleted_at
`

type CreateHosPolicyVersionParams struct {
	CompanyID     uuid.UUID
	EffectiveFrom pgtype.Timestamptz
	Policy        []byte
	CreatedBy     pgtype.UUID
}

// effective_from NULL bo'lsa DB soati ishlatiladi: ilova va DB soati orasidagi
// farq tufayli yangi versiya "kelajakda" qolib ketmasin (Q10.1).
func (q *Queries) CreateHosPolicyVersion(ctx context.Context, arg CreateHosPolicyVersionParams) (HosPolicyVersion, error) {
	row := q.db.QueryRow(ctx, createHosPolicyVersion,
		arg.CompanyID,
		arg.EffectiveFrom,
		arg.Policy,
		arg.CreatedBy,
	)
	var i HosPolicyVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EffectiveFrom,
		&i.Policy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveHosPolicy = `-- name: GetActiveHosPolicy :one
SELECT id, company_id, effective_from, policy, created_by, created_at, updated_at, deleted_at FROM hos_policy_versions
WHERE company_id = $1 AND deleted_at IS NULL AND effective_from <= now()
ORDER BY effective_from DESC LIMIT 1
`

func (q *Queries) GetActiveHosPolicy(ctx context.Context, companyID uuid.UUID) (HosPolicyVersion, error) {
	row := q.db.QueryRow(ctx, getActiveHosPolicy, companyID)
	var i HosPolicyVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EffectiveFrom,
		&i.Policy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBranch = `-- name: GetBranch :one
SELECT id, company_id, name, address, timezone, created_at, updated_at, deleted_at FROM branches WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetBranchParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetBranch(ctx context.Context, arg GetBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, arg.CompanyID, arg.ID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, address, home_terminal_address, timezone, email, phone, registration_no, logo_key, region, unit_system, regulation_profile, subscription_status, subscription_end_at, plan, settings, created_at, updated_at, deleted_at FROM companies WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.HomeTerminalAddress,
		&i.Timezone,
		&i.Email,
		&i.Phone,
		&i.RegistrationNo,
		&i.LogoKey,
		&i.Region,
		&i.UnitSystem,
		&i.RegulationProfile,
		&i.SubscriptionStatus,
		&i.SubscriptionEndAt,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, description, created_at, updated_at FROM system_settings WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT id, company_id, name, address, timezone, created_at, updated_at, deleted_at FROM branches
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR name ILIKE '%' || $2::text || '%')
ORDER BY
  CASE WHEN $3::text = 'name'       AND $4::text = 'asc'  THEN lower(name) END ASC,
  CASE WHEN $3::text = 'name'       AND $4::text = 'desc' THEN lower(name) END DESC,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'asc'  THEN created_at END ASC,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN created_at END DESC,
  lower(name) ASC
LIMIT $6 OFFSET $5
`

type ListBranchesParams struct {
	CompanyID uuid.UUID
	Search    *string
	SortBy    string
	SortDir   string
	RowOffset int32
	RowLimit  int32
}

// Saralash oq ro'yxati: name | created_at.
func (q *Queries) ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches,
		arg.CompanyID,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Address,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, address, home_terminal_address, timezone, email, phone, registration_no, logo_key, region, unit_system, regulation_profile, subscription_status, subscription_end_at, plan, settings, created_at, updated_at, deleted_at FROM companies
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR subscription_status = $2::text)
  AND ($3::text IS NULL OR region = $3::text)
ORDER BY
  CASE WHEN $4::text = 'name'                AND $5::text = 'asc'  THEN lower(name) END ASC,
  CASE WHEN $4::text = 'name'                AND $5::text = 'desc' THEN lower(name) END DESC,
  CASE WHEN $4::text = 'created_at'          AND $5::text = 'asc'  THEN created_at END ASC,
  CASE WHEN $4::text = 'created_at'          AND $5::text = 'desc' THEN created_at END DESC,
  CASE WHEN $4::text = 'subscription_end_at' AND $5::text = 'asc'  THEN subscription_end_at END ASC,
  CASE WHEN $4::text = 'subscription_end_at' AND $5::text = 'desc' THEN subscription_end_at END DESC,
  lower(name) ASC
LIMIT $7 OFFSET $6
`

type ListCompaniesParams struct {
	Search    *string
	Status    *string
	Region    *string
	SortBy    string
	SortDir   string
	RowOffset int32
	RowLimit  int32
}

// Super Admin ro'yxati: nom bo'yicha qidiruv + obuna holati + region filtri.
// Saralash oq ro'yxati: name | created_at | subscription_end_at.
func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies,
		arg.Search,
		arg.Status,
		arg.Region,
		arg.SortBy,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.HomeTerminalAddress,
			&i.Timezone,
			&i.Email,
			&i.Phone,
			&i.RegistrationNo,
			&i.LogoKey,
			&i.Region,
			&i.UnitSystem,
			&i.RegulationProfile,
			&i.SubscriptionStatus,
			&i.SubscriptionEndAt,
			&i.Plan,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHosPolicyVersions = `-- name: ListHosPolicyVersions :many
SELECT id, company_id, effective_from, policy, created_by, created_at, updated_at, deleted_at FROM hos_policy_versions
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY effective_from DESC LIMIT $2 OFFSET $3
`

type ListHosPolicyVersionsParams struct {
	CompanyID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListHosPolicyVersions(ctx context.Context, arg ListHosPolicyVersionsParams) ([]HosPolicyVersion, error) {
	rows, err := q.db.Query(ctx, listHosPolicyVersions, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HosPolicyVersion{}
	for rows.Next() {
		var i HosPolicyVersion
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EffectiveFrom,
			&i.Policy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT key, value, description, created_at, updated_at FROM system_settings ORDER BY key
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBranch = `-- name: SoftDeleteBranch :exec
UPDATE branches SET deleted_at = now() WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteBranchParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteBranch(ctx context.Context, arg SoftDeleteBranchParams) error {
	_, err := q.db.Exec(ctx, softDeleteBranch, arg.CompanyID, arg.ID)
	return err
}

const softDeleteCompany = `-- name: SoftDeleteCompany :exec
UPDATE companies SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCompany, id)
	return err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches SET
  name     = COALESCE($1::text, name),
  address  = COALESCE($2::text, address),
  timezone = COALESCE($3::text, timezone)
WHERE company_id = $4 AND id = $5 AND deleted_at IS NULL
RETURNING id, company_id, name, address, timezone, created_at, updated_at, deleted_at
`

type UpdateBranchParams struct {
	Name      *string
	Address   *string
	Timezone  *string
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.Name,
		arg.Address,
		arg.Timezone,
		arg.CompanyID,
		arg.ID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies SET
  name                  = COALESCE($1::text, name),
  address               = COALESCE($2::text, address),
  home_terminal_address = COALESCE($3::text, home_terminal_address),
  timezone              = COALESCE($4::text, timezone),
  email                 = COALESCE($5::text, email),
  phone                 = COALESCE($6::text, phone),
  registration_no       = COALESCE($7::text, registration_no),
  logo_key              = COALESCE($8::text, logo_key),
  region                = COALESCE($9::text, region),
  unit_system           = COALESCE($10::text, unit_system),
  regulation_profile    = COALESCE($11::text, regulation_profile),
  plan                  = COALESCE($12::text, plan),
  settings              = settings || COALESCE($13::jsonb, '{}'::jsonb)
WHERE id = $14 AND deleted_at IS NULL
RETURNING id, name, address, home_terminal_address, timezone, email, phone, registration_no, logo_key, region, unit_system, regulation_profile, subscription_status, subscription_end_at, plan, settings, created_at, updated_at, deleted_at
`

type UpdateCompanyParams struct {
	Name                *string
	Address             *string
	HomeTerminalAddress *string
	Timezone            *string
	Email               *string
	Phone               *string
	RegistrationNo      *string
	LogoKey             *string
	Region              *string
	UnitSystem          *string
	RegulationProfile   *string
	Plan                *string
	Settings            []byte
	ID                  uuid.UUID
}

// Qisman yangilash: berilmagan maydon NULL bo'lib keladi va tegilmaydi.
func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.Address,
		arg.HomeTerminalAddress,
		arg.Timezone,
		arg.Email,
		arg.Phone,
		arg.RegistrationNo,
		arg.LogoKey,
		arg.Region,
		arg.UnitSystem,
		arg.RegulationProfile,
		arg.Plan,
		arg.Settings,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.HomeTerminalAddress,
		&i.Timezone,
		&i.Email,
		&i.Phone,
		&i.RegistrationNo,
		&i.LogoKey,
		&i.Region,
		&i.UnitSystem,
		&i.RegulationProfile,
		&i.SubscriptionStatus,
		&i.SubscriptionEndAt,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCompanySettings = `-- name: UpdateCompanySettings :one
UPDATE companies SET settings = settings || $2::jsonb
WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, address, home_terminal_address, timezone, email, phone, registration_no, logo_key, region, unit_system, regulation_profile, subscription_status, subscription_end_at, plan, settings, created_at, updated_at, deleted_at
`

type UpdateCompanySettingsParams struct {
	ID      uuid.UUID
	Column2 []byte
}

func (q *Queries) UpdateCompanySettings(ctx context.Context, arg UpdateCompanySettingsParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompanySettings, arg.ID, arg.Column2)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.HomeTerminalAddress,
		&i.Timezone,
		&i.Email,
		&i.Phone,
		&i.RegistrationNo,
		&i.LogoKey,
		&i.Region,
		&i.UnitSystem,
		&i.RegulationProfile,
		&i.SubscriptionStatus,
		&i.SubscriptionEndAt,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCompanySubscription = `-- name: UpdateCompanySubscription :one
UPDATE companies SET
  subscription_status = COALESCE($1::text, subscription_status),
  subscription_end_at = CASE WHEN $2::boolean THEN NULL
                             ELSE COALESCE($3::timestamptz, subscription_end_at) END,
  plan                = COALESCE($4::text, plan)
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, name, address, home_terminal_address, timezone, email, phone, registration_no, logo_key, region, unit_system, regulation_profile, subscription_status, subscription_end_at, plan, settings, created_at, updated_at, deleted_at
`

type UpdateCompanySubscriptionParams struct {
	SubscriptionStatus *string
	ClearEndAt         bool
	SubscriptionEndAt  pgtype.Timestamptz
	Plan               *string
	ID                 uuid.UUID
}

func (q *Queries) UpdateCompanySubscription(ctx context.Context, arg UpdateCompanySubscriptionParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompanySubscription,
		arg.SubscriptionStatus,
		arg.ClearEndAt,
		arg.SubscriptionEndAt,
		arg.Plan,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.HomeTerminalAddress,
		&i.Timezone,
		&i.Email,
		&i.Phone,
		&i.RegistrationNo,
		&i.LogoKey,
		&i.Region,
		&i.UnitSystem,
		&i.RegulationProfile,
		&i.SubscriptionStatus,
		&i.SubscriptionEndAt,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value, description) VALUES ($1,$2,$3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    description = COALESCE(EXCLUDED.description, system_settings.description)
RETURNING key, value, description, created_at, updated_at
`

type UpsertSystemSettingParams struct {
	Key         string
	Value       []byte
	Description *string
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Key, arg.Value, arg.Description)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
