// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_logs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const certifyDailyLog = `-- name: CertifyDailyLog :one
UPDATE daily_logs SET
  certification_status = 'certified',
  signed_at = now(),
  signature_key = $3,
  signed_device_id = $4
WHERE company_id = $1 AND id = $2
RETURNING id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by
`

type CertifyDailyLogParams struct {
	CompanyID      uuid.UUID
	ID             uuid.UUID
	SignatureKey   *string
	SignedDeviceID *string
}

func (q *Queries) CertifyDailyLog(ctx context.Context, arg CertifyDailyLogParams) (DailyLog, error) {
	row := q.db.QueryRow(ctx, certifyDailyLog,
		arg.CompanyID,
		arg.ID,
		arg.SignatureKey,
		arg.SignedDeviceID,
	)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
	)
	return i, err
}

const countDailyLogs = `-- name: CountDailyLogs :one
SELECT count(*) FROM daily_logs l
WHERE l.company_id = $1
  AND l.log_date >= $2 AND l.log_date <= $3
  AND ($4::uuid IS NULL OR l.driver_id = $4::uuid)
  AND ($5::text IS NULL OR l.certification_status = $5::text)
`

type CountDailyLogsParams struct {
	CompanyID uuid.UUID
	LogDate   pgtype.Date
	LogDate_2 pgtype.Date
	Column4   uuid.UUID
	Column5   string
}

func (q *Queries) CountDailyLogs(ctx context.Context, arg CountDailyLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDailyLogs,
		arg.CompanyID,
		arg.LogDate,
		arg.LogDate_2,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDriverDailyLogs = `-- name: CountDriverDailyLogs :one
SELECT count(*) FROM daily_logs
WHERE company_id = $1 AND driver_id = $2 AND log_date >= $3 AND log_date <= $4
`

type CountDriverDailyLogsParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	LogDate   pgtype.Date
	LogDate_2 pgtype.Date
}

func (q *Queries) CountDriverDailyLogs(ctx context.Context, arg CountDriverDailyLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDriverDailyLogs,
		arg.CompanyID,
		arg.DriverID,
		arg.LogDate,
		arg.LogDate_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDailyLog = `-- name: CreateDailyLog :one
INSERT INTO daily_logs (
  company_id, driver_id, log_date, timezone, unit_ids, co_driver_id,
  distance_m, trailer_ids, shipping_doc_ids, totals, certification_status
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by
`

type CreateDailyLogParams struct {
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	Timezone            string
	UnitIds             []uuid.UUID
	CoDriverID          pgtype.UUID
	DistanceM           int64
	TrailerIds          []uuid.UUID
	ShippingDocIds      []uuid.UUID
	Totals              []byte
	CertificationStatus string
}

func (q *Queries) CreateDailyLog(ctx context.Context, arg CreateDailyLogParams) (DailyLog, error) {
	row := q.db.QueryRow(ctx, createDailyLog,
		arg.CompanyID,
		arg.DriverID,
		arg.LogDate,
		arg.Timezone,
		arg.UnitIds,
		arg.CoDriverID,
		arg.DistanceM,
		arg.TrailerIds,
		arg.ShippingDocIds,
		arg.Totals,
		arg.CertificationStatus,
	)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
	)
	return i, err
}

const getDailyLog = `-- name: GetDailyLog :one
SELECT id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by FROM daily_logs WHERE company_id = $1 AND id = $2
`

type GetDailyLogParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetDailyLog(ctx context.Context, arg GetDailyLogParams) (DailyLog, error) {
	row := q.db.QueryRow(ctx, getDailyLog, arg.CompanyID, arg.ID)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
	)
	return i, err
}

const getDailyLogByDate = `-- name: GetDailyLogByDate :one
SELECT id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by FROM daily_logs WHERE company_id = $1 AND driver_id = $2 AND log_date = $3
`

type GetDailyLogByDateParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	LogDate   pgtype.Date
}

func (q *Queries) GetDailyLogByDate(ctx context.Context, arg GetDailyLogByDateParams) (DailyLog, error) {
	row := q.db.QueryRow(ctx, getDailyLogByDate, arg.CompanyID, arg.DriverID, arg.LogDate)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
	)
	return i, err
}

const getOrCreateDailyLog = `-- name: GetOrCreateDailyLog :one
INSERT INTO daily_logs (company_id, driver_id, log_date, timezone)
VALUES ($1,$2,$3,$4)
ON CONFLICT (driver_id, log_date) DO UPDATE SET updated_at = now()
RETURNING id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by
`

type GetOrCreateDailyLogParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	LogDate   pgtype.Date
	Timezone  string
}

func (q *Queries) GetOrCreateDailyLog(ctx context.Context, arg GetOrCreateDailyLogParams) (DailyLog, error) {
	row := q.db.QueryRow(ctx, getOrCreateDailyLog,
		arg.CompanyID,
		arg.DriverID,
		arg.LogDate,
		arg.Timezone,
	)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
	)
	return i, err
}

const listDailyLogs = `-- name: ListDailyLogs :many
SELECT l.id, l.company_id, l.driver_id, l.log_date, l.timezone, l.unit_ids, l.co_driver_id, l.distance_m, l.trailer_ids, l.shipping_doc_ids, l.totals, l.certification_status, l.signed_at, l.signature_key, l.signed_device_id, l.created_at, l.updated_at, l.signed_ip, l.signed_by, u.first_name, u.last_name
FROM daily_logs l
JOIN drivers d ON d.id = l.driver_id
JOIN users   u ON u.id = d.user_id
WHERE l.company_id = $1
  AND l.log_date >= $2 AND l.log_date <= $3
  AND ($4::uuid IS NULL OR l.driver_id = $4::uuid)
  AND ($5::text IS NULL OR l.certification_status = $5::text)
ORDER BY l.log_date DESC, u.last_name
LIMIT $6 OFFSET $7
`

type ListDailyLogsParams struct {
	CompanyID uuid.UUID
	LogDate   pgtype.Date
	LogDate_2 pgtype.Date
	Column4   uuid.UUID
	Column5   string
	Limit     int32
	Offset    int32
}

type ListDailyLogsRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	Timezone            string
	UnitIds             []uuid.UUID
	CoDriverID          pgtype.UUID
	DistanceM           int64
	TrailerIds          []uuid.UUID
	ShippingDocIds      []uuid.UUID
	Totals              []byte
	CertificationStatus string
	SignedAt            pgtype.Timestamptz
	SignatureKey        *string
	SignedDeviceID      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SignedIp            *string
	SignedBy            pgtype.UUID
	FirstName           string
	LastName            string
}

func (q *Queries) ListDailyLogs(ctx context.Context, arg ListDailyLogsParams) ([]ListDailyLogsRow, error) {
	rows, err := q.db.Query(ctx, listDailyLogs,
		arg.CompanyID,
		arg.LogDate,
		arg.LogDate_2,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyLogsRow{}
	for rows.Next() {
		var i ListDailyLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.LogDate,
			&i.Timezone,
			&i.UnitIds,
			&i.CoDriverID,
			&i.DistanceM,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.Totals,
			&i.CertificationStatus,
			&i.SignedAt,
			&i.SignatureKey,
			&i.SignedDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SignedIp,
			&i.SignedBy,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLogsChangedSince = `-- name: ListDailyLogsChangedSince :many
SELECT id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by FROM daily_logs
WHERE company_id = $1 AND driver_id = $2 AND updated_at > $3
ORDER BY updated_at LIMIT $4
`

type ListDailyLogsChangedSinceParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	UpdatedAt time.Time
	Limit     int32
}

func (q *Queries) ListDailyLogsChangedSince(ctx context.Context, arg ListDailyLogsChangedSinceParams) ([]DailyLog, error) {
	rows, err := q.db.Query(ctx, listDailyLogsChangedSince,
		arg.CompanyID,
		arg.DriverID,
		arg.UpdatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyLog{}
	for rows.Next() {
		var i DailyLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.LogDate,
			&i.Timezone,
			&i.UnitIds,
			&i.CoDriverID,
			&i.DistanceM,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.Totals,
			&i.CertificationStatus,
			&i.SignedAt,
			&i.SignatureKey,
			&i.SignedDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SignedIp,
			&i.SignedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriverDailyLogs = `-- name: ListDriverDailyLogs :many
SELECT id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by FROM daily_logs
WHERE company_id = $1 AND driver_id = $2 AND log_date >= $3 AND log_date <= $4
ORDER BY log_date DESC LIMIT $5 OFFSET $6
`

type ListDriverDailyLogsParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	LogDate   pgtype.Date
	LogDate_2 pgtype.Date
	Limit     int32
	Offset    int32
}

func (q *Queries) ListDriverDailyLogs(ctx context.Context, arg ListDriverDailyLogsParams) ([]DailyLog, error) {
	rows, err := q.db.Query(ctx, listDriverDailyLogs,
		arg.CompanyID,
		arg.DriverID,
		arg.LogDate,
		arg.LogDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyLog{}
	for rows.Next() {
		var i DailyLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.LogDate,
			&i.Timezone,
			&i.UnitIds,
			&i.CoDriverID,
			&i.DistanceM,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.Totals,
			&i.CertificationStatus,
			&i.SignedAt,
			&i.SignatureKey,
			&i.SignedDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SignedIp,
			&i.SignedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncertifiedLogs = `-- name: ListUncertifiedLogs :many
SELECT l.id, l.company_id, l.driver_id, l.log_date, l.timezone, l.unit_ids, l.co_driver_id, l.distance_m, l.trailer_ids, l.shipping_doc_ids, l.totals, l.certification_status, l.signed_at, l.signature_key, l.signed_device_id, l.created_at, l.updated_at, l.signed_ip, l.signed_by, u.first_name, u.last_name
FROM daily_logs l
JOIN drivers d ON d.id = l.driver_id
JOIN users   u ON u.id = d.user_id
WHERE l.company_id = $1
  AND l.certification_status <> 'certified'
  AND l.log_date >= (CURRENT_DATE - ($2::int))
  AND l.log_date < CURRENT_DATE
ORDER BY l.log_date DESC
LIMIT $3 OFFSET $4
`

type ListUncertifiedLogsParams struct {
	CompanyID uuid.UUID
	Column2   int32
	Limit     int32
	Offset    int32
}

type ListUncertifiedLogsRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	Timezone            string
	UnitIds             []uuid.UUID
	CoDriverID          pgtype.UUID
	DistanceM           int64
	TrailerIds          []uuid.UUID
	ShippingDocIds      []uuid.UUID
	Totals              []byte
	CertificationStatus string
	SignedAt            pgtype.Timestamptz
	SignatureKey        *string
	SignedDeviceID      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SignedIp            *string
	SignedBy            pgtype.UUID
	FirstName           string
	LastName            string
}

func (q *Queries) ListUncertifiedLogs(ctx context.Context, arg ListUncertifiedLogsParams) ([]ListUncertifiedLogsRow, error) {
	rows, err := q.db.Query(ctx, listUncertifiedLogs,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUncertifiedLogsRow{}
	for rows.Next() {
		var i ListUncertifiedLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.LogDate,
			&i.Timezone,
			&i.UnitIds,
			&i.CoDriverID,
			&i.DistanceM,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.Totals,
			&i.CertificationStatus,
			&i.SignedAt,
			&i.SignatureKey,
			&i.SignedDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SignedIp,
			&i.SignedBy,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDailyLogNeedsRecertify = `-- name: MarkDailyLogNeedsRecertify :exec
UPDATE daily_logs SET certification_status = 'needs_recertify'
WHERE company_id = $1 AND id = $2 AND certification_status = 'certified'
`

type MarkDailyLogNeedsRecertifyParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkDailyLogNeedsRecertify(ctx context.Context, arg MarkDailyLogNeedsRecertifyParams) error {
	_, err := q.db.Exec(ctx, markDailyLogNeedsRecertify, arg.CompanyID, arg.ID)
	return err
}

const updateDailyLogTotals = `-- name: UpdateDailyLogTotals :one
UPDATE daily_logs SET
  totals           = $3,
  distance_m       = $4,
  unit_ids         = $5,
  trailer_ids      = $6,
  shipping_doc_ids = $7,
  co_driver_id     = $8
WHERE company_id = $1 AND id = $2
RETURNING id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by
`

type UpdateDailyLogTotalsParams struct {
	CompanyID      uuid.UUID
	ID             uuid.UUID
	Totals         []byte
	DistanceM      int64
	UnitIds        []uuid.UUID
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	CoDriverID     pgtype.UUID
}

func (q *Queries) UpdateDailyLogTotals(ctx context.Context, arg UpdateDailyLogTotalsParams) (DailyLog, error) {
	row := q.db.QueryRow(ctx, updateDailyLogTotals,
		arg.CompanyID,
		arg.ID,
		arg.Totals,
		arg.DistanceM,
		arg.UnitIds,
		arg.TrailerIds,
		arg.ShippingDocIds,
		arg.CoDriverID,
	)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
	)
	return i, err
}
