// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drivers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultSignature = `-- name: ClearDefaultSignature :exec
UPDATE signatures SET is_default = false
WHERE company_id = $1 AND user_id = $2 AND is_default AND deleted_at IS NULL
`

type ClearDefaultSignatureParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) ClearDefaultSignature(ctx context.Context, arg ClearDefaultSignatureParams) error {
	_, err := q.db.Exec(ctx, clearDefaultSignature, arg.CompanyID, arg.UserID)
	return err
}

const countDriverActivities = `-- name: CountDriverActivities :one
SELECT ((
  SELECT count(*) FROM audit_log a
  WHERE a.company_id = $1::uuid
    AND ((a.table_name = 'drivers' AND a.record_id = $2::uuid)
      OR (a.table_name = 'users'   AND a.record_id = $3::uuid)
      OR (a.edited_by = $3::uuid))
) + (
  SELECT count(*) FROM sessions s
  WHERE s.company_id = $1::uuid AND s.user_id = $3::uuid
))::bigint AS total
`

type CountDriverActivitiesParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CountDriverActivities(ctx context.Context, arg CountDriverActivitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDriverActivities, arg.CompanyID, arg.DriverID, arg.UserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDrivers = `-- name: CountDrivers :one
SELECT count(*)
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.company_id = $1 AND d.deleted_at IS NULL
  AND ($2::text IS NULL OR (u.first_name || ' ' || u.last_name || ' ' || u.username) ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR d.status = $3::text)
  AND ($4::uuid IS NULL OR d.branch_id = $4::uuid)
  AND ($5::uuid IS NULL OR d.fleet_manager_id = $5::uuid)
`

type CountDriversParams struct {
	CompanyID uuid.UUID
	Column2   string
	Column3   string
	Column4   uuid.UUID
	Column5   uuid.UUID
}

func (q *Queries) CountDrivers(ctx context.Context, arg CountDriversParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDrivers,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDriversPage = `-- name: CountDriversPage :one
SELECT count(*)
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.company_id = $1::uuid
  AND d.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (u.first_name || ' ' || u.last_name || ' ' || u.username
           || ' ' || COALESCE(u.email,'') || ' ' || COALESCE(u.phone,''))
          ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR d.status = $3::text)
  AND ($4::uuid IS NULL OR d.branch_id = $4::uuid)
  AND ($5::uuid IS NULL OR d.fleet_manager_id = $5::uuid)
  AND ($6::bool OR d.status <> 'inactive')
`

type CountDriversPageParams struct {
	CompanyID       uuid.UUID
	Search          *string
	Status          *string
	BranchID        pgtype.UUID
	FleetManagerID  pgtype.UUID
	IncludeInactive bool
}

func (q *Queries) CountDriversPage(ctx context.Context, arg CountDriversPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDriversPage,
		arg.CompanyID,
		arg.Search,
		arg.Status,
		arg.BranchID,
		arg.FleetManagerID,
		arg.IncludeInactive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers (
  company_id, user_id, branch_id, license_no_enc, license_region, home_terminal,
  city, state, zip, address1, address2, notes, fleet_manager_id, default_unit_id, status, activated_on
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
RETURNING id, company_id, user_id, branch_id, license_no_enc, license_region, home_terminal, city, state, zip, address1, address2, notes, fleet_manager_id, default_unit_id, status, app_version, activated_on, created_at, updated_at, deleted_at
`

type CreateDriverParams struct {
	CompanyID      uuid.UUID
	UserID         uuid.UUID
	BranchID       pgtype.UUID
	LicenseNoEnc   *string
	LicenseRegion  *string
	HomeTerminal   *string
	City           *string
	State          *string
	Zip            *string
	Address1       *string
	Address2       *string
	Notes          *string
	FleetManagerID pgtype.UUID
	DefaultUnitID  pgtype.UUID
	Status         string
	ActivatedOn    pgtype.Timestamptz
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.CompanyID,
		arg.UserID,
		arg.BranchID,
		arg.LicenseNoEnc,
		arg.LicenseRegion,
		arg.HomeTerminal,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Address1,
		arg.Address2,
		arg.Notes,
		arg.FleetManagerID,
		arg.DefaultUnitID,
		arg.Status,
		arg.ActivatedOn,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.LicenseNoEnc,
		&i.LicenseRegion,
		&i.HomeTerminal,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Address1,
		&i.Address2,
		&i.Notes,
		&i.FleetManagerID,
		&i.DefaultUnitID,
		&i.Status,
		&i.AppVersion,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDriverPair = `-- name: CreateDriverPair :one
INSERT INTO driver_pairs (company_id, driver_a_id, driver_b_id)
VALUES ($1, LEAST($2::uuid,$3::uuid), GREATEST($2::uuid,$3::uuid))
RETURNING id, company_id, driver_a_id, driver_b_id, created_at, updated_at, deleted_at
`

type CreateDriverPairParams struct {
	CompanyID uuid.UUID
	Column2   uuid.UUID
	Column3   uuid.UUID
}

func (q *Queries) CreateDriverPair(ctx context.Context, arg CreateDriverPairParams) (DriverPair, error) {
	row := q.db.QueryRow(ctx, createDriverPair, arg.CompanyID, arg.Column2, arg.Column3)
	var i DriverPair
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverAID,
		&i.DriverBID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSignature = `-- name: CreateSignature :one
INSERT INTO signatures (company_id, user_id, image_key_enc, is_default)
VALUES ($1,$2,$3,$4) RETURNING id, company_id, user_id, image_key_enc, is_default, created_at, updated_at, deleted_at
`

type CreateSignatureParams struct {
	CompanyID   uuid.UUID
	UserID      uuid.UUID
	ImageKeyEnc string
	IsDefault   bool
}

func (q *Queries) CreateSignature(ctx context.Context, arg CreateSignatureParams) (Signature, error) {
	row := q.db.QueryRow(ctx, createSignature,
		arg.CompanyID,
		arg.UserID,
		arg.ImageKeyEnc,
		arg.IsDefault,
	)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.ImageKeyEnc,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDriverPair = `-- name: DeleteDriverPair :exec
UPDATE driver_pairs SET deleted_at = now()
WHERE company_id = $1
  AND driver_a_id = LEAST($2::uuid,$3::uuid)
  AND driver_b_id = GREATEST($2::uuid,$3::uuid)
  AND deleted_at IS NULL
`

type DeleteDriverPairParams struct {
	CompanyID uuid.UUID
	Column2   uuid.UUID
	Column3   uuid.UUID
}

func (q *Queries) DeleteDriverPair(ctx context.Context, arg DeleteDriverPairParams) error {
	_, err := q.db.Exec(ctx, deleteDriverPair, arg.CompanyID, arg.Column2, arg.Column3)
	return err
}

const getDefaultSignature = `-- name: GetDefaultSignature :one
SELECT id, company_id, user_id, image_key_enc, is_default, created_at, updated_at, deleted_at FROM signatures
WHERE company_id = $1 AND user_id = $2 AND is_default AND deleted_at IS NULL
`

type GetDefaultSignatureParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetDefaultSignature(ctx context.Context, arg GetDefaultSignatureParams) (Signature, error) {
	row := q.db.QueryRow(ctx, getDefaultSignature, arg.CompanyID, arg.UserID)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.ImageKeyEnc,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriver = `-- name: GetDriver :one
SELECT id, company_id, user_id, branch_id, license_no_enc, license_region, home_terminal, city, state, zip, address1, address2, notes, fleet_manager_id, default_unit_id, status, app_version, activated_on, created_at, updated_at, deleted_at FROM drivers WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetDriverParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetDriver(ctx context.Context, arg GetDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriver, arg.CompanyID, arg.ID)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.LicenseNoEnc,
		&i.LicenseRegion,
		&i.HomeTerminal,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Address1,
		&i.Address2,
		&i.Notes,
		&i.FleetManagerID,
		&i.DefaultUnitID,
		&i.Status,
		&i.AppVersion,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverByUserID = `-- name: GetDriverByUserID :one
SELECT id, company_id, user_id, branch_id, license_no_enc, license_region, home_terminal, city, state, zip, address1, address2, notes, fleet_manager_id, default_unit_id, status, app_version, activated_on, created_at, updated_at, deleted_at FROM drivers WHERE company_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetDriverByUserIDParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetDriverByUserID(ctx context.Context, arg GetDriverByUserIDParams) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriverByUserID, arg.CompanyID, arg.UserID)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.LicenseNoEnc,
		&i.LicenseRegion,
		&i.HomeTerminal,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Address1,
		&i.Address2,
		&i.Notes,
		&i.FleetManagerID,
		&i.DefaultUnitID,
		&i.Status,
		&i.AppVersion,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverDetail = `-- name: GetDriverDetail :one
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.license_no_enc, d.license_region, d.home_terminal, d.city, d.state, d.zip, d.address1, d.address2, d.notes, d.fleet_manager_id, d.default_unit_id, d.status, d.app_version, d.activated_on, d.created_at, d.updated_at, d.deleted_at,
       u.first_name, u.last_name, u.username, u.email, u.phone,
       u.status AS user_status, u.last_login_at,
       fm.first_name AS fleet_manager_first_name,
       fm.last_name  AS fleet_manager_last_name,
       un.unit_number AS default_unit_number,
       b.name AS branch_name
FROM drivers d
JOIN users u ON u.id = d.user_id
LEFT JOIN users fm ON fm.id = d.fleet_manager_id
LEFT JOIN units un ON un.id = d.default_unit_id
LEFT JOIN branches b ON b.id = d.branch_id
WHERE d.company_id = $1::uuid AND d.id = $2::uuid AND d.deleted_at IS NULL
`

type GetDriverDetailParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetDriverDetailRow struct {
	ID                    uuid.UUID
	CompanyID             uuid.UUID
	UserID                uuid.UUID
	BranchID              pgtype.UUID
	LicenseNoEnc          *string
	LicenseRegion         *string
	HomeTerminal          *string
	City                  *string
	State                 *string
	Zip                   *string
	Address1              *string
	Address2              *string
	Notes                 *string
	FleetManagerID        pgtype.UUID
	DefaultUnitID         pgtype.UUID
	Status                string
	AppVersion            *string
	ActivatedOn           pgtype.Timestamptz
	CreatedAt             time.Time
	UpdatedAt             time.Time
	DeletedAt             pgtype.Timestamptz
	FirstName             string
	LastName              string
	Username              string
	Email                 *string
	Phone                 *string
	UserStatus            string
	LastLoginAt           pgtype.Timestamptz
	FleetManagerFirstName *string
	FleetManagerLastName  *string
	DefaultUnitNumber     *string
	BranchName            *string
}

func (q *Queries) GetDriverDetail(ctx context.Context, arg GetDriverDetailParams) (GetDriverDetailRow, error) {
	row := q.db.QueryRow(ctx, getDriverDetail, arg.CompanyID, arg.ID)
	var i GetDriverDetailRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.LicenseNoEnc,
		&i.LicenseRegion,
		&i.HomeTerminal,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Address1,
		&i.Address2,
		&i.Notes,
		&i.FleetManagerID,
		&i.DefaultUnitID,
		&i.Status,
		&i.AppVersion,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.UserStatus,
		&i.LastLoginAt,
		&i.FleetManagerFirstName,
		&i.FleetManagerLastName,
		&i.DefaultUnitNumber,
		&i.BranchName,
	)
	return i, err
}

const getDriverPairAny = `-- name: GetDriverPairAny :one
SELECT id, company_id, driver_a_id, driver_b_id, created_at, updated_at, deleted_at FROM driver_pairs
WHERE company_id = $1::uuid
  AND driver_a_id = LEAST($2::uuid, $3::uuid)
  AND driver_b_id = GREATEST($2::uuid, $3::uuid)
`

type GetDriverPairAnyParams struct {
	CompanyID uuid.UUID
	DriverA   uuid.UUID
	DriverB   uuid.UUID
}

// Soft-delete qilingan juftlikni ham qaytaradi (qayta tiklash uchun).
func (q *Queries) GetDriverPairAny(ctx context.Context, arg GetDriverPairAnyParams) (DriverPair, error) {
	row := q.db.QueryRow(ctx, getDriverPairAny, arg.CompanyID, arg.DriverA, arg.DriverB)
	var i DriverPair
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverAID,
		&i.DriverBID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCoDriverDetails = `-- name: ListCoDriverDetails :many
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.license_no_enc, d.license_region, d.home_terminal, d.city, d.state, d.zip, d.address1, d.address2, d.notes, d.fleet_manager_id, d.default_unit_id, d.status, d.app_version, d.activated_on, d.created_at, d.updated_at, d.deleted_at,
       u.first_name, u.last_name, u.username, u.email, u.phone,
       u.status AS user_status, u.last_login_at,
       p.id AS pair_id, p.created_at AS paired_at
FROM driver_pairs p
JOIN drivers d ON d.id = CASE WHEN p.driver_a_id = $1::uuid THEN p.driver_b_id ELSE p.driver_a_id END
JOIN users u ON u.id = d.user_id
WHERE p.company_id = $2::uuid
  AND p.deleted_at IS NULL AND d.deleted_at IS NULL
  AND (p.driver_a_id = $1::uuid OR p.driver_b_id = $1::uuid)
ORDER BY u.last_name, u.first_name
`

type ListCoDriverDetailsParams struct {
	DriverID  uuid.UUID
	CompanyID uuid.UUID
}

type ListCoDriverDetailsRow struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	UserID         uuid.UUID
	BranchID       pgtype.UUID
	LicenseNoEnc   *string
	LicenseRegion  *string
	HomeTerminal   *string
	City           *string
	State          *string
	Zip            *string
	Address1       *string
	Address2       *string
	Notes          *string
	FleetManagerID pgtype.UUID
	DefaultUnitID  pgtype.UUID
	Status         string
	AppVersion     *string
	ActivatedOn    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
	FirstName      string
	LastName       string
	Username       string
	Email          *string
	Phone          *string
	UserStatus     string
	LastLoginAt    pgtype.Timestamptz
	PairID         uuid.UUID
	PairedAt       time.Time
}

func (q *Queries) ListCoDriverDetails(ctx context.Context, arg ListCoDriverDetailsParams) ([]ListCoDriverDetailsRow, error) {
	rows, err := q.db.Query(ctx, listCoDriverDetails, arg.DriverID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoDriverDetailsRow{}
	for rows.Next() {
		var i ListCoDriverDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.BranchID,
			&i.LicenseNoEnc,
			&i.LicenseRegion,
			&i.HomeTerminal,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Address1,
			&i.Address2,
			&i.Notes,
			&i.FleetManagerID,
			&i.DefaultUnitID,
			&i.Status,
			&i.AppVersion,
			&i.ActivatedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.UserStatus,
			&i.LastLoginAt,
			&i.PairID,
			&i.PairedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoDrivers = `-- name: ListCoDrivers :many
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.license_no_enc, d.license_region, d.home_terminal, d.city, d.state, d.zip, d.address1, d.address2, d.notes, d.fleet_manager_id, d.default_unit_id, d.status, d.app_version, d.activated_on, d.created_at, d.updated_at, d.deleted_at
FROM driver_pairs p
JOIN drivers d ON d.id = CASE WHEN p.driver_a_id = $2 THEN p.driver_b_id ELSE p.driver_a_id END
WHERE p.company_id = $1 AND p.deleted_at IS NULL AND d.deleted_at IS NULL
  AND (p.driver_a_id = $2 OR p.driver_b_id = $2)
`

type ListCoDriversParams struct {
	CompanyID uuid.UUID
	DriverAID uuid.UUID
}

func (q *Queries) ListCoDrivers(ctx context.Context, arg ListCoDriversParams) ([]Driver, error) {
	rows, err := q.db.Query(ctx, listCoDrivers, arg.CompanyID, arg.DriverAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Driver{}
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.BranchID,
			&i.LicenseNoEnc,
			&i.LicenseRegion,
			&i.HomeTerminal,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Address1,
			&i.Address2,
			&i.Notes,
			&i.FleetManagerID,
			&i.DefaultUnitID,
			&i.Status,
			&i.AppVersion,
			&i.ActivatedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriverActivities = `-- name: ListDriverActivities :many
SELECT act.id, act.occurred_at, act.action, act.table_name, act.field,
       act.old_value, act.new_value, act.ip, act.user_agent, act.actor_id
FROM (
  SELECT a.id                AS id,
         a.ts                AS occurred_at,
         a.action            AS action,
         a.table_name        AS table_name,
         a.field             AS field,
         a.old_value         AS old_value,
         a.new_value         AS new_value,
         COALESCE(host(a.ip), '')::text AS ip,
         a.user_agent        AS user_agent,
         a.edited_by         AS actor_id
  FROM audit_log a
  WHERE a.company_id = $1::uuid
    AND ((a.table_name = 'drivers' AND a.record_id = $2::uuid)
      OR (a.table_name = 'users'   AND a.record_id = $3::uuid)
      OR (a.edited_by = $3::uuid))
  UNION ALL
  SELECT s.id,
         COALESCE(s.last_seen_at, s.created_at),
         'session_' || s.status,
         'sessions',
         s.device_type,
         NULL::jsonb,
         NULL::jsonb,
         COALESCE(host(s.ip), '')::text,
         s.user_agent,
         s.user_id
  FROM sessions s
  WHERE s.company_id = $1::uuid AND s.user_id = $3::uuid
) act
ORDER BY act.occurred_at DESC
LIMIT $5 OFFSET $4
`

type ListDriverActivitiesParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	UserID    uuid.UUID
	Off       int32
	Lim       int32
}

type ListDriverActivitiesRow struct {
	ID         uuid.UUID
	OccurredAt time.Time
	Action     string
	TableName  string
	Field      *string
	OldValue   []byte
	NewValue   []byte
	Ip         string
	UserAgent  *string
	ActorID    pgtype.UUID
}

func (q *Queries) ListDriverActivities(ctx context.Context, arg ListDriverActivitiesParams) ([]ListDriverActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listDriverActivities,
		arg.CompanyID,
		arg.DriverID,
		arg.UserID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriverActivitiesRow{}
	for rows.Next() {
		var i ListDriverActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Action,
			&i.TableName,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.Ip,
			&i.UserAgent,
			&i.ActorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrivers = `-- name: ListDrivers :many
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.license_no_enc, d.license_region, d.home_terminal, d.city, d.state, d.zip, d.address1, d.address2, d.notes, d.fleet_manager_id, d.default_unit_id, d.status, d.app_version, d.activated_on, d.created_at, d.updated_at, d.deleted_at, u.first_name, u.last_name, u.username, u.email, u.phone
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.company_id = $1 AND d.deleted_at IS NULL
  AND ($2::text IS NULL OR (u.first_name || ' ' || u.last_name || ' ' || u.username) ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR d.status = $3::text)
  AND ($4::uuid IS NULL OR d.branch_id = $4::uuid)
  AND ($5::uuid IS NULL OR d.fleet_manager_id = $5::uuid)
ORDER BY u.last_name, u.first_name
LIMIT $6 OFFSET $7
`

type ListDriversParams struct {
	CompanyID uuid.UUID
	Column2   string
	Column3   string
	Column4   uuid.UUID
	Column5   uuid.UUID
	Limit     int32
	Offset    int32
}

type ListDriversRow struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	UserID         uuid.UUID
	BranchID       pgtype.UUID
	LicenseNoEnc   *string
	LicenseRegion  *string
	HomeTerminal   *string
	City           *string
	State          *string
	Zip            *string
	Address1       *string
	Address2       *string
	Notes          *string
	FleetManagerID pgtype.UUID
	DefaultUnitID  pgtype.UUID
	Status         string
	AppVersion     *string
	ActivatedOn    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
	FirstName      string
	LastName       string
	Username       string
	Email          *string
	Phone          *string
}

func (q *Queries) ListDrivers(ctx context.Context, arg ListDriversParams) ([]ListDriversRow, error) {
	rows, err := q.db.Query(ctx, listDrivers,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriversRow{}
	for rows.Next() {
		var i ListDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.BranchID,
			&i.LicenseNoEnc,
			&i.LicenseRegion,
			&i.HomeTerminal,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Address1,
			&i.Address2,
			&i.Notes,
			&i.FleetManagerID,
			&i.DefaultUnitID,
			&i.Status,
			&i.AppVersion,
			&i.ActivatedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriversForExport = `-- name: ListDriversForExport :many
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.license_no_enc, d.license_region, d.home_terminal, d.city, d.state, d.zip, d.address1, d.address2, d.notes, d.fleet_manager_id, d.default_unit_id, d.status, d.app_version, d.activated_on, d.created_at, d.updated_at, d.deleted_at,
       u.first_name, u.last_name, u.username, u.email, u.phone,
       u.status AS user_status, u.last_login_at,
       fm.first_name AS fleet_manager_first_name,
       fm.last_name  AS fleet_manager_last_name,
       un.unit_number AS default_unit_number,
       b.name AS branch_name
FROM drivers d
JOIN users u ON u.id = d.user_id
LEFT JOIN users fm ON fm.id = d.fleet_manager_id
LEFT JOIN units un ON un.id = d.default_unit_id
LEFT JOIN branches b ON b.id = d.branch_id
WHERE d.company_id = $1::uuid
  AND d.deleted_at IS NULL
  AND ($2::text IS NULL OR d.status = $2::text)
  AND ($3::uuid IS NULL OR d.branch_id = $3::uuid)
  AND ($4::bool OR d.status <> 'inactive')
ORDER BY u.last_name, u.first_name
LIMIT $5
`

type ListDriversForExportParams struct {
	CompanyID       uuid.UUID
	Status          *string
	BranchID        pgtype.UUID
	IncludeInactive bool
	Lim             int32
}

type ListDriversForExportRow struct {
	ID                    uuid.UUID
	CompanyID             uuid.UUID
	UserID                uuid.UUID
	BranchID              pgtype.UUID
	LicenseNoEnc          *string
	LicenseRegion         *string
	HomeTerminal          *string
	City                  *string
	State                 *string
	Zip                   *string
	Address1              *string
	Address2              *string
	Notes                 *string
	FleetManagerID        pgtype.UUID
	DefaultUnitID         pgtype.UUID
	Status                string
	AppVersion            *string
	ActivatedOn           pgtype.Timestamptz
	CreatedAt             time.Time
	UpdatedAt             time.Time
	DeletedAt             pgtype.Timestamptz
	FirstName             string
	LastName              string
	Username              string
	Email                 *string
	Phone                 *string
	UserStatus            string
	LastLoginAt           pgtype.Timestamptz
	FleetManagerFirstName *string
	FleetManagerLastName  *string
	DefaultUnitNumber     *string
	BranchName            *string
}

func (q *Queries) ListDriversForExport(ctx context.Context, arg ListDriversForExportParams) ([]ListDriversForExportRow, error) {
	rows, err := q.db.Query(ctx, listDriversForExport,
		arg.CompanyID,
		arg.Status,
		arg.BranchID,
		arg.IncludeInactive,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriversForExportRow{}
	for rows.Next() {
		var i ListDriversForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.BranchID,
			&i.LicenseNoEnc,
			&i.LicenseRegion,
			&i.HomeTerminal,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Address1,
			&i.Address2,
			&i.Notes,
			&i.FleetManagerID,
			&i.DefaultUnitID,
			&i.Status,
			&i.AppVersion,
			&i.ActivatedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.UserStatus,
			&i.LastLoginAt,
			&i.FleetManagerFirstName,
			&i.FleetManagerLastName,
			&i.DefaultUnitNumber,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriversPage = `-- name: ListDriversPage :many

SELECT d.id, d.company_id, d.user_id, d.branch_id, d.license_no_enc, d.license_region, d.home_terminal, d.city, d.state, d.zip, d.address1, d.address2, d.notes, d.fleet_manager_id, d.default_unit_id, d.status, d.app_version, d.activated_on, d.created_at, d.updated_at, d.deleted_at,
       u.first_name, u.last_name, u.username, u.email, u.phone,
       u.status AS user_status, u.last_login_at,
       fm.first_name AS fleet_manager_first_name,
       fm.last_name  AS fleet_manager_last_name,
       un.unit_number AS default_unit_number,
       b.name AS branch_name
FROM drivers d
JOIN users u ON u.id = d.user_id
LEFT JOIN users fm ON fm.id = d.fleet_manager_id
LEFT JOIN units un ON un.id = d.default_unit_id
LEFT JOIN branches b ON b.id = d.branch_id
WHERE d.company_id = $1::uuid
  AND d.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (u.first_name || ' ' || u.last_name || ' ' || u.username
           || ' ' || COALESCE(u.email,'') || ' ' || COALESCE(u.phone,''))
          ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR d.status = $3::text)
  AND ($4::uuid IS NULL OR d.branch_id = $4::uuid)
  AND ($5::uuid IS NULL OR d.fleet_manager_id = $5::uuid)
  AND ($6::bool OR d.status <> 'inactive')
ORDER BY
  CASE WHEN $7::text = 'name.desc'       THEN u.last_name END DESC,
  CASE WHEN $7::text = 'username.asc'    THEN u.username END ASC,
  CASE WHEN $7::text = 'username.desc'   THEN u.username END DESC,
  CASE WHEN $7::text = 'status.asc'      THEN d.status END ASC,
  CASE WHEN $7::text = 'status.desc'     THEN d.status END DESC,
  CASE WHEN $7::text = 'created_at.asc'  THEN d.created_at END ASC,
  CASE WHEN $7::text = 'created_at.desc' THEN d.created_at END DESC,
  u.last_name, u.first_name
LIMIT $9 OFFSET $8
`

type ListDriversPageParams struct {
	CompanyID       uuid.UUID
	Search          *string
	Status          *string
	BranchID        pgtype.UUID
	FleetManagerID  pgtype.UUID
	IncludeInactive bool
	SortKey         string
	Off             int32
	Lim             int32
}

type ListDriversPageRow struct {
	ID                    uuid.UUID
	CompanyID             uuid.UUID
	UserID                uuid.UUID
	BranchID              pgtype.UUID
	LicenseNoEnc          *string
	LicenseRegion         *string
	HomeTerminal          *string
	City                  *string
	State                 *string
	Zip                   *string
	Address1              *string
	Address2              *string
	Notes                 *string
	FleetManagerID        pgtype.UUID
	DefaultUnitID         pgtype.UUID
	Status                string
	AppVersion            *string
	ActivatedOn           pgtype.Timestamptz
	CreatedAt             time.Time
	UpdatedAt             time.Time
	DeletedAt             pgtype.Timestamptz
	FirstName             string
	LastName              string
	Username              string
	Email                 *string
	Phone                 *string
	UserStatus            string
	LastLoginAt           pgtype.Timestamptz
	FleetManagerFirstName *string
	FleetManagerLastName  *string
	DefaultUnitNumber     *string
	BranchName            *string
}

// ---------------------------------------------------------------------------
// Driver Management (internal/domain/drivers). Barcha filtrlar `sqlc.narg` —
// NULL = filtr yo'q; saralash kaliti oq ro'yxatdan keladi (konkatenatsiya yo'q).
// ---------------------------------------------------------------------------
func (q *Queries) ListDriversPage(ctx context.Context, arg ListDriversPageParams) ([]ListDriversPageRow, error) {
	rows, err := q.db.Query(ctx, listDriversPage,
		arg.CompanyID,
		arg.Search,
		arg.Status,
		arg.BranchID,
		arg.FleetManagerID,
		arg.IncludeInactive,
		arg.SortKey,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriversPageRow{}
	for rows.Next() {
		var i ListDriversPageRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.BranchID,
			&i.LicenseNoEnc,
			&i.LicenseRegion,
			&i.HomeTerminal,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Address1,
			&i.Address2,
			&i.Notes,
			&i.FleetManagerID,
			&i.DefaultUnitID,
			&i.Status,
			&i.AppVersion,
			&i.ActivatedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.UserStatus,
			&i.LastLoginAt,
			&i.FleetManagerFirstName,
			&i.FleetManagerLastName,
			&i.DefaultUnitNumber,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatures = `-- name: ListSignatures :many
SELECT id, company_id, user_id, image_key_enc, is_default, created_at, updated_at, deleted_at FROM signatures WHERE company_id = $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListSignaturesParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) ListSignatures(ctx context.Context, arg ListSignaturesParams) ([]Signature, error) {
	rows, err := q.db.Query(ctx, listSignatures, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signature{}
	for rows.Next() {
		var i Signature
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.ImageKeyEnc,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDriverPair = `-- name: RestoreDriverPair :one
UPDATE driver_pairs SET deleted_at = NULL
WHERE company_id = $1::uuid AND id = $2::uuid
RETURNING id, company_id, driver_a_id, driver_b_id, created_at, updated_at, deleted_at
`

type RestoreDriverPairParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) RestoreDriverPair(ctx context.Context, arg RestoreDriverPairParams) (DriverPair, error) {
	row := q.db.QueryRow(ctx, restoreDriverPair, arg.CompanyID, arg.ID)
	var i DriverPair
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverAID,
		&i.DriverBID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setDriverAppVersion = `-- name: SetDriverAppVersion :exec
UPDATE drivers SET app_version = $3 WHERE company_id = $1 AND id = $2
`

type SetDriverAppVersionParams struct {
	CompanyID  uuid.UUID
	ID         uuid.UUID
	AppVersion *string
}

func (q *Queries) SetDriverAppVersion(ctx context.Context, arg SetDriverAppVersionParams) error {
	_, err := q.db.Exec(ctx, setDriverAppVersion, arg.CompanyID, arg.ID, arg.AppVersion)
	return err
}

const setDriverLicense = `-- name: SetDriverLicense :one
UPDATE drivers SET license_no_enc = $1::text
WHERE company_id = $2::uuid AND id = $3::uuid AND deleted_at IS NULL
RETURNING id, company_id, user_id, branch_id, license_no_enc, license_region, home_terminal, city, state, zip, address1, address2, notes, fleet_manager_id, default_unit_id, status, app_version, activated_on, created_at, updated_at, deleted_at
`

type SetDriverLicenseParams struct {
	LicenseNoEnc *string
	CompanyID    uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) SetDriverLicense(ctx context.Context, arg SetDriverLicenseParams) (Driver, error) {
	row := q.db.QueryRow(ctx, setDriverLicense, arg.LicenseNoEnc, arg.CompanyID, arg.ID)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.LicenseNoEnc,
		&i.LicenseRegion,
		&i.HomeTerminal,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Address1,
		&i.Address2,
		&i.Notes,
		&i.FleetManagerID,
		&i.DefaultUnitID,
		&i.Status,
		&i.AppVersion,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setDriverStatus = `-- name: SetDriverStatus :one
UPDATE drivers SET status = $3, activated_on = CASE WHEN $3 = 'active' THEN COALESCE(activated_on, now()) ELSE activated_on END
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL RETURNING id, company_id, user_id, branch_id, license_no_enc, license_region, home_terminal, city, state, zip, address1, address2, notes, fleet_manager_id, default_unit_id, status, app_version, activated_on, created_at, updated_at, deleted_at
`

type SetDriverStatusParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	Status    string
}

func (q *Queries) SetDriverStatus(ctx context.Context, arg SetDriverStatusParams) (Driver, error) {
	row := q.db.QueryRow(ctx, setDriverStatus, arg.CompanyID, arg.ID, arg.Status)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.LicenseNoEnc,
		&i.LicenseRegion,
		&i.HomeTerminal,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Address1,
		&i.Address2,
		&i.Notes,
		&i.FleetManagerID,
		&i.DefaultUnitID,
		&i.Status,
		&i.AppVersion,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteDriver = `-- name: SoftDeleteDriver :exec
UPDATE drivers SET deleted_at = now(), status = 'inactive'
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteDriverParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteDriver(ctx context.Context, arg SoftDeleteDriverParams) error {
	_, err := q.db.Exec(ctx, softDeleteDriver, arg.CompanyID, arg.ID)
	return err
}

const updateDriver = `-- name: UpdateDriver :one
UPDATE drivers SET
  branch_id        = COALESCE($3::uuid, branch_id),
  license_no_enc   = COALESCE($4::text, license_no_enc),
  license_region   = COALESCE($5::text, license_region),
  home_terminal    = COALESCE($6::text, home_terminal),
  city             = COALESCE($7::text, city),
  state            = COALESCE($8::text, state),
  zip              = COALESCE($9::text, zip),
  address1         = COALESCE($10::text, address1),
  address2         = COALESCE($11::text, address2),
  notes            = COALESCE($12::text, notes),
  fleet_manager_id = COALESCE($13::uuid, fleet_manager_id),
  default_unit_id  = COALESCE($14::uuid, default_unit_id)
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, company_id, user_id, branch_id, license_no_enc, license_region, home_terminal, city, state, zip, address1, address2, notes, fleet_manager_id, default_unit_id, status, app_version, activated_on, created_at, updated_at, deleted_at
`

type UpdateDriverParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	Column3   uuid.UUID
	Column4   string
	Column5   string
	Column6   string
	Column7   string
	Column8   string
	Column9   string
	Column10  string
	Column11  string
	Column12  string
	Column13  uuid.UUID
	Column14  uuid.UUID
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, updateDriver,
		arg.CompanyID,
		arg.ID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.LicenseNoEnc,
		&i.LicenseRegion,
		&i.HomeTerminal,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Address1,
		&i.Address2,
		&i.Notes,
		&i.FleetManagerID,
		&i.DefaultUnitID,
		&i.Status,
		&i.AppVersion,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDriverPartial = `-- name: UpdateDriverPartial :one
UPDATE drivers SET
  branch_id        = CASE WHEN $1::bool THEN NULL
                          ELSE COALESCE($2::uuid, branch_id) END,
  license_no_enc   = COALESCE($3::text, license_no_enc),
  license_region   = COALESCE($4::text, license_region),
  home_terminal    = COALESCE($5::text, home_terminal),
  city             = COALESCE($6::text, city),
  state            = COALESCE($7::text, state),
  zip              = COALESCE($8::text, zip),
  address1         = COALESCE($9::text, address1),
  address2         = COALESCE($10::text, address2),
  notes            = COALESCE($11::text, notes),
  fleet_manager_id = CASE WHEN $12::bool THEN NULL
                          ELSE COALESCE($13::uuid, fleet_manager_id) END,
  default_unit_id  = CASE WHEN $14::bool THEN NULL
                          ELSE COALESCE($15::uuid, default_unit_id) END
WHERE company_id = $16::uuid AND id = $17::uuid AND deleted_at IS NULL
RETURNING id, company_id, user_id, branch_id, license_no_enc, license_region, home_terminal, city, state, zip, address1, address2, notes, fleet_manager_id, default_unit_id, status, app_version, activated_on, created_at, updated_at, deleted_at
`

type UpdateDriverPartialParams struct {
	ClearBranch       bool
	BranchID          pgtype.UUID
	LicenseNoEnc      *string
	LicenseRegion     *string
	HomeTerminal      *string
	City              *string
	State             *string
	Zip               *string
	Address1          *string
	Address2          *string
	Notes             *string
	ClearFleetManager bool
	FleetManagerID    pgtype.UUID
	ClearDefaultUnit  bool
	DefaultUnitID     pgtype.UUID
	CompanyID         uuid.UUID
	ID                uuid.UUID
}

// PATCH /drivers/{id}: NULL argument = maydon o'zgarmaydi (COALESCE), shu bilan
// bo'sh satr bilan tasodifiy o'chirib yuborish mumkin emas.
func (q *Queries) UpdateDriverPartial(ctx context.Context, arg UpdateDriverPartialParams) (Driver, error) {
	row := q.db.QueryRow(ctx, updateDriverPartial,
		arg.ClearBranch,
		arg.BranchID,
		arg.LicenseNoEnc,
		arg.LicenseRegion,
		arg.HomeTerminal,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Address1,
		arg.Address2,
		arg.Notes,
		arg.ClearFleetManager,
		arg.FleetManagerID,
		arg.ClearDefaultUnit,
		arg.DefaultUnitID,
		arg.CompanyID,
		arg.ID,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.LicenseNoEnc,
		&i.LicenseRegion,
		&i.HomeTerminal,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Address1,
		&i.Address2,
		&i.Notes,
		&i.FleetManagerID,
		&i.DefaultUnitID,
		&i.Status,
		&i.AppVersion,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
