// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: duty_status_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignEventsToDriver = `-- name: AssignEventsToDriver :exec
UPDATE duty_status_events SET driver_id = $3, origin = 'assigned'
WHERE company_id = $1 AND id = ANY($2::uuid[]) AND driver_id IS NULL
`

type AssignEventsToDriverParams struct {
	CompanyID uuid.UUID
	Column2   []uuid.UUID
	DriverID  pgtype.UUID
}

func (q *Queries) AssignEventsToDriver(ctx context.Context, arg AssignEventsToDriverParams) error {
	_, err := q.db.Exec(ctx, assignEventsToDriver, arg.CompanyID, arg.Column2, arg.DriverID)
	return err
}

const countDriverDutyStatusEvents = `-- name: CountDriverDutyStatusEvents :one
SELECT count(*) FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2
  AND event_time >= $3 AND event_time < $4 AND superseded_by IS NULL
`

type CountDriverDutyStatusEventsParams struct {
	CompanyID   uuid.UUID
	DriverID    pgtype.UUID
	EventTime   time.Time
	EventTime_2 time.Time
}

func (q *Queries) CountDriverDutyStatusEvents(ctx context.Context, arg CountDriverDutyStatusEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDriverDutyStatusEvents,
		arg.CompanyID,
		arg.DriverID,
		arg.EventTime,
		arg.EventTime_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDutyStatusEvent = `-- name: CreateDutyStatusEvent :one
INSERT INTO duty_status_events (
  company_id, driver_id, unit_id, eld_device_id, event_type, status, special,
  event_time, time_source, time_unverified, clock_skew_sec, origin,
  lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes,
  trailer_ids, shipping_doc_ids, client_event_id, device_seq, daily_log_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24)
RETURNING id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at
`

type CreateDutyStatusEventParams struct {
	CompanyID      uuid.UUID
	DriverID       pgtype.UUID
	UnitID         pgtype.UUID
	EldDeviceID    pgtype.UUID
	EventType      string
	Status         *string
	Special        string
	EventTime      time.Time
	TimeSource     string
	TimeUnverified bool
	ClockSkewSec   int32
	Origin         string
	Lat            *float64
	Lng            *float64
	LocationText   *string
	GpsAccuracyM   *int32
	OdometerM      *int64
	EngineHours    pgtype.Numeric
	Notes          *string
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	ClientEventID  uuid.UUID
	DeviceSeq      *int64
	DailyLogID     pgtype.UUID
}

func (q *Queries) CreateDutyStatusEvent(ctx context.Context, arg CreateDutyStatusEventParams) (DutyStatusEvent, error) {
	row := q.db.QueryRow(ctx, createDutyStatusEvent,
		arg.CompanyID,
		arg.DriverID,
		arg.UnitID,
		arg.EldDeviceID,
		arg.EventType,
		arg.Status,
		arg.Special,
		arg.EventTime,
		arg.TimeSource,
		arg.TimeUnverified,
		arg.ClockSkewSec,
		arg.Origin,
		arg.Lat,
		arg.Lng,
		arg.LocationText,
		arg.GpsAccuracyM,
		arg.OdometerM,
		arg.EngineHours,
		arg.Notes,
		arg.TrailerIds,
		arg.ShippingDocIds,
		arg.ClientEventID,
		arg.DeviceSeq,
		arg.DailyLogID,
	)
	var i DutyStatusEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.EventType,
		&i.Status,
		&i.Special,
		&i.EventTime,
		&i.TimeSource,
		&i.TimeUnverified,
		&i.ClockSkewSec,
		&i.Origin,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.GpsAccuracyM,
		&i.OdometerM,
		&i.EngineHours,
		&i.Notes,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.ClientEventID,
		&i.DeviceSeq,
		&i.ReceivedAt,
		&i.SupersededBy,
		&i.Locked,
		&i.DailyLogID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDutyStatusEvent = `-- name: GetDutyStatusEvent :one
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events WHERE company_id = $1 AND id = $2
`

type GetDutyStatusEventParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetDutyStatusEvent(ctx context.Context, arg GetDutyStatusEventParams) (DutyStatusEvent, error) {
	row := q.db.QueryRow(ctx, getDutyStatusEvent, arg.CompanyID, arg.ID)
	var i DutyStatusEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.EventType,
		&i.Status,
		&i.Special,
		&i.EventTime,
		&i.TimeSource,
		&i.TimeUnverified,
		&i.ClockSkewSec,
		&i.Origin,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.GpsAccuracyM,
		&i.OdometerM,
		&i.EngineHours,
		&i.Notes,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.ClientEventID,
		&i.DeviceSeq,
		&i.ReceivedAt,
		&i.SupersededBy,
		&i.Locked,
		&i.DailyLogID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDutyStatusEventByClientID = `-- name: GetDutyStatusEventByClientID :one
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events WHERE company_id = $1 AND client_event_id = $2
`

type GetDutyStatusEventByClientIDParams struct {
	CompanyID     uuid.UUID
	ClientEventID uuid.UUID
}

func (q *Queries) GetDutyStatusEventByClientID(ctx context.Context, arg GetDutyStatusEventByClientIDParams) (DutyStatusEvent, error) {
	row := q.db.QueryRow(ctx, getDutyStatusEventByClientID, arg.CompanyID, arg.ClientEventID)
	var i DutyStatusEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.EventType,
		&i.Status,
		&i.Special,
		&i.EventTime,
		&i.TimeSource,
		&i.TimeUnverified,
		&i.ClockSkewSec,
		&i.Origin,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.GpsAccuracyM,
		&i.OdometerM,
		&i.EngineHours,
		&i.Notes,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.ClientEventID,
		&i.DeviceSeq,
		&i.ReceivedAt,
		&i.SupersededBy,
		&i.Locked,
		&i.DailyLogID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastDutyStatusEvent = `-- name: GetLastDutyStatusEvent :one
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2 AND event_type = 'duty_status' AND superseded_by IS NULL
ORDER BY event_time DESC LIMIT 1
`

type GetLastDutyStatusEventParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
}

func (q *Queries) GetLastDutyStatusEvent(ctx context.Context, arg GetLastDutyStatusEventParams) (DutyStatusEvent, error) {
	row := q.db.QueryRow(ctx, getLastDutyStatusEvent, arg.CompanyID, arg.DriverID)
	var i DutyStatusEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.EventType,
		&i.Status,
		&i.Special,
		&i.EventTime,
		&i.TimeSource,
		&i.TimeUnverified,
		&i.ClockSkewSec,
		&i.Origin,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.GpsAccuracyM,
		&i.OdometerM,
		&i.EngineHours,
		&i.Notes,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.ClientEventID,
		&i.DeviceSeq,
		&i.ReceivedAt,
		&i.SupersededBy,
		&i.Locked,
		&i.DailyLogID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkEventsToDailyLog = `-- name: LinkEventsToDailyLog :exec
UPDATE duty_status_events SET daily_log_id = $3
WHERE company_id = $1 AND id = ANY($2::uuid[])
`

type LinkEventsToDailyLogParams struct {
	CompanyID  uuid.UUID
	Column2    []uuid.UUID
	DailyLogID pgtype.UUID
}

func (q *Queries) LinkEventsToDailyLog(ctx context.Context, arg LinkEventsToDailyLogParams) error {
	_, err := q.db.Exec(ctx, linkEventsToDailyLog, arg.CompanyID, arg.Column2, arg.DailyLogID)
	return err
}

const listDriverDutyStatusEvents = `-- name: ListDriverDutyStatusEvents :many
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2
  AND event_time >= $3 AND event_time < $4
  AND superseded_by IS NULL
ORDER BY event_time, device_seq NULLS LAST
LIMIT $5 OFFSET $6
`

type ListDriverDutyStatusEventsParams struct {
	CompanyID   uuid.UUID
	DriverID    pgtype.UUID
	EventTime   time.Time
	EventTime_2 time.Time
	Limit       int32
	Offset      int32
}

func (q *Queries) ListDriverDutyStatusEvents(ctx context.Context, arg ListDriverDutyStatusEventsParams) ([]DutyStatusEvent, error) {
	rows, err := q.db.Query(ctx, listDriverDutyStatusEvents,
		arg.CompanyID,
		arg.DriverID,
		arg.EventTime,
		arg.EventTime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyStatusEvent{}
	for rows.Next() {
		var i DutyStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByDailyLog = `-- name: ListEventsByDailyLog :many
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND daily_log_id = $2 AND superseded_by IS NULL
ORDER BY event_time
`

type ListEventsByDailyLogParams struct {
	CompanyID  uuid.UUID
	DailyLogID pgtype.UUID
}

func (q *Queries) ListEventsByDailyLog(ctx context.Context, arg ListEventsByDailyLogParams) ([]DutyStatusEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByDailyLog, arg.CompanyID, arg.DailyLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyStatusEvent{}
	for rows.Next() {
		var i DutyStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsChangedSince = `-- name: ListEventsChangedSince :many
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2 AND updated_at > $3
ORDER BY updated_at LIMIT $4
`

type ListEventsChangedSinceParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	UpdatedAt time.Time
	Limit     int32
}

func (q *Queries) ListEventsChangedSince(ctx context.Context, arg ListEventsChangedSinceParams) ([]DutyStatusEvent, error) {
	rows, err := q.db.Query(ctx, listEventsChangedSince,
		arg.CompanyID,
		arg.DriverID,
		arg.UpdatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyStatusEvent{}
	for rows.Next() {
		var i DutyStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedDutyStatusEvents = `-- name: ListUnassignedDutyStatusEvents :many
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND driver_id IS NULL AND unit_id = $2
  AND event_time >= $3 AND event_time < $4
ORDER BY event_time
`

type ListUnassignedDutyStatusEventsParams struct {
	CompanyID   uuid.UUID
	UnitID      pgtype.UUID
	EventTime   time.Time
	EventTime_2 time.Time
}

func (q *Queries) ListUnassignedDutyStatusEvents(ctx context.Context, arg ListUnassignedDutyStatusEventsParams) ([]DutyStatusEvent, error) {
	rows, err := q.db.Query(ctx, listUnassignedDutyStatusEvents,
		arg.CompanyID,
		arg.UnitID,
		arg.EventTime,
		arg.EventTime_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyStatusEvent{}
	for rows.Next() {
		var i DutyStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitDutyStatusEvents = `-- name: ListUnitDutyStatusEvents :many
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND unit_id = $2
  AND event_time >= $3 AND event_time < $4 AND superseded_by IS NULL
ORDER BY event_time
LIMIT $5 OFFSET $6
`

type ListUnitDutyStatusEventsParams struct {
	CompanyID   uuid.UUID
	UnitID      pgtype.UUID
	EventTime   time.Time
	EventTime_2 time.Time
	Limit       int32
	Offset      int32
}

func (q *Queries) ListUnitDutyStatusEvents(ctx context.Context, arg ListUnitDutyStatusEventsParams) ([]DutyStatusEvent, error) {
	rows, err := q.db.Query(ctx, listUnitDutyStatusEvents,
		arg.CompanyID,
		arg.UnitID,
		arg.EventTime,
		arg.EventTime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyStatusEvent{}
	for rows.Next() {
		var i DutyStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventsForDailyLog = `-- name: LockEventsForDailyLog :exec
UPDATE duty_status_events SET locked = true
WHERE company_id = $1 AND daily_log_id = $2
`

type LockEventsForDailyLogParams struct {
	CompanyID  uuid.UUID
	DailyLogID pgtype.UUID
}

func (q *Queries) LockEventsForDailyLog(ctx context.Context, arg LockEventsForDailyLogParams) error {
	_, err := q.db.Exec(ctx, lockEventsForDailyLog, arg.CompanyID, arg.DailyLogID)
	return err
}

const supersedeDutyStatusEvent = `-- name: SupersedeDutyStatusEvent :exec
UPDATE duty_status_events SET superseded_by = $3
WHERE company_id = $1 AND id = $2 AND superseded_by IS NULL
`

type SupersedeDutyStatusEventParams struct {
	CompanyID    uuid.UUID
	ID           uuid.UUID
	SupersededBy pgtype.UUID
}

func (q *Queries) SupersedeDutyStatusEvent(ctx context.Context, arg SupersedeDutyStatusEventParams) error {
	_, err := q.db.Exec(ctx, supersedeDutyStatusEvent, arg.CompanyID, arg.ID, arg.SupersededBy)
	return err
}

const upsertDutyStatusEvent = `-- name: UpsertDutyStatusEvent :one
INSERT INTO duty_status_events (
  company_id, driver_id, unit_id, eld_device_id, event_type, status, special,
  event_time, time_source, time_unverified, clock_skew_sec, origin,
  lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes,
  trailer_ids, shipping_doc_ids, client_event_id, device_seq, daily_log_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24)
ON CONFLICT (client_event_id) DO UPDATE SET received_at = duty_status_events.received_at
RETURNING id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at
`

type UpsertDutyStatusEventParams struct {
	CompanyID      uuid.UUID
	DriverID       pgtype.UUID
	UnitID         pgtype.UUID
	EldDeviceID    pgtype.UUID
	EventType      string
	Status         *string
	Special        string
	EventTime      time.Time
	TimeSource     string
	TimeUnverified bool
	ClockSkewSec   int32
	Origin         string
	Lat            *float64
	Lng            *float64
	LocationText   *string
	GpsAccuracyM   *int32
	OdometerM      *int64
	EngineHours    pgtype.Numeric
	Notes          *string
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	ClientEventID  uuid.UUID
	DeviceSeq      *int64
	DailyLogID     pgtype.UUID
}

func (q *Queries) UpsertDutyStatusEvent(ctx context.Context, arg UpsertDutyStatusEventParams) (DutyStatusEvent, error) {
	row := q.db.QueryRow(ctx, upsertDutyStatusEvent,
		arg.CompanyID,
		arg.DriverID,
		arg.UnitID,
		arg.EldDeviceID,
		arg.EventType,
		arg.Status,
		arg.Special,
		arg.EventTime,
		arg.TimeSource,
		arg.TimeUnverified,
		arg.ClockSkewSec,
		arg.Origin,
		arg.Lat,
		arg.Lng,
		arg.LocationText,
		arg.GpsAccuracyM,
		arg.OdometerM,
		arg.EngineHours,
		arg.Notes,
		arg.TrailerIds,
		arg.ShippingDocIds,
		arg.ClientEventID,
		arg.DeviceSeq,
		arg.DailyLogID,
	)
	var i DutyStatusEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.EventType,
		&i.Status,
		&i.Special,
		&i.EventTime,
		&i.TimeSource,
		&i.TimeUnverified,
		&i.ClockSkewSec,
		&i.Origin,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.GpsAccuracyM,
		&i.OdometerM,
		&i.EngineHours,
		&i.Notes,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.ClientEventID,
		&i.DeviceSeq,
		&i.ReceivedAt,
		&i.SupersededBy,
		&i.Locked,
		&i.DailyLogID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
