// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dvir.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const certifyDvirReport = `-- name: CertifyDvirReport :one
UPDATE dvir_reports SET
  status                      = 'certified',
  certified_by_driver_id      = $1,
  certification_signature_key = $2,
  certified_at                = now()
WHERE company_id = $3 AND id = $4 AND status = 'repaired'
RETURNING id, company_id, unit_id, driver_id, type, trailer_ids, status, defects, lat, lng, location_text, odometer_m, engine_hours, driver_signature_key, mechanic_id, mechanic_note, mechanic_signature_key, repaired_at, certified_by_driver_id, certified_at, source, performed_at, created_at, updated_at, certification_signature_key, closed_at, closed_reason
`

type CertifyDvirReportParams struct {
	CertifiedByDriverID       pgtype.UUID
	CertificationSignatureKey *string
	CompanyID                 uuid.UUID
	ID                        uuid.UUID
}

func (q *Queries) CertifyDvirReport(ctx context.Context, arg CertifyDvirReportParams) (DvirReport, error) {
	row := q.db.QueryRow(ctx, certifyDvirReport,
		arg.CertifiedByDriverID,
		arg.CertificationSignatureKey,
		arg.CompanyID,
		arg.ID,
	)
	var i DvirReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Type,
		&i.TrailerIds,
		&i.Status,
		&i.Defects,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.OdometerM,
		&i.EngineHours,
		&i.DriverSignatureKey,
		&i.MechanicID,
		&i.MechanicNote,
		&i.MechanicSignatureKey,
		&i.RepairedAt,
		&i.CertifiedByDriverID,
		&i.CertifiedAt,
		&i.Source,
		&i.PerformedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificationSignatureKey,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const closeDvirNoCertification = `-- name: CloseDvirNoCertification :one
UPDATE dvir_reports SET
  status        = 'closed_no_certification',
  closed_at     = now(),
  closed_reason = $1
WHERE company_id = $2 AND id = $3
  AND status IN ('submitted_defects_found','repaired')
RETURNING id, company_id, unit_id, driver_id, type, trailer_ids, status, defects, lat, lng, location_text, odometer_m, engine_hours, driver_signature_key, mechanic_id, mechanic_note, mechanic_signature_key, repaired_at, certified_by_driver_id, certified_at, source, performed_at, created_at, updated_at, certification_signature_key, closed_at, closed_reason
`

type CloseDvirNoCertificationParams struct {
	ClosedReason *string
	CompanyID    uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) CloseDvirNoCertification(ctx context.Context, arg CloseDvirNoCertificationParams) (DvirReport, error) {
	row := q.db.QueryRow(ctx, closeDvirNoCertification, arg.ClosedReason, arg.CompanyID, arg.ID)
	var i DvirReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Type,
		&i.TrailerIds,
		&i.Status,
		&i.Defects,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.OdometerM,
		&i.EngineHours,
		&i.DriverSignatureKey,
		&i.MechanicID,
		&i.MechanicNote,
		&i.MechanicSignatureKey,
		&i.RepairedAt,
		&i.CertifiedByDriverID,
		&i.CertifiedAt,
		&i.Source,
		&i.PerformedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificationSignatureKey,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const countDefectTypes = `-- name: CountDefectTypes :one
SELECT count(*) FROM defect_types
WHERE (company_id = $1 OR company_id IS NULL) AND deleted_at IS NULL
  AND ($2::text IS NULL OR category = $2::text)
  AND ($3::bool IS NULL OR is_active = $3::bool)
  AND ($4::bool IS NULL OR is_critical = $4::bool)
`

type CountDefectTypesParams struct {
	CompanyID  pgtype.UUID
	Category   *string
	IsActive   *bool
	IsCritical *bool
}

func (q *Queries) CountDefectTypes(ctx context.Context, arg CountDefectTypesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDefectTypes,
		arg.CompanyID,
		arg.Category,
		arg.IsActive,
		arg.IsCritical,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDvirForUnitAfter = `-- name: CountDvirForUnitAfter :one
SELECT count(*) FROM dvir_reports
WHERE company_id = $1 AND unit_id = $2 AND performed_at > $3::timestamptz
`

type CountDvirForUnitAfterParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
	After     time.Time
}

func (q *Queries) CountDvirForUnitAfter(ctx context.Context, arg CountDvirForUnitAfterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDvirForUnitAfter, arg.CompanyID, arg.UnitID, arg.After)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDvirReports = `-- name: CountDvirReports :one
SELECT count(*) FROM dvir_reports r
JOIN units un ON un.id = r.unit_id
WHERE r.company_id = $1
  AND ($2::uuid IS NULL OR r.unit_id = $2::uuid)
  AND ($3::uuid IS NULL OR r.driver_id = $3::uuid)
  AND ($4::uuid IS NULL OR un.branch_id = $4::uuid)
  AND ($5::text IS NULL OR r.status = $5::text)
  AND ($6::text IS NULL OR r.type = $6::text)
  AND ($7::timestamptz IS NULL OR r.performed_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR r.performed_at < $8::timestamptz)
`

type CountDvirReportsParams struct {
	CompanyID uuid.UUID
	UnitID    pgtype.UUID
	DriverID  pgtype.UUID
	BranchID  pgtype.UUID
	Status    *string
	Type      *string
	From      pgtype.Timestamptz
	To        pgtype.Timestamptz
}

func (q *Queries) CountDvirReports(ctx context.Context, arg CountDvirReportsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDvirReports,
		arg.CompanyID,
		arg.UnitID,
		arg.DriverID,
		arg.BranchID,
		arg.Status,
		arg.Type,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDefectType = `-- name: CreateDefectType :one
INSERT INTO defect_types (company_id, name, category, is_critical, is_active, sort_order)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, company_id, name, category, is_critical, is_active, sort_order, created_at, updated_at, deleted_at
`

type CreateDefectTypeParams struct {
	CompanyID  pgtype.UUID
	Name       string
	Category   string
	IsCritical bool
	IsActive   bool
	SortOrder  int32
}

func (q *Queries) CreateDefectType(ctx context.Context, arg CreateDefectTypeParams) (DefectType, error) {
	row := q.db.QueryRow(ctx, createDefectType,
		arg.CompanyID,
		arg.Name,
		arg.Category,
		arg.IsCritical,
		arg.IsActive,
		arg.SortOrder,
	)
	var i DefectType
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Category,
		&i.IsCritical,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDvirReport = `-- name: CreateDvirReport :one
INSERT INTO dvir_reports (
  company_id, unit_id, driver_id, type, trailer_ids, status, defects,
  lat, lng, location_text, odometer_m, engine_hours, driver_signature_key,
  source, performed_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15
)
RETURNING id, company_id, unit_id, driver_id, type, trailer_ids, status, defects, lat, lng, location_text, odometer_m, engine_hours, driver_signature_key, mechanic_id, mechanic_note, mechanic_signature_key, repaired_at, certified_by_driver_id, certified_at, source, performed_at, created_at, updated_at, certification_signature_key, closed_at, closed_reason
`

type CreateDvirReportParams struct {
	CompanyID          uuid.UUID
	UnitID             uuid.UUID
	DriverID           uuid.UUID
	Type               string
	TrailerIds         []uuid.UUID
	Status             string
	Defects            []byte
	Lat                *float64
	Lng                *float64
	LocationText       *string
	OdometerM          *int64
	EngineHours        pgtype.Numeric
	DriverSignatureKey *string
	Source             string
	PerformedAt        time.Time
}

func (q *Queries) CreateDvirReport(ctx context.Context, arg CreateDvirReportParams) (DvirReport, error) {
	row := q.db.QueryRow(ctx, createDvirReport,
		arg.CompanyID,
		arg.UnitID,
		arg.DriverID,
		arg.Type,
		arg.TrailerIds,
		arg.Status,
		arg.Defects,
		arg.Lat,
		arg.Lng,
		arg.LocationText,
		arg.OdometerM,
		arg.EngineHours,
		arg.DriverSignatureKey,
		arg.Source,
		arg.PerformedAt,
	)
	var i DvirReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Type,
		&i.TrailerIds,
		&i.Status,
		&i.Defects,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.OdometerM,
		&i.EngineHours,
		&i.DriverSignatureKey,
		&i.MechanicID,
		&i.MechanicNote,
		&i.MechanicSignatureKey,
		&i.RepairedAt,
		&i.CertifiedByDriverID,
		&i.CertifiedAt,
		&i.Source,
		&i.PerformedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificationSignatureKey,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const getDefectType = `-- name: GetDefectType :one
SELECT id, company_id, name, category, is_critical, is_active, sort_order, created_at, updated_at, deleted_at FROM defect_types
WHERE id = $1 AND (company_id = $2 OR company_id IS NULL) AND deleted_at IS NULL
`

type GetDefectTypeParams struct {
	ID        uuid.UUID
	CompanyID pgtype.UUID
}

func (q *Queries) GetDefectType(ctx context.Context, arg GetDefectTypeParams) (DefectType, error) {
	row := q.db.QueryRow(ctx, getDefectType, arg.ID, arg.CompanyID)
	var i DefectType
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Category,
		&i.IsCritical,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDvirDriverByUser = `-- name: GetDvirDriverByUser :one
SELECT d.id, d.user_id, d.status, d.branch_id
FROM drivers d
WHERE d.company_id = $1 AND d.user_id = $2 AND d.deleted_at IS NULL
`

type GetDvirDriverByUserParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

type GetDvirDriverByUserRow struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Status   string
	BranchID pgtype.UUID
}

func (q *Queries) GetDvirDriverByUser(ctx context.Context, arg GetDvirDriverByUserParams) (GetDvirDriverByUserRow, error) {
	row := q.db.QueryRow(ctx, getDvirDriverByUser, arg.CompanyID, arg.UserID)
	var i GetDvirDriverByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.BranchID,
	)
	return i, err
}

const getDvirReport = `-- name: GetDvirReport :one
SELECT id, company_id, unit_id, driver_id, type, trailer_ids, status, defects, lat, lng, location_text, odometer_m, engine_hours, driver_signature_key, mechanic_id, mechanic_note, mechanic_signature_key, repaired_at, certified_by_driver_id, certified_at, source, performed_at, created_at, updated_at, certification_signature_key, closed_at, closed_reason FROM dvir_reports WHERE company_id = $1 AND id = $2
`

type GetDvirReportParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetDvirReport(ctx context.Context, arg GetDvirReportParams) (DvirReport, error) {
	row := q.db.QueryRow(ctx, getDvirReport, arg.CompanyID, arg.ID)
	var i DvirReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Type,
		&i.TrailerIds,
		&i.Status,
		&i.Defects,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.OdometerM,
		&i.EngineHours,
		&i.DriverSignatureKey,
		&i.MechanicID,
		&i.MechanicNote,
		&i.MechanicSignatureKey,
		&i.RepairedAt,
		&i.CertifiedByDriverID,
		&i.CertifiedAt,
		&i.Source,
		&i.PerformedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificationSignatureKey,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const getDvirReportDetail = `-- name: GetDvirReportDetail :one
SELECT r.id, r.company_id, r.unit_id, r.driver_id, r.type, r.trailer_ids, r.status, r.defects, r.lat, r.lng, r.location_text, r.odometer_m, r.engine_hours, r.driver_signature_key, r.mechanic_id, r.mechanic_note, r.mechanic_signature_key, r.repaired_at, r.certified_by_driver_id, r.certified_at, r.source, r.performed_at, r.created_at, r.updated_at, r.certification_signature_key, r.closed_at, r.closed_reason, un.unit_number, un.out_of_service, u.first_name, u.last_name
FROM dvir_reports r
JOIN units un ON un.id = r.unit_id
JOIN drivers d ON d.id = r.driver_id
JOIN users   u ON u.id = d.user_id
WHERE r.company_id = $1 AND r.id = $2
`

type GetDvirReportDetailParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetDvirReportDetailRow struct {
	ID                        uuid.UUID
	CompanyID                 uuid.UUID
	UnitID                    uuid.UUID
	DriverID                  uuid.UUID
	Type                      string
	TrailerIds                []uuid.UUID
	Status                    string
	Defects                   []byte
	Lat                       *float64
	Lng                       *float64
	LocationText              *string
	OdometerM                 *int64
	EngineHours               pgtype.Numeric
	DriverSignatureKey        *string
	MechanicID                pgtype.UUID
	MechanicNote              *string
	MechanicSignatureKey      *string
	RepairedAt                pgtype.Timestamptz
	CertifiedByDriverID       pgtype.UUID
	CertifiedAt               pgtype.Timestamptz
	Source                    string
	PerformedAt               time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	CertificationSignatureKey *string
	ClosedAt                  pgtype.Timestamptz
	ClosedReason              *string
	UnitNumber                string
	OutOfService              bool
	FirstName                 string
	LastName                  string
}

func (q *Queries) GetDvirReportDetail(ctx context.Context, arg GetDvirReportDetailParams) (GetDvirReportDetailRow, error) {
	row := q.db.QueryRow(ctx, getDvirReportDetail, arg.CompanyID, arg.ID)
	var i GetDvirReportDetailRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Type,
		&i.TrailerIds,
		&i.Status,
		&i.Defects,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.OdometerM,
		&i.EngineHours,
		&i.DriverSignatureKey,
		&i.MechanicID,
		&i.MechanicNote,
		&i.MechanicSignatureKey,
		&i.RepairedAt,
		&i.CertifiedByDriverID,
		&i.CertifiedAt,
		&i.Source,
		&i.PerformedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificationSignatureKey,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.UnitNumber,
		&i.OutOfService,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getDvirUnit = `-- name: GetDvirUnit :one
SELECT id, unit_number, status, out_of_service, branch_id
FROM units WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetDvirUnitParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetDvirUnitRow struct {
	ID           uuid.UUID
	UnitNumber   string
	Status       string
	OutOfService bool
	BranchID     pgtype.UUID
}

func (q *Queries) GetDvirUnit(ctx context.Context, arg GetDvirUnitParams) (GetDvirUnitRow, error) {
	row := q.db.QueryRow(ctx, getDvirUnit, arg.CompanyID, arg.ID)
	var i GetDvirUnitRow
	err := row.Scan(
		&i.ID,
		&i.UnitNumber,
		&i.Status,
		&i.OutOfService,
		&i.BranchID,
	)
	return i, err
}

const getLastDvirForUnit = `-- name: GetLastDvirForUnit :one
SELECT id, company_id, unit_id, driver_id, type, trailer_ids, status, defects, lat, lng, location_text, odometer_m, engine_hours, driver_signature_key, mechanic_id, mechanic_note, mechanic_signature_key, repaired_at, certified_by_driver_id, certified_at, source, performed_at, created_at, updated_at, certification_signature_key, closed_at, closed_reason FROM dvir_reports
WHERE company_id = $1 AND unit_id = $2
  AND ($3::text IS NULL OR type = $3::text)
ORDER BY performed_at DESC LIMIT 1
`

type GetLastDvirForUnitParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
	Type      *string
}

func (q *Queries) GetLastDvirForUnit(ctx context.Context, arg GetLastDvirForUnitParams) (DvirReport, error) {
	row := q.db.QueryRow(ctx, getLastDvirForUnit, arg.CompanyID, arg.UnitID, arg.Type)
	var i DvirReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Type,
		&i.TrailerIds,
		&i.Status,
		&i.Defects,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.OdometerM,
		&i.EngineHours,
		&i.DriverSignatureKey,
		&i.MechanicID,
		&i.MechanicNote,
		&i.MechanicSignatureKey,
		&i.RepairedAt,
		&i.CertifiedByDriverID,
		&i.CertifiedAt,
		&i.Source,
		&i.PerformedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificationSignatureKey,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const listDefectTypes = `-- name: ListDefectTypes :many
SELECT id, company_id, name, category, is_critical, is_active, sort_order, created_at, updated_at, deleted_at FROM defect_types
WHERE (company_id = $1 OR company_id IS NULL) AND deleted_at IS NULL
  AND ($2::text IS NULL OR category = $2::text)
  AND ($3::bool IS NULL OR is_active = $3::bool)
  AND ($4::bool IS NULL OR is_critical = $4::bool)
ORDER BY category, sort_order, name
LIMIT $6 OFFSET $5
`

type ListDefectTypesParams struct {
	CompanyID  pgtype.UUID
	Category   *string
	IsActive   *bool
	IsCritical *bool
	Offset     int32
	Limit      int32
}

func (q *Queries) ListDefectTypes(ctx context.Context, arg ListDefectTypesParams) ([]DefectType, error) {
	rows, err := q.db.Query(ctx, listDefectTypes,
		arg.CompanyID,
		arg.Category,
		arg.IsActive,
		arg.IsCritical,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DefectType{}
	for rows.Next() {
		var i DefectType
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Category,
			&i.IsCritical,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefectTypesByIDs = `-- name: ListDefectTypesByIDs :many
SELECT id, company_id, name, category, is_critical, is_active, sort_order, created_at, updated_at, deleted_at FROM defect_types
WHERE id = ANY($1::uuid[])
  AND (company_id = $2 OR company_id IS NULL) AND deleted_at IS NULL
`

type ListDefectTypesByIDsParams struct {
	Ids       []uuid.UUID
	CompanyID pgtype.UUID
}

func (q *Queries) ListDefectTypesByIDs(ctx context.Context, arg ListDefectTypesByIDsParams) ([]DefectType, error) {
	rows, err := q.db.Query(ctx, listDefectTypesByIDs, arg.Ids, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DefectType{}
	for rows.Next() {
		var i DefectType
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Category,
			&i.IsCritical,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDvirCertificationOverdue = `-- name: ListDvirCertificationOverdue :many
SELECT r.id, r.company_id, r.unit_id, r.driver_id, r.type, r.trailer_ids, r.status, r.defects, r.lat, r.lng, r.location_text, r.odometer_m, r.engine_hours, r.driver_signature_key, r.mechanic_id, r.mechanic_note, r.mechanic_signature_key, r.repaired_at, r.certified_by_driver_id, r.certified_at, r.source, r.performed_at, r.created_at, r.updated_at, r.certification_signature_key, r.closed_at, r.closed_reason, un.status AS unit_status
FROM dvir_reports r
JOIN units un ON un.id = r.unit_id
WHERE r.company_id = $1
  AND r.status IN ('submitted_defects_found','repaired')
  AND (
        r.performed_at < now() - ($2::int || ' days')::interval
     OR un.status <> 'active'
     OR un.deleted_at IS NOT NULL
  )
ORDER BY r.performed_at
LIMIT $3
`

type ListDvirCertificationOverdueParams struct {
	CompanyID uuid.UUID
	GraceDays int32
	Limit     int32
}

type ListDvirCertificationOverdueRow struct {
	ID                        uuid.UUID
	CompanyID                 uuid.UUID
	UnitID                    uuid.UUID
	DriverID                  uuid.UUID
	Type                      string
	TrailerIds                []uuid.UUID
	Status                    string
	Defects                   []byte
	Lat                       *float64
	Lng                       *float64
	LocationText              *string
	OdometerM                 *int64
	EngineHours               pgtype.Numeric
	DriverSignatureKey        *string
	MechanicID                pgtype.UUID
	MechanicNote              *string
	MechanicSignatureKey      *string
	RepairedAt                pgtype.Timestamptz
	CertifiedByDriverID       pgtype.UUID
	CertifiedAt               pgtype.Timestamptz
	Source                    string
	PerformedAt               time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	CertificationSignatureKey *string
	ClosedAt                  pgtype.Timestamptz
	ClosedReason              *string
	UnitStatus                string
}

// Q30.1 — reports still waiting for the "Previous defects repaired?" signature
// past the grace window, or whose unit is no longer active.
func (q *Queries) ListDvirCertificationOverdue(ctx context.Context, arg ListDvirCertificationOverdueParams) ([]ListDvirCertificationOverdueRow, error) {
	rows, err := q.db.Query(ctx, listDvirCertificationOverdue, arg.CompanyID, arg.GraceDays, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDvirCertificationOverdueRow{}
	for rows.Next() {
		var i ListDvirCertificationOverdueRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.DriverID,
			&i.Type,
			&i.TrailerIds,
			&i.Status,
			&i.Defects,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.OdometerM,
			&i.EngineHours,
			&i.DriverSignatureKey,
			&i.MechanicID,
			&i.MechanicNote,
			&i.MechanicSignatureKey,
			&i.RepairedAt,
			&i.CertifiedByDriverID,
			&i.CertifiedAt,
			&i.Source,
			&i.PerformedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CertificationSignatureKey,
			&i.ClosedAt,
			&i.ClosedReason,
			&i.UnitStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDvirPendingCertification = `-- name: ListDvirPendingCertification :many
SELECT r.id, r.company_id, r.unit_id, r.driver_id, r.type, r.trailer_ids, r.status, r.defects, r.lat, r.lng, r.location_text, r.odometer_m, r.engine_hours, r.driver_signature_key, r.mechanic_id, r.mechanic_note, r.mechanic_signature_key, r.repaired_at, r.certified_by_driver_id, r.certified_at, r.source, r.performed_at, r.created_at, r.updated_at, r.certification_signature_key, r.closed_at, r.closed_reason, un.unit_number, un.out_of_service, u.first_name, u.last_name
FROM dvir_reports r
JOIN units un ON un.id = r.unit_id
JOIN drivers d ON d.id = r.driver_id
JOIN users   u ON u.id = d.user_id
WHERE r.company_id = $1
  AND r.status IN ('submitted_defects_found','repaired')
  AND ($2::uuid IS NULL OR r.unit_id = $2::uuid)
ORDER BY r.performed_at DESC
LIMIT $3
`

type ListDvirPendingCertificationParams struct {
	CompanyID uuid.UUID
	UnitID    pgtype.UUID
	Limit     int32
}

type ListDvirPendingCertificationRow struct {
	ID                        uuid.UUID
	CompanyID                 uuid.UUID
	UnitID                    uuid.UUID
	DriverID                  uuid.UUID
	Type                      string
	TrailerIds                []uuid.UUID
	Status                    string
	Defects                   []byte
	Lat                       *float64
	Lng                       *float64
	LocationText              *string
	OdometerM                 *int64
	EngineHours               pgtype.Numeric
	DriverSignatureKey        *string
	MechanicID                pgtype.UUID
	MechanicNote              *string
	MechanicSignatureKey      *string
	RepairedAt                pgtype.Timestamptz
	CertifiedByDriverID       pgtype.UUID
	CertifiedAt               pgtype.Timestamptz
	Source                    string
	PerformedAt               time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	CertificationSignatureKey *string
	ClosedAt                  pgtype.Timestamptz
	ClosedReason              *string
	UnitNumber                string
	OutOfService              bool
	FirstName                 string
	LastName                  string
}

func (q *Queries) ListDvirPendingCertification(ctx context.Context, arg ListDvirPendingCertificationParams) ([]ListDvirPendingCertificationRow, error) {
	rows, err := q.db.Query(ctx, listDvirPendingCertification, arg.CompanyID, arg.UnitID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDvirPendingCertificationRow{}
	for rows.Next() {
		var i ListDvirPendingCertificationRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.DriverID,
			&i.Type,
			&i.TrailerIds,
			&i.Status,
			&i.Defects,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.OdometerM,
			&i.EngineHours,
			&i.DriverSignatureKey,
			&i.MechanicID,
			&i.MechanicNote,
			&i.MechanicSignatureKey,
			&i.RepairedAt,
			&i.CertifiedByDriverID,
			&i.CertifiedAt,
			&i.Source,
			&i.PerformedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CertificationSignatureKey,
			&i.ClosedAt,
			&i.ClosedReason,
			&i.UnitNumber,
			&i.OutOfService,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDvirReports = `-- name: ListDvirReports :many
SELECT r.id, r.company_id, r.unit_id, r.driver_id, r.type, r.trailer_ids, r.status, r.defects, r.lat, r.lng, r.location_text, r.odometer_m, r.engine_hours, r.driver_signature_key, r.mechanic_id, r.mechanic_note, r.mechanic_signature_key, r.repaired_at, r.certified_by_driver_id, r.certified_at, r.source, r.performed_at, r.created_at, r.updated_at, r.certification_signature_key, r.closed_at, r.closed_reason, un.unit_number, un.out_of_service, u.first_name, u.last_name
FROM dvir_reports r
JOIN units un ON un.id = r.unit_id
JOIN drivers d ON d.id = r.driver_id
JOIN users   u ON u.id = d.user_id
WHERE r.company_id = $1
  AND ($2::uuid IS NULL OR r.unit_id = $2::uuid)
  AND ($3::uuid IS NULL OR r.driver_id = $3::uuid)
  AND ($4::uuid IS NULL OR un.branch_id = $4::uuid)
  AND ($5::text IS NULL OR r.status = $5::text)
  AND ($6::text IS NULL OR r.type = $6::text)
  AND ($7::timestamptz IS NULL OR r.performed_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR r.performed_at < $8::timestamptz)
ORDER BY r.performed_at DESC
LIMIT $10 OFFSET $9
`

type ListDvirReportsParams struct {
	CompanyID uuid.UUID
	UnitID    pgtype.UUID
	DriverID  pgtype.UUID
	BranchID  pgtype.UUID
	Status    *string
	Type      *string
	From      pgtype.Timestamptz
	To        pgtype.Timestamptz
	Offset    int32
	Limit     int32
}

type ListDvirReportsRow struct {
	ID                        uuid.UUID
	CompanyID                 uuid.UUID
	UnitID                    uuid.UUID
	DriverID                  uuid.UUID
	Type                      string
	TrailerIds                []uuid.UUID
	Status                    string
	Defects                   []byte
	Lat                       *float64
	Lng                       *float64
	LocationText              *string
	OdometerM                 *int64
	EngineHours               pgtype.Numeric
	DriverSignatureKey        *string
	MechanicID                pgtype.UUID
	MechanicNote              *string
	MechanicSignatureKey      *string
	RepairedAt                pgtype.Timestamptz
	CertifiedByDriverID       pgtype.UUID
	CertifiedAt               pgtype.Timestamptz
	Source                    string
	PerformedAt               time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	CertificationSignatureKey *string
	ClosedAt                  pgtype.Timestamptz
	ClosedReason              *string
	UnitNumber                string
	OutOfService              bool
	FirstName                 string
	LastName                  string
}

func (q *Queries) ListDvirReports(ctx context.Context, arg ListDvirReportsParams) ([]ListDvirReportsRow, error) {
	rows, err := q.db.Query(ctx, listDvirReports,
		arg.CompanyID,
		arg.UnitID,
		arg.DriverID,
		arg.BranchID,
		arg.Status,
		arg.Type,
		arg.From,
		arg.To,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDvirReportsRow{}
	for rows.Next() {
		var i ListDvirReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.DriverID,
			&i.Type,
			&i.TrailerIds,
			&i.Status,
			&i.Defects,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.OdometerM,
			&i.EngineHours,
			&i.DriverSignatureKey,
			&i.MechanicID,
			&i.MechanicNote,
			&i.MechanicSignatureKey,
			&i.RepairedAt,
			&i.CertifiedByDriverID,
			&i.CertifiedAt,
			&i.Source,
			&i.PerformedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CertificationSignatureKey,
			&i.ClosedAt,
			&i.ClosedReason,
			&i.UnitNumber,
			&i.OutOfService,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDvirTrailers = `-- name: ListDvirTrailers :many
SELECT id, number FROM trailers
WHERE company_id = $1 AND id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type ListDvirTrailersParams struct {
	CompanyID uuid.UUID
	Ids       []uuid.UUID
}

type ListDvirTrailersRow struct {
	ID     uuid.UUID
	Number string
}

func (q *Queries) ListDvirTrailers(ctx context.Context, arg ListDvirTrailersParams) ([]ListDvirTrailersRow, error) {
	rows, err := q.db.Query(ctx, listDvirTrailers, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDvirTrailersRow{}
	for rows.Next() {
		var i ListDvirTrailersRow
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repairDvirReport = `-- name: RepairDvirReport :one
UPDATE dvir_reports SET
  status                 = 'repaired',
  mechanic_id            = $1,
  mechanic_note          = $2,
  mechanic_signature_key = $3,
  repaired_at            = now()
WHERE company_id = $4 AND id = $5
  AND status = 'submitted_defects_found'
RETURNING id, company_id, unit_id, driver_id, type, trailer_ids, status, defects, lat, lng, location_text, odometer_m, engine_hours, driver_signature_key, mechanic_id, mechanic_note, mechanic_signature_key, repaired_at, certified_by_driver_id, certified_at, source, performed_at, created_at, updated_at, certification_signature_key, closed_at, closed_reason
`

type RepairDvirReportParams struct {
	MechanicID           pgtype.UUID
	MechanicNote         *string
	MechanicSignatureKey *string
	CompanyID            uuid.UUID
	ID                   uuid.UUID
}

func (q *Queries) RepairDvirReport(ctx context.Context, arg RepairDvirReportParams) (DvirReport, error) {
	row := q.db.QueryRow(ctx, repairDvirReport,
		arg.MechanicID,
		arg.MechanicNote,
		arg.MechanicSignatureKey,
		arg.CompanyID,
		arg.ID,
	)
	var i DvirReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Type,
		&i.TrailerIds,
		&i.Status,
		&i.Defects,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.OdometerM,
		&i.EngineHours,
		&i.DriverSignatureKey,
		&i.MechanicID,
		&i.MechanicNote,
		&i.MechanicSignatureKey,
		&i.RepairedAt,
		&i.CertifiedByDriverID,
		&i.CertifiedAt,
		&i.Source,
		&i.PerformedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificationSignatureKey,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const setUnitOutOfService = `-- name: SetUnitOutOfService :one
UPDATE units SET out_of_service = $1
WHERE company_id = $2 AND id = $3 AND deleted_at IS NULL
RETURNING id, unit_number, out_of_service, status
`

type SetUnitOutOfServiceParams struct {
	OutOfService bool
	CompanyID    uuid.UUID
	ID           uuid.UUID
}

type SetUnitOutOfServiceRow struct {
	ID           uuid.UUID
	UnitNumber   string
	OutOfService bool
	Status       string
}

func (q *Queries) SetUnitOutOfService(ctx context.Context, arg SetUnitOutOfServiceParams) (SetUnitOutOfServiceRow, error) {
	row := q.db.QueryRow(ctx, setUnitOutOfService, arg.OutOfService, arg.CompanyID, arg.ID)
	var i SetUnitOutOfServiceRow
	err := row.Scan(
		&i.ID,
		&i.UnitNumber,
		&i.OutOfService,
		&i.Status,
	)
	return i, err
}

const softDeleteDefectType = `-- name: SoftDeleteDefectType :exec
UPDATE defect_types SET deleted_at = now() WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteDefectTypeParams struct {
	CompanyID pgtype.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteDefectType(ctx context.Context, arg SoftDeleteDefectTypeParams) error {
	_, err := q.db.Exec(ctx, softDeleteDefectType, arg.CompanyID, arg.ID)
	return err
}

const updateDefectType = `-- name: UpdateDefectType :one
UPDATE defect_types SET
  name        = COALESCE($1::text, name),
  category    = COALESCE($2::text, category),
  is_critical = COALESCE($3::bool, is_critical),
  is_active   = COALESCE($4::bool, is_active),
  sort_order  = COALESCE($5::int, sort_order)
WHERE company_id = $6 AND id = $7 AND deleted_at IS NULL
RETURNING id, company_id, name, category, is_critical, is_active, sort_order, created_at, updated_at, deleted_at
`

type UpdateDefectTypeParams struct {
	Name       *string
	Category   *string
	IsCritical *bool
	IsActive   *bool
	SortOrder  *int32
	CompanyID  pgtype.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateDefectType(ctx context.Context, arg UpdateDefectTypeParams) (DefectType, error) {
	row := q.db.QueryRow(ctx, updateDefectType,
		arg.Name,
		arg.Category,
		arg.IsCritical,
		arg.IsActive,
		arg.SortOrder,
		arg.CompanyID,
		arg.ID,
	)
	var i DefectType
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Category,
		&i.IsCritical,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
