// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eld_devices.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignEldDeviceToUnit = `-- name: AssignEldDeviceToUnit :one
WITH closed AS (
  UPDATE eld_device_assignments AS a SET to_at = now()
  WHERE a.company_id = $1 AND a.eld_device_id = $2 AND a.to_at IS NULL
  RETURNING a.id
), linked AS (
  UPDATE eld_devices AS d SET unit_id = $3
  WHERE d.company_id = $1 AND d.id = $2
  RETURNING d.id
)
INSERT INTO eld_device_assignments (company_id, eld_device_id, unit_id, from_at)
VALUES ($1,$2,$3, now())
RETURNING id, company_id, eld_device_id, unit_id, from_at, to_at, created_at, updated_at
`

type AssignEldDeviceToUnitParams struct {
	CompanyID   uuid.UUID
	EldDeviceID uuid.UUID
	UnitID      uuid.UUID
}

func (q *Queries) AssignEldDeviceToUnit(ctx context.Context, arg AssignEldDeviceToUnitParams) (EldDeviceAssignment, error) {
	row := q.db.QueryRow(ctx, assignEldDeviceToUnit, arg.CompanyID, arg.EldDeviceID, arg.UnitID)
	var i EldDeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EldDeviceID,
		&i.UnitID,
		&i.FromAt,
		&i.ToAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countEldDevices = `-- name: CountEldDevices :one
SELECT count(*) FROM eld_devices
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR (serial || ' ' || vendor || ' ' || COALESCE(model,'')) ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::uuid IS NULL OR unit_id = $4::uuid)
`

type CountEldDevicesParams struct {
	CompanyID uuid.UUID
	Column2   string
	Column3   string
	Column4   uuid.UUID
}

func (q *Queries) CountEldDevices(ctx context.Context, arg CountEldDevicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEldDevices,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEldDevice = `-- name: CreateEldDevice :one
INSERT INTO eld_devices (
  company_id, unit_id, vendor, model, serial, firmware,
  connection_type, sim_present, status, notes
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, company_id, unit_id, vendor, model, serial, firmware, connection_type, sim_present, last_seen_at, malfunction_codes, status, notes, created_at, updated_at, deleted_at
`

type CreateEldDeviceParams struct {
	CompanyID      uuid.UUID
	UnitID         pgtype.UUID
	Vendor         string
	Model          *string
	Serial         string
	Firmware       *string
	ConnectionType *string
	SimPresent     bool
	Status         string
	Notes          *string
}

func (q *Queries) CreateEldDevice(ctx context.Context, arg CreateEldDeviceParams) (EldDevice, error) {
	row := q.db.QueryRow(ctx, createEldDevice,
		arg.CompanyID,
		arg.UnitID,
		arg.Vendor,
		arg.Model,
		arg.Serial,
		arg.Firmware,
		arg.ConnectionType,
		arg.SimPresent,
		arg.Status,
		arg.Notes,
	)
	var i EldDevice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.Firmware,
		&i.ConnectionType,
		&i.SimPresent,
		&i.LastSeenAt,
		&i.MalfunctionCodes,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEldDevice = `-- name: GetEldDevice :one
SELECT id, company_id, unit_id, vendor, model, serial, firmware, connection_type, sim_present, last_seen_at, malfunction_codes, status, notes, created_at, updated_at, deleted_at FROM eld_devices WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetEldDeviceParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetEldDevice(ctx context.Context, arg GetEldDeviceParams) (EldDevice, error) {
	row := q.db.QueryRow(ctx, getEldDevice, arg.CompanyID, arg.ID)
	var i EldDevice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.Firmware,
		&i.ConnectionType,
		&i.SimPresent,
		&i.LastSeenAt,
		&i.MalfunctionCodes,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEldDeviceBySerial = `-- name: GetEldDeviceBySerial :one
SELECT id, company_id, unit_id, vendor, model, serial, firmware, connection_type, sim_present, last_seen_at, malfunction_codes, status, notes, created_at, updated_at, deleted_at FROM eld_devices WHERE company_id = $1 AND upper(serial) = upper($2::text) AND deleted_at IS NULL
`

type GetEldDeviceBySerialParams struct {
	CompanyID uuid.UUID
	Column2   string
}

func (q *Queries) GetEldDeviceBySerial(ctx context.Context, arg GetEldDeviceBySerialParams) (EldDevice, error) {
	row := q.db.QueryRow(ctx, getEldDeviceBySerial, arg.CompanyID, arg.Column2)
	var i EldDevice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.Firmware,
		&i.ConnectionType,
		&i.SimPresent,
		&i.LastSeenAt,
		&i.MalfunctionCodes,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUnitDiagnostics = `-- name: GetUnitDiagnostics :one
SELECT d.id, d.serial, d.vendor, d.model, d.firmware, d.status,
       d.malfunction_codes, d.last_seen_at, d.sim_present, d.connection_type,
       s.ts AS last_telemetry_at, s.online_status, s.odometer_m, s.engine_hours
FROM eld_devices d
LEFT JOIN unit_last_state s ON s.unit_id = d.unit_id
WHERE d.company_id = $1 AND d.unit_id = $2 AND d.deleted_at IS NULL
ORDER BY d.last_seen_at DESC NULLS LAST
LIMIT 1
`

type GetUnitDiagnosticsParams struct {
	CompanyID uuid.UUID
	UnitID    pgtype.UUID
}

type GetUnitDiagnosticsRow struct {
	ID               uuid.UUID
	Serial           string
	Vendor           string
	Model            *string
	Firmware         *string
	Status           string
	MalfunctionCodes []string
	LastSeenAt       pgtype.Timestamptz
	SimPresent       bool
	ConnectionType   *string
	LastTelemetryAt  pgtype.Timestamptz
	OnlineStatus     *string
	OdometerM        *int64
	EngineHours      pgtype.Numeric
}

func (q *Queries) GetUnitDiagnostics(ctx context.Context, arg GetUnitDiagnosticsParams) (GetUnitDiagnosticsRow, error) {
	row := q.db.QueryRow(ctx, getUnitDiagnostics, arg.CompanyID, arg.UnitID)
	var i GetUnitDiagnosticsRow
	err := row.Scan(
		&i.ID,
		&i.Serial,
		&i.Vendor,
		&i.Model,
		&i.Firmware,
		&i.Status,
		&i.MalfunctionCodes,
		&i.LastSeenAt,
		&i.SimPresent,
		&i.ConnectionType,
		&i.LastTelemetryAt,
		&i.OnlineStatus,
		&i.OdometerM,
		&i.EngineHours,
	)
	return i, err
}

const listEldDeviceAssignments = `-- name: ListEldDeviceAssignments :many
SELECT id, company_id, eld_device_id, unit_id, from_at, to_at, created_at, updated_at FROM eld_device_assignments
WHERE company_id = $1 AND eld_device_id = $2
ORDER BY from_at DESC LIMIT $3 OFFSET $4
`

type ListEldDeviceAssignmentsParams struct {
	CompanyID   uuid.UUID
	EldDeviceID uuid.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) ListEldDeviceAssignments(ctx context.Context, arg ListEldDeviceAssignmentsParams) ([]EldDeviceAssignment, error) {
	rows, err := q.db.Query(ctx, listEldDeviceAssignments,
		arg.CompanyID,
		arg.EldDeviceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EldDeviceAssignment{}
	for rows.Next() {
		var i EldDeviceAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EldDeviceID,
			&i.UnitID,
			&i.FromAt,
			&i.ToAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEldDevices = `-- name: ListEldDevices :many
SELECT id, company_id, unit_id, vendor, model, serial, firmware, connection_type, sim_present, last_seen_at, malfunction_codes, status, notes, created_at, updated_at, deleted_at FROM eld_devices
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR (serial || ' ' || vendor || ' ' || COALESCE(model,'')) ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::uuid IS NULL OR unit_id = $4::uuid)
ORDER BY serial
LIMIT $5 OFFSET $6
`

type ListEldDevicesParams struct {
	CompanyID uuid.UUID
	Column2   string
	Column3   string
	Column4   uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListEldDevices(ctx context.Context, arg ListEldDevicesParams) ([]EldDevice, error) {
	rows, err := q.db.Query(ctx, listEldDevices,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EldDevice{}
	for rows.Next() {
		var i EldDevice
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.Vendor,
			&i.Model,
			&i.Serial,
			&i.Firmware,
			&i.ConnectionType,
			&i.SimPresent,
			&i.LastSeenAt,
			&i.MalfunctionCodes,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEldDevice = `-- name: SoftDeleteEldDevice :exec
UPDATE eld_devices SET deleted_at = now() WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteEldDeviceParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteEldDevice(ctx context.Context, arg SoftDeleteEldDeviceParams) error {
	_, err := q.db.Exec(ctx, softDeleteEldDevice, arg.CompanyID, arg.ID)
	return err
}

const touchEldDevice = `-- name: TouchEldDevice :exec
UPDATE eld_devices SET last_seen_at = now(), firmware = COALESCE($3::text, firmware), malfunction_codes = COALESCE($4::text[], malfunction_codes)
WHERE company_id = $1 AND id = $2
`

type TouchEldDeviceParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	Column3   string
	Column4   []string
}

func (q *Queries) TouchEldDevice(ctx context.Context, arg TouchEldDeviceParams) error {
	_, err := q.db.Exec(ctx, touchEldDevice,
		arg.CompanyID,
		arg.ID,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const unassignEldDevice = `-- name: UnassignEldDevice :exec
WITH closed AS (
  UPDATE eld_device_assignments AS a SET to_at = now()
  WHERE a.company_id = $1 AND a.eld_device_id = $2 AND a.to_at IS NULL
  RETURNING a.id
)
UPDATE eld_devices AS d SET unit_id = NULL
WHERE d.company_id = $1 AND d.id = $2
`

type UnassignEldDeviceParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) UnassignEldDevice(ctx context.Context, arg UnassignEldDeviceParams) error {
	_, err := q.db.Exec(ctx, unassignEldDevice, arg.CompanyID, arg.ID)
	return err
}

const updateEldDevice = `-- name: UpdateEldDevice :one
UPDATE eld_devices SET
  vendor          = COALESCE($3::text, vendor),
  model           = COALESCE($4::text, model),
  serial          = COALESCE($5::text, serial),
  firmware        = COALESCE($6::text, firmware),
  connection_type = COALESCE($7::text, connection_type),
  sim_present     = COALESCE($8::bool, sim_present),
  status          = COALESCE($9::text, status),
  notes           = COALESCE($10::text, notes)
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, company_id, unit_id, vendor, model, serial, firmware, connection_type, sim_present, last_seen_at, malfunction_codes, status, notes, created_at, updated_at, deleted_at
`

type UpdateEldDeviceParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	Column3   string
	Column4   string
	Column5   string
	Column6   string
	Column7   string
	Column8   bool
	Column9   string
	Column10  string
}

func (q *Queries) UpdateEldDevice(ctx context.Context, arg UpdateEldDeviceParams) (EldDevice, error) {
	row := q.db.QueryRow(ctx, updateEldDevice,
		arg.CompanyID,
		arg.ID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
	)
	var i EldDevice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.Firmware,
		&i.ConnectionType,
		&i.SimPresent,
		&i.LastSeenAt,
		&i.MalfunctionCodes,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
