// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleet.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const fleetActiveDeviceForUnit = `-- name: FleetActiveDeviceForUnit :one
SELECT d.id, d.serial FROM eld_devices d
WHERE d.company_id = $1 AND d.unit_id = $2::uuid AND d.deleted_at IS NULL
LIMIT 1
`

type FleetActiveDeviceForUnitParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
}

type FleetActiveDeviceForUnitRow struct {
	ID     uuid.UUID
	Serial string
}

func (q *Queries) FleetActiveDeviceForUnit(ctx context.Context, arg FleetActiveDeviceForUnitParams) (FleetActiveDeviceForUnitRow, error) {
	row := q.db.QueryRow(ctx, fleetActiveDeviceForUnit, arg.CompanyID, arg.UnitID)
	var i FleetActiveDeviceForUnitRow
	err := row.Scan(&i.ID, &i.Serial)
	return i, err
}

const fleetCloseDriverAssignments = `-- name: FleetCloseDriverAssignments :exec
UPDATE unit_driver_assignments SET unassigned_at = now()
WHERE company_id = $1 AND driver_id = $2 AND unassigned_at IS NULL
`

type FleetCloseDriverAssignmentsParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
}

func (q *Queries) FleetCloseDriverAssignments(ctx context.Context, arg FleetCloseDriverAssignmentsParams) error {
	_, err := q.db.Exec(ctx, fleetCloseDriverAssignments, arg.CompanyID, arg.DriverID)
	return err
}

const fleetCloseUnitRoleAssignment = `-- name: FleetCloseUnitRoleAssignment :exec
UPDATE unit_driver_assignments SET unassigned_at = now()
WHERE company_id = $1 AND unit_id = $2 AND role = $3 AND unassigned_at IS NULL
`

type FleetCloseUnitRoleAssignmentParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
	Role      string
}

func (q *Queries) FleetCloseUnitRoleAssignment(ctx context.Context, arg FleetCloseUnitRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, fleetCloseUnitRoleAssignment, arg.CompanyID, arg.UnitID, arg.Role)
	return err
}

const fleetCountEldDevices = `-- name: FleetCountEldDevices :one
SELECT count(*) FROM eld_devices d
WHERE d.company_id = $1 AND d.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (d.serial || ' ' || d.vendor || ' ' || COALESCE(d.model,''))
          ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR d.status = $3::text)
  AND ($4::uuid IS NULL OR d.unit_id = $4::uuid)
  AND ($5::text IS NULL OR d.connection_type = $5::text)
`

type FleetCountEldDevicesParams struct {
	CompanyID      uuid.UUID
	Search         *string
	Status         *string
	UnitID         pgtype.UUID
	ConnectionType *string
}

func (q *Queries) FleetCountEldDevices(ctx context.Context, arg FleetCountEldDevicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, fleetCountEldDevices,
		arg.CompanyID,
		arg.Search,
		arg.Status,
		arg.UnitID,
		arg.ConnectionType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fleetCountUnitAssignments = `-- name: FleetCountUnitAssignments :one
SELECT count(*) FROM unit_driver_assignments a
WHERE a.company_id = $1 AND a.unit_id = $2
  AND ($3::timestamptz IS NULL OR a.assigned_at >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR a.assigned_at <  $4::timestamptz)
`

type FleetCountUnitAssignmentsParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

func (q *Queries) FleetCountUnitAssignments(ctx context.Context, arg FleetCountUnitAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, fleetCountUnitAssignments,
		arg.CompanyID,
		arg.UnitID,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fleetCountUnitAudit = `-- name: FleetCountUnitAudit :one
SELECT count(*) FROM audit_log a
WHERE a.company_id = $1::uuid
  AND a.table_name = 'units'
  AND a.record_id = $2::uuid
  AND ($3::timestamptz IS NULL OR a.ts >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR a.ts <  $4::timestamptz)
`

type FleetCountUnitAuditParams struct {
	CompanyID uuid.UUID
	RecordID  uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

func (q *Queries) FleetCountUnitAudit(ctx context.Context, arg FleetCountUnitAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, fleetCountUnitAudit,
		arg.CompanyID,
		arg.RecordID,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fleetCountUnits = `-- name: FleetCountUnits :one
SELECT count(*) FROM units u
WHERE u.company_id = $1 AND u.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (u.unit_number || ' ' || COALESCE(u.vin,'') || ' ' || COALESCE(u.license_plate,''))
          ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR u.status = $3::text)
  AND ($4::uuid IS NULL OR u.branch_id = $4::uuid)
  AND ($5::bool IS NULL OR u.out_of_service = $5::bool)
  AND ($6::bool OR u.status = 'active')
`

type FleetCountUnitsParams struct {
	CompanyID       uuid.UUID
	Search          *string
	Status          *string
	BranchID        pgtype.UUID
	OutOfService    *bool
	IncludeInactive bool
}

func (q *Queries) FleetCountUnits(ctx context.Context, arg FleetCountUnitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, fleetCountUnits,
		arg.CompanyID,
		arg.Search,
		arg.Status,
		arg.BranchID,
		arg.OutOfService,
		arg.IncludeInactive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fleetGetBranch = `-- name: FleetGetBranch :one
SELECT id, company_id, name FROM branches
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type FleetGetBranchParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type FleetGetBranchRow struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	Name      string
}

func (q *Queries) FleetGetBranch(ctx context.Context, arg FleetGetBranchParams) (FleetGetBranchRow, error) {
	row := q.db.QueryRow(ctx, fleetGetBranch, arg.CompanyID, arg.ID)
	var i FleetGetBranchRow
	err := row.Scan(&i.ID, &i.CompanyID, &i.Name)
	return i, err
}

const fleetGetDriverBrief = `-- name: FleetGetDriverBrief :one
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.status, us.first_name, us.last_name, us.username
FROM drivers d
JOIN users us ON us.id = d.user_id
WHERE d.company_id = $1 AND d.id = $2 AND d.deleted_at IS NULL
`

type FleetGetDriverBriefParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type FleetGetDriverBriefRow struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	UserID    uuid.UUID
	BranchID  pgtype.UUID
	Status    string
	FirstName string
	LastName  string
	Username  string
}

func (q *Queries) FleetGetDriverBrief(ctx context.Context, arg FleetGetDriverBriefParams) (FleetGetDriverBriefRow, error) {
	row := q.db.QueryRow(ctx, fleetGetDriverBrief, arg.CompanyID, arg.ID)
	var i FleetGetDriverBriefRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.Username,
	)
	return i, err
}

const fleetGetEldDevice = `-- name: FleetGetEldDevice :one
SELECT d.id, d.company_id, d.unit_id, d.vendor, d.model, d.serial, d.firmware, d.connection_type, d.sim_present, d.last_seen_at, d.malfunction_codes, d.status, d.notes, d.created_at, d.updated_at, d.deleted_at, u.unit_number AS unit_number
FROM eld_devices d
LEFT JOIN units u ON u.id = d.unit_id AND u.deleted_at IS NULL
WHERE d.company_id = $1 AND d.id = $2 AND d.deleted_at IS NULL
`

type FleetGetEldDeviceParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type FleetGetEldDeviceRow struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	UnitID           pgtype.UUID
	Vendor           string
	Model            *string
	Serial           string
	Firmware         *string
	ConnectionType   *string
	SimPresent       bool
	LastSeenAt       pgtype.Timestamptz
	MalfunctionCodes []string
	Status           string
	Notes            *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
	UnitNumber       *string
}

func (q *Queries) FleetGetEldDevice(ctx context.Context, arg FleetGetEldDeviceParams) (FleetGetEldDeviceRow, error) {
	row := q.db.QueryRow(ctx, fleetGetEldDevice, arg.CompanyID, arg.ID)
	var i FleetGetEldDeviceRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.Firmware,
		&i.ConnectionType,
		&i.SimPresent,
		&i.LastSeenAt,
		&i.MalfunctionCodes,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UnitNumber,
	)
	return i, err
}

const fleetGetUnit = `-- name: FleetGetUnit :one
SELECT u.id, u.company_id, u.branch_id, u.unit_number, u.make, u.model, u.year, u.vin, u.license_plate, u.plate_region, u.fuel_type, u.sleeper_berth, u.gvwr_class, u.status, u.out_of_service, u.notes, u.activated_on, u.created_at, u.updated_at, u.deleted_at,
       s.odometer_m       AS odometer_m,
       s.ts               AS telemetry_at,
       d.id               AS eld_device_id,
       d.serial           AS eld_device_serial,
       b.name             AS branch_name
FROM units u
LEFT JOIN unit_last_state s ON s.unit_id = u.id
LEFT JOIN branches b ON b.id = u.branch_id
LEFT JOIN eld_devices d ON d.unit_id = u.id AND d.deleted_at IS NULL
WHERE u.company_id = $1 AND u.id = $2 AND u.deleted_at IS NULL
`

type FleetGetUnitParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type FleetGetUnitRow struct {
	ID              uuid.UUID
	CompanyID       uuid.UUID
	BranchID        pgtype.UUID
	UnitNumber      string
	Make            *string
	Model           *string
	Year            *int32
	Vin             *string
	LicensePlate    *string
	PlateRegion     *string
	FuelType        *string
	SleeperBerth    bool
	GvwrClass       *string
	Status          string
	OutOfService    bool
	Notes           *string
	ActivatedOn     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       pgtype.Timestamptz
	OdometerM       *int64
	TelemetryAt     pgtype.Timestamptz
	EldDeviceID     pgtype.UUID
	EldDeviceSerial *string
	BranchName      *string
}

func (q *Queries) FleetGetUnit(ctx context.Context, arg FleetGetUnitParams) (FleetGetUnitRow, error) {
	row := q.db.QueryRow(ctx, fleetGetUnit, arg.CompanyID, arg.ID)
	var i FleetGetUnitRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.UnitNumber,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Vin,
		&i.LicensePlate,
		&i.PlateRegion,
		&i.FuelType,
		&i.SleeperBerth,
		&i.GvwrClass,
		&i.Status,
		&i.OutOfService,
		&i.Notes,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OdometerM,
		&i.TelemetryAt,
		&i.EldDeviceID,
		&i.EldDeviceSerial,
		&i.BranchName,
	)
	return i, err
}

const fleetGetUnitDiagnostics = `-- name: FleetGetUnitDiagnostics :one
SELECT
  u.id                AS unit_id,
  u.unit_number       AS unit_number,
  d.id                AS device_id,
  d.serial            AS device_serial,
  d.vendor            AS device_vendor,
  d.model             AS device_model,
  d.firmware          AS device_firmware,
  d.connection_type   AS connection_type,
  d.sim_present       AS sim_present,
  d.status            AS device_status,
  d.malfunction_codes AS malfunction_codes,
  d.last_seen_at      AS last_seen_at,
  s.online_status     AS online_status,
  t.ts                AS telemetry_at,
  t.odometer_m        AS odometer_m,
  t.engine_hours      AS engine_hours,
  t.fuel_pct          AS fuel_pct,
  t.coolant_temp_c    AS coolant_temp_c,
  t.coolant_level_pct AS coolant_level_pct,
  t.oil_level_pct     AS oil_level_pct,
  t.battery_pct       AS battery_pct,
  t.battery_voltage_v AS battery_voltage_v
FROM units u
LEFT JOIN unit_last_state s ON s.unit_id = u.id
LEFT JOIN eld_devices d ON d.unit_id = u.id AND d.deleted_at IS NULL
LEFT JOIN telemetry t ON t.company_id = u.company_id AND t.unit_id = u.id
  AND t.ts = (SELECT max(x.ts) FROM telemetry x WHERE x.company_id = u.company_id AND x.unit_id = u.id)
WHERE u.company_id = $1 AND u.id = $2 AND u.deleted_at IS NULL
`

type FleetGetUnitDiagnosticsParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type FleetGetUnitDiagnosticsRow struct {
	UnitID           uuid.UUID
	UnitNumber       string
	DeviceID         pgtype.UUID
	DeviceSerial     *string
	DeviceVendor     *string
	DeviceModel      *string
	DeviceFirmware   *string
	ConnectionType   *string
	SimPresent       *bool
	DeviceStatus     *string
	MalfunctionCodes []string
	LastSeenAt       pgtype.Timestamptz
	OnlineStatus     *string
	TelemetryAt      pgtype.Timestamptz
	OdometerM        *int64
	EngineHours      pgtype.Numeric
	FuelPct          *float64
	CoolantTempC     *float64
	CoolantLevelPct  *float64
	OilLevelPct      *float64
	BatteryPct       *float64
	BatteryVoltageV  *float64
}

func (q *Queries) FleetGetUnitDiagnostics(ctx context.Context, arg FleetGetUnitDiagnosticsParams) (FleetGetUnitDiagnosticsRow, error) {
	row := q.db.QueryRow(ctx, fleetGetUnitDiagnostics, arg.CompanyID, arg.ID)
	var i FleetGetUnitDiagnosticsRow
	err := row.Scan(
		&i.UnitID,
		&i.UnitNumber,
		&i.DeviceID,
		&i.DeviceSerial,
		&i.DeviceVendor,
		&i.DeviceModel,
		&i.DeviceFirmware,
		&i.ConnectionType,
		&i.SimPresent,
		&i.DeviceStatus,
		&i.MalfunctionCodes,
		&i.LastSeenAt,
		&i.OnlineStatus,
		&i.TelemetryAt,
		&i.OdometerM,
		&i.EngineHours,
		&i.FuelPct,
		&i.CoolantTempC,
		&i.CoolantLevelPct,
		&i.OilLevelPct,
		&i.BatteryPct,
		&i.BatteryVoltageV,
	)
	return i, err
}

const fleetListEldDevices = `-- name: FleetListEldDevices :many
SELECT d.id, d.company_id, d.unit_id, d.vendor, d.model, d.serial, d.firmware, d.connection_type, d.sim_present, d.last_seen_at, d.malfunction_codes, d.status, d.notes, d.created_at, d.updated_at, d.deleted_at, u.unit_number AS unit_number
FROM eld_devices d
LEFT JOIN units u ON u.id = d.unit_id AND u.deleted_at IS NULL
WHERE d.company_id = $1 AND d.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (d.serial || ' ' || d.vendor || ' ' || COALESCE(d.model,''))
          ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR d.status = $3::text)
  AND ($4::uuid IS NULL OR d.unit_id = $4::uuid)
  AND ($5::text IS NULL OR d.connection_type = $5::text)
ORDER BY
  CASE WHEN $6::text = 'serial'     AND $7::text = 'asc'  THEN d.serial     END ASC  NULLS LAST,
  CASE WHEN $6::text = 'serial'     AND $7::text = 'desc' THEN d.serial     END DESC NULLS LAST,
  CASE WHEN $6::text = 'vendor'     AND $7::text = 'asc'  THEN d.vendor     END ASC  NULLS LAST,
  CASE WHEN $6::text = 'vendor'     AND $7::text = 'desc' THEN d.vendor     END DESC NULLS LAST,
  CASE WHEN $6::text = 'status'     AND $7::text = 'asc'  THEN d.status     END ASC  NULLS LAST,
  CASE WHEN $6::text = 'status'     AND $7::text = 'desc' THEN d.status     END DESC NULLS LAST,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'asc'  THEN d.created_at END ASC  NULLS LAST,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'desc' THEN d.created_at END DESC NULLS LAST,
  d.serial ASC
LIMIT $9 OFFSET $8
`

type FleetListEldDevicesParams struct {
	CompanyID      uuid.UUID
	Search         *string
	Status         *string
	UnitID         pgtype.UUID
	ConnectionType *string
	Sort           string
	SortOrder      string
	Offset         int32
	Limit          int32
}

type FleetListEldDevicesRow struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	UnitID           pgtype.UUID
	Vendor           string
	Model            *string
	Serial           string
	Firmware         *string
	ConnectionType   *string
	SimPresent       bool
	LastSeenAt       pgtype.Timestamptz
	MalfunctionCodes []string
	Status           string
	Notes            *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
	UnitNumber       *string
}

func (q *Queries) FleetListEldDevices(ctx context.Context, arg FleetListEldDevicesParams) ([]FleetListEldDevicesRow, error) {
	rows, err := q.db.Query(ctx, fleetListEldDevices,
		arg.CompanyID,
		arg.Search,
		arg.Status,
		arg.UnitID,
		arg.ConnectionType,
		arg.Sort,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetListEldDevicesRow{}
	for rows.Next() {
		var i FleetListEldDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.Vendor,
			&i.Model,
			&i.Serial,
			&i.Firmware,
			&i.ConnectionType,
			&i.SimPresent,
			&i.LastSeenAt,
			&i.MalfunctionCodes,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UnitNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fleetListUnitAssignments = `-- name: FleetListUnitAssignments :many
SELECT a.id, a.unit_id, a.driver_id, a.role, a.assigned_at, a.unassigned_at,
       us.first_name, us.last_name, us.username
FROM unit_driver_assignments a
JOIN drivers dr ON dr.id = a.driver_id
JOIN users us ON us.id = dr.user_id
WHERE a.company_id = $1 AND a.unit_id = $2
  AND ($3::timestamptz IS NULL OR a.assigned_at >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR a.assigned_at <  $4::timestamptz)
ORDER BY a.assigned_at DESC
LIMIT $6 OFFSET $5
`

type FleetListUnitAssignmentsParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
	Offset    int32
	Limit     int32
}

type FleetListUnitAssignmentsRow struct {
	ID           uuid.UUID
	UnitID       uuid.UUID
	DriverID     uuid.UUID
	Role         string
	AssignedAt   time.Time
	UnassignedAt pgtype.Timestamptz
	FirstName    string
	LastName     string
	Username     string
}

func (q *Queries) FleetListUnitAssignments(ctx context.Context, arg FleetListUnitAssignmentsParams) ([]FleetListUnitAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, fleetListUnitAssignments,
		arg.CompanyID,
		arg.UnitID,
		arg.FromTs,
		arg.ToTs,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetListUnitAssignmentsRow{}
	for rows.Next() {
		var i FleetListUnitAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.DriverID,
			&i.Role,
			&i.AssignedAt,
			&i.UnassignedAt,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fleetListUnitAudit = `-- name: FleetListUnitAudit :many
SELECT a.id, a.table_name, a.record_id, a.field, a.old_value, a.new_value,
       a.action, a.edited_by, a.ts, us.first_name, us.last_name, us.username
FROM audit_log a
LEFT JOIN users us ON us.id = a.edited_by
WHERE a.company_id = $1::uuid
  AND a.table_name = 'units'
  AND a.record_id = $2::uuid
  AND ($3::timestamptz IS NULL OR a.ts >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR a.ts <  $4::timestamptz)
ORDER BY a.ts DESC
LIMIT $6 OFFSET $5
`

type FleetListUnitAuditParams struct {
	CompanyID uuid.UUID
	RecordID  uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
	Offset    int32
	Limit     int32
}

type FleetListUnitAuditRow struct {
	ID        uuid.UUID
	TableName string
	RecordID  pgtype.UUID
	Field     *string
	OldValue  []byte
	NewValue  []byte
	Action    string
	EditedBy  pgtype.UUID
	Ts        time.Time
	FirstName *string
	LastName  *string
	Username  *string
}

func (q *Queries) FleetListUnitAudit(ctx context.Context, arg FleetListUnitAuditParams) ([]FleetListUnitAuditRow, error) {
	rows, err := q.db.Query(ctx, fleetListUnitAudit,
		arg.CompanyID,
		arg.RecordID,
		arg.FromTs,
		arg.ToTs,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetListUnitAuditRow{}
	for rows.Next() {
		var i FleetListUnitAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RecordID,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.Action,
			&i.EditedBy,
			&i.Ts,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fleetListUnits = `-- name: FleetListUnits :many

SELECT u.id, u.company_id, u.branch_id, u.unit_number, u.make, u.model, u.year, u.vin, u.license_plate, u.plate_region, u.fuel_type, u.sleeper_berth, u.gvwr_class, u.status, u.out_of_service, u.notes, u.activated_on, u.created_at, u.updated_at, u.deleted_at,
       s.odometer_m       AS odometer_m,
       s.ts               AS telemetry_at,
       d.id               AS eld_device_id,
       d.serial           AS eld_device_serial,
       b.name             AS branch_name
FROM units u
LEFT JOIN unit_last_state s ON s.unit_id = u.id
LEFT JOIN branches b ON b.id = u.branch_id
LEFT JOIN eld_devices d ON d.unit_id = u.id AND d.deleted_at IS NULL
WHERE u.company_id = $1 AND u.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (u.unit_number || ' ' || COALESCE(u.vin,'') || ' ' || COALESCE(u.license_plate,''))
          ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR u.status = $3::text)
  AND ($4::uuid IS NULL OR u.branch_id = $4::uuid)
  AND ($5::bool IS NULL OR u.out_of_service = $5::bool)
  AND ($6::bool OR u.status = 'active')
ORDER BY
  CASE WHEN $7::text = 'unit_number' AND $8::text = 'asc'  THEN u.unit_number END ASC  NULLS LAST,
  CASE WHEN $7::text = 'unit_number' AND $8::text = 'desc' THEN u.unit_number END DESC NULLS LAST,
  CASE WHEN $7::text = 'status'      AND $8::text = 'asc'  THEN u.status      END ASC  NULLS LAST,
  CASE WHEN $7::text = 'status'      AND $8::text = 'desc' THEN u.status      END DESC NULLS LAST,
  CASE WHEN $7::text = 'make'        AND $8::text = 'asc'  THEN u.make        END ASC  NULLS LAST,
  CASE WHEN $7::text = 'make'        AND $8::text = 'desc' THEN u.make        END DESC NULLS LAST,
  CASE WHEN $7::text = 'year'        AND $8::text = 'asc'  THEN u.year        END ASC  NULLS LAST,
  CASE WHEN $7::text = 'year'        AND $8::text = 'desc' THEN u.year        END DESC NULLS LAST,
  CASE WHEN $7::text = 'created_at'  AND $8::text = 'asc'  THEN u.created_at  END ASC  NULLS LAST,
  CASE WHEN $7::text = 'created_at'  AND $8::text = 'desc' THEN u.created_at  END DESC NULLS LAST,
  u.unit_number ASC
LIMIT $10 OFFSET $9
`

type FleetListUnitsParams struct {
	CompanyID       uuid.UUID
	Search          *string
	Status          *string
	BranchID        pgtype.UUID
	OutOfService    *bool
	IncludeInactive bool
	Sort            string
	SortOrder       string
	Offset          int32
	Limit           int32
}

type FleetListUnitsRow struct {
	ID              uuid.UUID
	CompanyID       uuid.UUID
	BranchID        pgtype.UUID
	UnitNumber      string
	Make            *string
	Model           *string
	Year            *int32
	Vin             *string
	LicensePlate    *string
	PlateRegion     *string
	FuelType        *string
	SleeperBerth    bool
	GvwrClass       *string
	Status          string
	OutOfService    bool
	Notes           *string
	ActivatedOn     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       pgtype.Timestamptz
	OdometerM       *int64
	TelemetryAt     pgtype.Timestamptz
	EldDeviceID     pgtype.UUID
	EldDeviceSerial *string
	BranchName      *string
}

// Fleet domain (units + eld_devices + trailers + shipping_documents).
// Nullable filtrlar sqlc.narg() bilan yoziladi, saralash esa oq ro'yxatdan
// kelgan (sort, order) juftligi ustidan CASE bilan — SQL hech qachon
// konkatenatsiya qilinmaydi.
func (q *Queries) FleetListUnits(ctx context.Context, arg FleetListUnitsParams) ([]FleetListUnitsRow, error) {
	rows, err := q.db.Query(ctx, fleetListUnits,
		arg.CompanyID,
		arg.Search,
		arg.Status,
		arg.BranchID,
		arg.OutOfService,
		arg.IncludeInactive,
		arg.Sort,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetListUnitsRow{}
	for rows.Next() {
		var i FleetListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BranchID,
			&i.UnitNumber,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.Vin,
			&i.LicensePlate,
			&i.PlateRegion,
			&i.FuelType,
			&i.SleeperBerth,
			&i.GvwrClass,
			&i.Status,
			&i.OutOfService,
			&i.Notes,
			&i.ActivatedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OdometerM,
			&i.TelemetryAt,
			&i.EldDeviceID,
			&i.EldDeviceSerial,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fleetUpdateEldDevice = `-- name: FleetUpdateEldDevice :one
UPDATE eld_devices SET
  vendor          = COALESCE($1::text, vendor),
  model           = COALESCE($2::text, model),
  serial          = COALESCE($3::text, serial),
  firmware        = COALESCE($4::text, firmware),
  connection_type = COALESCE($5::text, connection_type),
  sim_present     = COALESCE($6::bool, sim_present),
  status          = COALESCE($7::text, status),
  notes           = COALESCE($8::text, notes)
WHERE company_id = $9 AND id = $10 AND deleted_at IS NULL
RETURNING id, company_id, unit_id, vendor, model, serial, firmware, connection_type, sim_present, last_seen_at, malfunction_codes, status, notes, created_at, updated_at, deleted_at
`

type FleetUpdateEldDeviceParams struct {
	Vendor         *string
	Model          *string
	Serial         *string
	Firmware       *string
	ConnectionType *string
	SimPresent     *bool
	Status         *string
	Notes          *string
	CompanyID      uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) FleetUpdateEldDevice(ctx context.Context, arg FleetUpdateEldDeviceParams) (EldDevice, error) {
	row := q.db.QueryRow(ctx, fleetUpdateEldDevice,
		arg.Vendor,
		arg.Model,
		arg.Serial,
		arg.Firmware,
		arg.ConnectionType,
		arg.SimPresent,
		arg.Status,
		arg.Notes,
		arg.CompanyID,
		arg.ID,
	)
	var i EldDevice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.Firmware,
		&i.ConnectionType,
		&i.SimPresent,
		&i.LastSeenAt,
		&i.MalfunctionCodes,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const fleetUpdateShippingDocument = `-- name: FleetUpdateShippingDocument :one
UPDATE shipping_documents SET
  number = COALESCE($1::text, number),
  notes  = COALESCE($2::text, notes)
WHERE company_id = $3 AND id = $4 AND deleted_at IS NULL
RETURNING id, company_id, number, notes, created_at, updated_at, deleted_at
`

type FleetUpdateShippingDocumentParams struct {
	Number    *string
	Notes     *string
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) FleetUpdateShippingDocument(ctx context.Context, arg FleetUpdateShippingDocumentParams) (ShippingDocument, error) {
	row := q.db.QueryRow(ctx, fleetUpdateShippingDocument,
		arg.Number,
		arg.Notes,
		arg.CompanyID,
		arg.ID,
	)
	var i ShippingDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const fleetUpdateTrailer = `-- name: FleetUpdateTrailer :one
UPDATE trailers SET
  number = COALESCE($1::text, number),
  notes  = COALESCE($2::text, notes)
WHERE company_id = $3 AND id = $4 AND deleted_at IS NULL
RETURNING id, company_id, number, notes, created_at, updated_at, deleted_at
`

type FleetUpdateTrailerParams struct {
	Number    *string
	Notes     *string
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) FleetUpdateTrailer(ctx context.Context, arg FleetUpdateTrailerParams) (Trailer, error) {
	row := q.db.QueryRow(ctx, fleetUpdateTrailer,
		arg.Number,
		arg.Notes,
		arg.CompanyID,
		arg.ID,
	)
	var i Trailer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const fleetUpdateUnit = `-- name: FleetUpdateUnit :one
UPDATE units SET
  branch_id      = COALESCE($1::uuid, branch_id),
  unit_number    = COALESCE($2::text, unit_number),
  make           = COALESCE($3::text, make),
  model          = COALESCE($4::text, model),
  year           = COALESCE($5::int, year),
  vin            = COALESCE($6::text, vin),
  license_plate  = COALESCE($7::text, license_plate),
  plate_region   = COALESCE($8::text, plate_region),
  fuel_type      = COALESCE($9::text, fuel_type),
  sleeper_berth  = COALESCE($10::bool, sleeper_berth),
  gvwr_class     = COALESCE($11::text, gvwr_class),
  notes          = COALESCE($12::text, notes),
  out_of_service = COALESCE($13::bool, out_of_service)
WHERE company_id = $14 AND id = $15 AND deleted_at IS NULL
RETURNING id, company_id, branch_id, unit_number, make, model, year, vin, license_plate, plate_region, fuel_type, sleeper_berth, gvwr_class, status, out_of_service, notes, activated_on, created_at, updated_at, deleted_at
`

type FleetUpdateUnitParams struct {
	BranchID     pgtype.UUID
	UnitNumber   *string
	Make         *string
	Model        *string
	Year         *int32
	Vin          *string
	LicensePlate *string
	PlateRegion  *string
	FuelType     *string
	SleeperBerth *bool
	GvwrClass    *string
	Notes        *string
	OutOfService *bool
	CompanyID    uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) FleetUpdateUnit(ctx context.Context, arg FleetUpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, fleetUpdateUnit,
		arg.BranchID,
		arg.UnitNumber,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Vin,
		arg.LicensePlate,
		arg.PlateRegion,
		arg.FuelType,
		arg.SleeperBerth,
		arg.GvwrClass,
		arg.Notes,
		arg.OutOfService,
		arg.CompanyID,
		arg.ID,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.UnitNumber,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Vin,
		&i.LicensePlate,
		&i.PlateRegion,
		&i.FuelType,
		&i.SleeperBerth,
		&i.GvwrClass,
		&i.Status,
		&i.OutOfService,
		&i.Notes,
		&i.ActivatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
