// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log_edit_requests.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLogEditRequests = `-- name: CountLogEditRequests :one
SELECT count(*) FROM log_edit_requests r
WHERE r.company_id = $1
  AND ($2::text IS NULL OR r.status = $2::text)
  AND ($3::uuid IS NULL OR r.driver_id = $3::uuid)
`

type CountLogEditRequestsParams struct {
	CompanyID uuid.UUID
	Column2   string
	Column3   uuid.UUID
}

func (q *Queries) CountLogEditRequests(ctx context.Context, arg CountLogEditRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogEditRequests, arg.CompanyID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingLogEditRequests = `-- name: CountPendingLogEditRequests :one
SELECT count(*) FROM log_edit_requests WHERE company_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingLogEditRequests(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingLogEditRequests, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLogEditRequest = `-- name: CreateLogEditRequest :one
INSERT INTO log_edit_requests (company_id, driver_id, daily_log_id, requested_by, changes, driver_note)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, company_id, driver_id, daily_log_id, requested_by, status, changes, driver_note, resolved_by, resolved_at, created_at, updated_at, source, unidentified_event_id
`

type CreateLogEditRequestParams struct {
	CompanyID   uuid.UUID
	DriverID    uuid.UUID
	DailyLogID  uuid.UUID
	RequestedBy uuid.UUID
	Changes     []byte
	DriverNote  *string
}

func (q *Queries) CreateLogEditRequest(ctx context.Context, arg CreateLogEditRequestParams) (LogEditRequest, error) {
	row := q.db.QueryRow(ctx, createLogEditRequest,
		arg.CompanyID,
		arg.DriverID,
		arg.DailyLogID,
		arg.RequestedBy,
		arg.Changes,
		arg.DriverNote,
	)
	var i LogEditRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.DailyLogID,
		&i.RequestedBy,
		&i.Status,
		&i.Changes,
		&i.DriverNote,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.UnidentifiedEventID,
	)
	return i, err
}

const getLogEditRequest = `-- name: GetLogEditRequest :one
SELECT id, company_id, driver_id, daily_log_id, requested_by, status, changes, driver_note, resolved_by, resolved_at, created_at, updated_at, source, unidentified_event_id FROM log_edit_requests WHERE company_id = $1 AND id = $2
`

type GetLogEditRequestParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetLogEditRequest(ctx context.Context, arg GetLogEditRequestParams) (LogEditRequest, error) {
	row := q.db.QueryRow(ctx, getLogEditRequest, arg.CompanyID, arg.ID)
	var i LogEditRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.DailyLogID,
		&i.RequestedBy,
		&i.Status,
		&i.Changes,
		&i.DriverNote,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.UnidentifiedEventID,
	)
	return i, err
}

const listLogEditRequests = `-- name: ListLogEditRequests :many
SELECT r.id, r.company_id, r.driver_id, r.daily_log_id, r.requested_by, r.status, r.changes, r.driver_note, r.resolved_by, r.resolved_at, r.created_at, r.updated_at, r.source, r.unidentified_event_id, u.first_name, u.last_name
FROM log_edit_requests r
JOIN drivers d ON d.id = r.driver_id
JOIN users   u ON u.id = d.user_id
WHERE r.company_id = $1
  AND ($2::text IS NULL OR r.status = $2::text)
  AND ($3::uuid IS NULL OR r.driver_id = $3::uuid)
ORDER BY r.created_at DESC
LIMIT $4 OFFSET $5
`

type ListLogEditRequestsParams struct {
	CompanyID uuid.UUID
	Column2   string
	Column3   uuid.UUID
	Limit     int32
	Offset    int32
}

type ListLogEditRequestsRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	DailyLogID          uuid.UUID
	RequestedBy         uuid.UUID
	Status              string
	Changes             []byte
	DriverNote          *string
	ResolvedBy          pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Source              string
	UnidentifiedEventID pgtype.UUID
	FirstName           string
	LastName            string
}

func (q *Queries) ListLogEditRequests(ctx context.Context, arg ListLogEditRequestsParams) ([]ListLogEditRequestsRow, error) {
	rows, err := q.db.Query(ctx, listLogEditRequests,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogEditRequestsRow{}
	for rows.Next() {
		var i ListLogEditRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.DailyLogID,
			&i.RequestedBy,
			&i.Status,
			&i.Changes,
			&i.DriverNote,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.UnidentifiedEventID,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveLogEditRequest = `-- name: ResolveLogEditRequest :one
UPDATE log_edit_requests SET status = $3, resolved_by = $4, resolved_at = now(), driver_note = COALESCE($5::text, driver_note)
WHERE company_id = $1 AND id = $2 AND status = 'pending'
RETURNING id, company_id, driver_id, daily_log_id, requested_by, status, changes, driver_note, resolved_by, resolved_at, created_at, updated_at, source, unidentified_event_id
`

type ResolveLogEditRequestParams struct {
	CompanyID  uuid.UUID
	ID         uuid.UUID
	Status     string
	ResolvedBy pgtype.UUID
	Column5    string
}

func (q *Queries) ResolveLogEditRequest(ctx context.Context, arg ResolveLogEditRequestParams) (LogEditRequest, error) {
	row := q.db.QueryRow(ctx, resolveLogEditRequest,
		arg.CompanyID,
		arg.ID,
		arg.Status,
		arg.ResolvedBy,
		arg.Column5,
	)
	var i LogEditRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.DailyLogID,
		&i.RequestedBy,
		&i.Status,
		&i.Changes,
		&i.DriverNote,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.UnidentifiedEventID,
	)
	return i, err
}
