// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const logsAnnotateUnidentifiedEvent = `-- name: LogsAnnotateUnidentifiedEvent :one
UPDATE unidentified_events
SET status = 'annotated', annotation = $1, resolved_by = $2, resolved_at = now()
WHERE company_id = $3 AND id = $4 AND status IN ('pending','proposed')
RETURNING id, company_id, unit_id, eld_device_id, start_at, end_at, distance_m, track_key, status, assigned_driver_id, annotation, resolved_by, resolved_at, created_at, updated_at, edit_request_id
`

type LogsAnnotateUnidentifiedEventParams struct {
	Annotation *string
	ResolvedBy pgtype.UUID
	CompanyID  uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) LogsAnnotateUnidentifiedEvent(ctx context.Context, arg LogsAnnotateUnidentifiedEventParams) (UnidentifiedEvent, error) {
	row := q.db.QueryRow(ctx, logsAnnotateUnidentifiedEvent,
		arg.Annotation,
		arg.ResolvedBy,
		arg.CompanyID,
		arg.ID,
	)
	var i UnidentifiedEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.StartAt,
		&i.EndAt,
		&i.DistanceM,
		&i.TrackKey,
		&i.Status,
		&i.AssignedDriverID,
		&i.Annotation,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditRequestID,
	)
	return i, err
}

const logsAssignEventsToDriver = `-- name: LogsAssignEventsToDriver :exec
UPDATE duty_status_events SET driver_id = $1, origin = 'assigned', daily_log_id = $2
WHERE company_id = $3 AND id = ANY($4::uuid[]) AND driver_id IS NULL
`

type LogsAssignEventsToDriverParams struct {
	DriverID   pgtype.UUID
	DailyLogID pgtype.UUID
	CompanyID  uuid.UUID
	Ids        []uuid.UUID
}

func (q *Queries) LogsAssignEventsToDriver(ctx context.Context, arg LogsAssignEventsToDriverParams) error {
	_, err := q.db.Exec(ctx, logsAssignEventsToDriver,
		arg.DriverID,
		arg.DailyLogID,
		arg.CompanyID,
		arg.Ids,
	)
	return err
}

const logsCertifyDailyLog = `-- name: LogsCertifyDailyLog :one
UPDATE daily_logs SET
  certification_status = 'certified',
  signed_at        = $1,
  signature_key    = $2,
  signed_device_id = $3::text,
  signed_ip        = $4::text,
  signed_by        = $5
WHERE company_id = $6 AND id = $7
RETURNING id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by
`

type LogsCertifyDailyLogParams struct {
	SignedAt       pgtype.Timestamptz
	SignatureKey   *string
	SignedDeviceID *string
	SignedIp       *string
	SignedBy       pgtype.UUID
	CompanyID      uuid.UUID
	ID             uuid.UUID
}

// Q26.1: sertifikatsiya = imzo kaliti + signed_at/ip/device + `certification` event.
func (q *Queries) LogsCertifyDailyLog(ctx context.Context, arg LogsCertifyDailyLogParams) (DailyLog, error) {
	row := q.db.QueryRow(ctx, logsCertifyDailyLog,
		arg.SignedAt,
		arg.SignatureKey,
		arg.SignedDeviceID,
		arg.SignedIp,
		arg.SignedBy,
		arg.CompanyID,
		arg.ID,
	)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
	)
	return i, err
}

const logsClaimUnidentifiedEvent = `-- name: LogsClaimUnidentifiedEvent :one
UPDATE unidentified_events
SET status = 'assigned', assigned_driver_id = $1, resolved_at = now()
WHERE company_id = $2 AND id = $3 AND status IN ('pending','proposed')
RETURNING id, company_id, unit_id, eld_device_id, start_at, end_at, distance_m, track_key, status, assigned_driver_id, annotation, resolved_by, resolved_at, created_at, updated_at, edit_request_id
`

type LogsClaimUnidentifiedEventParams struct {
	AssignedDriverID pgtype.UUID
	CompanyID        uuid.UUID
	ID               uuid.UUID
}

// §10.4: haydovchining o'zi qabul qilsa darhol `assigned`.
func (q *Queries) LogsClaimUnidentifiedEvent(ctx context.Context, arg LogsClaimUnidentifiedEventParams) (UnidentifiedEvent, error) {
	row := q.db.QueryRow(ctx, logsClaimUnidentifiedEvent, arg.AssignedDriverID, arg.CompanyID, arg.ID)
	var i UnidentifiedEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.StartAt,
		&i.EndAt,
		&i.DistanceM,
		&i.TrackKey,
		&i.Status,
		&i.AssignedDriverID,
		&i.Annotation,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditRequestID,
	)
	return i, err
}

const logsCountDriverDailyLogs = `-- name: LogsCountDriverDailyLogs :one
SELECT count(*) FROM daily_logs
WHERE company_id = $1 AND driver_id = $2
  AND log_date >= $3 AND log_date <= $4
`

type LogsCountDriverDailyLogsParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	FromDate  pgtype.Date
	ToDate    pgtype.Date
}

func (q *Queries) LogsCountDriverDailyLogs(ctx context.Context, arg LogsCountDriverDailyLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, logsCountDriverDailyLogs,
		arg.CompanyID,
		arg.DriverID,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const logsCountEditRequests = `-- name: LogsCountEditRequests :one
SELECT count(*)
FROM log_edit_requests r
JOIN drivers d ON d.id = r.driver_id
WHERE r.company_id = $1
  AND ($2::text IS NULL OR r.status = $2::text)
  AND ($3::uuid IS NULL OR r.driver_id = $3::uuid)
  AND ($4::uuid IS NULL OR d.branch_id = $4::uuid)
`

type LogsCountEditRequestsParams struct {
	CompanyID uuid.UUID
	Status    *string
	DriverID  pgtype.UUID
	BranchID  pgtype.UUID
}

func (q *Queries) LogsCountEditRequests(ctx context.Context, arg LogsCountEditRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, logsCountEditRequests,
		arg.CompanyID,
		arg.Status,
		arg.DriverID,
		arg.BranchID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const logsCountUncertifiedOlderThan = `-- name: LogsCountUncertifiedOlderThan :one
SELECT count(*)
FROM daily_logs l
JOIN drivers d ON d.id = l.driver_id
WHERE l.company_id = $1
  AND l.certification_status <> 'certified'
  AND l.log_date < $2
  AND ($3::uuid IS NULL OR l.driver_id = $3::uuid)
  AND ($4::uuid IS NULL OR d.branch_id = $4::uuid)
`

type LogsCountUncertifiedOlderThanParams struct {
	CompanyID  uuid.UUID
	BeforeDate pgtype.Date
	DriverID   pgtype.UUID
	BranchID   pgtype.UUID
}

func (q *Queries) LogsCountUncertifiedOlderThan(ctx context.Context, arg LogsCountUncertifiedOlderThanParams) (int64, error) {
	row := q.db.QueryRow(ctx, logsCountUncertifiedOlderThan,
		arg.CompanyID,
		arg.BeforeDate,
		arg.DriverID,
		arg.BranchID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const logsCountViolations = `-- name: LogsCountViolations :one
SELECT count(*)
FROM violations v
LEFT JOIN drivers d ON d.id = v.driver_id
WHERE v.company_id = $1
  AND ($2::uuid IS NULL OR v.driver_id = $2::uuid)
  AND ($3::uuid IS NULL OR d.branch_id = $3::uuid)
  AND ($4::text IS NULL OR v.type = $4::text)
  AND ($5::text IS NULL OR v.severity = $5::text)
  AND ($6::bool IS NULL
       OR ($6::bool AND v.resolved_at IS NOT NULL)
       OR (NOT $6::bool AND v.resolved_at IS NULL))
  AND ($7::timestamptz IS NULL OR v.occurred_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR v.occurred_at < $8::timestamptz)
`

type LogsCountViolationsParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	BranchID  pgtype.UUID
	Type      *string
	Severity  *string
	Resolved  *bool
	FromAt    pgtype.Timestamptz
	ToAt      pgtype.Timestamptz
}

func (q *Queries) LogsCountViolations(ctx context.Context, arg LogsCountViolationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, logsCountViolations,
		arg.CompanyID,
		arg.DriverID,
		arg.BranchID,
		arg.Type,
		arg.Severity,
		arg.Resolved,
		arg.FromAt,
		arg.ToAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const logsCreateEditRequest = `-- name: LogsCreateEditRequest :one

INSERT INTO log_edit_requests (
  company_id, driver_id, daily_log_id, requested_by, changes, source, unidentified_event_id
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7::uuid
)
RETURNING id, company_id, driver_id, daily_log_id, requested_by, status, changes, driver_note, resolved_by, resolved_at, created_at, updated_at, source, unidentified_event_id
`

type LogsCreateEditRequestParams struct {
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	DailyLogID          uuid.UUID
	RequestedBy         uuid.UUID
	Changes             []byte
	Source              string
	UnidentifiedEventID pgtype.UUID
}

// ------------------------------------------------------ log edit requests
func (q *Queries) LogsCreateEditRequest(ctx context.Context, arg LogsCreateEditRequestParams) (LogEditRequest, error) {
	row := q.db.QueryRow(ctx, logsCreateEditRequest,
		arg.CompanyID,
		arg.DriverID,
		arg.DailyLogID,
		arg.RequestedBy,
		arg.Changes,
		arg.Source,
		arg.UnidentifiedEventID,
	)
	var i LogEditRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.DailyLogID,
		&i.RequestedBy,
		&i.Status,
		&i.Changes,
		&i.DriverNote,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.UnidentifiedEventID,
	)
	return i, err
}

const logsGetDailyLog = `-- name: LogsGetDailyLog :one
SELECT l.id, l.company_id, l.driver_id, l.log_date, l.timezone, l.unit_ids, l.co_driver_id, l.distance_m, l.trailer_ids, l.shipping_doc_ids, l.totals, l.certification_status, l.signed_at, l.signature_key, l.signed_device_id, l.created_at, l.updated_at, l.signed_ip, l.signed_by, u.first_name, u.last_name, d.branch_id, d.user_id,
       cu.first_name AS co_driver_first_name,
       cu.last_name  AS co_driver_last_name,
       c.name        AS company_name,
       c.home_terminal_address,
       c.regulation_profile
FROM daily_logs l
JOIN drivers   d ON d.id = l.driver_id
JOIN users     u ON u.id = d.user_id
JOIN companies c ON c.id = l.company_id
LEFT JOIN drivers cd ON cd.id = l.co_driver_id
LEFT JOIN users   cu ON cu.id = cd.user_id
WHERE l.company_id = $1 AND l.id = $2
`

type LogsGetDailyLogParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type LogsGetDailyLogRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	Timezone            string
	UnitIds             []uuid.UUID
	CoDriverID          pgtype.UUID
	DistanceM           int64
	TrailerIds          []uuid.UUID
	ShippingDocIds      []uuid.UUID
	Totals              []byte
	CertificationStatus string
	SignedAt            pgtype.Timestamptz
	SignatureKey        *string
	SignedDeviceID      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SignedIp            *string
	SignedBy            pgtype.UUID
	FirstName           string
	LastName            string
	BranchID            pgtype.UUID
	UserID              uuid.UUID
	CoDriverFirstName   *string
	CoDriverLastName    *string
	CompanyName         string
	HomeTerminalAddress *string
	RegulationProfile   string
}

func (q *Queries) LogsGetDailyLog(ctx context.Context, arg LogsGetDailyLogParams) (LogsGetDailyLogRow, error) {
	row := q.db.QueryRow(ctx, logsGetDailyLog, arg.CompanyID, arg.ID)
	var i LogsGetDailyLogRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
		&i.FirstName,
		&i.LastName,
		&i.BranchID,
		&i.UserID,
		&i.CoDriverFirstName,
		&i.CoDriverLastName,
		&i.CompanyName,
		&i.HomeTerminalAddress,
		&i.RegulationProfile,
	)
	return i, err
}

const logsGetDefaultSignature = `-- name: LogsGetDefaultSignature :one
SELECT id, image_key_enc FROM signatures
WHERE company_id = $1 AND user_id = $2 AND is_default AND deleted_at IS NULL
LIMIT 1
`

type LogsGetDefaultSignatureParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

type LogsGetDefaultSignatureRow struct {
	ID          uuid.UUID
	ImageKeyEnc string
}

func (q *Queries) LogsGetDefaultSignature(ctx context.Context, arg LogsGetDefaultSignatureParams) (LogsGetDefaultSignatureRow, error) {
	row := q.db.QueryRow(ctx, logsGetDefaultSignature, arg.CompanyID, arg.UserID)
	var i LogsGetDefaultSignatureRow
	err := row.Scan(&i.ID, &i.ImageKeyEnc)
	return i, err
}

const logsGetDriverForUser = `-- name: LogsGetDriverForUser :one

SELECT d.id, d.company_id, d.user_id, d.branch_id, d.status, d.default_unit_id,
       d.home_terminal, u.first_name, u.last_name, u.email,
       c.timezone, c.name AS company_name, c.home_terminal_address, c.regulation_profile
FROM drivers d
JOIN users     u ON u.id = d.user_id
JOIN companies c ON c.id = d.company_id
WHERE d.company_id = $1 AND d.id = $2 AND d.deleted_at IS NULL
`

type LogsGetDriverForUserParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type LogsGetDriverForUserRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	UserID              uuid.UUID
	BranchID            pgtype.UUID
	Status              string
	DefaultUnitID       pgtype.UUID
	HomeTerminal        *string
	FirstName           string
	LastName            string
	Email               *string
	Timezone            string
	CompanyName         string
	HomeTerminalAddress *string
	RegulationProfile   string
}

// ------------------------------------------------------------ inspection
func (q *Queries) LogsGetDriverForUser(ctx context.Context, arg LogsGetDriverForUserParams) (LogsGetDriverForUserRow, error) {
	row := q.db.QueryRow(ctx, logsGetDriverForUser, arg.CompanyID, arg.ID)
	var i LogsGetDriverForUserRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.Status,
		&i.DefaultUnitID,
		&i.HomeTerminal,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Timezone,
		&i.CompanyName,
		&i.HomeTerminalAddress,
		&i.RegulationProfile,
	)
	return i, err
}

const logsGetEditRequest = `-- name: LogsGetEditRequest :one
SELECT r.id, r.company_id, r.driver_id, r.daily_log_id, r.requested_by, r.status, r.changes, r.driver_note, r.resolved_by, r.resolved_at, r.created_at, r.updated_at, r.source, r.unidentified_event_id, u.first_name, u.last_name, d.user_id, d.branch_id, l.log_date, l.timezone
FROM log_edit_requests r
JOIN drivers    d ON d.id = r.driver_id
JOIN users      u ON u.id = d.user_id
JOIN daily_logs l ON l.id = r.daily_log_id
WHERE r.company_id = $1 AND r.id = $2
`

type LogsGetEditRequestParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type LogsGetEditRequestRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	DailyLogID          uuid.UUID
	RequestedBy         uuid.UUID
	Status              string
	Changes             []byte
	DriverNote          *string
	ResolvedBy          pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Source              string
	UnidentifiedEventID pgtype.UUID
	FirstName           string
	LastName            string
	UserID              uuid.UUID
	BranchID            pgtype.UUID
	LogDate             pgtype.Date
	Timezone            string
}

func (q *Queries) LogsGetEditRequest(ctx context.Context, arg LogsGetEditRequestParams) (LogsGetEditRequestRow, error) {
	row := q.db.QueryRow(ctx, logsGetEditRequest, arg.CompanyID, arg.ID)
	var i LogsGetEditRequestRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.DailyLogID,
		&i.RequestedBy,
		&i.Status,
		&i.Changes,
		&i.DriverNote,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.UnidentifiedEventID,
		&i.FirstName,
		&i.LastName,
		&i.UserID,
		&i.BranchID,
		&i.LogDate,
		&i.Timezone,
	)
	return i, err
}

const logsGetEvent = `-- name: LogsGetEvent :one
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events WHERE company_id = $1 AND id = $2
`

type LogsGetEventParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) LogsGetEvent(ctx context.Context, arg LogsGetEventParams) (DutyStatusEvent, error) {
	row := q.db.QueryRow(ctx, logsGetEvent, arg.CompanyID, arg.ID)
	var i DutyStatusEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.EventType,
		&i.Status,
		&i.Special,
		&i.EventTime,
		&i.TimeSource,
		&i.TimeUnverified,
		&i.ClockSkewSec,
		&i.Origin,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.GpsAccuracyM,
		&i.OdometerM,
		&i.EngineHours,
		&i.Notes,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.ClientEventID,
		&i.DeviceSeq,
		&i.ReceivedAt,
		&i.SupersededBy,
		&i.Locked,
		&i.DailyLogID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logsGetSignature = `-- name: LogsGetSignature :one
SELECT id, image_key_enc FROM signatures
WHERE company_id = $1 AND id = $2 AND user_id = $3 AND deleted_at IS NULL
`

type LogsGetSignatureParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	UserID    uuid.UUID
}

type LogsGetSignatureRow struct {
	ID          uuid.UUID
	ImageKeyEnc string
}

func (q *Queries) LogsGetSignature(ctx context.Context, arg LogsGetSignatureParams) (LogsGetSignatureRow, error) {
	row := q.db.QueryRow(ctx, logsGetSignature, arg.CompanyID, arg.ID, arg.UserID)
	var i LogsGetSignatureRow
	err := row.Scan(&i.ID, &i.ImageKeyEnc)
	return i, err
}

const logsGetUnidentifiedEvent = `-- name: LogsGetUnidentifiedEvent :one

SELECT e.id, e.company_id, e.unit_id, e.eld_device_id, e.start_at, e.end_at, e.distance_m, e.track_key, e.status, e.assigned_driver_id, e.annotation, e.resolved_by, e.resolved_at, e.created_at, e.updated_at, e.edit_request_id, u.unit_number
FROM unidentified_events e
JOIN units u ON u.id = e.unit_id
WHERE e.company_id = $1 AND e.id = $2
`

type LogsGetUnidentifiedEventParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type LogsGetUnidentifiedEventRow struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	UnitID           uuid.UUID
	EldDeviceID      pgtype.UUID
	StartAt          time.Time
	EndAt            pgtype.Timestamptz
	DistanceM        int64
	TrackKey         *string
	Status           string
	AssignedDriverID pgtype.UUID
	Annotation       *string
	ResolvedBy       pgtype.UUID
	ResolvedAt       pgtype.Timestamptz
	CreatedAt        time.Time
	UpdatedAt        time.Time
	EditRequestID    pgtype.UUID
	UnitNumber       string
}

// --------------------------------------------------- unidentified driving
func (q *Queries) LogsGetUnidentifiedEvent(ctx context.Context, arg LogsGetUnidentifiedEventParams) (LogsGetUnidentifiedEventRow, error) {
	row := q.db.QueryRow(ctx, logsGetUnidentifiedEvent, arg.CompanyID, arg.ID)
	var i LogsGetUnidentifiedEventRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.StartAt,
		&i.EndAt,
		&i.DistanceM,
		&i.TrackKey,
		&i.Status,
		&i.AssignedDriverID,
		&i.Annotation,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditRequestID,
		&i.UnitNumber,
	)
	return i, err
}

const logsGetViolation = `-- name: LogsGetViolation :one
SELECT v.id, v.company_id, v.driver_id, v.unit_id, v.daily_log_id, v.type, v.severity, v.occurred_at, v.details, v.policy_version_id, v.resolved_at, v.resolved_reason, v.created_at, v.updated_at, v.unidentified_event_id, v.resolved_by, u.first_name, u.last_name, d.branch_id, l.log_date
FROM violations v
LEFT JOIN drivers d ON d.id = v.driver_id
LEFT JOIN users   u ON u.id = d.user_id
LEFT JOIN daily_logs l ON l.id = v.daily_log_id
WHERE v.company_id = $1 AND v.id = $2
`

type LogsGetViolationParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type LogsGetViolationRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            pgtype.UUID
	UnitID              pgtype.UUID
	DailyLogID          pgtype.UUID
	Type                string
	Severity            string
	OccurredAt          time.Time
	Details             []byte
	PolicyVersionID     pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	ResolvedReason      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	UnidentifiedEventID pgtype.UUID
	ResolvedBy          pgtype.UUID
	FirstName           *string
	LastName            *string
	BranchID            pgtype.UUID
	LogDate             pgtype.Date
}

func (q *Queries) LogsGetViolation(ctx context.Context, arg LogsGetViolationParams) (LogsGetViolationRow, error) {
	row := q.db.QueryRow(ctx, logsGetViolation, arg.CompanyID, arg.ID)
	var i LogsGetViolationRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.DailyLogID,
		&i.Type,
		&i.Severity,
		&i.OccurredAt,
		&i.Details,
		&i.PolicyVersionID,
		&i.ResolvedAt,
		&i.ResolvedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnidentifiedEventID,
		&i.ResolvedBy,
		&i.FirstName,
		&i.LastName,
		&i.BranchID,
		&i.LogDate,
	)
	return i, err
}

const logsInsertEditEvent = `-- name: LogsInsertEditEvent :one
INSERT INTO duty_status_events (
  company_id, driver_id, unit_id, event_type, status, special,
  event_time, time_source, origin, notes, client_event_id, daily_log_id
) VALUES (
  $1, $2, $3::uuid, 'duty_status', $4, $5,
  $6, 'server', $7, $8, $9, $10
)
RETURNING id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at
`

type LogsInsertEditEventParams struct {
	CompanyID     uuid.UUID
	DriverID      pgtype.UUID
	UnitID        pgtype.UUID
	Status        *string
	Special       string
	EventTime     time.Time
	Origin        string
	Notes         *string
	ClientEventID uuid.UUID
	DailyLogID    pgtype.UUID
}

// Tahrir natijasi: yangi event `origin` bilan (`driver_edit` yoki `admin_edit`),
// asl event `superseded_by` orqali saqlanadi (hech narsa o'chmaydi).
func (q *Queries) LogsInsertEditEvent(ctx context.Context, arg LogsInsertEditEventParams) (DutyStatusEvent, error) {
	row := q.db.QueryRow(ctx, logsInsertEditEvent,
		arg.CompanyID,
		arg.DriverID,
		arg.UnitID,
		arg.Status,
		arg.Special,
		arg.EventTime,
		arg.Origin,
		arg.Notes,
		arg.ClientEventID,
		arg.DailyLogID,
	)
	var i DutyStatusEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.EventType,
		&i.Status,
		&i.Special,
		&i.EventTime,
		&i.TimeSource,
		&i.TimeUnverified,
		&i.ClockSkewSec,
		&i.Origin,
		&i.Lat,
		&i.Lng,
		&i.LocationText,
		&i.GpsAccuracyM,
		&i.OdometerM,
		&i.EngineHours,
		&i.Notes,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.ClientEventID,
		&i.DeviceSeq,
		&i.ReceivedAt,
		&i.SupersededBy,
		&i.Locked,
		&i.DailyLogID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logsListDayEvents = `-- name: LogsListDayEvents :many

SELECT e.id, e.company_id, e.driver_id, e.unit_id, e.eld_device_id, e.event_type, e.status, e.special, e.event_time, e.time_source, e.time_unverified, e.clock_skew_sec, e.origin, e.lat, e.lng, e.location_text, e.gps_accuracy_m, e.odometer_m, e.engine_hours, e.notes, e.trailer_ids, e.shipping_doc_ids, e.client_event_id, e.device_seq, e.received_at, e.superseded_by, e.locked, e.daily_log_id, e.created_at, e.updated_at, un.unit_number
FROM duty_status_events e
LEFT JOIN units un ON un.id = e.unit_id
WHERE e.company_id = $1 AND e.daily_log_id = $2
ORDER BY e.event_time, e.device_seq NULLS LAST
`

type LogsListDayEventsParams struct {
	CompanyID  uuid.UUID
	DailyLogID pgtype.UUID
}

type LogsListDayEventsRow struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	DriverID       pgtype.UUID
	UnitID         pgtype.UUID
	EldDeviceID    pgtype.UUID
	EventType      string
	Status         *string
	Special        string
	EventTime      time.Time
	TimeSource     string
	TimeUnverified bool
	ClockSkewSec   int32
	Origin         string
	Lat            *float64
	Lng            *float64
	LocationText   *string
	GpsAccuracyM   *int32
	OdometerM      *int64
	EngineHours    pgtype.Numeric
	Notes          *string
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	ClientEventID  uuid.UUID
	DeviceSeq      *int64
	ReceivedAt     time.Time
	SupersededBy   pgtype.UUID
	Locked         bool
	DailyLogID     pgtype.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UnitNumber     *string
}

// ------------------------------------------------------------ log events
// Kun eventlari; superseded qatorlar ham qaytadi, tarix ✎ belgisi uchun kerak (Q17.2).
func (q *Queries) LogsListDayEvents(ctx context.Context, arg LogsListDayEventsParams) ([]LogsListDayEventsRow, error) {
	rows, err := q.db.Query(ctx, logsListDayEvents, arg.CompanyID, arg.DailyLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListDayEventsRow{}
	for rows.Next() {
		var i LogsListDayEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListDriverDailyLogs = `-- name: LogsListDriverDailyLogs :many


SELECT l.id, l.company_id, l.driver_id, l.log_date, l.timezone, l.unit_ids, l.co_driver_id, l.distance_m, l.trailer_ids, l.shipping_doc_ids, l.totals, l.certification_status, l.signed_at, l.signature_key, l.signed_device_id, l.created_at, l.updated_at, l.signed_ip, l.signed_by, u.first_name, u.last_name,
       cu.first_name AS co_driver_first_name,
       cu.last_name  AS co_driver_last_name
FROM daily_logs l
JOIN drivers d ON d.id = l.driver_id
JOIN users   u ON u.id = d.user_id
LEFT JOIN drivers cd ON cd.id = l.co_driver_id
LEFT JOIN users   cu ON cu.id = cd.user_id
WHERE l.company_id = $1 AND l.driver_id = $2
  AND l.log_date >= $3 AND l.log_date <= $4
ORDER BY l.log_date DESC
LIMIT $6 OFFSET $5
`

type LogsListDriverDailyLogsParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	FromDate  pgtype.Date
	ToDate    pgtype.Date
	Off       int32
	Lim       int32
}

type LogsListDriverDailyLogsRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	Timezone            string
	UnitIds             []uuid.UUID
	CoDriverID          pgtype.UUID
	DistanceM           int64
	TrailerIds          []uuid.UUID
	ShippingDocIds      []uuid.UUID
	Totals              []byte
	CertificationStatus string
	SignedAt            pgtype.Timestamptz
	SignatureKey        *string
	SignedDeviceID      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SignedIp            *string
	SignedBy            pgtype.UUID
	FirstName           string
	LastName            string
	CoDriverFirstName   *string
	CoDriverLastName    *string
}

// Stage 4 (internal/domain/logs): daily log window, certification, the
// propose/approve edit model, unidentified driving assignment, the canonical
// violation catalogue and the roadside inspection window.
// Vaqtlar UTC; kunga ajratish Home Terminal TZ bo'yicha Go tomonida.
// ------------------------------------------------------------- daily logs
// Q19: certification oynasi — [from, to] kunlari, eng yangisi birinchi.
func (q *Queries) LogsListDriverDailyLogs(ctx context.Context, arg LogsListDriverDailyLogsParams) ([]LogsListDriverDailyLogsRow, error) {
	rows, err := q.db.Query(ctx, logsListDriverDailyLogs,
		arg.CompanyID,
		arg.DriverID,
		arg.FromDate,
		arg.ToDate,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListDriverDailyLogsRow{}
	for rows.Next() {
		var i LogsListDriverDailyLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.LogDate,
			&i.Timezone,
			&i.UnitIds,
			&i.CoDriverID,
			&i.DistanceM,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.Totals,
			&i.CertificationStatus,
			&i.SignedAt,
			&i.SignatureKey,
			&i.SignedDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SignedIp,
			&i.SignedBy,
			&i.FirstName,
			&i.LastName,
			&i.CoDriverFirstName,
			&i.CoDriverLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListDriverEventsBetween = `-- name: LogsListDriverEventsBetween :many
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2
  AND event_time >= $3 AND event_time < $4
  AND superseded_by IS NULL
ORDER BY event_time, device_seq NULLS LAST
`

type LogsListDriverEventsBetweenParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	FromAt    time.Time
	ToAt      time.Time
}

func (q *Queries) LogsListDriverEventsBetween(ctx context.Context, arg LogsListDriverEventsBetweenParams) ([]DutyStatusEvent, error) {
	rows, err := q.db.Query(ctx, logsListDriverEventsBetween,
		arg.CompanyID,
		arg.DriverID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyStatusEvent{}
	for rows.Next() {
		var i DutyStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListEditRequests = `-- name: LogsListEditRequests :many
SELECT r.id, r.company_id, r.driver_id, r.daily_log_id, r.requested_by, r.status, r.changes, r.driver_note, r.resolved_by, r.resolved_at, r.created_at, r.updated_at, r.source, r.unidentified_event_id, u.first_name, u.last_name, l.log_date, l.timezone
FROM log_edit_requests r
JOIN drivers    d ON d.id = r.driver_id
JOIN users      u ON u.id = d.user_id
JOIN daily_logs l ON l.id = r.daily_log_id
WHERE r.company_id = $1
  AND ($2::text IS NULL OR r.status = $2::text)
  AND ($3::uuid IS NULL OR r.driver_id = $3::uuid)
  AND ($4::uuid IS NULL OR d.branch_id = $4::uuid)
ORDER BY r.created_at DESC
LIMIT $6 OFFSET $5
`

type LogsListEditRequestsParams struct {
	CompanyID uuid.UUID
	Status    *string
	DriverID  pgtype.UUID
	BranchID  pgtype.UUID
	Off       int32
	Lim       int32
}

type LogsListEditRequestsRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	DailyLogID          uuid.UUID
	RequestedBy         uuid.UUID
	Status              string
	Changes             []byte
	DriverNote          *string
	ResolvedBy          pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Source              string
	UnidentifiedEventID pgtype.UUID
	FirstName           string
	LastName            string
	LogDate             pgtype.Date
	Timezone            string
}

func (q *Queries) LogsListEditRequests(ctx context.Context, arg LogsListEditRequestsParams) ([]LogsListEditRequestsRow, error) {
	rows, err := q.db.Query(ctx, logsListEditRequests,
		arg.CompanyID,
		arg.Status,
		arg.DriverID,
		arg.BranchID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListEditRequestsRow{}
	for rows.Next() {
		var i LogsListEditRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.DailyLogID,
			&i.RequestedBy,
			&i.Status,
			&i.Changes,
			&i.DriverNote,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.UnidentifiedEventID,
			&i.FirstName,
			&i.LastName,
			&i.LogDate,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListEventsByIDs = `-- name: LogsListEventsByIDs :many
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND id = ANY($2::uuid[])
`

type LogsListEventsByIDsParams struct {
	CompanyID uuid.UUID
	Ids       []uuid.UUID
}

func (q *Queries) LogsListEventsByIDs(ctx context.Context, arg LogsListEventsByIDsParams) ([]DutyStatusEvent, error) {
	rows, err := q.db.Query(ctx, logsListEventsByIDs, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyStatusEvent{}
	for rows.Next() {
		var i DutyStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListOpenViolationsForLog = `-- name: LogsListOpenViolationsForLog :many
SELECT id, company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id, resolved_at, resolved_reason, created_at, updated_at, unidentified_event_id, resolved_by FROM violations
WHERE company_id = $1 AND daily_log_id = $2 AND resolved_at IS NULL
ORDER BY occurred_at
`

type LogsListOpenViolationsForLogParams struct {
	CompanyID  uuid.UUID
	DailyLogID pgtype.UUID
}

func (q *Queries) LogsListOpenViolationsForLog(ctx context.Context, arg LogsListOpenViolationsForLogParams) ([]Violation, error) {
	rows, err := q.db.Query(ctx, logsListOpenViolationsForLog, arg.CompanyID, arg.DailyLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Violation{}
	for rows.Next() {
		var i Violation
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.DailyLogID,
			&i.Type,
			&i.Severity,
			&i.OccurredAt,
			&i.Details,
			&i.PolicyVersionID,
			&i.ResolvedAt,
			&i.ResolvedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnidentifiedEventID,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListPendingEditRequestsForDriver = `-- name: LogsListPendingEditRequestsForDriver :many
SELECT r.id, r.daily_log_id, r.status, r.changes, r.source, r.created_at, r.updated_at,
       l.log_date, l.timezone
FROM log_edit_requests r
JOIN daily_logs l ON l.id = r.daily_log_id
WHERE r.company_id = $1 AND r.driver_id = $2
  AND r.status = 'pending' AND r.updated_at > $3
ORDER BY r.updated_at
LIMIT $4
`

type LogsListPendingEditRequestsForDriverParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	Since     time.Time
	Lim       int32
}

type LogsListPendingEditRequestsForDriverRow struct {
	ID         uuid.UUID
	DailyLogID uuid.UUID
	Status     string
	Changes    []byte
	Source     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LogDate    pgtype.Date
	Timezone   string
}

// /sync/pull: haydovchining javobini kutayotgan takliflar.
func (q *Queries) LogsListPendingEditRequestsForDriver(ctx context.Context, arg LogsListPendingEditRequestsForDriverParams) ([]LogsListPendingEditRequestsForDriverRow, error) {
	rows, err := q.db.Query(ctx, logsListPendingEditRequestsForDriver,
		arg.CompanyID,
		arg.DriverID,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListPendingEditRequestsForDriverRow{}
	for rows.Next() {
		var i LogsListPendingEditRequestsForDriverRow
		if err := rows.Scan(
			&i.ID,
			&i.DailyLogID,
			&i.Status,
			&i.Changes,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogDate,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListShippingDocNumbersByIDs = `-- name: LogsListShippingDocNumbersByIDs :many
SELECT id, number FROM shipping_documents
WHERE company_id = $1 AND id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type LogsListShippingDocNumbersByIDsParams struct {
	CompanyID uuid.UUID
	Ids       []uuid.UUID
}

type LogsListShippingDocNumbersByIDsRow struct {
	ID     uuid.UUID
	Number string
}

func (q *Queries) LogsListShippingDocNumbersByIDs(ctx context.Context, arg LogsListShippingDocNumbersByIDsParams) ([]LogsListShippingDocNumbersByIDsRow, error) {
	rows, err := q.db.Query(ctx, logsListShippingDocNumbersByIDs, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListShippingDocNumbersByIDsRow{}
	for rows.Next() {
		var i LogsListShippingDocNumbersByIDsRow
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListStaleUnidentifiedEvents = `-- name: LogsListStaleUnidentifiedEvents :many
SELECT id, company_id, unit_id, eld_device_id, start_at, end_at, distance_m, track_key, status, assigned_driver_id, annotation, resolved_by, resolved_at, created_at, updated_at, edit_request_id FROM unidentified_events
WHERE company_id = $1 AND status = 'pending' AND start_at < $2
ORDER BY start_at
`

type LogsListStaleUnidentifiedEventsParams struct {
	CompanyID uuid.UUID
	Before    time.Time
}

// Q57 `unidentified_driving`: 8 kundan ortiq tayinlanmagan bloklar.
func (q *Queries) LogsListStaleUnidentifiedEvents(ctx context.Context, arg LogsListStaleUnidentifiedEventsParams) ([]UnidentifiedEvent, error) {
	rows, err := q.db.Query(ctx, logsListStaleUnidentifiedEvents, arg.CompanyID, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnidentifiedEvent{}
	for rows.Next() {
		var i UnidentifiedEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.StartAt,
			&i.EndAt,
			&i.DistanceM,
			&i.TrackKey,
			&i.Status,
			&i.AssignedDriverID,
			&i.Annotation,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditRequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListTrailerNumbersByIDs = `-- name: LogsListTrailerNumbersByIDs :many
SELECT id, number FROM trailers
WHERE company_id = $1 AND id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type LogsListTrailerNumbersByIDsParams struct {
	CompanyID uuid.UUID
	Ids       []uuid.UUID
}

type LogsListTrailerNumbersByIDsRow struct {
	ID     uuid.UUID
	Number string
}

func (q *Queries) LogsListTrailerNumbersByIDs(ctx context.Context, arg LogsListTrailerNumbersByIDsParams) ([]LogsListTrailerNumbersByIDsRow, error) {
	rows, err := q.db.Query(ctx, logsListTrailerNumbersByIDs, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListTrailerNumbersByIDsRow{}
	for rows.Next() {
		var i LogsListTrailerNumbersByIDsRow
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListUnassignedEventsInRange = `-- name: LogsListUnassignedEventsInRange :many
SELECT id, company_id, driver_id, unit_id, eld_device_id, event_type, status, special, event_time, time_source, time_unverified, clock_skew_sec, origin, lat, lng, location_text, gps_accuracy_m, odometer_m, engine_hours, notes, trailer_ids, shipping_doc_ids, client_event_id, device_seq, received_at, superseded_by, locked, daily_log_id, created_at, updated_at FROM duty_status_events
WHERE company_id = $1 AND driver_id IS NULL AND unit_id = $2
  AND event_time >= $3 AND event_time <= $4
ORDER BY event_time
`

type LogsListUnassignedEventsInRangeParams struct {
	CompanyID uuid.UUID
	UnitID    pgtype.UUID
	FromAt    time.Time
	ToAt      time.Time
}

func (q *Queries) LogsListUnassignedEventsInRange(ctx context.Context, arg LogsListUnassignedEventsInRangeParams) ([]DutyStatusEvent, error) {
	rows, err := q.db.Query(ctx, logsListUnassignedEventsInRange,
		arg.CompanyID,
		arg.UnitID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyStatusEvent{}
	for rows.Next() {
		var i DutyStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListUncertifiedInWindow = `-- name: LogsListUncertifiedInWindow :many
SELECT id, driver_id, log_date, certification_status
FROM daily_logs
WHERE company_id = $1 AND driver_id = $2
  AND certification_status <> 'certified'
  AND log_date >= $3 AND log_date <= $4
ORDER BY log_date
`

type LogsListUncertifiedInWindowParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	FromDate  pgtype.Date
	ToDate    pgtype.Date
}

type LogsListUncertifiedInWindowRow struct {
	ID                  uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	CertificationStatus string
}

// Q57 `uncertified_log`: oynadagi sertifikatlanmagan kunlar (1 kun warning,
// >=2 kun violation) — nightly qayta hisob uchun.
func (q *Queries) LogsListUncertifiedInWindow(ctx context.Context, arg LogsListUncertifiedInWindowParams) ([]LogsListUncertifiedInWindowRow, error) {
	rows, err := q.db.Query(ctx, logsListUncertifiedInWindow,
		arg.CompanyID,
		arg.DriverID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListUncertifiedInWindowRow{}
	for rows.Next() {
		var i LogsListUncertifiedInWindowRow
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.LogDate,
			&i.CertificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListUncertifiedOlderThan = `-- name: LogsListUncertifiedOlderThan :many
SELECT l.id, l.company_id, l.driver_id, l.log_date, l.timezone, l.unit_ids, l.co_driver_id, l.distance_m, l.trailer_ids, l.shipping_doc_ids, l.totals, l.certification_status, l.signed_at, l.signature_key, l.signed_device_id, l.created_at, l.updated_at, l.signed_ip, l.signed_by, u.first_name, u.last_name
FROM daily_logs l
JOIN drivers d ON d.id = l.driver_id
JOIN users   u ON u.id = d.user_id
WHERE l.company_id = $1
  AND l.certification_status <> 'certified'
  AND l.log_date < $2
  AND ($3::uuid IS NULL OR l.driver_id = $3::uuid)
  AND ($4::uuid IS NULL OR d.branch_id = $4::uuid)
ORDER BY l.log_date DESC, u.last_name
LIMIT $6 OFFSET $5
`

type LogsListUncertifiedOlderThanParams struct {
	CompanyID  uuid.UUID
	BeforeDate pgtype.Date
	DriverID   pgtype.UUID
	BranchID   pgtype.UUID
	Off        int32
	Lim        int32
}

type LogsListUncertifiedOlderThanRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	Timezone            string
	UnitIds             []uuid.UUID
	CoDriverID          pgtype.UUID
	DistanceM           int64
	TrailerIds          []uuid.UUID
	ShippingDocIds      []uuid.UUID
	Totals              []byte
	CertificationStatus string
	SignedAt            pgtype.Timestamptz
	SignatureKey        *string
	SignedDeviceID      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SignedIp            *string
	SignedBy            pgtype.UUID
	FirstName           string
	LastName            string
}

// Q19.1: 8 kundan eskirgan sertifikatlanmagan kunlar — admin alerti.
func (q *Queries) LogsListUncertifiedOlderThan(ctx context.Context, arg LogsListUncertifiedOlderThanParams) ([]LogsListUncertifiedOlderThanRow, error) {
	rows, err := q.db.Query(ctx, logsListUncertifiedOlderThan,
		arg.CompanyID,
		arg.BeforeDate,
		arg.DriverID,
		arg.BranchID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListUncertifiedOlderThanRow{}
	for rows.Next() {
		var i LogsListUncertifiedOlderThanRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.LogDate,
			&i.Timezone,
			&i.UnitIds,
			&i.CoDriverID,
			&i.DistanceM,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.Totals,
			&i.CertificationStatus,
			&i.SignedAt,
			&i.SignatureKey,
			&i.SignedDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SignedIp,
			&i.SignedBy,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListUnitNumbersByIDs = `-- name: LogsListUnitNumbersByIDs :many
SELECT id, unit_number, vin, license_plate FROM units
WHERE company_id = $1 AND id = ANY($2::uuid[])
`

type LogsListUnitNumbersByIDsParams struct {
	CompanyID uuid.UUID
	Ids       []uuid.UUID
}

type LogsListUnitNumbersByIDsRow struct {
	ID           uuid.UUID
	UnitNumber   string
	Vin          *string
	LicensePlate *string
}

func (q *Queries) LogsListUnitNumbersByIDs(ctx context.Context, arg LogsListUnitNumbersByIDsParams) ([]LogsListUnitNumbersByIDsRow, error) {
	rows, err := q.db.Query(ctx, logsListUnitNumbersByIDs, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListUnitNumbersByIDsRow{}
	for rows.Next() {
		var i LogsListUnitNumbersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitNumber,
			&i.Vin,
			&i.LicensePlate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsListViolations = `-- name: LogsListViolations :many
SELECT v.id, v.company_id, v.driver_id, v.unit_id, v.daily_log_id, v.type, v.severity, v.occurred_at, v.details, v.policy_version_id, v.resolved_at, v.resolved_reason, v.created_at, v.updated_at, v.unidentified_event_id, v.resolved_by, u.first_name, u.last_name, l.log_date
FROM violations v
LEFT JOIN drivers d ON d.id = v.driver_id
LEFT JOIN users   u ON u.id = d.user_id
LEFT JOIN daily_logs l ON l.id = v.daily_log_id
WHERE v.company_id = $1
  AND ($2::uuid IS NULL OR v.driver_id = $2::uuid)
  AND ($3::uuid IS NULL OR d.branch_id = $3::uuid)
  AND ($4::text IS NULL OR v.type = $4::text)
  AND ($5::text IS NULL OR v.severity = $5::text)
  AND ($6::bool IS NULL
       OR ($6::bool AND v.resolved_at IS NOT NULL)
       OR (NOT $6::bool AND v.resolved_at IS NULL))
  AND ($7::timestamptz IS NULL OR v.occurred_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR v.occurred_at < $8::timestamptz)
ORDER BY v.occurred_at DESC
LIMIT $10 OFFSET $9
`

type LogsListViolationsParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	BranchID  pgtype.UUID
	Type      *string
	Severity  *string
	Resolved  *bool
	FromAt    pgtype.Timestamptz
	ToAt      pgtype.Timestamptz
	Off       int32
	Lim       int32
}

type LogsListViolationsRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            pgtype.UUID
	UnitID              pgtype.UUID
	DailyLogID          pgtype.UUID
	Type                string
	Severity            string
	OccurredAt          time.Time
	Details             []byte
	PolicyVersionID     pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	ResolvedReason      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	UnidentifiedEventID pgtype.UUID
	ResolvedBy          pgtype.UUID
	FirstName           *string
	LastName            *string
	LogDate             pgtype.Date
}

func (q *Queries) LogsListViolations(ctx context.Context, arg LogsListViolationsParams) ([]LogsListViolationsRow, error) {
	rows, err := q.db.Query(ctx, logsListViolations,
		arg.CompanyID,
		arg.DriverID,
		arg.BranchID,
		arg.Type,
		arg.Severity,
		arg.Resolved,
		arg.FromAt,
		arg.ToAt,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogsListViolationsRow{}
	for rows.Next() {
		var i LogsListViolationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.DailyLogID,
			&i.Type,
			&i.Severity,
			&i.OccurredAt,
			&i.Details,
			&i.PolicyVersionID,
			&i.ResolvedAt,
			&i.ResolvedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnidentifiedEventID,
			&i.ResolvedBy,
			&i.FirstName,
			&i.LastName,
			&i.LogDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logsLockDayEvents = `-- name: LogsLockDayEvents :exec
UPDATE duty_status_events SET locked = $1
WHERE company_id = $2 AND daily_log_id = $3
`

type LogsLockDayEventsParams struct {
	Locked     bool
	CompanyID  uuid.UUID
	DailyLogID pgtype.UUID
}

// Q26.1: sertifikatlangan kun eventlari `locked` — faqat edit-request orqali.
func (q *Queries) LogsLockDayEvents(ctx context.Context, arg LogsLockDayEventsParams) error {
	_, err := q.db.Exec(ctx, logsLockDayEvents, arg.Locked, arg.CompanyID, arg.DailyLogID)
	return err
}

const logsMarkNeedsRecertify = `-- name: LogsMarkNeedsRecertify :exec
UPDATE daily_logs SET certification_status = 'needs_recertify'
WHERE company_id = $1 AND id = $2 AND certification_status = 'certified'
`

type LogsMarkNeedsRecertifyParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

// Q18: sertifikatlangan kun tahrirlansa qayta imzo talab qilinadi.
func (q *Queries) LogsMarkNeedsRecertify(ctx context.Context, arg LogsMarkNeedsRecertifyParams) error {
	_, err := q.db.Exec(ctx, logsMarkNeedsRecertify, arg.CompanyID, arg.ID)
	return err
}

const logsProposeUnidentifiedEvent = `-- name: LogsProposeUnidentifiedEvent :one
UPDATE unidentified_events
SET status = 'proposed', assigned_driver_id = $1,
    edit_request_id = $2, resolved_by = $3
WHERE company_id = $4 AND id = $5 AND status = 'pending'
RETURNING id, company_id, unit_id, eld_device_id, start_at, end_at, distance_m, track_key, status, assigned_driver_id, annotation, resolved_by, resolved_at, created_at, updated_at, edit_request_id
`

type LogsProposeUnidentifiedEventParams struct {
	AssignedDriverID pgtype.UUID
	EditRequestID    pgtype.UUID
	ResolvedBy       pgtype.UUID
	CompanyID        uuid.UUID
	ID               uuid.UUID
}

// §10.4: admin tayinlashi taklif — haydovchi tasdig'igacha `proposed`.
func (q *Queries) LogsProposeUnidentifiedEvent(ctx context.Context, arg LogsProposeUnidentifiedEventParams) (UnidentifiedEvent, error) {
	row := q.db.QueryRow(ctx, logsProposeUnidentifiedEvent,
		arg.AssignedDriverID,
		arg.EditRequestID,
		arg.ResolvedBy,
		arg.CompanyID,
		arg.ID,
	)
	var i UnidentifiedEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.StartAt,
		&i.EndAt,
		&i.DistanceM,
		&i.TrackKey,
		&i.Status,
		&i.AssignedDriverID,
		&i.Annotation,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditRequestID,
	)
	return i, err
}

const logsResetUnidentifiedEvent = `-- name: LogsResetUnidentifiedEvent :exec
UPDATE unidentified_events
SET status = 'pending', assigned_driver_id = NULL, edit_request_id = NULL, resolved_by = NULL
WHERE company_id = $1 AND id = $2 AND status = 'proposed'
`

type LogsResetUnidentifiedEventParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

// Taklif rad etilsa blok yana `pending` bo'ladi.
func (q *Queries) LogsResetUnidentifiedEvent(ctx context.Context, arg LogsResetUnidentifiedEventParams) error {
	_, err := q.db.Exec(ctx, logsResetUnidentifiedEvent, arg.CompanyID, arg.ID)
	return err
}

const logsResolveDayViolations = `-- name: LogsResolveDayViolations :exec
UPDATE violations
SET resolved_at = now(), resolved_reason = $1,
    resolved_by = $2::uuid
WHERE company_id = $3 AND daily_log_id = $4
  AND resolved_at IS NULL AND type = ANY($5::text[])
`

type LogsResolveDayViolationsParams struct {
	ResolvedReason *string
	ResolvedBy     pgtype.UUID
	CompanyID      uuid.UUID
	DailyLogID     pgtype.UUID
	Types          []string
}

// Yopilish qoidalari (Q58): sabab bilan yopiladi, qator saqlanadi.
func (q *Queries) LogsResolveDayViolations(ctx context.Context, arg LogsResolveDayViolationsParams) error {
	_, err := q.db.Exec(ctx, logsResolveDayViolations,
		arg.ResolvedReason,
		arg.ResolvedBy,
		arg.CompanyID,
		arg.DailyLogID,
		arg.Types,
	)
	return err
}

const logsResolveEditRequest = `-- name: LogsResolveEditRequest :one
UPDATE log_edit_requests
SET status = $1, resolved_by = $2, resolved_at = now(),
    driver_note = $3::text
WHERE company_id = $4 AND id = $5 AND status = 'pending'
RETURNING id, company_id, driver_id, daily_log_id, requested_by, status, changes, driver_note, resolved_by, resolved_at, created_at, updated_at, source, unidentified_event_id
`

type LogsResolveEditRequestParams struct {
	Status     string
	ResolvedBy pgtype.UUID
	DriverNote *string
	CompanyID  uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) LogsResolveEditRequest(ctx context.Context, arg LogsResolveEditRequestParams) (LogEditRequest, error) {
	row := q.db.QueryRow(ctx, logsResolveEditRequest,
		arg.Status,
		arg.ResolvedBy,
		arg.DriverNote,
		arg.CompanyID,
		arg.ID,
	)
	var i LogEditRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.DailyLogID,
		&i.RequestedBy,
		&i.Status,
		&i.Changes,
		&i.DriverNote,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.UnidentifiedEventID,
	)
	return i, err
}

const logsResolveUnidentifiedViolation = `-- name: LogsResolveUnidentifiedViolation :exec
UPDATE violations
SET resolved_at = now(), resolved_reason = $1,
    resolved_by = $2::uuid
WHERE company_id = $3 AND unidentified_event_id = $4
  AND resolved_at IS NULL
`

type LogsResolveUnidentifiedViolationParams struct {
	ResolvedReason      *string
	ResolvedBy          pgtype.UUID
	CompanyID           uuid.UUID
	UnidentifiedEventID pgtype.UUID
}

func (q *Queries) LogsResolveUnidentifiedViolation(ctx context.Context, arg LogsResolveUnidentifiedViolationParams) error {
	_, err := q.db.Exec(ctx, logsResolveUnidentifiedViolation,
		arg.ResolvedReason,
		arg.ResolvedBy,
		arg.CompanyID,
		arg.UnidentifiedEventID,
	)
	return err
}

const logsSetDailyLogForm = `-- name: LogsSetDailyLogForm :one
UPDATE daily_logs SET
  trailer_ids      = $1,
  shipping_doc_ids = $2,
  co_driver_id     = $3::uuid
WHERE company_id = $4 AND id = $5
RETURNING id, company_id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m, trailer_ids, shipping_doc_ids, totals, certification_status, signed_at, signature_key, signed_device_id, created_at, updated_at, signed_ip, signed_by
`

type LogsSetDailyLogFormParams struct {
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	CoDriverID     pgtype.UUID
	CompanyID      uuid.UUID
	ID             uuid.UUID
}

// Q16: Log Form maydonlari (distance telemetriyadan keladi, qo'lda emas).
func (q *Queries) LogsSetDailyLogForm(ctx context.Context, arg LogsSetDailyLogFormParams) (DailyLog, error) {
	row := q.db.QueryRow(ctx, logsSetDailyLogForm,
		arg.TrailerIds,
		arg.ShippingDocIds,
		arg.CoDriverID,
		arg.CompanyID,
		arg.ID,
	)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.LogDate,
		&i.Timezone,
		&i.UnitIds,
		&i.CoDriverID,
		&i.DistanceM,
		&i.TrailerIds,
		&i.ShippingDocIds,
		&i.Totals,
		&i.CertificationStatus,
		&i.SignedAt,
		&i.SignatureKey,
		&i.SignedDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignedIp,
		&i.SignedBy,
	)
	return i, err
}

const logsSupersedeEvents = `-- name: LogsSupersedeEvents :exec
UPDATE duty_status_events SET superseded_by = $1
WHERE company_id = $2 AND id = ANY($3::uuid[]) AND superseded_by IS NULL
`

type LogsSupersedeEventsParams struct {
	SupersededBy pgtype.UUID
	CompanyID    uuid.UUID
	Ids          []uuid.UUID
}

func (q *Queries) LogsSupersedeEvents(ctx context.Context, arg LogsSupersedeEventsParams) error {
	_, err := q.db.Exec(ctx, logsSupersedeEvents, arg.SupersededBy, arg.CompanyID, arg.Ids)
	return err
}

const logsUpsertDayViolation = `-- name: LogsUpsertDayViolation :one

INSERT INTO violations (
  company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id
) VALUES (
  $1, $2, $3::uuid, $4, $5, $6,
  $7, $8, $9::uuid
)
ON CONFLICT (daily_log_id, type) WHERE daily_log_id IS NOT NULL AND resolved_at IS NULL
DO UPDATE SET severity = EXCLUDED.severity, occurred_at = EXCLUDED.occurred_at,
              details = EXCLUDED.details, policy_version_id = EXCLUDED.policy_version_id
RETURNING id, company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id, resolved_at, resolved_reason, created_at, updated_at, unidentified_event_id, resolved_by
`

type LogsUpsertDayViolationParams struct {
	CompanyID       uuid.UUID
	DriverID        pgtype.UUID
	UnitID          pgtype.UUID
	DailyLogID      pgtype.UUID
	Type            string
	Severity        string
	OccurredAt      time.Time
	Details         []byte
	PolicyVersionID pgtype.UUID
}

// ------------------------------------------------------------ violations
// Q58: violation o'chmaydi. Bir kun + bir tur uchun bitta ochiq qator; qayta
// hisobda severity/vaqt yangilanadi, yopilganlari tarixda qoladi.
func (q *Queries) LogsUpsertDayViolation(ctx context.Context, arg LogsUpsertDayViolationParams) (Violation, error) {
	row := q.db.QueryRow(ctx, logsUpsertDayViolation,
		arg.CompanyID,
		arg.DriverID,
		arg.UnitID,
		arg.DailyLogID,
		arg.Type,
		arg.Severity,
		arg.OccurredAt,
		arg.Details,
		arg.PolicyVersionID,
	)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.DailyLogID,
		&i.Type,
		&i.Severity,
		&i.OccurredAt,
		&i.Details,
		&i.PolicyVersionID,
		&i.ResolvedAt,
		&i.ResolvedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnidentifiedEventID,
		&i.ResolvedBy,
	)
	return i, err
}

const logsUpsertUnidentifiedViolation = `-- name: LogsUpsertUnidentifiedViolation :one
INSERT INTO violations (
  company_id, driver_id, unit_id, unidentified_event_id, type, severity, occurred_at, details
) VALUES (
  $1, $2::uuid, $3::uuid, $4,
  'unidentified_driving', 'violation', $5, $6
)
ON CONFLICT (unidentified_event_id) WHERE unidentified_event_id IS NOT NULL AND resolved_at IS NULL
DO UPDATE SET occurred_at = EXCLUDED.occurred_at, details = EXCLUDED.details
RETURNING id, company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id, resolved_at, resolved_reason, created_at, updated_at, unidentified_event_id, resolved_by
`

type LogsUpsertUnidentifiedViolationParams struct {
	CompanyID           uuid.UUID
	DriverID            pgtype.UUID
	UnitID              pgtype.UUID
	UnidentifiedEventID pgtype.UUID
	OccurredAt          time.Time
	Details             []byte
}

func (q *Queries) LogsUpsertUnidentifiedViolation(ctx context.Context, arg LogsUpsertUnidentifiedViolationParams) (Violation, error) {
	row := q.db.QueryRow(ctx, logsUpsertUnidentifiedViolation,
		arg.CompanyID,
		arg.DriverID,
		arg.UnitID,
		arg.UnidentifiedEventID,
		arg.OccurredAt,
		arg.Details,
	)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.DailyLogID,
		&i.Type,
		&i.Severity,
		&i.OccurredAt,
		&i.Details,
		&i.PolicyVersionID,
		&i.ResolvedAt,
		&i.ResolvedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnidentifiedEventID,
		&i.ResolvedBy,
	)
	return i, err
}
