// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        uuid.UUID
	CompanyID pgtype.UUID
	TableName string
	RecordID  pgtype.UUID
	Field     *string
	OldValue  []byte
	NewValue  []byte
	Action    string
	EditedBy  pgtype.UUID
	Ip        *netip.Addr
	UserAgent *string
	Ts        time.Time
	Reason    *string
}

type Branch struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	Name      string
	Address   *string
	Timezone  *string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type ChatMessage struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	DriverID    uuid.UUID
	SenderID    uuid.UUID
	Kind        string
	Text        *string
	FileKey     *string
	Lat         *float64
	Lng         *float64
	SentAt      time.Time
	DeliveredAt pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Company struct {
	ID                  uuid.UUID
	Name                string
	Address             *string
	HomeTerminalAddress *string
	Timezone            string
	Email               *string
	Phone               *string
	RegistrationNo      *string
	LogoKey             *string
	Region              *string
	UnitSystem          string
	RegulationProfile   string
	SubscriptionStatus  string
	SubscriptionEndAt   pgtype.Timestamptz
	Plan                *string
	Settings            []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           pgtype.Timestamptz
}

type DailyLog struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	Timezone            string
	UnitIds             []uuid.UUID
	CoDriverID          pgtype.UUID
	DistanceM           int64
	TrailerIds          []uuid.UUID
	ShippingDocIds      []uuid.UUID
	Totals              []byte
	CertificationStatus string
	SignedAt            pgtype.Timestamptz
	SignatureKey        *string
	SignedDeviceID      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SignedIp            *string
	SignedBy            pgtype.UUID
}

type DefectType struct {
	ID         uuid.UUID
	CompanyID  pgtype.UUID
	Name       string
	Category   string
	IsCritical bool
	IsActive   bool
	SortOrder  int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
}

type DevicePushToken struct {
	ID         uuid.UUID
	CompanyID  uuid.UUID
	UserID     uuid.UUID
	DeviceID   string
	Platform   string
	Token      string
	AppVersion *string
	LastSeenAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
}

type Driver struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	UserID         uuid.UUID
	BranchID       pgtype.UUID
	LicenseNoEnc   *string
	LicenseRegion  *string
	HomeTerminal   *string
	City           *string
	State          *string
	Zip            *string
	Address1       *string
	Address2       *string
	Notes          *string
	FleetManagerID pgtype.UUID
	DefaultUnitID  pgtype.UUID
	Status         string
	AppVersion     *string
	ActivatedOn    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}

type DriverPair struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	DriverAID uuid.UUID
	DriverBID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type DutyStatusEvent struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	DriverID       pgtype.UUID
	UnitID         pgtype.UUID
	EldDeviceID    pgtype.UUID
	EventType      string
	Status         *string
	Special        string
	EventTime      time.Time
	TimeSource     string
	TimeUnverified bool
	ClockSkewSec   int32
	Origin         string
	Lat            *float64
	Lng            *float64
	LocationText   *string
	GpsAccuracyM   *int32
	OdometerM      *int64
	EngineHours    pgtype.Numeric
	Notes          *string
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	ClientEventID  uuid.UUID
	DeviceSeq      *int64
	ReceivedAt     time.Time
	SupersededBy   pgtype.UUID
	Locked         bool
	DailyLogID     pgtype.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type DvirReport struct {
	ID                        uuid.UUID
	CompanyID                 uuid.UUID
	UnitID                    uuid.UUID
	DriverID                  uuid.UUID
	Type                      string
	TrailerIds                []uuid.UUID
	Status                    string
	Defects                   []byte
	Lat                       *float64
	Lng                       *float64
	LocationText              *string
	OdometerM                 *int64
	EngineHours               pgtype.Numeric
	DriverSignatureKey        *string
	MechanicID                pgtype.UUID
	MechanicNote              *string
	MechanicSignatureKey      *string
	RepairedAt                pgtype.Timestamptz
	CertifiedByDriverID       pgtype.UUID
	CertifiedAt               pgtype.Timestamptz
	Source                    string
	PerformedAt               time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	CertificationSignatureKey *string
	ClosedAt                  pgtype.Timestamptz
	ClosedReason              *string
}

type EldDevice struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	UnitID           pgtype.UUID
	Vendor           string
	Model            *string
	Serial           string
	Firmware         *string
	ConnectionType   *string
	SimPresent       bool
	LastSeenAt       pgtype.Timestamptz
	MalfunctionCodes []string
	Status           string
	Notes            *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
}

type EldDeviceAssignment struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	EldDeviceID uuid.UUID
	UnitID      uuid.UUID
	FromAt      time.Time
	ToAt        pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Feedback struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	DriverID    pgtype.UUID
	AppRating   *int16
	Text        *string
	SubmittedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type HosPolicyVersion struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	EffectiveFrom time.Time
	Policy        []byte
	CreatedBy     pgtype.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type Invitation struct {
	ID        uuid.UUID
	CompanyID pgtype.UUID
	UserID    uuid.UUID
	TokenHash string
	Channel   string
	Purpose   string
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LogEditRequest struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            uuid.UUID
	DailyLogID          uuid.UUID
	RequestedBy         uuid.UUID
	Status              string
	Changes             []byte
	DriverNote          *string
	ResolvedBy          pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Source              string
	UnidentifiedEventID pgtype.UUID
}

type MaintenanceRecord struct {
	ID              uuid.UUID
	CompanyID       uuid.UUID
	ScheduleUnitID  pgtype.UUID
	UnitID          uuid.UUID
	Status          string
	PerformedAt     time.Time
	InvoiceNo       *string
	Vendor          *string
	Cost            pgtype.Numeric
	Currency        string
	OdometerM       *int64
	EngineHours     pgtype.Numeric
	InvoiceKey      *string
	DvirPreID       pgtype.UUID
	DvirPostID      pgtype.UUID
	CancelledReason *string
	Notes           *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MaintenanceSchedule struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	Name                string
	Type                *string
	IntervalValue       pgtype.Numeric
	IntervalUnit        string
	ReminderBeforeValue pgtype.Numeric
	AlertType           string
	DeliveryMethods     []string
	NotifyCoDriver      bool
	Notes               *string
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           pgtype.Timestamptz
}

type MaintenanceScheduleUnit struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	ScheduleID       uuid.UUID
	UnitID           uuid.UUID
	LastServiceValue pgtype.Numeric
	NextDueValue     pgtype.Numeric
	NextDueAt        pgtype.Timestamptz
	ReminderSentAt   pgtype.Timestamptz
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
	LastServiceAt    pgtype.Timestamptz
	CancelledReason  *string
}

type Notification struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	UserID      uuid.UUID
	AlertType   string
	Title       string
	Body        *string
	EntityType  *string
	EntityID    pgtype.UUID
	Channels    []string
	SentAt      pgtype.Timestamptz
	DeliveredAt pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type NotificationSetting struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	AlertType      string
	Channels       []string
	RecipientRoles []uuid.UUID
	Enabled        bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Region struct {
	Code      string
	Name      string
	Country   string
	Geom      interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ReportExportJob struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	RequestedBy uuid.UUID
	Type        string
	Format      string
	Params      []byte
	Status      string
	Error       *string
	FileKey     *string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FileName    *string
	FileSizeB   *int64
	ContentType *string
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type Role struct {
	ID          uuid.UUID
	CompanyID   pgtype.UUID
	Name        string
	Description *string
	Scope       string
	IsSystem    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type RolePermission struct {
	RoleID        uuid.UUID
	PermissionKey string
	CreatedAt     time.Time
}

type Route struct {
	ID                 uuid.UUID
	CompanyID          uuid.UUID
	UnitID             uuid.UUID
	DriverID           uuid.UUID
	Sequence           int32
	OriginText         *string
	OriginLat          *float64
	OriginLng          *float64
	DestText           *string
	DestLat            *float64
	DestLng            *float64
	GeofenceM          int32
	Status             string
	CreatedBy          pgtype.UUID
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	NotCompletedReason *string
	Note               *string
	PolylineKey        *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          pgtype.Timestamptz
	NotCompletedNote   *string
	NotCompletedBy     pgtype.UUID
	GeofenceEnteredAt  pgtype.Timestamptz
}

type Session struct {
	ID                   uuid.UUID
	CompanyID            pgtype.UUID
	UserID               uuid.UUID
	DeviceID             *string
	DeviceType           string
	RefreshTokenHash     string
	Status               string
	RevokedReason        *string
	ExpiresAt            time.Time
	LastSeenAt           pgtype.Timestamptz
	AppVersion           *string
	Ip                   *netip.Addr
	UserAgent            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PrevRefreshTokenHash *string
}

type ShippingDocument struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	Number    string
	Notes     *string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type Signature struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	UserID      uuid.UUID
	ImageKeyEnc string
	IsDefault   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type SupportTicket struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	DriverID    pgtype.UUID
	CreatedBy   pgtype.UUID
	Subject     string
	Description *string
	ContactOn   *string
	Status      string
	Attachments []string
	ResolvedAt  pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type SystemSetting struct {
	Key         string
	Value       []byte
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Telemetry struct {
	Ts              time.Time
	CompanyID       uuid.UUID
	UnitID          uuid.UUID
	EldDeviceID     pgtype.UUID
	DriverID        pgtype.UUID
	Lat             *float64
	Lng             *float64
	SpeedKmh        *float64
	Heading         *float64
	OdometerM       *int64
	EngineHours     pgtype.Numeric
	FuelPct         *float64
	CoolantTempC    *float64
	CoolantLevelPct *float64
	OilLevelPct     *float64
	BatteryPct      *float64
	Ignition        *bool
	Source          string
	CreatedAt       time.Time
	BatteryVoltageV *float64
}

type Telemetry1min struct {
	Bucket         time.Time
	CompanyID      uuid.UUID
	UnitID         uuid.UUID
	AvgSpeedKmh    *float64
	MaxSpeedKmh    *float64
	LastLat        *float64
	LastLng        *float64
	LastHeading    *float64
	MaxOdometerM   *int64
	MaxEngineHours pgtype.Numeric
	LastFuelPct    *float64
	SampleCount    int64
}

type Telemetry5min struct {
	Bucket         time.Time
	CompanyID      uuid.UUID
	UnitID         uuid.UUID
	AvgSpeedKmh    *float64
	MaxSpeedKmh    *float64
	LastLat        *float64
	LastLng        *float64
	LastHeading    *float64
	MaxOdometerM   *int64
	MaxEngineHours pgtype.Numeric
	LastFuelPct    *float64
	SampleCount    int64
}

type TicketMessage struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	TicketID    uuid.UUID
	SenderID    uuid.UUID
	Text        string
	Attachments []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Trailer struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	Number    string
	Notes     *string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type Trip struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	UnitID      uuid.UUID
	DriverID    pgtype.UUID
	StartAt     time.Time
	EndAt       pgtype.Timestamptz
	StartLat    *float64
	StartLng    *float64
	EndLat      *float64
	EndLng      *float64
	DistanceM   int64
	DurationSec *int32
	MaxSpeedKmh *float64
	PolylineKey *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UnidentifiedEvent struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	UnitID           uuid.UUID
	EldDeviceID      pgtype.UUID
	StartAt          time.Time
	EndAt            pgtype.Timestamptz
	DistanceM        int64
	TrackKey         *string
	Status           string
	AssignedDriverID pgtype.UUID
	Annotation       *string
	ResolvedBy       pgtype.UUID
	ResolvedAt       pgtype.Timestamptz
	CreatedAt        time.Time
	UpdatedAt        time.Time
	EditRequestID    pgtype.UUID
}

type Unit struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	BranchID     pgtype.UUID
	UnitNumber   string
	Make         *string
	Model        *string
	Year         *int32
	Vin          *string
	LicensePlate *string
	PlateRegion  *string
	FuelType     *string
	SleeperBerth bool
	GvwrClass    *string
	Status       string
	OutOfService bool
	Notes        *string
	ActivatedOn  pgtype.Timestamptz
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
}

type UnitDriverAssignment struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	UnitID       uuid.UUID
	DriverID     uuid.UUID
	Role         string
	AssignedAt   time.Time
	UnassignedAt pgtype.Timestamptz
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UnitLastState struct {
	UnitID       uuid.UUID
	CompanyID    uuid.UUID
	Ts           pgtype.Timestamptz
	Lat          *float64
	Lng          *float64
	SpeedKmh     *float64
	Heading      *float64
	OdometerM    *int64
	EngineHours  pgtype.Numeric
	DutyStatus   *string
	DriverID     pgtype.UUID
	OnlineStatus string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UnitRegionDistanceDaily struct {
	UnitID     uuid.UUID
	RegionCode string
	Date       pgtype.Date
	CompanyID  uuid.UUID
	DistanceM  int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID             uuid.UUID
	CompanyID      pgtype.UUID
	BranchID       pgtype.UUID
	FirstName      string
	LastName       string
	Email          *string
	Phone          *string
	Username       string
	PasswordHash   *string
	RoleID         uuid.UUID
	Status         string
	TotpSecretEnc  *string
	TotpEnabled    bool
	RecoveryCodes  []string
	PinHash        *string
	InvitedAt      pgtype.Timestamptz
	ActivatedAt    pgtype.Timestamptz
	LastLoginAt    pgtype.Timestamptz
	FailedLogins   int32
	LockedUntil    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
	TelegramChatID *string
}

type Violation struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            pgtype.UUID
	UnitID              pgtype.UUID
	DailyLogID          pgtype.UUID
	Type                string
	Severity            string
	OccurredAt          time.Time
	Details             []byte
	PolicyVersionID     pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	ResolvedReason      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	UnidentifiedEventID pgtype.UUID
	ResolvedBy          pgtype.UUID
}
