// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT count(*) FROM notifications
WHERE company_id = $1
  AND user_id = $2
  AND ($3::bool IS NULL
       OR ($3::bool IS TRUE  AND read_at IS NULL)
       OR ($3::bool IS FALSE AND read_at IS NOT NULL))
  AND ($4::text IS NULL OR alert_type = $4::text)
`

type CountNotificationsParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
	Unread    *bool
	AlertType *string
}

func (q *Queries) CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications,
		arg.CompanyID,
		arg.UserID,
		arg.Unread,
		arg.AlertType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE company_id = $1 AND user_id = $2 AND read_at IS NULL
`

type CountUnreadNotificationsParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.CompanyID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (company_id, user_id, alert_type, title, body, entity_type, entity_id, channels, sent_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, company_id, user_id, alert_type, title, body, entity_type, entity_id, channels, sent_at, delivered_at, read_at, created_at, updated_at
`

type CreateNotificationParams struct {
	CompanyID  uuid.UUID
	UserID     uuid.UUID
	AlertType  string
	Title      string
	Body       *string
	EntityType *string
	EntityID   pgtype.UUID
	Channels   []string
	SentAt     pgtype.Timestamptz
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.CompanyID,
		arg.UserID,
		arg.AlertType,
		arg.Title,
		arg.Body,
		arg.EntityType,
		arg.EntityID,
		arg.Channels,
		arg.SentAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AlertType,
		&i.Title,
		&i.Body,
		&i.EntityType,
		&i.EntityID,
		&i.Channels,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDevicePushToken = `-- name: DeleteDevicePushToken :execrows
UPDATE device_push_tokens SET deleted_at = now()
WHERE company_id = $1 AND user_id = $2 AND device_id = $3 AND deleted_at IS NULL
`

type DeleteDevicePushTokenParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
	DeviceID  string
}

func (q *Queries) DeleteDevicePushToken(ctx context.Context, arg DeleteDevicePushTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevicePushToken, arg.CompanyID, arg.UserID, arg.DeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :execrows
DELETE FROM notifications
WHERE company_id = $1 AND created_at < $2 AND read_at IS NOT NULL
`

type DeleteOldNotificationsParams struct {
	CompanyID uuid.UUID
	CreatedAt time.Time
}

// Retention: 90 kundan eski o'qilgan bildirishnomalar tozalanadi.
func (q *Queries) DeleteOldNotifications(ctx context.Context, arg DeleteOldNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldNotifications, arg.CompanyID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotification = `-- name: GetNotification :one
SELECT id, company_id, user_id, alert_type, title, body, entity_type, entity_id, channels, sent_at, delivered_at, read_at, created_at, updated_at FROM notifications WHERE company_id = $1 AND id = $2
`

type GetNotificationParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.CompanyID, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AlertType,
		&i.Title,
		&i.Body,
		&i.EntityType,
		&i.EntityID,
		&i.Channels,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationSetting = `-- name: GetNotificationSetting :one
SELECT id, company_id, alert_type, channels, recipient_roles, enabled, created_at, updated_at FROM notification_settings WHERE company_id = $1 AND alert_type = $2
`

type GetNotificationSettingParams struct {
	CompanyID uuid.UUID
	AlertType string
}

func (q *Queries) GetNotificationSetting(ctx context.Context, arg GetNotificationSettingParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSetting, arg.CompanyID, arg.AlertType)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AlertType,
		&i.Channels,
		&i.RecipientRoles,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationSettings = `-- name: ListNotificationSettings :many
SELECT id, company_id, alert_type, channels, recipient_roles, enabled, created_at, updated_at FROM notification_settings WHERE company_id = $1 ORDER BY alert_type
`

func (q *Queries) ListNotificationSettings(ctx context.Context, companyID uuid.UUID) ([]NotificationSetting, error) {
	rows, err := q.db.Query(ctx, listNotificationSettings, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationSetting{}
	for rows.Next() {
		var i NotificationSetting
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.AlertType,
			&i.Channels,
			&i.RecipientRoles,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, company_id, user_id, alert_type, title, body, entity_type, entity_id, channels, sent_at, delivered_at, read_at, created_at, updated_at FROM notifications
WHERE company_id = $1
  AND user_id = $2
  AND ($3::bool IS NULL
       OR ($3::bool IS TRUE  AND read_at IS NULL)
       OR ($3::bool IS FALSE AND read_at IS NOT NULL))
  AND ($4::text IS NULL OR alert_type = $4::text)
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListNotificationsParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
	Unread    *bool
	AlertType *string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.CompanyID,
		arg.UserID,
		arg.Unread,
		arg.AlertType,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AlertType,
			&i.Title,
			&i.Body,
			&i.EntityType,
			&i.EntityID,
			&i.Channels,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushTokensForUsers = `-- name: ListPushTokensForUsers :many
SELECT user_id, device_id, platform, token FROM device_push_tokens
WHERE company_id = $1 AND user_id = ANY($2::uuid[]) AND deleted_at IS NULL
ORDER BY user_id, last_seen_at DESC
`

type ListPushTokensForUsersParams struct {
	CompanyID uuid.UUID
	Column2   []uuid.UUID
}

type ListPushTokensForUsersRow struct {
	UserID   uuid.UUID
	DeviceID string
	Platform string
	Token    string
}

func (q *Queries) ListPushTokensForUsers(ctx context.Context, arg ListPushTokensForUsersParams) ([]ListPushTokensForUsersRow, error) {
	rows, err := q.db.Query(ctx, listPushTokensForUsers, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPushTokensForUsersRow{}
	for rows.Next() {
		var i ListPushTokensForUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.DeviceID,
			&i.Platform,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at = now() WHERE company_id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, arg.CompanyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :exec
UPDATE notifications SET delivered_at = now() WHERE company_id = $1 AND id = $2 AND delivered_at IS NULL
`

type MarkNotificationDeliveredParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkNotificationDelivered(ctx context.Context, arg MarkNotificationDeliveredParams) error {
	_, err := q.db.Exec(ctx, markNotificationDelivered, arg.CompanyID, arg.ID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = now()
WHERE company_id = $1 AND user_id = $2 AND id = $3 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.CompanyID, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notifyRecipientsByRoles = `-- name: NotifyRecipientsByRoles :many
SELECT u.id, u.email, u.phone, u.telegram_chat_id
FROM users u
WHERE u.company_id = $1 AND u.deleted_at IS NULL AND u.status = 'active'
  AND u.role_id = ANY($2::uuid[])
`

type NotifyRecipientsByRolesParams struct {
	CompanyID pgtype.UUID
	Column2   []uuid.UUID
}

type NotifyRecipientsByRolesRow struct {
	ID             uuid.UUID
	Email          *string
	Phone          *string
	TelegramChatID *string
}

func (q *Queries) NotifyRecipientsByRoles(ctx context.Context, arg NotifyRecipientsByRolesParams) ([]NotifyRecipientsByRolesRow, error) {
	rows, err := q.db.Query(ctx, notifyRecipientsByRoles, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifyRecipientsByRolesRow{}
	for rows.Next() {
		var i NotifyRecipientsByRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.TelegramChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyRecipientsByUsers = `-- name: NotifyRecipientsByUsers :many
SELECT u.id, u.email, u.phone, u.telegram_chat_id
FROM users u
WHERE u.company_id = $1 AND u.deleted_at IS NULL AND u.status = 'active'
  AND u.id = ANY($2::uuid[])
`

type NotifyRecipientsByUsersParams struct {
	CompanyID pgtype.UUID
	Column2   []uuid.UUID
}

type NotifyRecipientsByUsersRow struct {
	ID             uuid.UUID
	Email          *string
	Phone          *string
	TelegramChatID *string
}

// Qabul qiluvchilar: faqat faol foydalanuvchilar. Telefon/email — PII, javobga
// chiqmaydi, faqat `internal/notify` provayderlariga uzatiladi.
func (q *Queries) NotifyRecipientsByUsers(ctx context.Context, arg NotifyRecipientsByUsersParams) ([]NotifyRecipientsByUsersRow, error) {
	rows, err := q.db.Query(ctx, notifyRecipientsByUsers, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifyRecipientsByUsersRow{}
	for rows.Next() {
		var i NotifyRecipientsByUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.TelegramChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevicePushTokenElsewhere = `-- name: RevokeDevicePushTokenElsewhere :exec
UPDATE device_push_tokens SET deleted_at = now()
WHERE token = $1 AND deleted_at IS NULL AND NOT (user_id = $2 AND device_id = $3)
`

type RevokeDevicePushTokenElsewhereParams struct {
	Token    string
	UserID   uuid.UUID
	DeviceID string
}

// Bir xil token boshqa foydalanuvchida qolib ketmasin (qurilma egasi o'zgardi).
func (q *Queries) RevokeDevicePushTokenElsewhere(ctx context.Context, arg RevokeDevicePushTokenElsewhereParams) error {
	_, err := q.db.Exec(ctx, revokeDevicePushTokenElsewhere, arg.Token, arg.UserID, arg.DeviceID)
	return err
}

const upsertDevicePushToken = `-- name: UpsertDevicePushToken :one
INSERT INTO device_push_tokens (company_id, user_id, device_id, platform, token, app_version, last_seen_at)
VALUES ($1,$2,$3,$4,$5,$6, now())
ON CONFLICT (user_id, device_id) WHERE deleted_at IS NULL DO UPDATE SET
  platform     = EXCLUDED.platform,
  token        = EXCLUDED.token,
  app_version  = EXCLUDED.app_version,
  last_seen_at = now()
RETURNING id, company_id, user_id, device_id, platform, token, app_version, last_seen_at, created_at, updated_at, deleted_at
`

type UpsertDevicePushTokenParams struct {
	CompanyID  uuid.UUID
	UserID     uuid.UUID
	DeviceID   string
	Platform   string
	Token      string
	AppVersion *string
}

func (q *Queries) UpsertDevicePushToken(ctx context.Context, arg UpsertDevicePushTokenParams) (DevicePushToken, error) {
	row := q.db.QueryRow(ctx, upsertDevicePushToken,
		arg.CompanyID,
		arg.UserID,
		arg.DeviceID,
		arg.Platform,
		arg.Token,
		arg.AppVersion,
	)
	var i DevicePushToken
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.Token,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertNotificationSetting = `-- name: UpsertNotificationSetting :one
INSERT INTO notification_settings (company_id, alert_type, channels, recipient_roles, enabled)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (company_id, alert_type) DO UPDATE SET
  channels        = EXCLUDED.channels,
  recipient_roles = EXCLUDED.recipient_roles,
  enabled         = EXCLUDED.enabled
RETURNING id, company_id, alert_type, channels, recipient_roles, enabled, created_at, updated_at
`

type UpsertNotificationSettingParams struct {
	CompanyID      uuid.UUID
	AlertType      string
	Channels       []string
	RecipientRoles []uuid.UUID
	Enabled        bool
}

func (q *Queries) UpsertNotificationSetting(ctx context.Context, arg UpsertNotificationSettingParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertNotificationSetting,
		arg.CompanyID,
		arg.AlertType,
		arg.Channels,
		arg.RecipientRoles,
		arg.Enabled,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AlertType,
		&i.Channels,
		&i.RecipientRoles,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
