// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const retentionDeleteNotifications = `-- name: RetentionDeleteNotifications :execrows

DELETE FROM notifications WHERE company_id = $1 AND created_at < $2
`

type RetentionDeleteNotificationsParams struct {
	CompanyID uuid.UUID
	CreatedAt time.Time
}

// Retention sweeps (TZ B§15, 00011_retention.sql). Timescale hypertable'lar
// o'z policy'si bilan tozalanadi; bu yerda faqat oddiy jadvallar.
// Har so'rov bitta tenant'ni tozalaydi: fan-out `internal/jobs/retention.go`.
func (q *Queries) RetentionDeleteNotifications(ctx context.Context, arg RetentionDeleteNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, retentionDeleteNotifications, arg.CompanyID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retentionDeleteSessions = `-- name: RetentionDeleteSessions :execrows
DELETE FROM sessions WHERE company_id = $1 AND expires_at < $2
`

type RetentionDeleteSessionsParams struct {
	CompanyID pgtype.UUID
	ExpiresAt time.Time
}

func (q *Queries) RetentionDeleteSessions(ctx context.Context, arg RetentionDeleteSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, retentionDeleteSessions, arg.CompanyID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retentionExpireReportExports = `-- name: RetentionExpireReportExports :many
WITH expired AS (
  SELECT j.id, j.file_key
  FROM report_export_jobs j
  WHERE j.company_id = $1 AND j.file_key IS NOT NULL
    AND COALESCE(j.expires_at, j.created_at + INTERVAL '24 hours') < $2
  FOR UPDATE
), cleared AS (
  UPDATE report_export_jobs j SET file_key = NULL
  FROM expired e WHERE j.id = e.id
  RETURNING j.id
)
SELECT e.id, e.file_key::text AS file_key FROM expired e
`

type RetentionExpireReportExportsParams struct {
	CompanyID uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

type RetentionExpireReportExportsRow struct {
	ID      uuid.UUID
	FileKey string
}

// Eksport fayllari 24 soatdan keyin o'chadi: `file_key` tozalanadi va obyekt
// kalitlari qaytariladi, job ularni obyekt-omboridan o'chiradi.
func (q *Queries) RetentionExpireReportExports(ctx context.Context, arg RetentionExpireReportExportsParams) ([]RetentionExpireReportExportsRow, error) {
	rows, err := q.db.Query(ctx, retentionExpireReportExports, arg.CompanyID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetentionExpireReportExportsRow{}
	for rows.Next() {
		var i RetentionExpireReportExportsRow
		if err := rows.Scan(&i.ID, &i.FileKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
