// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermissions = `-- name: AddRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_key)
SELECT $1, k FROM unnest($2::text[]) AS k
ON CONFLICT DO NOTHING
`

type AddRolePermissionsParams struct {
	RoleID  uuid.UUID
	Column2 []string
}

// AddRolePermissions — DeleteRolePermissions bilan bitta tranzaksiyada chaqiriladi
// (data-modifying CTE bir snapshot'da ishlagani uchun ular birlashtirilmaydi).
func (q *Queries) AddRolePermissions(ctx context.Context, arg AddRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, addRolePermissions, arg.RoleID, arg.Column2)
	return err
}

const countRoles = `-- name: CountRoles :one
SELECT count(*) FROM roles r
WHERE (r.company_id = $1::uuid OR r.company_id IS NULL)
  AND r.deleted_at IS NULL
  AND ($2::text IS NULL OR r.scope = $2::text)
  AND ($3::bool IS NULL OR r.is_system = $3::bool)
  AND ($4::text IS NULL OR r.name ILIKE '%' || $4::text || '%')
`

type CountRolesParams struct {
	CompanyID uuid.UUID
	Scope     *string
	IsSystem  *bool
	Search    *string
}

func (q *Queries) CountRoles(ctx context.Context, arg CountRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles,
		arg.CompanyID,
		arg.Scope,
		arg.IsSystem,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithRole = `-- name: CountUsersWithRole :one
SELECT count(*) FROM users WHERE company_id = $1 AND role_id = $2 AND deleted_at IS NULL
`

type CountUsersWithRoleParams struct {
	CompanyID pgtype.UUID
	RoleID    uuid.UUID
}

func (q *Queries) CountUsersWithRole(ctx context.Context, arg CountUsersWithRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithRole, arg.CompanyID, arg.RoleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (company_id, name, description, scope, is_system)
VALUES ($1,$2,$3,$4,false) RETURNING id, company_id, name, description, scope, is_system, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	CompanyID   pgtype.UUID
	Name        string
	Description *string
	Scope       string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.Scope,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, company_id, name, description, scope, is_system, created_at, updated_at, deleted_at FROM roles
WHERE id = $1 AND (company_id = $2 OR company_id IS NULL) AND deleted_at IS NULL
`

type GetRoleParams struct {
	ID        uuid.UUID
	CompanyID pgtype.UUID
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ID, arg.CompanyID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, company_id, name, description, scope, is_system, created_at, updated_at, deleted_at FROM roles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByNameForCompany = `-- name: GetRoleByNameForCompany :one
SELECT id, company_id, name, description, scope, is_system, created_at, updated_at, deleted_at FROM roles
WHERE lower(name) = lower($1::text)
  AND (company_id = $2::uuid OR company_id IS NULL)
  AND deleted_at IS NULL
ORDER BY company_id NULLS LAST
LIMIT 1
`

type GetRoleByNameForCompanyParams struct {
	Name      string
	CompanyID uuid.UUID
}

// Kompaniya roli ustunlik qiladi; topilmasa tizim shabloni (company_id IS NULL).
func (q *Queries) GetRoleByNameForCompany(ctx context.Context, arg GetRoleByNameForCompanyParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByNameForCompany, arg.Name, arg.CompanyID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleWithUserCount = `-- name: GetRoleWithUserCount :one
SELECT
  r.id, r.company_id, r.name, r.description, r.scope, r.is_system, r.created_at, r.updated_at, r.deleted_at,
  (SELECT count(*) FROM users u
    WHERE u.role_id = r.id AND u.company_id = $1::uuid AND u.deleted_at IS NULL) AS user_count
FROM roles r
WHERE r.id = $2::uuid
  AND (r.company_id = $1::uuid OR r.company_id IS NULL)
  AND r.deleted_at IS NULL
`

type GetRoleWithUserCountParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetRoleWithUserCountRow struct {
	ID          uuid.UUID
	CompanyID   pgtype.UUID
	Name        string
	Description *string
	Scope       string
	IsSystem    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
	UserCount   int64
}

func (q *Queries) GetRoleWithUserCount(ctx context.Context, arg GetRoleWithUserCountParams) (GetRoleWithUserCountRow, error) {
	row := q.db.QueryRow(ctx, getRoleWithUserCount, arg.CompanyID, arg.ID)
	var i GetRoleWithUserCountRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserCount,
	)
	return i, err
}

const listPermissionsForRoles = `-- name: ListPermissionsForRoles :many
SELECT role_id, permission_key FROM role_permissions WHERE role_id = ANY($1::uuid[])
`

type ListPermissionsForRolesRow struct {
	RoleID        uuid.UUID
	PermissionKey string
}

func (q *Queries) ListPermissionsForRoles(ctx context.Context, dollar_1 []uuid.UUID) ([]ListPermissionsForRolesRow, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRoles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsForRolesRow{}
	for rows.Next() {
		var i ListPermissionsForRolesRow
		if err := rows.Scan(&i.RoleID, &i.PermissionKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT permission_key FROM role_permissions WHERE role_id = $1 ORDER BY permission_key
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT
  r.id, r.company_id, r.name, r.description, r.scope, r.is_system, r.created_at, r.updated_at, r.deleted_at,
  (SELECT count(*) FROM users u
    WHERE u.role_id = r.id AND u.company_id = $1::uuid AND u.deleted_at IS NULL) AS user_count
FROM roles r
WHERE (r.company_id = $1::uuid OR r.company_id IS NULL)
  AND r.deleted_at IS NULL
  AND ($2::text IS NULL OR r.scope = $2::text)
  AND ($3::bool IS NULL OR r.is_system = $3::bool)
  AND ($4::text IS NULL OR r.name ILIKE '%' || $4::text || '%')
ORDER BY
  CASE WHEN $5::text = 'name'       AND NOT $6::bool THEN lower(r.name)  END ASC  NULLS LAST,
  CASE WHEN $5::text = 'name'       AND     $6::bool THEN lower(r.name)  END DESC NULLS LAST,
  CASE WHEN $5::text = 'scope'      AND NOT $6::bool THEN r.scope        END ASC  NULLS LAST,
  CASE WHEN $5::text = 'scope'      AND     $6::bool THEN r.scope        END DESC NULLS LAST,
  CASE WHEN $5::text = 'created_at' AND NOT $6::bool THEN r.created_at   END ASC  NULLS LAST,
  CASE WHEN $5::text = 'created_at' AND     $6::bool THEN r.created_at   END DESC NULLS LAST,
  r.is_system DESC, lower(r.name), r.id
LIMIT $8::int OFFSET $7::int
`

type ListRolesParams struct {
	CompanyID  uuid.UUID
	Scope      *string
	IsSystem   *bool
	Search     *string
	SortKey    string
	SortDesc   bool
	PageOffset int32
	PageLimit  int32
}

type ListRolesRow struct {
	ID          uuid.UUID
	CompanyID   pgtype.UUID
	Name        string
	Description *string
	Scope       string
	IsSystem    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
	UserCount   int64
}

// Tizim shablonlari (company_id IS NULL) + kompaniya rollari.
// user_count faqat joriy tenant foydalanuvchilari bo'yicha sanaladi.
func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles,
		arg.CompanyID,
		arg.Scope,
		arg.IsSystem,
		arg.Search,
		arg.SortKey,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemRoleTemplates = `-- name: ListSystemRoleTemplates :many
SELECT id, company_id, name, description, scope, is_system, created_at, updated_at, deleted_at FROM roles WHERE company_id IS NULL AND is_system AND deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListSystemRoleTemplates(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listSystemRoleTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE roles SET deleted_at = now()
WHERE company_id = $1 AND id = $2 AND is_system = false AND deleted_at IS NULL
`

type SoftDeleteRoleParams struct {
	CompanyID pgtype.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) error {
	_, err := q.db.Exec(ctx, softDeleteRole, arg.CompanyID, arg.ID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET
  name        = COALESCE($1::text, name),
  description = COALESCE($2::text, description),
  scope       = COALESCE($3::text, scope)
WHERE company_id = $4::uuid AND id = $5::uuid
  AND is_system = false AND deleted_at IS NULL
RETURNING id, company_id, name, description, scope, is_system, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	Name        *string
	Description *string
	Scope       *string
	CompanyID   uuid.UUID
	ID          uuid.UUID
}

// is_system = false: tizim rollari hech qachon tahrirlanmaydi (SYSTEM_ROLE_IMMUTABLE).
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.CompanyID,
		arg.ID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
