// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeRoute = `-- name: CompleteRoute :one
UPDATE routes SET status = 'completed', completed_at = $3
WHERE company_id = $1 AND id = $2 AND status = 'ongoing' AND deleted_at IS NULL
RETURNING id, company_id, unit_id, driver_id, sequence, origin_text, origin_lat, origin_lng, dest_text, dest_lat, dest_lng, geofence_m, status, created_by, started_at, completed_at, not_completed_reason, note, polyline_key, created_at, updated_at, deleted_at, not_completed_note, not_completed_by, geofence_entered_at
`

type CompleteRouteParams struct {
	CompanyID   uuid.UUID
	ID          uuid.UUID
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) CompleteRoute(ctx context.Context, arg CompleteRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, completeRoute, arg.CompanyID, arg.ID, arg.CompletedAt)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Sequence,
		&i.OriginText,
		&i.OriginLat,
		&i.OriginLng,
		&i.DestText,
		&i.DestLat,
		&i.DestLng,
		&i.GeofenceM,
		&i.Status,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.NotCompletedReason,
		&i.Note,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NotCompletedNote,
		&i.NotCompletedBy,
		&i.GeofenceEnteredAt,
	)
	return i, err
}

const countRoutes = `-- name: CountRoutes :one
SELECT count(*) FROM routes r
JOIN drivers d ON d.id = r.driver_id
WHERE r.company_id = $1 AND r.deleted_at IS NULL
  AND ($2::text IS NULL OR r.status = $2::text)
  AND ($3::uuid IS NULL OR r.driver_id = $3::uuid)
  AND ($4::uuid IS NULL OR r.unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR d.branch_id = $5::uuid)
`

type CountRoutesParams struct {
	CompanyID uuid.UUID
	Status    *string
	DriverID  pgtype.UUID
	UnitID    pgtype.UUID
	BranchID  pgtype.UUID
}

func (q *Queries) CountRoutes(ctx context.Context, arg CountRoutesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutes,
		arg.CompanyID,
		arg.Status,
		arg.DriverID,
		arg.UnitID,
		arg.BranchID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (
  company_id, unit_id, driver_id, sequence, origin_text, origin_lat, origin_lng,
  dest_text, dest_lat, dest_lng, geofence_m, created_by, note, polyline_key
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id, company_id, unit_id, driver_id, sequence, origin_text, origin_lat, origin_lng, dest_text, dest_lat, dest_lng, geofence_m, status, created_by, started_at, completed_at, not_completed_reason, note, polyline_key, created_at, updated_at, deleted_at, not_completed_note, not_completed_by, geofence_entered_at
`

type CreateRouteParams struct {
	CompanyID   uuid.UUID
	UnitID      uuid.UUID
	DriverID    uuid.UUID
	Sequence    int32
	OriginText  *string
	OriginLat   *float64
	OriginLng   *float64
	DestText    *string
	DestLat     *float64
	DestLng     *float64
	GeofenceM   int32
	CreatedBy   pgtype.UUID
	Note        *string
	PolylineKey *string
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.CompanyID,
		arg.UnitID,
		arg.DriverID,
		arg.Sequence,
		arg.OriginText,
		arg.OriginLat,
		arg.OriginLng,
		arg.DestText,
		arg.DestLat,
		arg.DestLng,
		arg.GeofenceM,
		arg.CreatedBy,
		arg.Note,
		arg.PolylineKey,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Sequence,
		&i.OriginText,
		&i.OriginLat,
		&i.OriginLng,
		&i.DestText,
		&i.DestLat,
		&i.DestLng,
		&i.GeofenceM,
		&i.Status,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.NotCompletedReason,
		&i.Note,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NotCompletedNote,
		&i.NotCompletedBy,
		&i.GeofenceEnteredAt,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT id, company_id, unit_id, driver_id, sequence, origin_text, origin_lat, origin_lng, dest_text, dest_lat, dest_lng, geofence_m, status, created_by, started_at, completed_at, not_completed_reason, note, polyline_key, created_at, updated_at, deleted_at, not_completed_note, not_completed_by, geofence_entered_at FROM routes WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetRouteParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, arg.CompanyID, arg.ID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Sequence,
		&i.OriginText,
		&i.OriginLat,
		&i.OriginLng,
		&i.DestText,
		&i.DestLat,
		&i.DestLng,
		&i.GeofenceM,
		&i.Status,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.NotCompletedReason,
		&i.Note,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NotCompletedNote,
		&i.NotCompletedBy,
		&i.GeofenceEnteredAt,
	)
	return i, err
}

const getRouteDetail = `-- name: GetRouteDetail :one
SELECT r.id, r.company_id, r.unit_id, r.driver_id, r.sequence, r.origin_text, r.origin_lat, r.origin_lng, r.dest_text, r.dest_lat, r.dest_lng, r.geofence_m, r.status, r.created_by, r.started_at, r.completed_at, r.not_completed_reason, r.note, r.polyline_key, r.created_at, r.updated_at, r.deleted_at, r.not_completed_note, r.not_completed_by, r.geofence_entered_at, u.unit_number, ur.first_name, ur.last_name,
       d.branch_id AS driver_branch_id, u.branch_id AS unit_branch_id
FROM routes r
JOIN units u ON u.id = r.unit_id
JOIN drivers d ON d.id = r.driver_id
JOIN users ur ON ur.id = d.user_id
WHERE r.company_id = $1 AND r.id = $2 AND r.deleted_at IS NULL
`

type GetRouteDetailParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetRouteDetailRow struct {
	ID                 uuid.UUID
	CompanyID          uuid.UUID
	UnitID             uuid.UUID
	DriverID           uuid.UUID
	Sequence           int32
	OriginText         *string
	OriginLat          *float64
	OriginLng          *float64
	DestText           *string
	DestLat            *float64
	DestLng            *float64
	GeofenceM          int32
	Status             string
	CreatedBy          pgtype.UUID
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	NotCompletedReason *string
	Note               *string
	PolylineKey        *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          pgtype.Timestamptz
	NotCompletedNote   *string
	NotCompletedBy     pgtype.UUID
	GeofenceEnteredAt  pgtype.Timestamptz
	UnitNumber         string
	FirstName          string
	LastName           string
	DriverBranchID     pgtype.UUID
	UnitBranchID       pgtype.UUID
}

func (q *Queries) GetRouteDetail(ctx context.Context, arg GetRouteDetailParams) (GetRouteDetailRow, error) {
	row := q.db.QueryRow(ctx, getRouteDetail, arg.CompanyID, arg.ID)
	var i GetRouteDetailRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Sequence,
		&i.OriginText,
		&i.OriginLat,
		&i.OriginLng,
		&i.DestText,
		&i.DestLat,
		&i.DestLng,
		&i.GeofenceM,
		&i.Status,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.NotCompletedReason,
		&i.Note,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NotCompletedNote,
		&i.NotCompletedBy,
		&i.GeofenceEnteredAt,
		&i.UnitNumber,
		&i.FirstName,
		&i.LastName,
		&i.DriverBranchID,
		&i.UnitBranchID,
	)
	return i, err
}

const listCurrentRoutesForGeofence = `-- name: ListCurrentRoutesForGeofence :many
SELECT DISTINCT ON (r.unit_id)
  r.id, r.unit_id, r.driver_id, r.sequence, r.dest_lat, r.dest_lng,
  r.geofence_m, r.geofence_entered_at,
  s.lat AS unit_lat, s.lng AS unit_lng, s.ts AS unit_ts
FROM routes r
JOIN unit_last_state s ON s.unit_id = r.unit_id AND s.company_id = r.company_id
WHERE r.company_id = $1 AND r.deleted_at IS NULL AND r.status = 'ongoing'
  AND r.dest_lat IS NOT NULL AND r.dest_lng IS NOT NULL
  AND s.lat IS NOT NULL AND s.lng IS NOT NULL
ORDER BY r.unit_id, r.sequence, r.created_at
`

type ListCurrentRoutesForGeofenceRow struct {
	ID                uuid.UUID
	UnitID            uuid.UUID
	DriverID          uuid.UUID
	Sequence          int32
	DestLat           *float64
	DestLng           *float64
	GeofenceM         int32
	GeofenceEnteredAt pgtype.Timestamptz
	UnitLat           *float64
	UnitLng           *float64
	UnitTs            pgtype.Timestamptz
}

func (q *Queries) ListCurrentRoutesForGeofence(ctx context.Context, companyID uuid.UUID) ([]ListCurrentRoutesForGeofenceRow, error) {
	rows, err := q.db.Query(ctx, listCurrentRoutesForGeofence, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentRoutesForGeofenceRow{}
	for rows.Next() {
		var i ListCurrentRoutesForGeofenceRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.DriverID,
			&i.Sequence,
			&i.DestLat,
			&i.DestLng,
			&i.GeofenceM,
			&i.GeofenceEnteredAt,
			&i.UnitLat,
			&i.UnitLng,
			&i.UnitTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriverActiveRoutes = `-- name: ListDriverActiveRoutes :many
SELECT id, company_id, unit_id, driver_id, sequence, origin_text, origin_lat, origin_lng, dest_text, dest_lat, dest_lng, geofence_m, status, created_by, started_at, completed_at, not_completed_reason, note, polyline_key, created_at, updated_at, deleted_at, not_completed_note, not_completed_by, geofence_entered_at FROM routes
WHERE company_id = $1 AND driver_id = $2 AND status = 'ongoing' AND deleted_at IS NULL
ORDER BY sequence
`

type ListDriverActiveRoutesParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
}

func (q *Queries) ListDriverActiveRoutes(ctx context.Context, arg ListDriverActiveRoutesParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listDriverActiveRoutes, arg.CompanyID, arg.DriverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.DriverID,
			&i.Sequence,
			&i.OriginText,
			&i.OriginLat,
			&i.OriginLng,
			&i.DestText,
			&i.DestLat,
			&i.DestLng,
			&i.GeofenceM,
			&i.Status,
			&i.CreatedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.NotCompletedReason,
			&i.Note,
			&i.PolylineKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.NotCompletedNote,
			&i.NotCompletedBy,
			&i.GeofenceEnteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT r.id, r.company_id, r.unit_id, r.driver_id, r.sequence, r.origin_text, r.origin_lat, r.origin_lng, r.dest_text, r.dest_lat, r.dest_lng, r.geofence_m, r.status, r.created_by, r.started_at, r.completed_at, r.not_completed_reason, r.note, r.polyline_key, r.created_at, r.updated_at, r.deleted_at, r.not_completed_note, r.not_completed_by, r.geofence_entered_at, u.unit_number, ur.first_name, ur.last_name,
       d.branch_id AS driver_branch_id, u.branch_id AS unit_branch_id
FROM routes r
JOIN units u ON u.id = r.unit_id
JOIN drivers d ON d.id = r.driver_id
JOIN users ur ON ur.id = d.user_id
WHERE r.company_id = $1 AND r.deleted_at IS NULL
  AND ($2::text IS NULL OR r.status = $2::text)
  AND ($3::uuid IS NULL OR r.driver_id = $3::uuid)
  AND ($4::uuid IS NULL OR r.unit_id = $4::uuid)
  -- Branch scope (TZ A§16): the leg belongs to the branch of the driver it was
  -- assigned to. A NULL argument is a company scoped caller.
  AND ($5::uuid IS NULL OR d.branch_id = $5::uuid)
ORDER BY
  CASE WHEN $6::text = 'created_at' AND $7::text = 'asc'  THEN r.created_at END ASC  NULLS LAST,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'desc' THEN r.created_at END DESC NULLS LAST,
  CASE WHEN $6::text = 'sequence'   AND $7::text = 'asc'  THEN r.sequence   END ASC  NULLS LAST,
  CASE WHEN $6::text = 'sequence'   AND $7::text = 'desc' THEN r.sequence   END DESC NULLS LAST,
  CASE WHEN $6::text = 'status'     AND $7::text = 'asc'  THEN r.status     END ASC  NULLS LAST,
  CASE WHEN $6::text = 'status'     AND $7::text = 'desc' THEN r.status     END DESC NULLS LAST,
  r.created_at DESC, r.sequence ASC
LIMIT $9 OFFSET $8
`

type ListRoutesParams struct {
	CompanyID uuid.UUID
	Status    *string
	DriverID  pgtype.UUID
	UnitID    pgtype.UUID
	BranchID  pgtype.UUID
	Sort      string
	SortOrder string
	Offset    int32
	Limit     int32
}

type ListRoutesRow struct {
	ID                 uuid.UUID
	CompanyID          uuid.UUID
	UnitID             uuid.UUID
	DriverID           uuid.UUID
	Sequence           int32
	OriginText         *string
	OriginLat          *float64
	OriginLng          *float64
	DestText           *string
	DestLat            *float64
	DestLng            *float64
	GeofenceM          int32
	Status             string
	CreatedBy          pgtype.UUID
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	NotCompletedReason *string
	Note               *string
	PolylineKey        *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          pgtype.Timestamptz
	NotCompletedNote   *string
	NotCompletedBy     pgtype.UUID
	GeofenceEnteredAt  pgtype.Timestamptz
	UnitNumber         string
	FirstName          string
	LastName           string
	DriverBranchID     pgtype.UUID
	UnitBranchID       pgtype.UUID
}

func (q *Queries) ListRoutes(ctx context.Context, arg ListRoutesParams) ([]ListRoutesRow, error) {
	rows, err := q.db.Query(ctx, listRoutes,
		arg.CompanyID,
		arg.Status,
		arg.DriverID,
		arg.UnitID,
		arg.BranchID,
		arg.Sort,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutesRow{}
	for rows.Next() {
		var i ListRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.DriverID,
			&i.Sequence,
			&i.OriginText,
			&i.OriginLat,
			&i.OriginLng,
			&i.DestText,
			&i.DestLat,
			&i.DestLng,
			&i.GeofenceM,
			&i.Status,
			&i.CreatedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.NotCompletedReason,
			&i.Note,
			&i.PolylineKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.NotCompletedNote,
			&i.NotCompletedBy,
			&i.GeofenceEnteredAt,
			&i.UnitNumber,
			&i.FirstName,
			&i.LastName,
			&i.DriverBranchID,
			&i.UnitBranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRouteSequence = `-- name: NextRouteSequence :one
SELECT (COALESCE(max(sequence), 0) + 1)::int AS next_sequence
FROM routes
WHERE company_id = $1 AND unit_id = $2
  AND deleted_at IS NULL AND status = 'ongoing'
`

type NextRouteSequenceParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
}

func (q *Queries) NextRouteSequence(ctx context.Context, arg NextRouteSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextRouteSequence, arg.CompanyID, arg.UnitID)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const setRouteGeofenceEnteredAt = `-- name: SetRouteGeofenceEnteredAt :exec
UPDATE routes SET geofence_entered_at = $3
WHERE company_id = $1 AND id = $2 AND status = 'ongoing' AND deleted_at IS NULL
`

type SetRouteGeofenceEnteredAtParams struct {
	CompanyID         uuid.UUID
	ID                uuid.UUID
	GeofenceEnteredAt pgtype.Timestamptz
}

func (q *Queries) SetRouteGeofenceEnteredAt(ctx context.Context, arg SetRouteGeofenceEnteredAtParams) error {
	_, err := q.db.Exec(ctx, setRouteGeofenceEnteredAt, arg.CompanyID, arg.ID, arg.GeofenceEnteredAt)
	return err
}

const setRouteNotCompleted = `-- name: SetRouteNotCompleted :one
UPDATE routes SET
  status               = 'not_completed',
  completed_at         = now(),
  not_completed_reason = $3,
  not_completed_note   = $4,
  not_completed_by     = $5
WHERE company_id = $1 AND id = $2 AND status = 'ongoing' AND deleted_at IS NULL
RETURNING id, company_id, unit_id, driver_id, sequence, origin_text, origin_lat, origin_lng, dest_text, dest_lat, dest_lng, geofence_m, status, created_by, started_at, completed_at, not_completed_reason, note, polyline_key, created_at, updated_at, deleted_at, not_completed_note, not_completed_by, geofence_entered_at
`

type SetRouteNotCompletedParams struct {
	CompanyID          uuid.UUID
	ID                 uuid.UUID
	NotCompletedReason *string
	NotCompletedNote   *string
	NotCompletedBy     pgtype.UUID
}

func (q *Queries) SetRouteNotCompleted(ctx context.Context, arg SetRouteNotCompletedParams) (Route, error) {
	row := q.db.QueryRow(ctx, setRouteNotCompleted,
		arg.CompanyID,
		arg.ID,
		arg.NotCompletedReason,
		arg.NotCompletedNote,
		arg.NotCompletedBy,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Sequence,
		&i.OriginText,
		&i.OriginLat,
		&i.OriginLng,
		&i.DestText,
		&i.DestLat,
		&i.DestLng,
		&i.GeofenceM,
		&i.Status,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.NotCompletedReason,
		&i.Note,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NotCompletedNote,
		&i.NotCompletedBy,
		&i.GeofenceEnteredAt,
	)
	return i, err
}

const setRouteStatus = `-- name: SetRouteStatus :one
UPDATE routes SET
  status               = $3,
  started_at           = CASE WHEN $3 = 'in_progress' THEN COALESCE(started_at, now()) ELSE started_at END,
  completed_at         = CASE WHEN $3 IN ('completed','not_completed') THEN now() ELSE completed_at END,
  not_completed_reason = COALESCE($4::text, not_completed_reason)
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, company_id, unit_id, driver_id, sequence, origin_text, origin_lat, origin_lng, dest_text, dest_lat, dest_lng, geofence_m, status, created_by, started_at, completed_at, not_completed_reason, note, polyline_key, created_at, updated_at, deleted_at, not_completed_note, not_completed_by, geofence_entered_at
`

type SetRouteStatusParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	Status    string
	Column4   string
}

func (q *Queries) SetRouteStatus(ctx context.Context, arg SetRouteStatusParams) (Route, error) {
	row := q.db.QueryRow(ctx, setRouteStatus,
		arg.CompanyID,
		arg.ID,
		arg.Status,
		arg.Column4,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Sequence,
		&i.OriginText,
		&i.OriginLat,
		&i.OriginLng,
		&i.DestText,
		&i.DestLat,
		&i.DestLng,
		&i.GeofenceM,
		&i.Status,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.NotCompletedReason,
		&i.Note,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NotCompletedNote,
		&i.NotCompletedBy,
		&i.GeofenceEnteredAt,
	)
	return i, err
}

const softDeleteRoute = `-- name: SoftDeleteRoute :exec
UPDATE routes SET deleted_at = now() WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteRouteParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteRoute(ctx context.Context, arg SoftDeleteRouteParams) error {
	_, err := q.db.Exec(ctx, softDeleteRoute, arg.CompanyID, arg.ID)
	return err
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes SET
  unit_id     = COALESCE($1::uuid, unit_id),
  driver_id   = COALESCE($2::uuid, driver_id),
  sequence    = COALESCE($3::int, sequence),
  origin_text = COALESCE($4::text, origin_text),
  origin_lat  = COALESCE($5::double precision, origin_lat),
  origin_lng  = COALESCE($6::double precision, origin_lng),
  dest_text   = COALESCE($7::text, dest_text),
  dest_lat    = COALESCE($8::double precision, dest_lat),
  dest_lng    = COALESCE($9::double precision, dest_lng),
  geofence_m  = COALESCE($10::int, geofence_m),
  note        = COALESCE($11::text, note)
WHERE company_id = $12 AND id = $13 AND deleted_at IS NULL AND status = 'ongoing'
RETURNING id, company_id, unit_id, driver_id, sequence, origin_text, origin_lat, origin_lng, dest_text, dest_lat, dest_lng, geofence_m, status, created_by, started_at, completed_at, not_completed_reason, note, polyline_key, created_at, updated_at, deleted_at, not_completed_note, not_completed_by, geofence_entered_at
`

type UpdateRouteParams struct {
	UnitID     pgtype.UUID
	DriverID   pgtype.UUID
	Sequence   *int32
	OriginText *string
	OriginLat  *float64
	OriginLng  *float64
	DestText   *string
	DestLat    *float64
	DestLng    *float64
	GeofenceM  *int32
	Note       *string
	CompanyID  uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.UnitID,
		arg.DriverID,
		arg.Sequence,
		arg.OriginText,
		arg.OriginLat,
		arg.OriginLng,
		arg.DestText,
		arg.DestLat,
		arg.DestLng,
		arg.GeofenceM,
		arg.Note,
		arg.CompanyID,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.Sequence,
		&i.OriginText,
		&i.OriginLat,
		&i.OriginLng,
		&i.DestText,
		&i.DestLat,
		&i.DestLng,
		&i.GeofenceM,
		&i.Status,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.NotCompletedReason,
		&i.Note,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NotCompletedNote,
		&i.NotCompletedBy,
		&i.GeofenceEnteredAt,
	)
	return i, err
}
