// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping_documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countShippingDocuments = `-- name: CountShippingDocuments :one
SELECT count(*) FROM shipping_documents
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR number ILIKE '%' || $2::text || '%')
`

type CountShippingDocumentsParams struct {
	CompanyID uuid.UUID
	Column2   string
}

func (q *Queries) CountShippingDocuments(ctx context.Context, arg CountShippingDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShippingDocuments, arg.CompanyID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShippingDocument = `-- name: CreateShippingDocument :one
INSERT INTO shipping_documents (company_id, number, notes) VALUES ($1,$2,$3) RETURNING id, company_id, number, notes, created_at, updated_at, deleted_at
`

type CreateShippingDocumentParams struct {
	CompanyID uuid.UUID
	Number    string
	Notes     *string
}

func (q *Queries) CreateShippingDocument(ctx context.Context, arg CreateShippingDocumentParams) (ShippingDocument, error) {
	row := q.db.QueryRow(ctx, createShippingDocument, arg.CompanyID, arg.Number, arg.Notes)
	var i ShippingDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShippingDocument = `-- name: GetShippingDocument :one
SELECT id, company_id, number, notes, created_at, updated_at, deleted_at FROM shipping_documents WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetShippingDocumentParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetShippingDocument(ctx context.Context, arg GetShippingDocumentParams) (ShippingDocument, error) {
	row := q.db.QueryRow(ctx, getShippingDocument, arg.CompanyID, arg.ID)
	var i ShippingDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listShippingDocuments = `-- name: ListShippingDocuments :many
SELECT id, company_id, number, notes, created_at, updated_at, deleted_at FROM shipping_documents
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR number ILIKE '%' || $2::text || '%')
ORDER BY number LIMIT $3 OFFSET $4
`

type ListShippingDocumentsParams struct {
	CompanyID uuid.UUID
	Column2   string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListShippingDocuments(ctx context.Context, arg ListShippingDocumentsParams) ([]ShippingDocument, error) {
	rows, err := q.db.Query(ctx, listShippingDocuments,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingDocument{}
	for rows.Next() {
		var i ShippingDocument
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingDocumentsByIDs = `-- name: ListShippingDocumentsByIDs :many
SELECT id, company_id, number, notes, created_at, updated_at, deleted_at FROM shipping_documents WHERE company_id = $1 AND id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type ListShippingDocumentsByIDsParams struct {
	CompanyID uuid.UUID
	Column2   []uuid.UUID
}

func (q *Queries) ListShippingDocumentsByIDs(ctx context.Context, arg ListShippingDocumentsByIDsParams) ([]ShippingDocument, error) {
	rows, err := q.db.Query(ctx, listShippingDocumentsByIDs, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingDocument{}
	for rows.Next() {
		var i ShippingDocument
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteShippingDocument = `-- name: SoftDeleteShippingDocument :exec
UPDATE shipping_documents SET deleted_at = now() WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteShippingDocumentParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteShippingDocument(ctx context.Context, arg SoftDeleteShippingDocumentParams) error {
	_, err := q.db.Exec(ctx, softDeleteShippingDocument, arg.CompanyID, arg.ID)
	return err
}

const updateShippingDocument = `-- name: UpdateShippingDocument :one
UPDATE shipping_documents SET number = COALESCE($3::text, number), notes = COALESCE($4::text, notes)
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL RETURNING id, company_id, number, notes, created_at, updated_at, deleted_at
`

type UpdateShippingDocumentParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	Column3   string
	Column4   string
}

func (q *Queries) UpdateShippingDocument(ctx context.Context, arg UpdateShippingDocumentParams) (ShippingDocument, error) {
	row := q.db.QueryRow(ctx, updateShippingDocument,
		arg.CompanyID,
		arg.ID,
		arg.Column3,
		arg.Column4,
	)
	var i ShippingDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
