// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCompanySubscription = `-- name: GetCompanySubscription :one

SELECT subscription_status, subscription_end_at
FROM companies
WHERE id = $1 AND deleted_at IS NULL
`

type GetCompanySubscriptionRow struct {
	SubscriptionStatus string
	SubscriptionEndAt  pgtype.Timestamptz
}

// Obuna holati — `RequireWritableSubscription` middleware uchun (TZ B§15).
// Faqat o'qish: obunani Super Admin paneli o'zgartiradi.
func (q *Queries) GetCompanySubscription(ctx context.Context, id uuid.UUID) (GetCompanySubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getCompanySubscription, id)
	var i GetCompanySubscriptionRow
	err := row.Scan(&i.SubscriptionStatus, &i.SubscriptionEndAt)
	return i, err
}
