// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dutyCountDriverEventsBetween = `-- name: DutyCountDriverEventsBetween :one
SELECT count(*)
FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2
  AND event_time >= $3 AND event_time < $4
  AND superseded_by IS NULL
`

type DutyCountDriverEventsBetweenParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	FromAt    time.Time
	ToAt      time.Time
}

func (q *Queries) DutyCountDriverEventsBetween(ctx context.Context, arg DutyCountDriverEventsBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, dutyCountDriverEventsBetween,
		arg.CompanyID,
		arg.DriverID,
		arg.FromAt,
		arg.ToAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dutyListDriverEventsBetween = `-- name: DutyListDriverEventsBetween :many

SELECT id, driver_id, unit_id, event_type, status, special, event_time,
       time_source, time_unverified, clock_skew_sec, origin, lat, lng,
       location_text, gps_accuracy_m, odometer_m, engine_hours, notes,
       trailer_ids, shipping_doc_ids, client_event_id, device_seq,
       received_at, superseded_by, locked, daily_log_id
FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2
  AND event_time >= $3 AND event_time < $4
  AND superseded_by IS NULL
ORDER BY event_time, device_seq NULLS LAST
`

type DutyListDriverEventsBetweenParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	FromAt    time.Time
	ToAt      time.Time
}

type DutyListDriverEventsBetweenRow struct {
	ID             uuid.UUID
	DriverID       pgtype.UUID
	UnitID         pgtype.UUID
	EventType      string
	Status         *string
	Special        string
	EventTime      time.Time
	TimeSource     string
	TimeUnverified bool
	ClockSkewSec   int32
	Origin         string
	Lat            *float64
	Lng            *float64
	LocationText   *string
	GpsAccuracyM   *int32
	OdometerM      *int64
	EngineHours    pgtype.Numeric
	Notes          *string
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	ClientEventID  uuid.UUID
	DeviceSeq      *int64
	ReceivedAt     time.Time
	SupersededBy   pgtype.UUID
	Locked         bool
	DailyLogID     pgtype.UUID
}

// -------------------------------------------------------------- duty / HOS
// HOS hisobi uchun to'liq oyna (cycle_days + joriy kun). Pagination yo'q:
// natija hos.Compute ga to'liq ketadi.
func (q *Queries) DutyListDriverEventsBetween(ctx context.Context, arg DutyListDriverEventsBetweenParams) ([]DutyListDriverEventsBetweenRow, error) {
	rows, err := q.db.Query(ctx, dutyListDriverEventsBetween,
		arg.CompanyID,
		arg.DriverID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyListDriverEventsBetweenRow{}
	for rows.Next() {
		var i DutyListDriverEventsBetweenRow
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.UnitID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dutyListDriverEventsPage = `-- name: DutyListDriverEventsPage :many
SELECT id, driver_id, unit_id, event_type, status, special, event_time,
       time_source, time_unverified, clock_skew_sec, origin, lat, lng,
       location_text, gps_accuracy_m, odometer_m, engine_hours, notes,
       trailer_ids, shipping_doc_ids, client_event_id, device_seq,
       received_at, superseded_by, locked, daily_log_id
FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2
  AND event_time >= $3 AND event_time < $4
  AND superseded_by IS NULL
ORDER BY event_time, device_seq NULLS LAST
LIMIT $6 OFFSET $5
`

type DutyListDriverEventsPageParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	FromAt    time.Time
	ToAt      time.Time
	Off       int32
	Lim       int32
}

type DutyListDriverEventsPageRow struct {
	ID             uuid.UUID
	DriverID       pgtype.UUID
	UnitID         pgtype.UUID
	EventType      string
	Status         *string
	Special        string
	EventTime      time.Time
	TimeSource     string
	TimeUnverified bool
	ClockSkewSec   int32
	Origin         string
	Lat            *float64
	Lng            *float64
	LocationText   *string
	GpsAccuracyM   *int32
	OdometerM      *int64
	EngineHours    pgtype.Numeric
	Notes          *string
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	ClientEventID  uuid.UUID
	DeviceSeq      *int64
	ReceivedAt     time.Time
	SupersededBy   pgtype.UUID
	Locked         bool
	DailyLogID     pgtype.UUID
}

func (q *Queries) DutyListDriverEventsPage(ctx context.Context, arg DutyListDriverEventsPageParams) ([]DutyListDriverEventsPageRow, error) {
	rows, err := q.db.Query(ctx, dutyListDriverEventsPage,
		arg.CompanyID,
		arg.DriverID,
		arg.FromAt,
		arg.ToAt,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DutyListDriverEventsPageRow{}
	for rows.Next() {
		var i DutyListDriverEventsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.UnitID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dutySetDailyLogTotals = `-- name: DutySetDailyLogTotals :exec
UPDATE daily_logs
SET totals = $1, unit_ids = $2
WHERE company_id = $3 AND id = $4
`

type DutySetDailyLogTotalsParams struct {
	Totals    []byte
	UnitIds   []uuid.UUID
	CompanyID uuid.UUID
	ID        uuid.UUID
}

// `totals` JSONB ni hos.DayTotalsFor natijasi bilan qayta yozadi (Q10.2).
func (q *Queries) DutySetDailyLogTotals(ctx context.Context, arg DutySetDailyLogTotalsParams) error {
	_, err := q.db.Exec(ctx, dutySetDailyLogTotals,
		arg.Totals,
		arg.UnitIds,
		arg.CompanyID,
		arg.ID,
	)
	return err
}

const syncGetDriverByUserID = `-- name: SyncGetDriverByUserID :one
SELECT d.id, d.company_id, d.user_id, d.branch_id, d.status, d.default_unit_id,
       d.home_terminal, c.timezone, c.settings
FROM drivers d
JOIN companies c ON c.id = d.company_id
WHERE d.company_id = $1 AND d.user_id = $2 AND d.deleted_at IS NULL
`

type SyncGetDriverByUserIDParams struct {
	CompanyID uuid.UUID
	UserID    uuid.UUID
}

type SyncGetDriverByUserIDRow struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	UserID        uuid.UUID
	BranchID      pgtype.UUID
	Status        string
	DefaultUnitID pgtype.UUID
	HomeTerminal  *string
	Timezone      string
	Settings      []byte
}

func (q *Queries) SyncGetDriverByUserID(ctx context.Context, arg SyncGetDriverByUserIDParams) (SyncGetDriverByUserIDRow, error) {
	row := q.db.QueryRow(ctx, syncGetDriverByUserID, arg.CompanyID, arg.UserID)
	var i SyncGetDriverByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.Status,
		&i.DefaultUnitID,
		&i.HomeTerminal,
		&i.Timezone,
		&i.Settings,
	)
	return i, err
}

const syncGetDriverContext = `-- name: SyncGetDriverContext :one


SELECT d.id, d.company_id, d.user_id, d.branch_id, d.status, d.default_unit_id,
       d.home_terminal, c.timezone, c.settings
FROM drivers d
JOIN companies c ON c.id = d.company_id
WHERE d.company_id = $1 AND d.id = $2 AND d.deleted_at IS NULL
`

type SyncGetDriverContextParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type SyncGetDriverContextRow struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	UserID        uuid.UUID
	BranchID      pgtype.UUID
	Status        string
	DefaultUnitID pgtype.UUID
	HomeTerminal  *string
	Timezone      string
	Settings      []byte
}

// Offline sync (internal/domain/sync) va duty status / HOS (internal/domain/duty)
// query'lari. Har query'da `company_id` aniq predikat sifatida qoladi (RLS —
// ikkinchi qatlam). Vaqtlar UTC, kunga ajratish Home Terminal TZ bo'yicha
// Go tomonida (hos.StartOfDay) qilinadi.
// ------------------------------------------------------------------ konteks
// Push/pull uchun haydovchi konteksti: kompaniya TZ'i (Q10.2 kun chegarasi),
// quick_notes uchun settings va default unit.
func (q *Queries) SyncGetDriverContext(ctx context.Context, arg SyncGetDriverContextParams) (SyncGetDriverContextRow, error) {
	row := q.db.QueryRow(ctx, syncGetDriverContext, arg.CompanyID, arg.ID)
	var i SyncGetDriverContextRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.BranchID,
		&i.Status,
		&i.DefaultUnitID,
		&i.HomeTerminal,
		&i.Timezone,
		&i.Settings,
	)
	return i, err
}

const syncGetHosPolicyAt = `-- name: SyncGetHosPolicyAt :one
SELECT id, company_id, effective_from, policy
FROM hos_policy_versions
WHERE company_id = $1 AND deleted_at IS NULL AND effective_from <= $2
ORDER BY effective_from DESC
LIMIT 1
`

type SyncGetHosPolicyAtParams struct {
	CompanyID uuid.UUID
	At        time.Time
}

type SyncGetHosPolicyAtRow struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	EffectiveFrom time.Time
	Policy        []byte
}

// Q10.1: o'sha kunda amal qilgan versiya. Retroaktiv qayta hisob yo'q, shuning
// uchun `effective_from <= @at` bo'yicha eng so'nggisi olinadi.
func (q *Queries) SyncGetHosPolicyAt(ctx context.Context, arg SyncGetHosPolicyAtParams) (SyncGetHosPolicyAtRow, error) {
	row := q.db.QueryRow(ctx, syncGetHosPolicyAt, arg.CompanyID, arg.At)
	var i SyncGetHosPolicyAtRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EffectiveFrom,
		&i.Policy,
	)
	return i, err
}

const syncGetUnitFlags = `-- name: SyncGetUnitFlags :one
SELECT id, unit_number, sleeper_berth, status, out_of_service
FROM units
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SyncGetUnitFlagsParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type SyncGetUnitFlagsRow struct {
	ID           uuid.UUID
	UnitNumber   string
	SleeperBerth bool
	Status       string
	OutOfService bool
}

func (q *Queries) SyncGetUnitFlags(ctx context.Context, arg SyncGetUnitFlagsParams) (SyncGetUnitFlagsRow, error) {
	row := q.db.QueryRow(ctx, syncGetUnitFlags, arg.CompanyID, arg.ID)
	var i SyncGetUnitFlagsRow
	err := row.Scan(
		&i.ID,
		&i.UnitNumber,
		&i.SleeperBerth,
		&i.Status,
		&i.OutOfService,
	)
	return i, err
}

const syncKnownClientEventIDs = `-- name: SyncKnownClientEventIDs :many

SELECT client_event_id, (company_id = $1) AS same_company
FROM duty_status_events
WHERE client_event_id = ANY($2::uuid[])
`

type SyncKnownClientEventIDsParams struct {
	CompanyID      uuid.UUID
	ClientEventIds []uuid.UUID
}

type SyncKnownClientEventIDsRow struct {
	ClientEventID uuid.UUID
	SameCompany   bool
}

// --------------------------------------------------------------- idempotency
// `client_event_id` global UNIQUE, shuning uchun boshqa tenant'ning yozuvi ham
// qaytadi: `same_company=false` bo'lsa yozuv qilinmaydi, javob `duplicate`
// (cross-tenant ma'lumot chiqmaydi).
func (q *Queries) SyncKnownClientEventIDs(ctx context.Context, arg SyncKnownClientEventIDsParams) ([]SyncKnownClientEventIDsRow, error) {
	rows, err := q.db.Query(ctx, syncKnownClientEventIDs, arg.CompanyID, arg.ClientEventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncKnownClientEventIDsRow{}
	for rows.Next() {
		var i SyncKnownClientEventIDsRow
		if err := rows.Scan(&i.ClientEventID, &i.SameCompany); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncListCertifiedLogDates = `-- name: SyncListCertifiedLogDates :many
SELECT log_date
FROM daily_logs
WHERE company_id = $1 AND driver_id = $2
  AND log_date = ANY($3::date[])
  AND certification_status = 'certified'
`

type SyncListCertifiedLogDatesParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	LogDates  []pgtype.Date
}

// Konflikt qoidasi 5: sertifikatlangan (locked) kunga push yozmaydi.
func (q *Queries) SyncListCertifiedLogDates(ctx context.Context, arg SyncListCertifiedLogDatesParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, syncListCertifiedLogDates, arg.CompanyID, arg.DriverID, arg.LogDates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var log_date pgtype.Date
		if err := rows.Scan(&log_date); err != nil {
			return nil, err
		}
		items = append(items, log_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncListChatSince = `-- name: SyncListChatSince :many
SELECT id, driver_id, sender_id, kind, text, file_key, lat, lng,
       sent_at, delivered_at, read_at, updated_at
FROM chat_messages
WHERE company_id = $1 AND driver_id = $2 AND updated_at > $3
ORDER BY updated_at
LIMIT $4
`

type SyncListChatSinceParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	Since     time.Time
	Lim       int32
}

type SyncListChatSinceRow struct {
	ID          uuid.UUID
	DriverID    uuid.UUID
	SenderID    uuid.UUID
	Kind        string
	Text        *string
	FileKey     *string
	Lat         *float64
	Lng         *float64
	SentAt      time.Time
	DeliveredAt pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
	UpdatedAt   time.Time
}

func (q *Queries) SyncListChatSince(ctx context.Context, arg SyncListChatSinceParams) ([]SyncListChatSinceRow, error) {
	rows, err := q.db.Query(ctx, syncListChatSince,
		arg.CompanyID,
		arg.DriverID,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncListChatSinceRow{}
	for rows.Next() {
		var i SyncListChatSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.SenderID,
			&i.Kind,
			&i.Text,
			&i.FileKey,
			&i.Lat,
			&i.Lng,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncListDailyLogsChangedSince = `-- name: SyncListDailyLogsChangedSince :many
SELECT id, driver_id, log_date, timezone, unit_ids, co_driver_id, distance_m,
       trailer_ids, shipping_doc_ids, totals, certification_status, signed_at,
       updated_at
FROM daily_logs
WHERE company_id = $1 AND driver_id = $2 AND updated_at > $3
ORDER BY updated_at
LIMIT $4
`

type SyncListDailyLogsChangedSinceParams struct {
	CompanyID uuid.UUID
	DriverID  uuid.UUID
	Since     time.Time
	Lim       int32
}

type SyncListDailyLogsChangedSinceRow struct {
	ID                  uuid.UUID
	DriverID            uuid.UUID
	LogDate             pgtype.Date
	Timezone            string
	UnitIds             []uuid.UUID
	CoDriverID          pgtype.UUID
	DistanceM           int64
	TrailerIds          []uuid.UUID
	ShippingDocIds      []uuid.UUID
	Totals              []byte
	CertificationStatus string
	SignedAt            pgtype.Timestamptz
	UpdatedAt           time.Time
}

func (q *Queries) SyncListDailyLogsChangedSince(ctx context.Context, arg SyncListDailyLogsChangedSinceParams) ([]SyncListDailyLogsChangedSinceRow, error) {
	rows, err := q.db.Query(ctx, syncListDailyLogsChangedSince,
		arg.CompanyID,
		arg.DriverID,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncListDailyLogsChangedSinceRow{}
	for rows.Next() {
		var i SyncListDailyLogsChangedSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.LogDate,
			&i.Timezone,
			&i.UnitIds,
			&i.CoDriverID,
			&i.DistanceM,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.Totals,
			&i.CertificationStatus,
			&i.SignedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncListDefectTypes = `-- name: SyncListDefectTypes :many
SELECT id, company_id, name, category, is_critical, is_active, sort_order, updated_at
FROM defect_types
WHERE (company_id = $1 OR company_id IS NULL)
  AND deleted_at IS NULL AND is_active
ORDER BY category, sort_order, name
`

type SyncListDefectTypesRow struct {
	ID         uuid.UUID
	CompanyID  pgtype.UUID
	Name       string
	Category   string
	IsCritical bool
	IsActive   bool
	SortOrder  int32
	UpdatedAt  time.Time
}

func (q *Queries) SyncListDefectTypes(ctx context.Context, companyID pgtype.UUID) ([]SyncListDefectTypesRow, error) {
	rows, err := q.db.Query(ctx, syncListDefectTypes, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncListDefectTypesRow{}
	for rows.Next() {
		var i SyncListDefectTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Category,
			&i.IsCritical,
			&i.IsActive,
			&i.SortOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncListEventsAtInstants = `-- name: SyncListEventsAtInstants :many
SELECT id, client_event_id, event_time, time_source, device_seq, received_at
FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2
  AND event_type = 'duty_status'
  AND superseded_by IS NULL
  AND event_time >= $3 AND event_time <= $4
`

type SyncListEventsAtInstantsParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	FromAt    time.Time
	ToAt      time.Time
}

type SyncListEventsAtInstantsRow struct {
	ID            uuid.UUID
	ClientEventID uuid.UUID
	EventTime     time.Time
	TimeSource    string
	DeviceSeq     *int64
	ReceivedAt    time.Time
}

// Konflikt qoidasi 1: o'sha vaqt oralig'idagi saqlangan duty status eventlar.
func (q *Queries) SyncListEventsAtInstants(ctx context.Context, arg SyncListEventsAtInstantsParams) ([]SyncListEventsAtInstantsRow, error) {
	rows, err := q.db.Query(ctx, syncListEventsAtInstants,
		arg.CompanyID,
		arg.DriverID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncListEventsAtInstantsRow{}
	for rows.Next() {
		var i SyncListEventsAtInstantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientEventID,
			&i.EventTime,
			&i.TimeSource,
			&i.DeviceSeq,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncListEventsChangedSince = `-- name: SyncListEventsChangedSince :many
SELECT id, driver_id, unit_id, event_type, status, special, event_time,
       time_source, time_unverified, clock_skew_sec, origin, lat, lng,
       location_text, gps_accuracy_m, odometer_m, engine_hours, notes,
       trailer_ids, shipping_doc_ids, client_event_id, device_seq,
       received_at, superseded_by, locked, daily_log_id, updated_at
FROM duty_status_events
WHERE company_id = $1 AND driver_id = $2 AND updated_at > $3
ORDER BY updated_at
LIMIT $4
`

type SyncListEventsChangedSinceParams struct {
	CompanyID uuid.UUID
	DriverID  pgtype.UUID
	Since     time.Time
	Lim       int32
}

type SyncListEventsChangedSinceRow struct {
	ID             uuid.UUID
	DriverID       pgtype.UUID
	UnitID         pgtype.UUID
	EventType      string
	Status         *string
	Special        string
	EventTime      time.Time
	TimeSource     string
	TimeUnverified bool
	ClockSkewSec   int32
	Origin         string
	Lat            *float64
	Lng            *float64
	LocationText   *string
	GpsAccuracyM   *int32
	OdometerM      *int64
	EngineHours    pgtype.Numeric
	Notes          *string
	TrailerIds     []uuid.UUID
	ShippingDocIds []uuid.UUID
	ClientEventID  uuid.UUID
	DeviceSeq      *int64
	ReceivedAt     time.Time
	SupersededBy   pgtype.UUID
	Locked         bool
	DailyLogID     pgtype.UUID
	UpdatedAt      time.Time
}

// Server kanonik (konflikt qoidasi 2): admin tahriri/assignment natijasida
// o'zgargan eventlar mobilga qaytariladi.
func (q *Queries) SyncListEventsChangedSince(ctx context.Context, arg SyncListEventsChangedSinceParams) ([]SyncListEventsChangedSinceRow, error) {
	rows, err := q.db.Query(ctx, syncListEventsChangedSince,
		arg.CompanyID,
		arg.DriverID,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncListEventsChangedSinceRow{}
	for rows.Next() {
		var i SyncListEventsChangedSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.UnitID,
			&i.EventType,
			&i.Status,
			&i.Special,
			&i.EventTime,
			&i.TimeSource,
			&i.TimeUnverified,
			&i.ClockSkewSec,
			&i.Origin,
			&i.Lat,
			&i.Lng,
			&i.LocationText,
			&i.GpsAccuracyM,
			&i.OdometerM,
			&i.EngineHours,
			&i.Notes,
			&i.TrailerIds,
			&i.ShippingDocIds,
			&i.ClientEventID,
			&i.DeviceSeq,
			&i.ReceivedAt,
			&i.SupersededBy,
			&i.Locked,
			&i.DailyLogID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncListUnidentifiedForUnits = `-- name: SyncListUnidentifiedForUnits :many

SELECT e.id, e.unit_id, u.unit_number, e.start_at, e.end_at, e.distance_m,
       e.track_key, e.status, e.updated_at
FROM unidentified_events e
JOIN units u ON u.id = e.unit_id
WHERE e.company_id = $1
  AND e.unit_id = ANY($2::uuid[])
  AND e.status = 'pending'
  AND e.updated_at > $3
ORDER BY e.updated_at
LIMIT $4
`

type SyncListUnidentifiedForUnitsParams struct {
	CompanyID uuid.UUID
	UnitIds   []uuid.UUID
	Since     time.Time
	Lim       int32
}

type SyncListUnidentifiedForUnitsRow struct {
	ID         uuid.UUID
	UnitID     uuid.UUID
	UnitNumber string
	StartAt    time.Time
	EndAt      pgtype.Timestamptz
	DistanceM  int64
	TrackKey   *string
	Status     string
	UpdatedAt  time.Time
}

// ------------------------------------------------------------------- pull
// Haydovchi login qilgan unit(lar) uchun pending unidentified driving (A§10.4).
func (q *Queries) SyncListUnidentifiedForUnits(ctx context.Context, arg SyncListUnidentifiedForUnitsParams) ([]SyncListUnidentifiedForUnitsRow, error) {
	rows, err := q.db.Query(ctx, syncListUnidentifiedForUnits,
		arg.CompanyID,
		arg.UnitIds,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncListUnidentifiedForUnitsRow{}
	for rows.Next() {
		var i SyncListUnidentifiedForUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.UnitNumber,
			&i.StartAt,
			&i.EndAt,
			&i.DistanceM,
			&i.TrackKey,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncSupersedeEvents = `-- name: SyncSupersedeEvents :exec
UPDATE duty_status_events SET superseded_by = $1
WHERE company_id = $2 AND id = ANY($3::uuid[]) AND superseded_by IS NULL
`

type SyncSupersedeEventsParams struct {
	SupersededBy pgtype.UUID
	CompanyID    uuid.UUID
	Ids          []uuid.UUID
}

func (q *Queries) SyncSupersedeEvents(ctx context.Context, arg SyncSupersedeEventsParams) error {
	_, err := q.db.Exec(ctx, syncSupersedeEvents, arg.SupersededBy, arg.CompanyID, arg.Ids)
	return err
}
