// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracking.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const telemetryAccrueTrip = `-- name: TelemetryAccrueTrip :one
UPDATE trips SET
  distance_m    = distance_m + $1,
  max_speed_kmh = GREATEST(COALESCE(max_speed_kmh, 0), COALESCE($2::double precision, 0))
WHERE company_id = $3 AND id = $4 AND end_at IS NULL
RETURNING id, company_id, unit_id, driver_id, start_at, end_at, start_lat, start_lng, end_lat, end_lng, distance_m, duration_sec, max_speed_kmh, polyline_key, created_at, updated_at
`

type TelemetryAccrueTripParams struct {
	DistanceM   int64
	MaxSpeedKmh *float64
	CompanyID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) TelemetryAccrueTrip(ctx context.Context, arg TelemetryAccrueTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, telemetryAccrueTrip,
		arg.DistanceM,
		arg.MaxSpeedKmh,
		arg.CompanyID,
		arg.ID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.StartAt,
		&i.EndAt,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.DistanceM,
		&i.DurationSec,
		&i.MaxSpeedKmh,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const telemetryAccrueUnidentifiedEvent = `-- name: TelemetryAccrueUnidentifiedEvent :one
UPDATE unidentified_events SET distance_m = distance_m + $1
WHERE company_id = $2 AND id = $3 AND end_at IS NULL
RETURNING id, company_id, unit_id, eld_device_id, start_at, end_at, distance_m, track_key, status, assigned_driver_id, annotation, resolved_by, resolved_at, created_at, updated_at, edit_request_id
`

type TelemetryAccrueUnidentifiedEventParams struct {
	DistanceM int64
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) TelemetryAccrueUnidentifiedEvent(ctx context.Context, arg TelemetryAccrueUnidentifiedEventParams) (UnidentifiedEvent, error) {
	row := q.db.QueryRow(ctx, telemetryAccrueUnidentifiedEvent, arg.DistanceM, arg.CompanyID, arg.ID)
	var i UnidentifiedEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.StartAt,
		&i.EndAt,
		&i.DistanceM,
		&i.TrackKey,
		&i.Status,
		&i.AssignedDriverID,
		&i.Annotation,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditRequestID,
	)
	return i, err
}

const telemetryActiveDeviceForUnit = `-- name: TelemetryActiveDeviceForUnit :one
SELECT id, serial, vendor, status, malfunction_codes, firmware
FROM eld_devices
WHERE company_id = $1 AND unit_id = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type TelemetryActiveDeviceForUnitParams struct {
	CompanyID uuid.UUID
	UnitID    pgtype.UUID
}

type TelemetryActiveDeviceForUnitRow struct {
	ID               uuid.UUID
	Serial           string
	Vendor           string
	Status           string
	MalfunctionCodes []string
	Firmware         *string
}

func (q *Queries) TelemetryActiveDeviceForUnit(ctx context.Context, arg TelemetryActiveDeviceForUnitParams) (TelemetryActiveDeviceForUnitRow, error) {
	row := q.db.QueryRow(ctx, telemetryActiveDeviceForUnit, arg.CompanyID, arg.UnitID)
	var i TelemetryActiveDeviceForUnitRow
	err := row.Scan(
		&i.ID,
		&i.Serial,
		&i.Vendor,
		&i.Status,
		&i.MalfunctionCodes,
		&i.Firmware,
	)
	return i, err
}

const telemetryCloseTrip = `-- name: TelemetryCloseTrip :one
UPDATE trips SET
  end_at        = $1,
  end_lat       = $2::double precision,
  end_lng       = $3::double precision,
  distance_m    = distance_m + $4,
  duration_sec  = $5::integer,
  max_speed_kmh = GREATEST(COALESCE(max_speed_kmh, 0), COALESCE($6::double precision, 0)),
  polyline_key  = COALESCE($7::text, polyline_key)
WHERE company_id = $8 AND id = $9 AND end_at IS NULL
RETURNING id, company_id, unit_id, driver_id, start_at, end_at, start_lat, start_lng, end_lat, end_lng, distance_m, duration_sec, max_speed_kmh, polyline_key, created_at, updated_at
`

type TelemetryCloseTripParams struct {
	EndAt       pgtype.Timestamptz
	EndLat      *float64
	EndLng      *float64
	DistanceM   int64
	DurationSec *int32
	MaxSpeedKmh *float64
	PolylineKey *string
	CompanyID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) TelemetryCloseTrip(ctx context.Context, arg TelemetryCloseTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, telemetryCloseTrip,
		arg.EndAt,
		arg.EndLat,
		arg.EndLng,
		arg.DistanceM,
		arg.DurationSec,
		arg.MaxSpeedKmh,
		arg.PolylineKey,
		arg.CompanyID,
		arg.ID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.StartAt,
		&i.EndAt,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.DistanceM,
		&i.DurationSec,
		&i.MaxSpeedKmh,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const telemetryCloseUnidentifiedEvent = `-- name: TelemetryCloseUnidentifiedEvent :one
UPDATE unidentified_events SET
  end_at     = $1,
  distance_m = distance_m + $2,
  track_key  = COALESCE($3::text, track_key)
WHERE company_id = $4 AND id = $5 AND end_at IS NULL
RETURNING id, company_id, unit_id, eld_device_id, start_at, end_at, distance_m, track_key, status, assigned_driver_id, annotation, resolved_by, resolved_at, created_at, updated_at, edit_request_id
`

type TelemetryCloseUnidentifiedEventParams struct {
	EndAt     pgtype.Timestamptz
	DistanceM int64
	TrackKey  *string
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) TelemetryCloseUnidentifiedEvent(ctx context.Context, arg TelemetryCloseUnidentifiedEventParams) (UnidentifiedEvent, error) {
	row := q.db.QueryRow(ctx, telemetryCloseUnidentifiedEvent,
		arg.EndAt,
		arg.DistanceM,
		arg.TrackKey,
		arg.CompanyID,
		arg.ID,
	)
	var i UnidentifiedEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.StartAt,
		&i.EndAt,
		&i.DistanceM,
		&i.TrackKey,
		&i.Status,
		&i.AssignedDriverID,
		&i.Annotation,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditRequestID,
	)
	return i, err
}

const telemetryGetUnitBrief = `-- name: TelemetryGetUnitBrief :one


SELECT u.id, u.company_id, u.branch_id, u.unit_number, u.status
FROM units u
WHERE u.company_id = $1 AND u.id = $2 AND u.deleted_at IS NULL
`

type TelemetryGetUnitBriefParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type TelemetryGetUnitBriefRow struct {
	ID         uuid.UUID
	CompanyID  uuid.UUID
	BranchID   pgtype.UUID
	UnitNumber string
	Status     string
}

// Telemetriya ingestion (internal/domain/telemetry) va Tracking (internal/domain/tracking)
// query'lari. Continuous aggregate'larga RLS qo'llanmaydi, shuning uchun har
// query'da `company_id = @company_id` sharti MAJBURIY (xom jadvallarda ham
// aniq predikat qoldirilgan: RLS ikkinchi qatlam).
// ------------------------------------------------------------------ ingestion
func (q *Queries) TelemetryGetUnitBrief(ctx context.Context, arg TelemetryGetUnitBriefParams) (TelemetryGetUnitBriefRow, error) {
	row := q.db.QueryRow(ctx, telemetryGetUnitBrief, arg.CompanyID, arg.ID)
	var i TelemetryGetUnitBriefRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.UnitNumber,
		&i.Status,
	)
	return i, err
}

const telemetryOpenTrip = `-- name: TelemetryOpenTrip :one
SELECT id, company_id, unit_id, driver_id, start_at, end_at, start_lat, start_lng, end_lat, end_lng, distance_m, duration_sec, max_speed_kmh, polyline_key, created_at, updated_at FROM trips
WHERE company_id = $1 AND unit_id = $2 AND end_at IS NULL
ORDER BY start_at DESC
LIMIT 1
`

type TelemetryOpenTripParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
}

func (q *Queries) TelemetryOpenTrip(ctx context.Context, arg TelemetryOpenTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, telemetryOpenTrip, arg.CompanyID, arg.UnitID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.StartAt,
		&i.EndAt,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.DistanceM,
		&i.DurationSec,
		&i.MaxSpeedKmh,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const telemetryOpenUnidentifiedEvent = `-- name: TelemetryOpenUnidentifiedEvent :one
SELECT id, company_id, unit_id, eld_device_id, start_at, end_at, distance_m, track_key, status, assigned_driver_id, annotation, resolved_by, resolved_at, created_at, updated_at, edit_request_id FROM unidentified_events
WHERE company_id = $1 AND unit_id = $2 AND end_at IS NULL AND status = 'pending'
ORDER BY start_at DESC
LIMIT 1
`

type TelemetryOpenUnidentifiedEventParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
}

func (q *Queries) TelemetryOpenUnidentifiedEvent(ctx context.Context, arg TelemetryOpenUnidentifiedEventParams) (UnidentifiedEvent, error) {
	row := q.db.QueryRow(ctx, telemetryOpenUnidentifiedEvent, arg.CompanyID, arg.UnitID)
	var i UnidentifiedEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.EldDeviceID,
		&i.StartAt,
		&i.EndAt,
		&i.DistanceM,
		&i.TrackKey,
		&i.Status,
		&i.AssignedDriverID,
		&i.Annotation,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditRequestID,
	)
	return i, err
}

const telemetrySetDeviceHealth = `-- name: TelemetrySetDeviceHealth :one
UPDATE eld_devices SET
  last_seen_at      = $1,
  status            = COALESCE($2::text, status),
  malfunction_codes = COALESCE($3::text[], malfunction_codes),
  firmware          = COALESCE($4::text, firmware)
WHERE company_id = $5 AND id = $6 AND deleted_at IS NULL
RETURNING id, company_id, unit_id, vendor, model, serial, firmware, connection_type, sim_present, last_seen_at, malfunction_codes, status, notes, created_at, updated_at, deleted_at
`

type TelemetrySetDeviceHealthParams struct {
	LastSeenAt       pgtype.Timestamptz
	Status           *string
	MalfunctionCodes []string
	Firmware         *string
	CompanyID        uuid.UUID
	ID               uuid.UUID
}

func (q *Queries) TelemetrySetDeviceHealth(ctx context.Context, arg TelemetrySetDeviceHealthParams) (EldDevice, error) {
	row := q.db.QueryRow(ctx, telemetrySetDeviceHealth,
		arg.LastSeenAt,
		arg.Status,
		arg.MalfunctionCodes,
		arg.Firmware,
		arg.CompanyID,
		arg.ID,
	)
	var i EldDevice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.Firmware,
		&i.ConnectionType,
		&i.SimPresent,
		&i.LastSeenAt,
		&i.MalfunctionCodes,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const trackingCountLiveUnits = `-- name: TrackingCountLiveUnits :one
SELECT count(*) FROM units u
JOIN unit_last_state s ON s.unit_id = u.id AND s.company_id = $1
WHERE u.company_id = $1 AND u.deleted_at IS NULL
  AND ($2::uuid[] IS NULL OR u.id = ANY($2::uuid[]))
  AND ($3::uuid IS NULL OR u.branch_id = $3::uuid)
  AND ($4::text IS NULL OR s.online_status = $4::text)
  AND ($5::bool OR u.status = 'active')
`

type TrackingCountLiveUnitsParams struct {
	CompanyID       uuid.UUID
	UnitIds         []uuid.UUID
	BranchID        pgtype.UUID
	OnlineStatus    *string
	IncludeInactive bool
}

func (q *Queries) TrackingCountLiveUnits(ctx context.Context, arg TrackingCountLiveUnitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, trackingCountLiveUnits,
		arg.CompanyID,
		arg.UnitIds,
		arg.BranchID,
		arg.OnlineStatus,
		arg.IncludeInactive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const trackingCountUnidentifiedEvents = `-- name: TrackingCountUnidentifiedEvents :one
SELECT count(*) FROM unidentified_events e
JOIN units u ON u.id = e.unit_id
WHERE e.company_id = $1
  AND ($2::text IS NULL OR e.status = $2::text)
  AND ($3::uuid IS NULL OR e.unit_id = $3::uuid)
  AND ($4::uuid IS NULL OR u.branch_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR e.start_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR e.start_at < $6::timestamptz)
`

type TrackingCountUnidentifiedEventsParams struct {
	CompanyID uuid.UUID
	Status    *string
	UnitID    pgtype.UUID
	BranchID  pgtype.UUID
	FromAt    pgtype.Timestamptz
	ToAt      pgtype.Timestamptz
}

func (q *Queries) TrackingCountUnidentifiedEvents(ctx context.Context, arg TrackingCountUnidentifiedEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, trackingCountUnidentifiedEvents,
		arg.CompanyID,
		arg.Status,
		arg.UnitID,
		arg.BranchID,
		arg.FromAt,
		arg.ToAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const trackingCountUnitTrips = `-- name: TrackingCountUnitTrips :one
SELECT count(*) FROM trips t
WHERE t.company_id = $1 AND t.unit_id = $2
  AND t.start_at >= $3 AND t.start_at < $4
`

type TrackingCountUnitTripsParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
	FromAt    time.Time
	ToAt      time.Time
}

func (q *Queries) TrackingCountUnitTrips(ctx context.Context, arg TrackingCountUnitTripsParams) (int64, error) {
	row := q.db.QueryRow(ctx, trackingCountUnitTrips,
		arg.CompanyID,
		arg.UnitID,
		arg.FromAt,
		arg.ToAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const trackingGetCompanyTimezone = `-- name: TrackingGetCompanyTimezone :one
SELECT timezone FROM companies WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TrackingGetCompanyTimezone(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, trackingGetCompanyTimezone, id)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const trackingGetTrip = `-- name: TrackingGetTrip :one
SELECT t.id, t.company_id, t.unit_id, t.driver_id, t.start_at, t.end_at, t.start_lat, t.start_lng, t.end_lat, t.end_lng, t.distance_m, t.duration_sec, t.max_speed_kmh, t.polyline_key, t.created_at, t.updated_at, u.unit_number, u.branch_id, ur.first_name, ur.last_name
FROM trips t
JOIN units u        ON u.id = t.unit_id
LEFT JOIN drivers dr ON dr.id = t.driver_id
LEFT JOIN users ur   ON ur.id = dr.user_id
WHERE t.company_id = $1 AND t.id = $2
`

type TrackingGetTripParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type TrackingGetTripRow struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	UnitID      uuid.UUID
	DriverID    pgtype.UUID
	StartAt     time.Time
	EndAt       pgtype.Timestamptz
	StartLat    *float64
	StartLng    *float64
	EndLat      *float64
	EndLng      *float64
	DistanceM   int64
	DurationSec *int32
	MaxSpeedKmh *float64
	PolylineKey *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UnitNumber  string
	BranchID    pgtype.UUID
	FirstName   *string
	LastName    *string
}

func (q *Queries) TrackingGetTrip(ctx context.Context, arg TrackingGetTripParams) (TrackingGetTripRow, error) {
	row := q.db.QueryRow(ctx, trackingGetTrip, arg.CompanyID, arg.ID)
	var i TrackingGetTripRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UnitID,
		&i.DriverID,
		&i.StartAt,
		&i.EndAt,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.DistanceM,
		&i.DurationSec,
		&i.MaxSpeedKmh,
		&i.PolylineKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitNumber,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const trackingGetUnitBrief = `-- name: TrackingGetUnitBrief :one
SELECT u.id, u.unit_number, u.branch_id
FROM units u
WHERE u.company_id = $1 AND u.id = $2 AND u.deleted_at IS NULL
`

type TrackingGetUnitBriefParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type TrackingGetUnitBriefRow struct {
	ID         uuid.UUID
	UnitNumber string
	BranchID   pgtype.UUID
}

func (q *Queries) TrackingGetUnitBrief(ctx context.Context, arg TrackingGetUnitBriefParams) (TrackingGetUnitBriefRow, error) {
	row := q.db.QueryRow(ctx, trackingGetUnitBrief, arg.CompanyID, arg.ID)
	var i TrackingGetUnitBriefRow
	err := row.Scan(&i.ID, &i.UnitNumber, &i.BranchID)
	return i, err
}

const trackingListLiveUnits = `-- name: TrackingListLiveUnits :many

SELECT s.unit_id, s.ts, s.lat, s.lng, s.speed_kmh, s.heading, s.odometer_m,
       s.engine_hours, s.duty_status, s.driver_id, s.online_status, s.updated_at,
       u.unit_number, u.branch_id, u.out_of_service, u.status AS unit_status,
       b.name AS branch_name,
       ur.first_name, ur.last_name,
       d.id AS eld_device_id, d.serial AS eld_device_serial,
       d.status AS eld_device_status, d.malfunction_codes,
       d.last_seen_at AS eld_last_seen_at
FROM units u
JOIN unit_last_state s ON s.unit_id = u.id AND s.company_id = $1
LEFT JOIN branches b   ON b.id = u.branch_id
LEFT JOIN drivers dr   ON dr.id = s.driver_id
LEFT JOIN users ur     ON ur.id = dr.user_id
LEFT JOIN eld_devices d ON d.unit_id = u.id AND d.deleted_at IS NULL
WHERE u.company_id = $1 AND u.deleted_at IS NULL
  AND ($2::uuid[] IS NULL OR u.id = ANY($2::uuid[]))
  AND ($3::uuid IS NULL OR u.branch_id = $3::uuid)
  AND ($4::text IS NULL OR s.online_status = $4::text)
  AND ($5::bool OR u.status = 'active')
ORDER BY u.unit_number
LIMIT $7 OFFSET $6
`

type TrackingListLiveUnitsParams struct {
	CompanyID       uuid.UUID
	UnitIds         []uuid.UUID
	BranchID        pgtype.UUID
	OnlineStatus    *string
	IncludeInactive bool
	Offset          int32
	Limit           int32
}

type TrackingListLiveUnitsRow struct {
	UnitID           uuid.UUID
	Ts               pgtype.Timestamptz
	Lat              *float64
	Lng              *float64
	SpeedKmh         *float64
	Heading          *float64
	OdometerM        *int64
	EngineHours      pgtype.Numeric
	DutyStatus       *string
	DriverID         pgtype.UUID
	OnlineStatus     string
	UpdatedAt        time.Time
	UnitNumber       string
	BranchID         pgtype.UUID
	OutOfService     bool
	UnitStatus       string
	BranchName       *string
	FirstName        *string
	LastName         *string
	EldDeviceID      pgtype.UUID
	EldDeviceSerial  *string
	EldDeviceStatus  *string
	MalfunctionCodes []string
	EldLastSeenAt    pgtype.Timestamptz
}

// ------------------------------------------------------------------- tracking
func (q *Queries) TrackingListLiveUnits(ctx context.Context, arg TrackingListLiveUnitsParams) ([]TrackingListLiveUnitsRow, error) {
	rows, err := q.db.Query(ctx, trackingListLiveUnits,
		arg.CompanyID,
		arg.UnitIds,
		arg.BranchID,
		arg.OnlineStatus,
		arg.IncludeInactive,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingListLiveUnitsRow{}
	for rows.Next() {
		var i TrackingListLiveUnitsRow
		if err := rows.Scan(
			&i.UnitID,
			&i.Ts,
			&i.Lat,
			&i.Lng,
			&i.SpeedKmh,
			&i.Heading,
			&i.OdometerM,
			&i.EngineHours,
			&i.DutyStatus,
			&i.DriverID,
			&i.OnlineStatus,
			&i.UpdatedAt,
			&i.UnitNumber,
			&i.BranchID,
			&i.OutOfService,
			&i.UnitStatus,
			&i.BranchName,
			&i.FirstName,
			&i.LastName,
			&i.EldDeviceID,
			&i.EldDeviceSerial,
			&i.EldDeviceStatus,
			&i.MalfunctionCodes,
			&i.EldLastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackingListTripPoints = `-- name: TrackingListTripPoints :many
SELECT ts, lat, lng, speed_kmh
FROM telemetry
WHERE company_id = $1 AND unit_id = $2
  AND ts >= $3 AND ts <= $4
  AND lat IS NOT NULL AND lng IS NOT NULL
ORDER BY ts
LIMIT $5
`

type TrackingListTripPointsParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
	FromAt    time.Time
	ToAt      time.Time
	Limit     int32
}

type TrackingListTripPointsRow struct {
	Ts       time.Time
	Lat      *float64
	Lng      *float64
	SpeedKmh *float64
}

func (q *Queries) TrackingListTripPoints(ctx context.Context, arg TrackingListTripPointsParams) ([]TrackingListTripPointsRow, error) {
	rows, err := q.db.Query(ctx, trackingListTripPoints,
		arg.CompanyID,
		arg.UnitID,
		arg.FromAt,
		arg.ToAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingListTripPointsRow{}
	for rows.Next() {
		var i TrackingListTripPointsRow
		if err := rows.Scan(
			&i.Ts,
			&i.Lat,
			&i.Lng,
			&i.SpeedKmh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackingListUnidentifiedEvents = `-- name: TrackingListUnidentifiedEvents :many
SELECT e.id, e.company_id, e.unit_id, e.eld_device_id, e.start_at, e.end_at, e.distance_m, e.track_key, e.status, e.assigned_driver_id, e.annotation, e.resolved_by, e.resolved_at, e.created_at, e.updated_at, e.edit_request_id, u.unit_number, u.branch_id
FROM unidentified_events e
JOIN units u ON u.id = e.unit_id
WHERE e.company_id = $1
  AND ($2::text IS NULL OR e.status = $2::text)
  AND ($3::uuid IS NULL OR e.unit_id = $3::uuid)
  AND ($4::uuid IS NULL OR u.branch_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR e.start_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR e.start_at < $6::timestamptz)
ORDER BY e.start_at DESC
LIMIT $8 OFFSET $7
`

type TrackingListUnidentifiedEventsParams struct {
	CompanyID uuid.UUID
	Status    *string
	UnitID    pgtype.UUID
	BranchID  pgtype.UUID
	FromAt    pgtype.Timestamptz
	ToAt      pgtype.Timestamptz
	Offset    int32
	Limit     int32
}

type TrackingListUnidentifiedEventsRow struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	UnitID           uuid.UUID
	EldDeviceID      pgtype.UUID
	StartAt          time.Time
	EndAt            pgtype.Timestamptz
	DistanceM        int64
	TrackKey         *string
	Status           string
	AssignedDriverID pgtype.UUID
	Annotation       *string
	ResolvedBy       pgtype.UUID
	ResolvedAt       pgtype.Timestamptz
	CreatedAt        time.Time
	UpdatedAt        time.Time
	EditRequestID    pgtype.UUID
	UnitNumber       string
	BranchID         pgtype.UUID
}

func (q *Queries) TrackingListUnidentifiedEvents(ctx context.Context, arg TrackingListUnidentifiedEventsParams) ([]TrackingListUnidentifiedEventsRow, error) {
	rows, err := q.db.Query(ctx, trackingListUnidentifiedEvents,
		arg.CompanyID,
		arg.Status,
		arg.UnitID,
		arg.BranchID,
		arg.FromAt,
		arg.ToAt,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingListUnidentifiedEventsRow{}
	for rows.Next() {
		var i TrackingListUnidentifiedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.EldDeviceID,
			&i.StartAt,
			&i.EndAt,
			&i.DistanceM,
			&i.TrackKey,
			&i.Status,
			&i.AssignedDriverID,
			&i.Annotation,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditRequestID,
			&i.UnitNumber,
			&i.BranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackingListUnitTrips = `-- name: TrackingListUnitTrips :many
SELECT t.id, t.company_id, t.unit_id, t.driver_id, t.start_at, t.end_at, t.start_lat, t.start_lng, t.end_lat, t.end_lng, t.distance_m, t.duration_sec, t.max_speed_kmh, t.polyline_key, t.created_at, t.updated_at, u.unit_number, u.branch_id, ur.first_name, ur.last_name
FROM trips t
JOIN units u        ON u.id = t.unit_id
LEFT JOIN drivers dr ON dr.id = t.driver_id
LEFT JOIN users ur   ON ur.id = dr.user_id
WHERE t.company_id = $1 AND t.unit_id = $2
  AND t.start_at >= $3 AND t.start_at < $4
ORDER BY t.start_at
LIMIT $6 OFFSET $5
`

type TrackingListUnitTripsParams struct {
	CompanyID uuid.UUID
	UnitID    uuid.UUID
	FromAt    time.Time
	ToAt      time.Time
	Offset    int32
	Limit     int32
}

type TrackingListUnitTripsRow struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	UnitID      uuid.UUID
	DriverID    pgtype.UUID
	StartAt     time.Time
	EndAt       pgtype.Timestamptz
	StartLat    *float64
	StartLng    *float64
	EndLat      *float64
	EndLng      *float64
	DistanceM   int64
	DurationSec *int32
	MaxSpeedKmh *float64
	PolylineKey *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UnitNumber  string
	BranchID    pgtype.UUID
	FirstName   *string
	LastName    *string
}

func (q *Queries) TrackingListUnitTrips(ctx context.Context, arg TrackingListUnitTripsParams) ([]TrackingListUnitTripsRow, error) {
	rows, err := q.db.Query(ctx, trackingListUnitTrips,
		arg.CompanyID,
		arg.UnitID,
		arg.FromAt,
		arg.ToAt,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingListUnitTripsRow{}
	for rows.Next() {
		var i TrackingListUnitTripsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UnitID,
			&i.DriverID,
			&i.StartAt,
			&i.EndAt,
			&i.StartLat,
			&i.StartLng,
			&i.EndLat,
			&i.EndLng,
			&i.DistanceM,
			&i.DurationSec,
			&i.MaxSpeedKmh,
			&i.PolylineKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitNumber,
			&i.BranchID,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
