// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trailers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countTrailers = `-- name: CountTrailers :one
SELECT count(*) FROM trailers
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR number ILIKE '%' || $2::text || '%')
`

type CountTrailersParams struct {
	CompanyID uuid.UUID
	Column2   string
}

func (q *Queries) CountTrailers(ctx context.Context, arg CountTrailersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTrailers, arg.CompanyID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrailer = `-- name: CreateTrailer :one
INSERT INTO trailers (company_id, number, notes) VALUES ($1,$2,$3) RETURNING id, company_id, number, notes, created_at, updated_at, deleted_at
`

type CreateTrailerParams struct {
	CompanyID uuid.UUID
	Number    string
	Notes     *string
}

func (q *Queries) CreateTrailer(ctx context.Context, arg CreateTrailerParams) (Trailer, error) {
	row := q.db.QueryRow(ctx, createTrailer, arg.CompanyID, arg.Number, arg.Notes)
	var i Trailer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTrailer = `-- name: GetTrailer :one
SELECT id, company_id, number, notes, created_at, updated_at, deleted_at FROM trailers WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetTrailerParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetTrailer(ctx context.Context, arg GetTrailerParams) (Trailer, error) {
	row := q.db.QueryRow(ctx, getTrailer, arg.CompanyID, arg.ID)
	var i Trailer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTrailers = `-- name: ListTrailers :many
SELECT id, company_id, number, notes, created_at, updated_at, deleted_at FROM trailers
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR number ILIKE '%' || $2::text || '%')
ORDER BY number LIMIT $3 OFFSET $4
`

type ListTrailersParams struct {
	CompanyID uuid.UUID
	Column2   string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListTrailers(ctx context.Context, arg ListTrailersParams) ([]Trailer, error) {
	rows, err := q.db.Query(ctx, listTrailers,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trailer{}
	for rows.Next() {
		var i Trailer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrailersByIDs = `-- name: ListTrailersByIDs :many
SELECT id, company_id, number, notes, created_at, updated_at, deleted_at FROM trailers WHERE company_id = $1 AND id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type ListTrailersByIDsParams struct {
	CompanyID uuid.UUID
	Column2   []uuid.UUID
}

func (q *Queries) ListTrailersByIDs(ctx context.Context, arg ListTrailersByIDsParams) ([]Trailer, error) {
	rows, err := q.db.Query(ctx, listTrailersByIDs, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trailer{}
	for rows.Next() {
		var i Trailer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTrailer = `-- name: SoftDeleteTrailer :exec
UPDATE trailers SET deleted_at = now() WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteTrailerParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteTrailer(ctx context.Context, arg SoftDeleteTrailerParams) error {
	_, err := q.db.Exec(ctx, softDeleteTrailer, arg.CompanyID, arg.ID)
	return err
}

const updateTrailer = `-- name: UpdateTrailer :one
UPDATE trailers SET number = COALESCE($3::text, number), notes = COALESCE($4::text, notes)
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL RETURNING id, company_id, number, notes, created_at, updated_at, deleted_at
`

type UpdateTrailerParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
	Column3   string
	Column4   string
}

func (q *Queries) UpdateTrailer(ctx context.Context, arg UpdateTrailerParams) (Trailer, error) {
	row := q.db.QueryRow(ctx, updateTrailer,
		arg.CompanyID,
		arg.ID,
		arg.Column3,
		arg.Column4,
	)
	var i Trailer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
