// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompanyAdministrators = `-- name: CountCompanyAdministrators :one
SELECT count(*) FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.company_id = $1::uuid
  AND u.deleted_at IS NULL
  AND u.status = 'active'
  AND r.is_system
  AND lower(r.name) = 'administrator'
  AND u.id <> $2::uuid
`

type CountCompanyAdministratorsParams struct {
	CompanyID     uuid.UUID
	ExcludeUserID uuid.UUID
}

// Q81: oxirgi Administrator o'chirilmaydi/deaktivatsiya qilinmaydi.
func (q *Queries) CountCompanyAdministrators(ctx context.Context, arg CountCompanyAdministratorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanyAdministrators, arg.CompanyID, arg.ExcludeUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users u
WHERE u.company_id = $1::uuid
  AND u.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (u.first_name || ' ' || u.last_name || ' ' || u.username || ' ' || coalesce(u.email, '') || ' ' || coalesce(u.phone, ''))
          ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR u.status = $3::text)
  AND ($4::uuid IS NULL OR u.role_id = $4::uuid)
  AND ($5::uuid IS NULL OR u.branch_id = $5::uuid)
`

type CountUsersParams struct {
	CompanyID uuid.UUID
	Search    *string
	Status    *string
	RoleID    pgtype.UUID
	BranchID  pgtype.UUID
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers,
		arg.CompanyID,
		arg.Search,
		arg.Status,
		arg.RoleID,
		arg.BranchID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  company_id, branch_id, first_name, last_name, email, phone,
  username, password_hash, role_id, status, invited_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id
`

type CreateUserParams struct {
	CompanyID    pgtype.UUID
	BranchID     pgtype.UUID
	FirstName    string
	LastName     string
	Email        *string
	Phone        *string
	Username     string
	PasswordHash *string
	RoleID       uuid.UUID
	Status       string
	InvitedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.CompanyID,
		arg.BranchID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Username,
		arg.PasswordHash,
		arg.RoleID,
		arg.Status,
		arg.InvitedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.RecoveryCodes,
		&i.PinHash,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TelegramChatID,
	)
	return i, err
}

const findExistingEmails = `-- name: FindExistingEmails :many
SELECT lower(email)::text AS email FROM users
WHERE company_id = $1::uuid AND deleted_at IS NULL AND email IS NOT NULL
  AND lower(email) = ANY($2::text[])
`

type FindExistingEmailsParams struct {
	CompanyID uuid.UUID
	Emails    []string
}

func (q *Queries) FindExistingEmails(ctx context.Context, arg FindExistingEmailsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, findExistingEmails, arg.CompanyID, arg.Emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExistingUsernames = `-- name: FindExistingUsernames :many
SELECT lower(username)::text AS username FROM users
WHERE company_id = $1::uuid AND deleted_at IS NULL
  AND lower(username) = ANY($2::text[])
`

type FindExistingUsernamesParams struct {
	CompanyID uuid.UUID
	Usernames []string
}

// Import oldidan (all-or-nothing) mavjud username'larni bir so'rovda tekshirish.
func (q *Queries) FindExistingUsernames(ctx context.Context, arg FindExistingUsernamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, findExistingUsernames, arg.CompanyID, arg.Usernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUsersByLogin = `-- name: FindUsersByLogin :many
SELECT id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id FROM users
WHERE deleted_at IS NULL
  AND (lower(username) = lower($1::text)
       OR lower(email) = lower($1::text))
ORDER BY created_at
LIMIT 10
`

// Login oldidan (autentifikatsiyasiz) username yoki email bo'yicha nomzodlar.
// Bir nechta kompaniyada bir xil username bo'lsa, xizmat qatlami
// `company_id` bilan aniqlashtiradi; aniqlanmasa INVALID_CREDENTIALS.
func (q *Queries) FindUsersByLogin(ctx context.Context, login string) ([]User, error) {
	rows, err := q.db.Query(ctx, findUsersByLogin, login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BranchID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Username,
			&i.PasswordHash,
			&i.RoleID,
			&i.Status,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.RecoveryCodes,
			&i.PinHash,
			&i.InvitedAt,
			&i.ActivatedAt,
			&i.LastLoginAt,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TelegramChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id FROM users WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetUserParams struct {
	CompanyID pgtype.UUID
	ID        uuid.UUID
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.CompanyID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.RecoveryCodes,
		&i.PinHash,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TelegramChatID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id FROM users
WHERE lower(email) = lower($1::text) AND company_id = $2 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	Column1   string
	CompanyID pgtype.UUID
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Column1, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.RecoveryCodes,
		&i.PinHash,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TelegramChatID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.RecoveryCodes,
		&i.PinHash,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TelegramChatID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id FROM users
WHERE lower(username) = lower($1::text)
  AND (($2::uuid IS NULL AND company_id IS NULL)
       OR company_id = $2::uuid)
  AND deleted_at IS NULL
`

type GetUserByUsernameParams struct {
	Username  string
	CompanyID pgtype.UUID
}

// company_id NULL -> super admin (company_id IS NULL) yozuvi qidiriladi.
func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, arg.Username, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.RecoveryCodes,
		&i.PinHash,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TelegramChatID,
	)
	return i, err
}

const getUserDetail = `-- name: GetUserDetail :one
SELECT
  u.id, u.company_id, u.branch_id, u.first_name, u.last_name, u.email, u.phone, u.username, u.password_hash, u.role_id, u.status, u.totp_secret_enc, u.totp_enabled, u.recovery_codes, u.pin_hash, u.invited_at, u.activated_at, u.last_login_at, u.failed_logins, u.locked_until, u.created_at, u.updated_at, u.deleted_at, u.telegram_chat_id,
  r.name      AS role_name,
  r.scope     AS role_scope,
  r.is_system AS role_is_system,
  b.name      AS branch_name
FROM users u
JOIN roles r ON r.id = u.role_id
LEFT JOIN branches b ON b.id = u.branch_id
WHERE u.company_id = $1::uuid
  AND u.id = $2::uuid
  AND u.deleted_at IS NULL
`

type GetUserDetailParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetUserDetailRow struct {
	ID             uuid.UUID
	CompanyID      pgtype.UUID
	BranchID       pgtype.UUID
	FirstName      string
	LastName       string
	Email          *string
	Phone          *string
	Username       string
	PasswordHash   *string
	RoleID         uuid.UUID
	Status         string
	TotpSecretEnc  *string
	TotpEnabled    bool
	RecoveryCodes  []string
	PinHash        *string
	InvitedAt      pgtype.Timestamptz
	ActivatedAt    pgtype.Timestamptz
	LastLoginAt    pgtype.Timestamptz
	FailedLogins   int32
	LockedUntil    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
	TelegramChatID *string
	RoleName       string
	RoleScope      string
	RoleIsSystem   bool
	BranchName     *string
}

// Bitta foydalanuvchi + rol/filial nomlari. Cross-tenant -> qator yo'q -> 404.
func (q *Queries) GetUserDetail(ctx context.Context, arg GetUserDetailParams) (GetUserDetailRow, error) {
	row := q.db.QueryRow(ctx, getUserDetail, arg.CompanyID, arg.ID)
	var i GetUserDetailRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.RecoveryCodes,
		&i.PinHash,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TelegramChatID,
		&i.RoleName,
		&i.RoleScope,
		&i.RoleIsSystem,
		&i.BranchName,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
  u.id, u.company_id, u.branch_id, u.first_name, u.last_name, u.email, u.phone, u.username, u.password_hash, u.role_id, u.status, u.totp_secret_enc, u.totp_enabled, u.recovery_codes, u.pin_hash, u.invited_at, u.activated_at, u.last_login_at, u.failed_logins, u.locked_until, u.created_at, u.updated_at, u.deleted_at, u.telegram_chat_id,
  r.name      AS role_name,
  r.scope     AS role_scope,
  r.is_system AS role_is_system,
  b.name      AS branch_name
FROM users u
JOIN roles r ON r.id = u.role_id
LEFT JOIN branches b ON b.id = u.branch_id
WHERE u.company_id = $1::uuid
  AND u.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (u.first_name || ' ' || u.last_name || ' ' || u.username || ' ' || coalesce(u.email, '') || ' ' || coalesce(u.phone, ''))
          ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR u.status = $3::text)
  AND ($4::uuid IS NULL OR u.role_id = $4::uuid)
  AND ($5::uuid IS NULL OR u.branch_id = $5::uuid)
ORDER BY
  CASE WHEN $6::text = 'last_name'  AND NOT $7::bool THEN lower(u.last_name)  END ASC  NULLS LAST,
  CASE WHEN $6::text = 'last_name'  AND     $7::bool THEN lower(u.last_name)  END DESC NULLS LAST,
  CASE WHEN $6::text = 'first_name' AND NOT $7::bool THEN lower(u.first_name) END ASC  NULLS LAST,
  CASE WHEN $6::text = 'first_name' AND     $7::bool THEN lower(u.first_name) END DESC NULLS LAST,
  CASE WHEN $6::text = 'username'   AND NOT $7::bool THEN lower(u.username)   END ASC  NULLS LAST,
  CASE WHEN $6::text = 'username'   AND     $7::bool THEN lower(u.username)   END DESC NULLS LAST,
  CASE WHEN $6::text = 'email'      AND NOT $7::bool THEN lower(u.email)      END ASC  NULLS LAST,
  CASE WHEN $6::text = 'email'      AND     $7::bool THEN lower(u.email)      END DESC NULLS LAST,
  CASE WHEN $6::text = 'status'     AND NOT $7::bool THEN u.status            END ASC  NULLS LAST,
  CASE WHEN $6::text = 'status'     AND     $7::bool THEN u.status            END DESC NULLS LAST,
  CASE WHEN $6::text = 'created_at' AND NOT $7::bool THEN u.created_at        END ASC  NULLS LAST,
  CASE WHEN $6::text = 'created_at' AND     $7::bool THEN u.created_at        END DESC NULLS LAST,
  lower(u.last_name), lower(u.first_name), u.id
LIMIT $9::int OFFSET $8::int
`

type ListUsersParams struct {
	CompanyID  uuid.UUID
	Search     *string
	Status     *string
	RoleID     pgtype.UUID
	BranchID   pgtype.UUID
	SortKey    string
	SortDesc   bool
	PageOffset int32
	PageLimit  int32
}

type ListUsersRow struct {
	ID             uuid.UUID
	CompanyID      pgtype.UUID
	BranchID       pgtype.UUID
	FirstName      string
	LastName       string
	Email          *string
	Phone          *string
	Username       string
	PasswordHash   *string
	RoleID         uuid.UUID
	Status         string
	TotpSecretEnc  *string
	TotpEnabled    bool
	RecoveryCodes  []string
	PinHash        *string
	InvitedAt      pgtype.Timestamptz
	ActivatedAt    pgtype.Timestamptz
	LastLoginAt    pgtype.Timestamptz
	FailedLogins   int32
	LockedUntil    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
	TelegramChatID *string
	RoleName       string
	RoleScope      string
	RoleIsSystem   bool
	BranchName     *string
}

// Ro'yxat: filtr + saralash oq ro'yxati (CASE -> string konkatenatsiyasi yo'q).
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.CompanyID,
		arg.Search,
		arg.Status,
		arg.RoleID,
		arg.BranchID,
		arg.SortKey,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BranchID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Username,
			&i.PasswordHash,
			&i.RoleID,
			&i.Status,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.RecoveryCodes,
			&i.PinHash,
			&i.InvitedAt,
			&i.ActivatedAt,
			&i.LastLoginAt,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TelegramChatID,
			&i.RoleName,
			&i.RoleScope,
			&i.RoleIsSystem,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id FROM users WHERE company_id = $1 AND role_id = ANY($2::uuid[]) AND status = 'active' AND deleted_at IS NULL
`

type ListUsersByRoleParams struct {
	CompanyID pgtype.UUID
	Column2   []uuid.UUID
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BranchID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Username,
			&i.PasswordHash,
			&i.RoleID,
			&i.Status,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.RecoveryCodes,
			&i.PinHash,
			&i.InvitedAt,
			&i.ActivatedAt,
			&i.LastLoginAt,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TelegramChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserLoginFailure = `-- name: MarkUserLoginFailure :one
UPDATE users SET failed_logins = failed_logins + 1,
                 locked_until = CASE WHEN failed_logins + 1 >= $2::int THEN now() + ($3::int || ' minutes')::interval ELSE locked_until END
WHERE id = $1
RETURNING failed_logins, locked_until
`

type MarkUserLoginFailureParams struct {
	ID      uuid.UUID
	Column2 int32
	Column3 int32
}

type MarkUserLoginFailureRow struct {
	FailedLogins int32
	LockedUntil  pgtype.Timestamptz
}

func (q *Queries) MarkUserLoginFailure(ctx context.Context, arg MarkUserLoginFailureParams) (MarkUserLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, markUserLoginFailure, arg.ID, arg.Column2, arg.Column3)
	var i MarkUserLoginFailureRow
	err := row.Scan(&i.FailedLogins, &i.LockedUntil)
	return i, err
}

const markUserLoginSuccess = `-- name: MarkUserLoginSuccess :exec
UPDATE users SET last_login_at = now(), failed_logins = 0, locked_until = NULL WHERE id = $1
`

func (q *Queries) MarkUserLoginSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserLoginSuccess, id)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, status = 'active', activated_at = COALESCE(activated_at, now()),
                 failed_logins = 0, locked_until = NULL
WHERE id = $1 AND deleted_at IS NULL
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserPin = `-- name: SetUserPin :exec
UPDATE users SET pin_hash = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetUserPinParams struct {
	ID      uuid.UUID
	PinHash *string
}

func (q *Queries) SetUserPin(ctx context.Context, arg SetUserPinParams) error {
	_, err := q.db.Exec(ctx, setUserPin, arg.ID, arg.PinHash)
	return err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users SET
  status       = $1::text,
  activated_at = CASE WHEN $1::text = 'active' THEN COALESCE(activated_at, now()) ELSE activated_at END
WHERE company_id = $2::uuid AND id = $3::uuid AND deleted_at IS NULL
RETURNING id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id
`

type SetUserStatusParams struct {
	Status    string
	CompanyID uuid.UUID
	ID        uuid.UUID
}

// Q1: active <-> inactive qaytariladigan o'tish.
func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.Status, arg.CompanyID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.RecoveryCodes,
		&i.PinHash,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TelegramChatID,
	)
	return i, err
}

const setUserTotp = `-- name: SetUserTotp :exec
UPDATE users SET totp_secret_enc = $2, totp_enabled = $3, recovery_codes = $4
WHERE id = $1 AND deleted_at IS NULL
`

type SetUserTotpParams struct {
	ID            uuid.UUID
	TotpSecretEnc *string
	TotpEnabled   bool
	RecoveryCodes []string
}

func (q *Queries) SetUserTotp(ctx context.Context, arg SetUserTotpParams) error {
	_, err := q.db.Exec(ctx, setUserTotp,
		arg.ID,
		arg.TotpSecretEnc,
		arg.TotpEnabled,
		arg.RecoveryCodes,
	)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now(), status = 'inactive'
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	CompanyID pgtype.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.CompanyID, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  first_name = COALESCE($1::text, first_name),
  last_name  = COALESCE($2::text, last_name),
  email      = COALESCE($3::text, email),
  phone      = COALESCE($4::text, phone),
  username   = COALESCE($5::text, username),
  role_id    = COALESCE($6::uuid, role_id),
  branch_id  = CASE WHEN $7::bool THEN NULL
                    ELSE COALESCE($8::uuid, branch_id) END
WHERE company_id = $9::uuid AND id = $10::uuid AND deleted_at IS NULL
RETURNING id, company_id, branch_id, first_name, last_name, email, phone, username, password_hash, role_id, status, totp_secret_enc, totp_enabled, recovery_codes, pin_hash, invited_at, activated_at, last_login_at, failed_logins, locked_until, created_at, updated_at, deleted_at, telegram_chat_id
`

type UpdateUserParams struct {
	FirstName   *string
	LastName    *string
	Email       *string
	Phone       *string
	Username    *string
	RoleID      pgtype.UUID
	ClearBranch bool
	BranchID    pgtype.UUID
	CompanyID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Username,
		arg.RoleID,
		arg.ClearBranch,
		arg.BranchID,
		arg.CompanyID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.RoleID,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.RecoveryCodes,
		&i.PinHash,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TelegramChatID,
	)
	return i, err
}
