// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: violations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countViolations = `-- name: CountViolations :one
SELECT count(*) FROM violations v
WHERE v.company_id = $1
  AND ($2::uuid IS NULL OR v.driver_id = $2::uuid)
  AND ($3::text IS NULL OR v.type = $3::text)
  AND ($4::text IS NULL OR v.severity = $4::text)
  AND ($5::timestamptz IS NULL OR v.occurred_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR v.occurred_at < $6::timestamptz)
`

type CountViolationsParams struct {
	CompanyID uuid.UUID
	Column2   uuid.UUID
	Column3   string
	Column4   string
	Column5   time.Time
	Column6   time.Time
}

func (q *Queries) CountViolations(ctx context.Context, arg CountViolationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countViolations,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createViolation = `-- name: CreateViolation :one
INSERT INTO violations (
  company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id, resolved_at, resolved_reason, created_at, updated_at, unidentified_event_id, resolved_by
`

type CreateViolationParams struct {
	CompanyID       uuid.UUID
	DriverID        pgtype.UUID
	UnitID          pgtype.UUID
	DailyLogID      pgtype.UUID
	Type            string
	Severity        string
	OccurredAt      time.Time
	Details         []byte
	PolicyVersionID pgtype.UUID
}

func (q *Queries) CreateViolation(ctx context.Context, arg CreateViolationParams) (Violation, error) {
	row := q.db.QueryRow(ctx, createViolation,
		arg.CompanyID,
		arg.DriverID,
		arg.UnitID,
		arg.DailyLogID,
		arg.Type,
		arg.Severity,
		arg.OccurredAt,
		arg.Details,
		arg.PolicyVersionID,
	)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.DailyLogID,
		&i.Type,
		&i.Severity,
		&i.OccurredAt,
		&i.Details,
		&i.PolicyVersionID,
		&i.ResolvedAt,
		&i.ResolvedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnidentifiedEventID,
		&i.ResolvedBy,
	)
	return i, err
}

const getViolation = `-- name: GetViolation :one
SELECT id, company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id, resolved_at, resolved_reason, created_at, updated_at, unidentified_event_id, resolved_by FROM violations WHERE company_id = $1 AND id = $2
`

type GetViolationParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetViolation(ctx context.Context, arg GetViolationParams) (Violation, error) {
	row := q.db.QueryRow(ctx, getViolation, arg.CompanyID, arg.ID)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.DailyLogID,
		&i.Type,
		&i.Severity,
		&i.OccurredAt,
		&i.Details,
		&i.PolicyVersionID,
		&i.ResolvedAt,
		&i.ResolvedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnidentifiedEventID,
		&i.ResolvedBy,
	)
	return i, err
}

const listViolations = `-- name: ListViolations :many
SELECT v.id, v.company_id, v.driver_id, v.unit_id, v.daily_log_id, v.type, v.severity, v.occurred_at, v.details, v.policy_version_id, v.resolved_at, v.resolved_reason, v.created_at, v.updated_at, v.unidentified_event_id, v.resolved_by, u.first_name, u.last_name
FROM violations v
JOIN drivers d ON d.id = v.driver_id
JOIN users   u ON u.id = d.user_id
WHERE v.company_id = $1
  AND ($2::uuid IS NULL OR v.driver_id = $2::uuid)
  AND ($3::text IS NULL OR v.type = $3::text)
  AND ($4::text IS NULL OR v.severity = $4::text)
  AND ($5::timestamptz IS NULL OR v.occurred_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR v.occurred_at < $6::timestamptz)
ORDER BY v.occurred_at DESC
LIMIT $7 OFFSET $8
`

type ListViolationsParams struct {
	CompanyID uuid.UUID
	Column2   uuid.UUID
	Column3   string
	Column4   string
	Column5   time.Time
	Column6   time.Time
	Limit     int32
	Offset    int32
}

type ListViolationsRow struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	DriverID            pgtype.UUID
	UnitID              pgtype.UUID
	DailyLogID          pgtype.UUID
	Type                string
	Severity            string
	OccurredAt          time.Time
	Details             []byte
	PolicyVersionID     pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	ResolvedReason      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	UnidentifiedEventID pgtype.UUID
	ResolvedBy          pgtype.UUID
	FirstName           string
	LastName            string
}

func (q *Queries) ListViolations(ctx context.Context, arg ListViolationsParams) ([]ListViolationsRow, error) {
	rows, err := q.db.Query(ctx, listViolations,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListViolationsRow{}
	for rows.Next() {
		var i ListViolationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.DailyLogID,
			&i.Type,
			&i.Severity,
			&i.OccurredAt,
			&i.Details,
			&i.PolicyVersionID,
			&i.ResolvedAt,
			&i.ResolvedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnidentifiedEventID,
			&i.ResolvedBy,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViolationsByDailyLog = `-- name: ListViolationsByDailyLog :many
SELECT id, company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id, resolved_at, resolved_reason, created_at, updated_at, unidentified_event_id, resolved_by FROM violations WHERE company_id = $1 AND daily_log_id = $2 ORDER BY occurred_at
`

type ListViolationsByDailyLogParams struct {
	CompanyID  uuid.UUID
	DailyLogID pgtype.UUID
}

func (q *Queries) ListViolationsByDailyLog(ctx context.Context, arg ListViolationsByDailyLogParams) ([]Violation, error) {
	rows, err := q.db.Query(ctx, listViolationsByDailyLog, arg.CompanyID, arg.DailyLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Violation{}
	for rows.Next() {
		var i Violation
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DriverID,
			&i.UnitID,
			&i.DailyLogID,
			&i.Type,
			&i.Severity,
			&i.OccurredAt,
			&i.Details,
			&i.PolicyVersionID,
			&i.ResolvedAt,
			&i.ResolvedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnidentifiedEventID,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveViolation = `-- name: ResolveViolation :one
UPDATE violations SET resolved_at = now(), resolved_reason = $3
WHERE company_id = $1 AND id = $2 AND resolved_at IS NULL RETURNING id, company_id, driver_id, unit_id, daily_log_id, type, severity, occurred_at, details, policy_version_id, resolved_at, resolved_reason, created_at, updated_at, unidentified_event_id, resolved_by
`

type ResolveViolationParams struct {
	CompanyID      uuid.UUID
	ID             uuid.UUID
	ResolvedReason *string
}

func (q *Queries) ResolveViolation(ctx context.Context, arg ResolveViolationParams) (Violation, error) {
	row := q.db.QueryRow(ctx, resolveViolation, arg.CompanyID, arg.ID, arg.ResolvedReason)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DriverID,
		&i.UnitID,
		&i.DailyLogID,
		&i.Type,
		&i.Severity,
		&i.OccurredAt,
		&i.Details,
		&i.PolicyVersionID,
		&i.ResolvedAt,
		&i.ResolvedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnidentifiedEventID,
		&i.ResolvedBy,
	)
	return i, err
}

const summarizeViolationsByType = `-- name: SummarizeViolationsByType :many
SELECT type, severity, count(*) AS total
FROM violations
WHERE company_id = $1 AND occurred_at >= $2 AND occurred_at < $3
GROUP BY type, severity
ORDER BY total DESC
`

type SummarizeViolationsByTypeParams struct {
	CompanyID    uuid.UUID
	OccurredAt   time.Time
	OccurredAt_2 time.Time
}

type SummarizeViolationsByTypeRow struct {
	Type     string
	Severity string
	Total    int64
}

func (q *Queries) SummarizeViolationsByType(ctx context.Context, arg SummarizeViolationsByTypeParams) ([]SummarizeViolationsByTypeRow, error) {
	rows, err := q.db.Query(ctx, summarizeViolationsByType, arg.CompanyID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeViolationsByTypeRow{}
	for rows.Next() {
		var i SummarizeViolationsByTypeRow
		if err := rows.Scan(&i.Type, &i.Severity, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
