//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_import

import 'package:one_of_serializer/any_of_serializer.dart';
import 'package:one_of_serializer/one_of_serializer.dart';
import 'package:built_collection/built_collection.dart';
import 'package:built_value/json_object.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';
import 'package:built_value/iso_8601_date_time_serializer.dart';
import 'package:eld_api/src/date_serializer.dart';
import 'package:eld_api/src/model/date.dart';

import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auditlog_dto_entry.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auditlog_dto_entry_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auditlog_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auditlog_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auditlog_dto_table_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_app_config.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_app_config_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_invitation_accept_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_login_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_login_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_login_result.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_logout_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_message_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_message_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_pin_verified.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_pin_verified_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_pin_verify_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_password_forgot_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_password_reset_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_profile.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_profile_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_refresh_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_session.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_session_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_totp_setup.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_totp_setup_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_totp_verified.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_totp_verified_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_totp_verify_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_tokens.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_auth_dto_tokens_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_cursor_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_message.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_message_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_message_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_message_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_read_result.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_read_result_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_thread.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_chat_dto_thread_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_admin_company_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_admin_company_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_administrator_invite.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_company.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_company_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_company_created.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_company_created_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_company_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_companies_dto_subscription_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_branch.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_branch_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_branch_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_branch_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_branch_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_company.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_company_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_company_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_history_entry.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_history_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_hos_policy.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_hos_policy_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_hos_policy_doc.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_hos_policy_doc_input.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_hos_policy_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_notification_setting.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_notification_setting_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_notification_settings_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_notification_settings_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_settings.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_warning_thresholds.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_company_dto_warning_thresholds_input.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dashboard_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dashboard_dto_kpi.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dashboard_dto_route.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dashboard_dto_status_block.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dashboard_dto_summary.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dashboard_dto_summary_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dashboard_dto_window.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_activity.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_activity_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_co_driver.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_co_driver_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_co_driver_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_driver.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_driver_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_driver_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_driver_license.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_driver_license_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_driver_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_driver_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_reset_password_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_reset_password_result.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_drivers_dto_status_change.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_counters.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_day_totals.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_duty_status_event.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_duty_status_event_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_hos_summary.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_hos_summary_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_recap_day.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_duty_dto_violation.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_defect.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_defect_input.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_defect_type.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_defect_type_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_defect_type_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_defect_type_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_defect_type_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_driver_brief.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_dvir_certify.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_dvir_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_dvir_repair.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_dvir_report.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_dvir_report_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_dvir_report_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_dvir_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_files_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_files_dto_import_result.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_files_dto_import_result_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_files_dto_import_row_error.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_files_dto_presign_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_files_dto_presign_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_files_dto_presign_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_catalog_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_catalog_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_eld_device.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_eld_device_assign_unit.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_eld_device_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_eld_device_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_eld_device_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_eld_device_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_malfunction_code.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_shipping_document.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_shipping_document_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_shipping_document_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_trailer.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_trailer_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_trailer_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_assign_driver.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_assignment.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_assignment_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_diagnostics.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_diagnostics_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_history_entry.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_history_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_telemetry.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_fleet_dto_unit_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_certify_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_daily_log_detail.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_daily_log_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_daily_log_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_daily_log_summary.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_day_totals.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_inspection_email.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_inspection_report.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_inspection_report_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_inspection_session.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_inspection_session_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_inspection_transfer.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_inspection_transfer_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_inspection_transfer_result.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_edit_change.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_edit_reject.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_edit_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_edit_request_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_edit_request_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_edit_request_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_event.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_event_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_log_form.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_message_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_number_ref.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_uncertified_log.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_uncertified_log_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_unidentified_annotate.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_unidentified_assign.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_unidentified_event.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_unidentified_event_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_unit_ref.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_violation.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_violation_details.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_violation_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_logs_dto_violation_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_cancel_input.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_complete_input.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_record.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_record_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule_unit.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule_unit_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule_unit_input.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule_unit_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_maintenance_dto_schedule_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_list_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_notification.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_notification_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_push_token.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_push_token_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_push_token_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_read_result.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_notifications_dto_read_result_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_activity_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_activity_row.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_distance_by_region_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_distance_by_region_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_export_job.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_export_job_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_export_job_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_export_job_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_export_params.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_reports_dto_region_distance_row.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_directions.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_directions_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_route.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_route_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_route_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_route_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_route_not_completed.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_route_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_waypoint.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_routes_dto_waypoint_input.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_feedback.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_feedback_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_feedback_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_feedback_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket_message.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket_message_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket_message_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket_message_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_support_dto_ticket_status_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_chat_message.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_chat_push.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_clock.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_clock_verdict.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_daily_log_summary.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_defect_type.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_duty_status_event.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_dvir_push.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_element_result.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_event_push.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_hos_policy.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_log_edit_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_pull_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_pull_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_push_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_push_request.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_push_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_telemetry_point.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_telemetry_result.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_sync_dto_unidentified_event.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_driver_brief.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_live_unit.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_live_unit_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_trip.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_trip_detail.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_trip_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_trip_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_unidentified_event.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_tracking_dto_unidentified_event_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_error_response.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_invitation_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_invitation_sent.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_meta.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_permission.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_permission_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_permission_module.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_role.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_role_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_role_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_role_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_role_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_user.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_user_create.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_user_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_user_list_envelope.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_user_role.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_domain_users_dto_user_update.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_httpx_dto_error_body.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_httpx_dto_field_error.dart';
import 'package:eld_api/src/model/github_com_devline_onebook_eld_internal_httpx_dto_message_response.dart';

part 'serializers.g.dart';

@SerializersFor([
  GithubComDevlineOnebookEldInternalDomainAuditlogDtoEntry,
  GithubComDevlineOnebookEldInternalDomainAuditlogDtoEntryListEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuditlogDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainAuditlogDtoMeta,
  GithubComDevlineOnebookEldInternalDomainAuditlogDtoTableListEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoAppConfig,
  GithubComDevlineOnebookEldInternalDomainAuthDtoAppConfigEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainAuthDtoInvitationAcceptRequest,
  GithubComDevlineOnebookEldInternalDomainAuthDtoLoginEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoLoginRequest,
  GithubComDevlineOnebookEldInternalDomainAuthDtoLoginResult,
  GithubComDevlineOnebookEldInternalDomainAuthDtoLogoutRequest,
  GithubComDevlineOnebookEldInternalDomainAuthDtoMessageEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoMessageResponse,
  GithubComDevlineOnebookEldInternalDomainAuthDtoMeta,
  GithubComDevlineOnebookEldInternalDomainAuthDtoPINVerified,
  GithubComDevlineOnebookEldInternalDomainAuthDtoPINVerifiedEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoPINVerifyRequest,
  GithubComDevlineOnebookEldInternalDomainAuthDtoPasswordForgotRequest,
  GithubComDevlineOnebookEldInternalDomainAuthDtoPasswordResetRequest,
  GithubComDevlineOnebookEldInternalDomainAuthDtoProfile,
  GithubComDevlineOnebookEldInternalDomainAuthDtoProfileEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoRefreshRequest,
  GithubComDevlineOnebookEldInternalDomainAuthDtoSession,
  GithubComDevlineOnebookEldInternalDomainAuthDtoSessionListEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoTOTPSetup,
  GithubComDevlineOnebookEldInternalDomainAuthDtoTOTPSetupEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoTOTPVerified,
  GithubComDevlineOnebookEldInternalDomainAuthDtoTOTPVerifiedEnvelope,
  GithubComDevlineOnebookEldInternalDomainAuthDtoTOTPVerifyRequest,
  GithubComDevlineOnebookEldInternalDomainAuthDtoTokens,
  GithubComDevlineOnebookEldInternalDomainAuthDtoTokensEnvelope,
  GithubComDevlineOnebookEldInternalDomainChatDtoCursorMeta,
  GithubComDevlineOnebookEldInternalDomainChatDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainChatDtoMessage,
  GithubComDevlineOnebookEldInternalDomainChatDtoMessageCreate,
  GithubComDevlineOnebookEldInternalDomainChatDtoMessageEnvelope,
  GithubComDevlineOnebookEldInternalDomainChatDtoMessageListEnvelope,
  GithubComDevlineOnebookEldInternalDomainChatDtoMeta,
  GithubComDevlineOnebookEldInternalDomainChatDtoReadResult,
  GithubComDevlineOnebookEldInternalDomainChatDtoReadResultEnvelope,
  GithubComDevlineOnebookEldInternalDomainChatDtoThread,
  GithubComDevlineOnebookEldInternalDomainChatDtoThreadListEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoAdminCompanyEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoAdminCompanyListEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoAdministratorInvite,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoCompany,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoCompanyCreate,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoCompanyCreated,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoCompanyCreatedEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoCompanyUpdate,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoMeta,
  GithubComDevlineOnebookEldInternalDomainCompaniesDtoSubscriptionUpdate,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoBranch,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoBranchCreate,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoBranchEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoBranchListEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoBranchUpdate,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoCompany,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoCompanyEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoCompanyUpdate,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoHistoryEntry,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoHistoryListEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoHosPolicy,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoHosPolicyCreate,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoHosPolicyDoc,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoHosPolicyDocInput,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoHosPolicyEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoMeta,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoNotificationSetting,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoNotificationSettingUpdate,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoNotificationSettingsEnvelope,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoNotificationSettingsUpdate,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoSettings,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoWarningThresholds,
  GithubComDevlineOnebookEldInternalDomainCompanyDtoWarningThresholdsInput,
  GithubComDevlineOnebookEldInternalDomainDashboardDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainDashboardDtoKPI,
  GithubComDevlineOnebookEldInternalDomainDashboardDtoRoute,
  GithubComDevlineOnebookEldInternalDomainDashboardDtoStatusBlock,
  GithubComDevlineOnebookEldInternalDomainDashboardDtoSummary,
  GithubComDevlineOnebookEldInternalDomainDashboardDtoSummaryEnvelope,
  GithubComDevlineOnebookEldInternalDomainDashboardDtoWindow,
  GithubComDevlineOnebookEldInternalDomainDriversDtoActivity,
  GithubComDevlineOnebookEldInternalDomainDriversDtoActivityListEnvelope,
  GithubComDevlineOnebookEldInternalDomainDriversDtoCoDriver,
  GithubComDevlineOnebookEldInternalDomainDriversDtoCoDriverCreate,
  GithubComDevlineOnebookEldInternalDomainDriversDtoCoDriverListEnvelope,
  GithubComDevlineOnebookEldInternalDomainDriversDtoDriver,
  GithubComDevlineOnebookEldInternalDomainDriversDtoDriverCreate,
  GithubComDevlineOnebookEldInternalDomainDriversDtoDriverEnvelope,
  GithubComDevlineOnebookEldInternalDomainDriversDtoDriverLicense,
  GithubComDevlineOnebookEldInternalDomainDriversDtoDriverLicenseEnvelope,
  GithubComDevlineOnebookEldInternalDomainDriversDtoDriverListEnvelope,
  GithubComDevlineOnebookEldInternalDomainDriversDtoDriverUpdate,
  GithubComDevlineOnebookEldInternalDomainDriversDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainDriversDtoMeta,
  GithubComDevlineOnebookEldInternalDomainDriversDtoResetPasswordEnvelope,
  GithubComDevlineOnebookEldInternalDomainDriversDtoResetPasswordResult,
  GithubComDevlineOnebookEldInternalDomainDriversDtoStatusChange,
  GithubComDevlineOnebookEldInternalDomainDutyDtoCounters,
  GithubComDevlineOnebookEldInternalDomainDutyDtoDayTotals,
  GithubComDevlineOnebookEldInternalDomainDutyDtoDutyStatusEvent,
  GithubComDevlineOnebookEldInternalDomainDutyDtoDutyStatusEventListEnvelope,
  GithubComDevlineOnebookEldInternalDomainDutyDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainDutyDtoHosSummary,
  GithubComDevlineOnebookEldInternalDomainDutyDtoHosSummaryEnvelope,
  GithubComDevlineOnebookEldInternalDomainDutyDtoMeta,
  GithubComDevlineOnebookEldInternalDomainDutyDtoRecapDay,
  GithubComDevlineOnebookEldInternalDomainDutyDtoViolation,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDefect,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDefectInput,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDefectType,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDefectTypeCreate,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDefectTypeEnvelope,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDefectTypeListEnvelope,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDefectTypeUpdate,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDriverBrief,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDvirCertify,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDvirCreate,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDvirRepair,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDvirReport,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDvirReportEnvelope,
  GithubComDevlineOnebookEldInternalDomainDvirDtoDvirReportListEnvelope,
  GithubComDevlineOnebookEldInternalDomainDvirDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainDvirDtoMeta,
  GithubComDevlineOnebookEldInternalDomainFilesDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainFilesDtoImportResult,
  GithubComDevlineOnebookEldInternalDomainFilesDtoImportResultEnvelope,
  GithubComDevlineOnebookEldInternalDomainFilesDtoImportRowError,
  GithubComDevlineOnebookEldInternalDomainFilesDtoPresignEnvelope,
  GithubComDevlineOnebookEldInternalDomainFilesDtoPresignRequest,
  GithubComDevlineOnebookEldInternalDomainFilesDtoPresignResponse,
  GithubComDevlineOnebookEldInternalDomainFleetDtoCatalogCreate,
  GithubComDevlineOnebookEldInternalDomainFleetDtoCatalogUpdate,
  GithubComDevlineOnebookEldInternalDomainFleetDtoEldDevice,
  GithubComDevlineOnebookEldInternalDomainFleetDtoEldDeviceAssignUnit,
  GithubComDevlineOnebookEldInternalDomainFleetDtoEldDeviceCreate,
  GithubComDevlineOnebookEldInternalDomainFleetDtoEldDeviceEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoEldDeviceListEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoEldDeviceUpdate,
  GithubComDevlineOnebookEldInternalDomainFleetDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainFleetDtoMalfunctionCode,
  GithubComDevlineOnebookEldInternalDomainFleetDtoMeta,
  GithubComDevlineOnebookEldInternalDomainFleetDtoShippingDocument,
  GithubComDevlineOnebookEldInternalDomainFleetDtoShippingDocumentEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoShippingDocumentListEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoTrailer,
  GithubComDevlineOnebookEldInternalDomainFleetDtoTrailerEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoTrailerListEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnit,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitAssignDriver,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitAssignment,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitAssignmentEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitCreate,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitDiagnostics,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitDiagnosticsEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitHistoryEntry,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitHistoryEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitListEnvelope,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitTelemetry,
  GithubComDevlineOnebookEldInternalDomainFleetDtoUnitUpdate,
  GithubComDevlineOnebookEldInternalDomainLogsDtoCertifyRequest,
  GithubComDevlineOnebookEldInternalDomainLogsDtoDailyLogDetail,
  GithubComDevlineOnebookEldInternalDomainLogsDtoDailyLogEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoDailyLogListEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoDailyLogSummary,
  GithubComDevlineOnebookEldInternalDomainLogsDtoDayTotals,
  GithubComDevlineOnebookEldInternalDomainLogsDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainLogsDtoInspectionEmail,
  GithubComDevlineOnebookEldInternalDomainLogsDtoInspectionReport,
  GithubComDevlineOnebookEldInternalDomainLogsDtoInspectionReportEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoInspectionSession,
  GithubComDevlineOnebookEldInternalDomainLogsDtoInspectionSessionEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoInspectionTransfer,
  GithubComDevlineOnebookEldInternalDomainLogsDtoInspectionTransferEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoInspectionTransferResult,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditChange,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditReject,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditRequest,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditRequestCreate,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditRequestEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditRequestListEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogEvent,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogEventCreate,
  GithubComDevlineOnebookEldInternalDomainLogsDtoLogForm,
  GithubComDevlineOnebookEldInternalDomainLogsDtoMessageEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoMeta,
  GithubComDevlineOnebookEldInternalDomainLogsDtoNumberRef,
  GithubComDevlineOnebookEldInternalDomainLogsDtoUncertifiedLog,
  GithubComDevlineOnebookEldInternalDomainLogsDtoUncertifiedLogListEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoUnidentifiedAnnotate,
  GithubComDevlineOnebookEldInternalDomainLogsDtoUnidentifiedAssign,
  GithubComDevlineOnebookEldInternalDomainLogsDtoUnidentifiedEvent,
  GithubComDevlineOnebookEldInternalDomainLogsDtoUnidentifiedEventEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoUnitRef,
  GithubComDevlineOnebookEldInternalDomainLogsDtoViolation,
  GithubComDevlineOnebookEldInternalDomainLogsDtoViolationDetails,
  GithubComDevlineOnebookEldInternalDomainLogsDtoViolationEnvelope,
  GithubComDevlineOnebookEldInternalDomainLogsDtoViolationListEnvelope,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoCancelInput,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoCompleteInput,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoMeta,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoRecord,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoRecordListEnvelope,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoSchedule,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleCreate,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleEnvelope,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleListEnvelope,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUnit,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUnitEnvelope,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUnitInput,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUnitListEnvelope,
  GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUpdate,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoListMeta,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoNotification,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoNotificationListEnvelope,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoPushToken,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoPushTokenCreate,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoPushTokenEnvelope,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoReadResult,
  GithubComDevlineOnebookEldInternalDomainNotificationsDtoReadResultEnvelope,
  GithubComDevlineOnebookEldInternalDomainReportsDtoActivityListEnvelope,
  GithubComDevlineOnebookEldInternalDomainReportsDtoActivityRow,
  GithubComDevlineOnebookEldInternalDomainReportsDtoDistanceByRegionEnvelope,
  GithubComDevlineOnebookEldInternalDomainReportsDtoDistanceByRegionMeta,
  GithubComDevlineOnebookEldInternalDomainReportsDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainReportsDtoExportJob,
  GithubComDevlineOnebookEldInternalDomainReportsDtoExportJobCreate,
  GithubComDevlineOnebookEldInternalDomainReportsDtoExportJobEnvelope,
  GithubComDevlineOnebookEldInternalDomainReportsDtoExportJobListEnvelope,
  GithubComDevlineOnebookEldInternalDomainReportsDtoExportParams,
  GithubComDevlineOnebookEldInternalDomainReportsDtoMeta,
  GithubComDevlineOnebookEldInternalDomainReportsDtoRegionDistanceRow,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoDirections,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoDirectionsEnvelope,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoMeta,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoRoute,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoRouteCreate,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoRouteEnvelope,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoRouteListEnvelope,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoRouteNotCompleted,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoRouteUpdate,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoWaypoint,
  GithubComDevlineOnebookEldInternalDomainRoutesDtoWaypointInput,
  GithubComDevlineOnebookEldInternalDomainSupportDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainSupportDtoFeedback,
  GithubComDevlineOnebookEldInternalDomainSupportDtoFeedbackCreate,
  GithubComDevlineOnebookEldInternalDomainSupportDtoFeedbackEnvelope,
  GithubComDevlineOnebookEldInternalDomainSupportDtoFeedbackListEnvelope,
  GithubComDevlineOnebookEldInternalDomainSupportDtoMeta,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicket,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicketCreate,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicketEnvelope,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicketListEnvelope,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicketMessage,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicketMessageCreate,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicketMessageEnvelope,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicketMessageListEnvelope,
  GithubComDevlineOnebookEldInternalDomainSupportDtoTicketStatusUpdate,
  GithubComDevlineOnebookEldInternalDomainSyncDtoChatMessage,
  GithubComDevlineOnebookEldInternalDomainSyncDtoChatPush,
  GithubComDevlineOnebookEldInternalDomainSyncDtoClock,
  GithubComDevlineOnebookEldInternalDomainSyncDtoClockVerdict,
  GithubComDevlineOnebookEldInternalDomainSyncDtoDailyLogSummary,
  GithubComDevlineOnebookEldInternalDomainSyncDtoDefectType,
  GithubComDevlineOnebookEldInternalDomainSyncDtoDutyStatusEvent,
  GithubComDevlineOnebookEldInternalDomainSyncDtoDvirPush,
  GithubComDevlineOnebookEldInternalDomainSyncDtoElementResult,
  GithubComDevlineOnebookEldInternalDomainSyncDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainSyncDtoEventPush,
  GithubComDevlineOnebookEldInternalDomainSyncDtoHosPolicy,
  GithubComDevlineOnebookEldInternalDomainSyncDtoLogEditRequest,
  GithubComDevlineOnebookEldInternalDomainSyncDtoPullEnvelope,
  GithubComDevlineOnebookEldInternalDomainSyncDtoPullResponse,
  GithubComDevlineOnebookEldInternalDomainSyncDtoPushEnvelope,
  GithubComDevlineOnebookEldInternalDomainSyncDtoPushRequest,
  GithubComDevlineOnebookEldInternalDomainSyncDtoPushResponse,
  GithubComDevlineOnebookEldInternalDomainSyncDtoTelemetryPoint,
  GithubComDevlineOnebookEldInternalDomainSyncDtoTelemetryResult,
  GithubComDevlineOnebookEldInternalDomainSyncDtoUnidentifiedEvent,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoDriverBrief,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoLiveUnit,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoLiveUnitListEnvelope,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoMeta,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoTrip,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoTripDetail,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoTripEnvelope,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoTripListEnvelope,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoUnidentifiedEvent,
  GithubComDevlineOnebookEldInternalDomainTrackingDtoUnidentifiedEventListEnvelope,
  GithubComDevlineOnebookEldInternalDomainUsersDtoErrorResponse,
  GithubComDevlineOnebookEldInternalDomainUsersDtoInvitationEnvelope,
  GithubComDevlineOnebookEldInternalDomainUsersDtoInvitationSent,
  GithubComDevlineOnebookEldInternalDomainUsersDtoMeta,
  GithubComDevlineOnebookEldInternalDomainUsersDtoPermission,
  GithubComDevlineOnebookEldInternalDomainUsersDtoPermissionListEnvelope,
  GithubComDevlineOnebookEldInternalDomainUsersDtoPermissionModule,
  GithubComDevlineOnebookEldInternalDomainUsersDtoRole,
  GithubComDevlineOnebookEldInternalDomainUsersDtoRoleCreate,
  GithubComDevlineOnebookEldInternalDomainUsersDtoRoleEnvelope,
  GithubComDevlineOnebookEldInternalDomainUsersDtoRoleListEnvelope,
  GithubComDevlineOnebookEldInternalDomainUsersDtoRoleUpdate,
  GithubComDevlineOnebookEldInternalDomainUsersDtoUser,
  GithubComDevlineOnebookEldInternalDomainUsersDtoUserCreate,
  GithubComDevlineOnebookEldInternalDomainUsersDtoUserEnvelope,
  GithubComDevlineOnebookEldInternalDomainUsersDtoUserListEnvelope,
  GithubComDevlineOnebookEldInternalDomainUsersDtoUserRole,
  GithubComDevlineOnebookEldInternalDomainUsersDtoUserUpdate,
  GithubComDevlineOnebookEldInternalHttpxDtoErrorBody,
  GithubComDevlineOnebookEldInternalHttpxDtoFieldError,
  GithubComDevlineOnebookEldInternalHttpxDtoMessageResponse,
])
Serializers serializers = (_$serializers.toBuilder()
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoDvirPush)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoDvirPush>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainMaintenanceDtoRecord)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainMaintenanceDtoRecord>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainMaintenanceDtoSchedule)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainMaintenanceDtoSchedule>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSupportDtoFeedback)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSupportDtoFeedback>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoNumberRef)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoNumberRef>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoDutyStatusEvent)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoDutyStatusEvent>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainFilesDtoImportRowError)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainFilesDtoImportRowError>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainFleetDtoUnitHistoryEntry)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainFleetDtoUnitHistoryEntry>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainUsersDtoPermissionModule)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainUsersDtoPermissionModule>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainUsersDtoPermission)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainUsersDtoPermission>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDashboardDtoRoute)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDashboardDtoRoute>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoUnidentifiedEvent)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoUnidentifiedEvent>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainReportsDtoRegionDistanceRow)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainReportsDtoRegionDistanceRow>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoElementResult)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoElementResult>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainCompaniesDtoCompany)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainCompaniesDtoCompany>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoUncertifiedLog)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoUncertifiedLog>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainAuthDtoSession)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainAuthDtoSession>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainFleetDtoShippingDocument)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainFleetDtoShippingDocument>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoTelemetryPoint)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoTelemetryPoint>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainReportsDtoExportJob)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainReportsDtoExportJob>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDutyDtoRecapDay)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDutyDtoRecapDay>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoUnitRef)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoUnitRef>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSupportDtoTicketMessage)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSupportDtoTicketMessage>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoChatMessage)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoChatMessage>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainUsersDtoRole)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainUsersDtoRole>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDriversDtoCoDriver)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDriversDtoCoDriver>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoDefectType)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoDefectType>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUnitInput)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUnitInput>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainCompanyDtoBranch)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainCompanyDtoBranch>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDvirDtoDefect)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDvirDtoDefect>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDvirDtoDvirReport)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDvirDtoDvirReport>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainTrackingDtoUnidentifiedEvent)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainTrackingDtoUnidentifiedEvent>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainNotificationsDtoNotification)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainNotificationsDtoNotification>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainRoutesDtoRoute)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainRoutesDtoRoute>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUnit)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainMaintenanceDtoScheduleUnit>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoEventPush)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoEventPush>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDutyDtoDutyStatusEvent)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDutyDtoDutyStatusEvent>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltMap, [FullType(String), FullType(String)]),
        () => MapBuilder<String, String>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoLogEditRequest)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoLogEditRequest>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDvirDtoDefectType)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDvirDtoDefectType>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoDailyLogSummary)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoDailyLogSummary>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditRequest)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditRequest>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoDailyLogSummary)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoDailyLogSummary>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainFleetDtoMalfunctionCode)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainFleetDtoMalfunctionCode>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditChange)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoLogEditChange>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainFleetDtoEldDevice)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainFleetDtoEldDevice>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainChatDtoMessage)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainChatDtoMessage>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainChatDtoThread)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainChatDtoThread>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDvirDtoDefectInput)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDvirDtoDefectInput>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainFleetDtoUnit)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainFleetDtoUnit>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDutyDtoViolation)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDutyDtoViolation>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainFleetDtoTrailer)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainFleetDtoTrailer>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSyncDtoChatPush)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSyncDtoChatPush>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoLogEvent)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoLogEvent>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainAuditlogDtoEntry)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainAuditlogDtoEntry>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoViolation)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoViolation>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDriversDtoActivity)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDriversDtoActivity>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainCompanyDtoNotificationSetting)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainCompanyDtoNotificationSetting>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainLogsDtoDailyLogDetail)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainLogsDtoDailyLogDetail>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainReportsDtoActivityRow)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainReportsDtoActivityRow>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainCompanyDtoHistoryEntry)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainCompanyDtoHistoryEntry>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainTrackingDtoLiveUnit)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainTrackingDtoLiveUnit>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainCompanyDtoNotificationSettingUpdate)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainCompanyDtoNotificationSettingUpdate>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalHttpxDtoFieldError)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalHttpxDtoFieldError>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainSupportDtoTicket)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainSupportDtoTicket>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainTrackingDtoTrip)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainTrackingDtoTrip>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltMap, [FullType(String), FullType(bool)]),
        () => MapBuilder<String, bool>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainDriversDtoDriver)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainDriversDtoDriver>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(String)]),
        () => ListBuilder<String>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(GithubComDevlineOnebookEldInternalDomainUsersDtoUser)]),
        () => ListBuilder<GithubComDevlineOnebookEldInternalDomainUsersDtoUser>(),
      )
      ..add(const OneOfSerializer())
      ..add(const AnyOfSerializer())
      ..add(const DateSerializer())
      ..add(Iso8601DateTimeSerializer())
    ).build();

Serializers standardSerializers =
    (serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();
